### ISSUE TITLE
How to install on ubuntu 16.04?

### ISSUE THREAD

**Issue by saintthor** [trojan-gfw/trojan#100]
升级时提示：cmake 已经是最新版 (3.5.1-1ubuntu3)。

**Comment by siaimes** [comment]
@saintthor Due to insufficient boost version, Trojan is no longer supported in Ubuntu 18.04. This change has been reflected on the wiki. The current minimum supported version is Ubuntu 18.10

**Comment by iamid0** [comment]
Does the binary app work?

**Comment by saintthor** [comment]
> Does the binary app work?

where is the binary app?

**Comment by iamid0** [comment]
https://github.com/trojan-gfw/trojan/releases/latest

Maybe these pre-compiled binary file would work.

**Comment by saintthor** [comment]
> https://github.com/trojan-gfw/trojan/releases/latest
> 
> Maybe these pre-compiled binary file would work.

thanks. I should change the example.com in confilg.json to my own server to make it work, right? there is no available server?

**Comment by briancblog** [comment]
> 
> 
> > https://github.com/trojan-gfw/trojan/releases/latest
> > Maybe these pre-compiled binary file would work.
> 
> thanks. I should change the example.com in confilg.json to my own server to make it work, right? there is no available server?

You have to set up your own server, and replace the example.com by your own domain in config.json file.

You'd better deploy a latest Ubuntu server.

**Comment by saintthor** [comment]
> > > https://github.com/trojan-gfw/trojan/releases/latest
> > > Maybe these pre-compiled binary file would work.
> > 
> > 
> > thanks. I should change the example.com in confilg.json to my own server to make it work, right? there is no available server?
> 
> You have to set up your own server, and replace the example.com by your own domain in config.json file.
> 
> You'd better deploy a latest Ubuntu server.

thanks.
