### ISSUE TITLE
What is forward exactly please?

### ISSUE THREAD

**Issue by brian-cheng** [trojan-gfw/trojan#101]
(1) What are the target_addr and target_port exactly, please? What are they designed for?

(2) I'd like to access the internet as a US IP, but the direct connection to the US is slower. So I'd like to speed up the connection by adding a **Japan server** between the client and the Trojan server.  It looks like this below.

**Trojan Client ==> Japan server ==> Trojan server**

Could you please give me some senses of how to set up the **Japan server**?

In ss mode, I can set it up as "ss client ==> haproxy ==> ss server",  But Trojan is domain related application, I have no idea at all.

I appreciate any help in advance!

**Comment by GreaterFire** [comment]
`forward` mode is equivalent to `ss-tunnel` or `ssh -L`.

**Comment by GreaterFire** [comment]
To achieve the scheme you described, you can just fire up a `socat` (tcp forward) on your Japan server (and point your DNS to the Japan server).

**Comment by brian-cheng** [comment]
> To achieve the scheme you described, you can just fire up a `socat` (tcp forward) on your Japan server (and point your DNS to the Japan server).

Thanks for your swift reply! I do appreciate that!

I will set up `socat ` and keep the case updated.
Thanks again!

**Comment by brian-cheng** [comment]
> To achieve the scheme you described, you can just fire up a `socat` (tcp forward) on your Japan server (and point your DNS to the Japan server).

Thanks! `socat `does works great! That is exactly what I was looking for!
Hope this case will be helpful to other users who want bridge for speed!

Thank administrator again!

**Comment by widewind2015** [comment]
@GreaterFire 
It turns out that I have to disable certificates and hostname verification to use socat to forwarding TCP stream as described in above scheme.  
`"ssl": {
    "verify": false,
    "verify_hostname": false,`

Otherwise trojan(nat mode) fails with error:
`[2020-02-24 23:07:22] [ERROR] XXX.XXX.XXX.XXX:PORT SSL handshake failed with XXX.XXX.XXX.XXX:PORT: certificate verify failed
[2020-02-24 23:07:22] [INFO] XXX.XXX.XXX.XXX:PORT disconnected, 0 bytes received, 223 bytes sent, lasted for 0 seconds`

Is the right and only configuration to support socat? But certification and hostname verification are STRONGLY RECOMMENDED [here](https://trojan-gfw.github.io/trojan/config).

**Comment by GreaterFire** [comment]
@widewind2015 put your real domain name in the sni field

**Comment by widewind2015** [comment]
> @widewind2015 put your real domain name in the sni field

It works. Thanks very much!

**Comment by praschak** [comment]
@GreaterFire I'm trying something similar to achieve a speedy connection to Germany:

**Trojan Client ==> la1.server.cc (socat relay) ==> de1.server.cc (trojan server)**

My socat on la1.server.cc looks like this:
`socat TCP-LISTEN:443,fork TCP-CONNECT:de1.server.cc:443`

The config on the client side runs as NAT and connects to la1.server.cc (socat relay):
```
"remote_addr": "la1.server.cc",
"remote_port": 443,
```

It only works if I set `"verify_hostname": false`. If it is `true`, i get the error:
`SSL handshake failed with la1.server.cc:443: certificate verify failed`

Is there something I can do to use host name verification?

**Comment by GreaterFire** [comment]
@praschak put your hostname in sni field

**Comment by praschak** [comment]
> @praschak put your hostname in sni field

Thanks a lot! Works now.

To clarify for others who come across the same issue:
Add the hostname of your Trojan server (`de1.server.cc` in my case) to the sni field of your **Trojan client configuration**:
```
"ssl": {
  "verify": true,
  "verify_hostname": true,
  ...
  "sni": "de1.server.cc",
  ...
```

**Comment by 0neday** [comment]
transmit all package, include tcp and udp
