### ISSUE TITLE
ERROR on Fedora 30 client: unsupported command

### ISSUE THREAD

**Issue by briancblog** [trojan-gfw/trojan#102]
Server is working on Fedora 30, and client is working on Windows 7 SP1 as well.

But I got error messages on setting up client on local Fedora 30, which makes client on Fedora 30 not working. Here is the error message output on local Fedora 30. (Log level is 0.)

As you see, **the error message is unsupported command**

> [root@tj-client trojan]# trojan -c config.json
> Welcome to trojan 1.12.2
> [2019-06-10 17:25:25] [WARN] trojan service (client) started at 127.0.0.1:7070
> [2019-06-10 17:25:52] [ALL] 127.0.0.1:47902 incoming connection
> [2019-06-10 17:25:52] [ERROR] 127.0.0.1:47902 unsupported command
> [2019-06-10 17:25:52] [INFO] 127.0.0.1:47902 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
> [2019-06-10 17:25:57] [ALL] 127.0.0.1:47906 incoming connection
> [2019-06-10 17:25:57] [ERROR] 127.0.0.1:47906 unsupported command
> [2019-06-10 17:25:57] [INFO] 127.0.0.1:47906 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds

Thanks for this great project!

Please let me know if you need more detailed information.

=================

Update: The error message of "unsupported command" occurs on Ubuntu 19.04 either.

Please check it. I can provide more information when necessary.

Thanks!

**Comment by GreaterFire** [comment]
I'm not sure. Are you using a correct SOCKS5 client implementation?

**Comment by briancblog** [comment]
> 
> 
> I'm not sure. Are you using a correct SOCKS5 client implementation?
Sorry for my late reply!

Yes, I think both the implementation and configuration are correct. On Ubuntu 19.04, it is simple to install the package through apt-get. The server edition works as it does, but the client does not work at all.

Could you please try Ubuntu as client on your end?

I appreciate your help!

**Comment by siaimes** [comment]
> > I'm not sure. Are you using a correct SOCKS5 client implementation?
> > Sorry for my late reply!
> 
> Yes, I think both the implementation and configuration are correct. On Ubuntu 19.04, it is simple to install the package through apt-get. The server edition works as it does, but the client does not work at all.
> 
> Could you please try Ubuntu as client on your end?
> 
> I appreciate your help!

I tested the client mode on ubuntu 19.04 but no problem occurred. I doubt if you are using a legitimate client configuration file as described  [here](https://trojan-gfw.github.io/trojan/config).

**Comment by GreaterFire** [comment]
How did you use trojan? Is it a browser proxying through it?

**Comment by briancblog** [comment]
> 
> 
> > > I'm not sure. Are you using a correct SOCKS5 client implementation?
> > > Sorry for my late reply!
> > 
> > 
> > Yes, I think both the implementation and configuration are correct. On Ubuntu 19.04, it is simple to install the package through apt-get. The server edition works as it does, but the client does not work at all.
> > Could you please try Ubuntu as client on your end?
> > I appreciate your help!
> 
> I tested the client mode on ubuntu 19.04 but no problem occurred. I doubt if you are using a legitimate client configuration file as described [here](https://trojan-gfw.github.io/trojan/config).

I created the client configuration file by copying the client.json.example file. 

If the client works on your ubuntu 19.04, the problem is probably on my end.

I will test it again and get back to you.

Thanks!

**Comment by briancblog** [comment]
> 
> 
> How did you use trojan? Is it a browser proxying through it?

Yes, I think I am not wrong, as Trojan client on Windows works already with Trojan server on ubuntu 19.04. The only issue is Trojan client on ubuntu 19.04.

I will get back soon.

Thanks!

**Comment by GreaterFire** [comment]
Since you didn't answer my question, I'll ask again. How did you use trojan's `SOCKS5` interface? Is it a browser that connects to it? Please post your browser configuration here.

**Comment by briancblog** [comment]
> 
> 
> Since you didn't answer my question, I'll ask again. How did you use trojan's `SOCKS5` interface? Is it a browser that connects to it? Please post your browser configuration here.

Thanks for getting back!

a> Trojan client listens on socks5 port 127.0.0.1:1080.
b> Privoxy converts socks5 port 127.0.0.1:1080 to http on port 127.0.0.1:8118
c> Start Privoxy by bash command `systemctl start privoxy.service` and Trojan client by `trojan -c config.json` (bash's current directory is /etc/trojan already). Both Trojan and Privoxy are running. I can see the ports are on by bash command `netstat -lntp`
d> Set proxy bash's proxy by commands `export http_proxy=http://localhost:8118 && export https_proxy=http://localhost:8118`

e> Check ip address by executing bash command `curl cip.cc`. I can not get IP address through cip.cc but see Privoxy's error message.

If I could see the IP address in step e>, I would setup proxy on my Firefox on Winodws 7.

This method works with shadowsocks before. Let me know if I missed something.
Thanks!

**Comment by GreaterFire** [comment]
@briancblog try curl --socks5-hostname 127.1 cip.cc

**Comment by briancblog** [comment]
> 
> 
> @briancblog try curl --socks5-hostname 127.1 cip.cc

Thanks for your swift reply! (and @siaimes )

Yes, the bash command `curl --socks5-hostname 127.0.0.1 cip.cc` works, and I can get IP correctly. Thanks!

**May I know the reason, please? Why Privoxy failed to convert Trojan's socks5 to http?**
I need http proxy sometimes. As you know, not all programs support socks5 proxy natively. For instance, I 'd like to share my Trojan with my cellphone over LAN. The WIFI network configuration on cellphone supports http proxy only, but no socks5 at all.

**Is Trojan's client socks5 proxy a standard one? I ask because I'd like to use it on other program like FTP.**

I appreciate your help so much!

**Comment by GreaterFire** [comment]
@briancblog It's definitely Privoxy's problem. Did you use the newest version of Privoxy?

**Comment by GreaterFire** [comment]
@briancblog Also, there are existing solutions to mobile device. Check wiki for more info.

**Comment by briancblog** [comment]
@GreaterFire Yes, my Privoxy is the latest version 3.0.28 already. Could you please test Privoxy on your end? As I mentioned in the previous message, some program like Google Drive client on Windows does not support socks5 proxy. I ask because Privoxy had been working fine with shadowsocks for years. Everything was going well. It shouldn't be so hard.

It will be much more convenient if mobile can connect through WIFI's native configuration.

Thanks!

**Comment by GreaterFire** [comment]
@briancblog Can you show me your Privoxy configuration?

**Comment by GreaterFire** [comment]
@briancblog I bet you had forward-socks5t. You should rather use forward-socks5.

**Comment by briancblog** [comment]
> 
> 
> @briancblog I bet you had forward-socks5t. You should rather use forward-socks5.

@GreaterFire @siaimes 

I am convinced of my wrong Privoxy configuration.

Provioxy'd default example looks like this below:
`#        forward-socks5t   /               127.0.0.1:1080 .`

I just un-commented it by removing the first symbol of number sign, and my wrong configuration looks like this below:
`        forward-socks5t   /               127.0.0.1:1080 .`

Thanks to @GreaterFire , **the correct configuration is as below**:
`        forward-socks5   /               127.0.0.1:1080 .`

**It is socks5, rather than socks5t.**

Thank again @GreaterFire and @siaimes for your time! I really appreciate that!
Hope this ticket will help more users who want a http proxy through Trojan.
Great project!
