### ISSUE TITLE
请问mac客户端怎样配置

### ISSUE THREAD

**Issue by sidneynot** [trojan-gfw/trojan#103]
主要是不知怎样找到 cert.pem文件并下载。

**Comment by shirakun** [comment]
证书需要自己生成

**Comment by sidneynot** [comment]
证书已经设置生成，但不知道怎样从服务器中找到并下载到mac电脑里？

**Comment by ghostinbits** [comment]
In the case of locating certificates issued by Let's Encrypt, your certificates would usually have been placed in /etc/letsencrypt/live/[hostname]/. Certbot would inform you of the location upon completion, you might want to write it down next time.

**Comment by sidneynot** [comment]
thanks.

**Comment by cattyhouse** [comment]
curl -v https://www.baidu.com  2>&1 | grep CAfile  | cut -d ":" -f2 | xargs
