### ISSUE TITLE
Issue with the Authenticator.cpp

### ISSUE THREAD

**Issue by wchen99998** [trojan-gfw/trojan#104]
I am learning c++ so I looked at your code as an example. Could you explain why you write the following code in such way?
Authenticator.cpp Line 101-103
```
bool Authenticator::auth(const string&) { return true; }
void Authenticator::record(const std::string&, uint64_t, uint64_t) {}
bool Authenticator::is_valid_password(const std::string&) { return true; }
```

So, it does not check the correctness of the password?

**Comment by GreaterFire** [comment]
Please read the code carefully. This segment of code is only compiled when your system doesn't contain a MySQL library (`ENABLE_MYSQL` is not defied), in which case this object will [not be even constructed](https://github.com/trojan-gfw/trojan/blob/34df04bbef24592e0a535e9376b31f8df333fab9/src/service.cpp#L109). The real implementation is [here](https://github.com/trojan-gfw/trojan/blob/34df04bbef24592e0a535e9376b31f8df333fab9/src/authenticator.cpp#L42-L92).

**Comment by wchen99998** [comment]
Thank you! Sorry for my misguided issue
