### ISSUE TITLE
[Enhance|Feature] specify which public ip the server to use for outgoging traffic

### ISSUE THREAD

**Issue by emiyalee1005** [trojan-gfw/trojan#105]
In my assumption, when we use vps to access those website behind the gfw intentionally or unintentionally. The wall may see a picture: a client send some outgoing connections to a outside server and then, almost in the same time, some incoming connection from that server to a website behind the wall. This may become an evidence that someone is using that server as a proxy and then the wall may ban the server according to this evidence.

To avoid this from happening, my solution is if a server has more than one public ip, then allow the user to config trojan-server to use a different ip for outgoing traffic to hide itself from the incoming connections.

Currently I have a vps with 2+ public ips and my workaround is let the trojan-server use the default main ip and then point my domain to the second ip.

I will be glad to see trojan can natively support this feature.

**Comment by GreaterFire** [comment]
@emiyalee1005 > a client send some outgoing connections to a outside server and then, almost in the same time, some incoming connection from that server to a website behind the wall.
This doesn't indicate that the server is a proxy server, since visiting a website has the same pattern as you described.
>  if a server has more than one public ip, then allow the user to config trojan-server to use a different ip for outgoing traffic to hide itself from the incoming connections.
You can already do this if you setup haproxy on your local machine. Trojan is merely a protocol implementation. It doesn't do load balancing as you described.

**Comment by GreaterFire** [comment]
@emiyalee1005 Well then the solution will actually be to use gfwlist with some traffic splitter (like SwitchyOmega).

**Comment by ghostinbits** [comment]
In the picture you described, why would anyone establish connections to a server which is behind the wall, from behind the wall? Typically, and as the project's name suggests, we ship Trojan horses through the wall, not to ship them back. Even if someone may use this technique to hide their identity when using services provided within the wall, it's not how traffic would be recognised by the wall.

Or if being behind the wall means outside the wall in your case, the picture is exactly what we'd like to achieve. Protocols designed within the framework of TCP, one of which is HTTPS, involve connections from both sides.

**Comment by emiyalee1005** [comment]
@vexetron @GreaterFire
The reason for me to suggest this feature:
1."In the picture you described, why would anyone establish connections to a server which is behind the wall, from behind the wall?" - If i use trojan as vpn, some of the app on my phone/pc may connect to some china ip which a normal user would never know and also no one can guarantee it would never happen
2."Protocols designed within the framework of TCP, one of which is HTTPS, involve connections from both sides" - I mean if the client connect to server through ip-A and request the server to proxy access to baidu.com, then the server use another ip-B , which is different from the ip-A used to communication itself with the client, to direct access baidu.com.
3."Even if someone may use this technique to hide their identity when using services provided within the wall" Yeah, this may be the one of the reasons
4."it's not how traffic would be recognized by the wall" - It's an idea and I know for now the gfw may not have the ability to do such traffic analysis. But in the future IT MAY. Most importantly, it`s not just me who came up with this idea. I have seen someone else post some similar topics in other place before(v2ray or ss or else, can't remember for a while).  

The wall is smart and always be evolving.  We must think farther than it.

**Comment by emiyalee1005** [comment]
@vexetron @GreaterFire 
btw, to clarify, behind the wall means being in China and outside the wall means global world except China

**Comment by ghostinbits** [comment]
While Trojan imitates HTTPS, which is different to the concepts of Project V and Shadowsocks, it would be a weird situation where a client would still send tons of connection requests should the server fail to respond.

**Comment by emiyalee1005** [comment]
> While Trojan imitates HTTPS, which is different to the concepts of Project V and Shadowsocks, it would be a weird situation where a client would still send tons of connection requests should the server fail to respond.

@vexetron You misunderstand what i means. The connection between client and server still be the same with a fixed ip, no matter request or response. This has nothing to do with ss/v2ray.

But the important is the server use a different ip to access the website which the client tell him to do.

Here is a example:
Client<<<ip:1.1.1.1>>>TrojanServer<<<ip:2:2:2:2>>>website(like baidu.com)

**Comment by GreaterFire** [comment]
To achieve what you described, you can also set up [`ip rule`](http://man7.org/linux/man-pages/man8/ip-rule.8.html) on your trojan server, which can do exactly what you want, using the other address for your outgoing connections. It's not trojan's responsibility to manage this kind of stuff.
