### ISSUE TITLE
Is URL visible or encrypted?

### ISSUE THREAD

**Issue by briancblog** [trojan-gfw/trojan#107]
When surfing the web through Trojan, will the URL in the browser address bar be visible or encrypted to ISP? Even accessing encrypted HTTPS pages?

Thank you!

**Comment by GreaterFire** [comment]
@briancblog Invisible.

**Comment by GreaterFire** [comment]
Please see the doc about the protocol for more details.

**Comment by briancblog** [comment]
@GreaterFire  Thank you for your swift reply!

Another quick question here. I have a Japan server running socat as a bridge between the US trojan server and local trojan client. As you know, local connection to Japan is faster and this will speed up local client's connection.

To get multiple US IP addresses, the bridge Japan server is running multiple socat instances with different ports. The deployment looks like this below. (**I have multiple trojan clients and multiple US servers, but only ONE Japan bridge server.**)

```
trojan client 1 ==> Janpan bridge server (socat instance 1, example1.com:441) ==> US server 1 (IP 1.2.3.4)
trojan client 2 ==> Janpan bridge server (socat instance 2, example2.com:442) ==> US server 1 (IP 2.2.3.4)
trojan client 3 ==> Janpan bridge server (socat instance 3, example3.com:443) ==> US server 1 (IP 3.2.3.4)
```

Is this method going to get much more potential risk of being blocked by 3rd party like ISP?
Is there a better method?

Thank you again!
