### ISSUE TITLE
android version?

### ISSUE THREAD

**Issue by asdfzxh8** [trojan-gfw/trojan#110]
Android apk igniter could run and connect on my cellphone, but it usually crashes within seconds of use ('sorry, igniter has stopped working'). Is there a minimum version of Android required? as the Android I use is pretty old 5.1.1. Thanks.

**Comment by a-fruity-melon** [comment]
@asdfzxh8 wrong repo.

**Comment by ProfessorX** [comment]
那么什么时候才会出安卓版本呢。
