### ISSUE TITLE
请问下自己有域名的用子域名该如何配置？

### ISSUE THREAD

**Issue by ProfessorX** [trojan-gfw/trojan#112]
如题。

子域名操作好像有点不一样？

阿里嘎多。

这个Wiki里面真没有。

**Comment by briancblog** [comment]
正常操作就可以了。不明白你问的是什么意思？

**Comment by mritd** [comment]
refs https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by ProfessorX** [comment]
1. 我自己有一个.org域名
2. 想用子域名做映射。
3. 配置好了证书。域名挂在Cloudflare.
4. 照网上一个教程弄弄好了连接对应域名连不上。

**Comment by ProfessorX** [comment]
@mritd 别ref了。互联网老狗都快奔三了。

**Comment by briancblog** [comment]
> 
> 
>     1. 我自己有一个.org域名
> 
>     2. 想用子域名做映射。
> 
>     3. 配置好了证书。域名挂在Cloudflare.
> 
>     4. 照网上一个教程弄弄好了连接对应域名连不上。

证书需要用子域名的，除非你是  wildcard
域名 DNS 设置好了，正常这样就可以了。
你再细细排查一下？

要不就再换个域名，再换个 VPS，重新再试试？

**Comment by mritd** [comment]
你可以先用 curl 测试一下 Cloudflare 地址的 TLS 证书是否正常，如果正常再测试 trojan，并提供 trojan 相关日志

**Comment by ProfessorX** [comment]
OK

我觉得再这么被你们玩下去GFW要用白名单模式了。

**Comment by Chigusa0w0** [comment]
@ProfessorX No, that's literally impossible to happen.

**Comment by a-fruity-melon** [comment]
@ProfessorX 承你吉言

**Comment by GreaterFire** [comment]
@ProfessorX Please stop being sarcastic.
