### ISSUE TITLE
Quite Slow on "Performing a TLS handshake with google.com"

### ISSUE THREAD

**Issue by briancblog** [trojan-gfw/trojan#113]
Sometimes it is **QUITE TOO** slow to access google.com directly. It got stuck at "Performing a TLS handshake with google.com" for **5-15 seconds**. And it is slow to click on one link in google's search results page. But the Previous and Next Page link is loading faster. It happens although not always.

After one site is fully loaded, it will be super fast to this site's other internal link. This is pretty cool!

Is this related with the feature of keep alive? How to fix the issue of getting stuck at "Performing a TLS handshake with google.com", please?

Thank you!

**Comment by a-fruity-melon** [comment]
@briancblog Could you please upload your log files (both client and server)? Thanks a lot!

**Comment by GreaterFire** [comment]
This is not trojan's issue. Trojan, when tested locally, doesn't have apparent overhead or bottleneck. Please change a server and test.

**Comment by GreaterFire** [comment]
Also, please stop posting this kind of usage related problems. This is GitHub Issues, not customer support.
