### ISSUE TITLE
1.12.2运行一段时间后服务器缓存很大，速度极慢

### ISSUE THREAD

**Issue by Alvin9999** [trojan-gfw/trojan#114]
反馈一下：用的1.12.2版本，运行一段时间后服务器缓存很大，大概占内存40%左右，速度极慢或无法使用，必须重启服务器才可以。另外一个问题，有时候会出现，刚打开客户端，打开网页需要等待20秒以上才能成功打开网页。

**Comment by GreaterFire** [comment]
Please update to `1.12.3`.

**Comment by Alvin9999** [comment]
vps系统是centos7，请问怎么升级?

**Comment by GreaterFire** [comment]
@Alvin9999 Please update to 1.12.3.

**Comment by GreaterFire** [comment]
Please download the binary [here](https://github.com/trojan-gfw/trojan/releases).

**Comment by Alvin9999** [comment]
也就是要重新安装吗

**Comment by a-fruity-melon** [comment]
@Alvin9999 是

**Comment by Alvin9999** [comment]
更新了1.12.3，使用时间不到1天的时间，服务器内存缓存增加了30%。您也可以测试下。

**Comment by a-fruity-melon** [comment]
@Alvin9999 不太可能吧，我这5%增加都不到
你该不会是1GB内存的vps吧

**Comment by Alvin9999** [comment]
4G以上的内存，现在内存缓存达到2G了
![1111](https://user-images.githubusercontent.com/12132898/60386520-64fdc480-9ac8-11e9-8f97-e68c825295e9.PNG)

**Comment by Alvin9999** [comment]
看视频很多

**Comment by Alvin9999** [comment]
ssr就不会这样，很奇怪哦

**Comment by GreaterFire** [comment]
This is not what trojan is using. Please Google what `buff/cache` mean. I'm locking this issue since asymmetric knowledge leads to nonconstructive discussion.

**Comment by GreaterFire** [comment]
As a courtesy, I offer you [this link](https://unix.stackexchange.com/questions/390518/what-do-the-buff-cache-and-avail-mem-fields-in-top-mean).
