### ISSUE TITLE
[BUG] Test how to check the BOX

### ISSUE THREAD

**Issue by chaos-sudo** [trojan-gfw/trojan#119]
- [*] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?

**Additional context**

**Comment by GreaterFire** [comment]
please type "x" in the box.

**Comment by chaos-sudo** [comment]
> please type "x" in the box.

I think it should give some hint to me. I failed to check the box twice :(
