### ISSUE TITLE
Can GFW detect TLS over TLS?

### ISSUE THREAD

**Issue by WANG-lp** [trojan-gfw/trojan#12]
Hi,
I have a question about this project: 
Does TLS over TLS make it more easy for GFW to detect such 'hidden' traffic? 

We already know that GFW can detect and interfere the OpenVPN traffic very quickly.

Ref:
https://gist.github.com/micooz/52a81852e3f6d1614f66e07b0757cd6c
https://gist.github.com/clowwindy/5947691
http://jiji.io/p/12699180487511941578

**Comment by GreaterFire** [comment]
It might be a problem. But since the wall can only guess the underlying protocol behind SSL by packet length pattern, adding some random padding may solve this problem. Moreover, with active probing defense and ALPN, we can achieve a pretty good obfs.

**Comment by klzgrad** [comment]
There was a [blog post](https://groups.google.com/d/msg/traffic-obf/hcaIt1cY8UQ/FQLsq9Q6AgAJ) claiming that a home-made TLS over TLS proxy was detected by the GFW allegedly using the packet size pattern of HTTP CONNECT requests. Another person commenting on this blog post also claimed certain commercial DPI device used this exact method in production. But I have yet to see any properly controlled experiments to establish the link between specific traffic features and detection in practice. Traffic analysis is a real threat but we don't have a way to determine how much a threat it is for our specific protocol designs so this question is now essentially unfalsifiable.

Your second link by clowwindy is a weak argument. Shadowsocks had repeated attempts at reinventing basic cryptography, which is considered by many a major sin, and had been suffering from replay attacks only until recently. In the mean time TLS is much better scrutinized for security (but it has its own problems with protocol-level info leak for detection).

**Comment by testcaoy7** [comment]
There is a technique called "Chaffing and winnowing". (conceived by Ron Rivest)
Maybe we can randomly add some "Chaff" (random data chuck) to the trojan protocol and winnow all the chaff packages after data stream is received.

[https://en.wikipedia.org/wiki/Chaffing_and_winnowing](url)

**Comment by GreaterFire** [comment]
Again, this is a technique that makes trojan diverted from normal HTTPS data, which adds more pattern to the protocol.

**Comment by DrVictor77** [comment]
> Hi, I have a question about this project: Does TLS over TLS make it more easy for GFW to detect such 'hidden' traffic?
> 
> We already know that GFW can detect and interfere the OpenVPN traffic very quickly.
> 
> Ref: https://gist.github.com/micooz/52a81852e3f6d1614f66e07b0757cd6c https://gist.github.com/clowwindy/5947691 http://jiji.io/p/12699180487511941578

can you send me a tls in tls trojan config ? no ip needed just configuration
