### ISSUE TITLE
Limiting Server Network Access problem.

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#120]
https://github.com/trojan-gfw/trojan/wiki/Limiting-Server-Network-Access

For convenience, I used acme.sh to generate a certificate because it can automatically update my certificate. However, when I configured trojan's limiting server network access according to this page, I encountered a permission denied problem. Now suppose my certificate file is also placed in the /etc/trojan directory. If I change the owner of /etc/trojan to trojan, then trojan can start normally, but acme.sh will not be able to write the certificate due to permission denied when updating the certificate. If you change the owner of /etc/trojan to the user used by acme.sh, trojan will fail to start due to permission denied issues. So I am here to ask you how to solve this problem or do you have a better solution?
Thank you in advance.

**Comment by GreaterFire** [comment]
You can add the user `trojan` to whatever group that has the permission to read the certificate.

**Comment by ghost** [comment]
thanks
