### ISSUE TITLE
Add TPROXY support?

### ISSUE THREAD

**Issue by cattyhouse** [trojan-gfw/trojan#121]
- [x] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

It would be nice to have tproxy support to accept traffic from iptables. 

reference:
https://www.kernel.org/doc/Documentation/networking/tproxy.txt

**Comment by cattyhouse** [comment]
Sorry, i forgot to check the BOX, would you help to reopen this issue?

**Comment by GreaterFire** [comment]
You can fix the format and reopen it yourself.
