### ISSUE TITLE
[Feature Request] Add TPROXY support

### ISSUE THREAD

**Issue by cattyhouse** [trojan-gfw/trojan#122]
- [x] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

It would be nice to have tproxy support to accept traffic from iptables, in this case it could act as a transparent proxy for LAN network. 

reference:
https://www.kernel.org/doc/Documentation/networking/tproxy.txt

**Comment by GreaterFire** [comment]
I might write a separated tool for that if this demand is high.

**Comment by cattyhouse** [comment]
TPROXY is really convenient for home and maybe office considering everyone’s got more than one device, plus some devices like TV boxes are not easy to do proxy configuration.  

By the way http listen is also good for programs which does not support socks5. I know polipo could transfer socks to http but that’s not as good as integrating all 3 protocols ( socks, http, tproxy) into Trojan.

**Comment by GreaterFire** [comment]
@cattyhouse HTTP proxy server is non-trivial to implement, it's close to implementing a full HTTP server.

**Comment by cattyhouse** [comment]
Hi, have you been working on this, so my propose was like this:

"run_type": "client",
    "local_addr": "127.0.0.1",
    "local_socks5_port": 1080, // currently featured already
    "local_http_port": 8123, // new http port to replace e.g. polipo
    "local_tproxy_port": 1999, // pure tproxy ports, listen on both **TCP and UDP**, like v2ray does. 
....


if port is empty, it should not listen on that protocol
so, on a transparent proxy linux gateway attached to a router or on a router itself, only tproxy is needed, we can work with iptables to  jump LAN  traffice to the tproxy port, so we do not need to setup every device within LAN network. 
on other devices, only socks and http is needed, for individual programs to use, e.g. when the device is traveling out, most likely Phones and Notebooks.

**Comment by GreaterFire** [comment]
I am very busy these days and haven't had a chance to look at this.

**Comment by klzgrad** [comment]
It's much simpler to implement the equivalent REDIRECT support, which is stated to be technically inferior to TPROXY but much simpler to implement and set up.

Take a look at https://github.com/shadowsocks/shadowsocks-libev/blob/64b97cd9a31af5d929d4f9b22d57a052025ccf95/src/redir.c#L101-L114. This is all you need on top of existing connection forwarding infrastructure.

Let the user set up `iptables -t nat -A OUTPUT -p tcp -j REDIRECT --to-ports 1080`, and any connection will be redirect to port 1080, to which you'll be listening. Then you accept the connection, and extract the upstream address and port with `SO_ORIGINAL_DST` and start proxying that upstream. (The original address info comes from netfilter's conntrack.)

**Comment by GreaterFire** [comment]
@klzgrad Thanks for your suggestion! It makes this feature really easy to implement!

**Comment by cattyhouse** [comment]
@klzgrad what about udp traffic, and the traffic from LAN to ! LOCAL

**Comment by GreaterFire** [comment]
@cattyhouse It's all possible with iptables.

**Comment by cattyhouse** [comment]
As i know, udp transparent proxy only works on mangle table and only works in PREROUTING chain. 

To get full udp support, TPROXY is still a must.

**Comment by GreaterFire** [comment]
I think I will implement NAT support.

**Comment by wongsyrone** [comment]
Both `IP6T_SO_ORIGINAL_DST` and `SO_ORIGINAL_DST` are Linux specific, thus we have to make it conditional.

```c
#include <linux/netfilter_ipv4.h>             /* SO_ORIGINAL_DST */
#include <linux/netfilter_ipv6/ip6_tables.h>  /* IP6T_SO_ORIGINAL_DST */
```

**Comment by GreaterFire** [comment]
I'll just duplicate `forwardsession.{h,cpp}` and do some slight modification. Should be fast.

**Comment by cattyhouse** [comment]
As far as I know:
1. there is no problem using REDIRECT target to deal with **tcp** traffic in OUTPUT and PREROUTING chain, as the **dst address** can be tracked and traced.
2. For **udp** traffic, TPROXY target has to be involved to track and trace **dst address**, REDIRECT can't do that for udp, check the [notes](https://www.kernel.org/doc/Documentation/networking/tproxy.txt) here (_`Think of proxying UDP for example: you won't
be able to find out the original destination address. Even in case of TCP
getting the original destination address is racy.`_)
3. ss-redir use REDIRECT for tcp and TPROXY for udp. v2ray can use TPROXY+TPROXY for tcp and udp or REDIRECT + TPROXY for tcp and udp.
4. when using TPROXY+TPROXY, all transparent proxy job can be done in mangle table, no nat needed.
5. NAT Full Cone could be another tough job.

**Comment by GreaterFire** [comment]
@cattyhouse Why do you care so much about udp traffic? If it's for DNS, I would just setup a DOH client.

**Comment by cattyhouse** [comment]
@GreaterFire for gaming console in most of the time.

**Comment by GreaterFire** [comment]
In that case I really suggest you use a third party software ([~v2ray~](https://github.com/v2ray/v2ray-core)[v2fly](https://github.com/v2fly/v2ray-core) or [redsocks](https://github.com/darkk/redsocks)) to do `TPROXY`. There has been a lot of wheels out there and I don't want to invent a new one.

**Comment by GreaterFire** [comment]
But I'll still keep the NAT REDIRECT implementation because it's relatively easy to implement and not that invasive (on the other hand, TPROXY UDP implementation requires another UDP session timer which I don't want to code yet again).

**Comment by cattyhouse** [comment]
well v2fly is not able to do NAT Full Cone, thought it supports udp, but it is Symmetric NAT (Dynamic NAT)

**Comment by GreaterFire** [comment]
@klzgrad @cattyhouse Is the only thing to implement `TPROXY` to set socket option `IP_TRANSPARENT`? The target endpoint can be retrieved by local peer? If so it's not more complicated than the NAT REDIRECT.

**Comment by cattyhouse** [comment]
It is actually not that hard.


# tproxy tcp

getsockname(sockfd, (void *)&destaddr, &(socklen_t){sizeof(destaddr)});

# redirect tcp

getsockopt(sockfd, SOL_IP, SO_ORIGINAL_DST, dstaddr, &addrlen)

**Comment by klzgrad** [comment]
With the amount of kernel setup required for tproxy I can create a full fledged packet forwarding VPN already. See https://gist.github.com/klzgrad/5661b64596d003f61980 I just don't see the point of using tproxy for udp.

**Comment by wongsyrone** [comment]
> It is actually not that hard. 

Any PR is appreciated.

**Comment by GreaterFire** [comment]
> > It is actually not that hard.
> 
> Any PR is appreciated.

+1

**Comment by GreaterFire** [comment]
The final decision has been made by the dev team that `v1.13.0` will only include the NAT REDIRECT mode. If you are not satisfied with this result, you can make your own fork of trojan and make it work for yourself.

**Comment by cattyhouse** [comment]
just to note, a new TPROXY to SOCKS5 tool is [here](https://github.com/zfl9/ipt2socks) , in case someone need PURE TPROXY support, it works very well with any socks5 listening.

**Comment by GreaterFire** [comment]
@cattyhouse Thanks for your update. You can see that it's best to implement it in another project, so all SOCKS5 proxies can use it, instead of implementing it in trojan.

**Comment by cattyhouse** [comment]
@GreaterFire

Yes. You were correct about separate tool , now all needed are done, i’ll begin to give trojan a try.
