### ISSUE TITLE
[Feature Request] KTLS and KCM support on modern linux kernels

### ISSUE THREAD

**Issue by ccaapton** [trojan-gfw/trojan#125]
- [x] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
Not related to a problem or bug.
There are two awesome features in recent linux kernels, KTLS and KCM. Benchmarks show that KTLS has 7% better throughput than userspace tls. If KTLS is used, you can also use splice to pass buffers within the kernel, thus completely avoid moving buffers in/out of userspace. 

KCM can combine multiple tcp connenctions to a single message-oriented interface, and could auto-balancing between tcp sockets. kcm could be used to implement socket reuse and acceleration.

**Is this problem relevant to what trojan should care about?**
Yes, this proposal tries to improve throughput and reduce server workload.

**Describe the solution you'd like**
KTLS could be implemented only on server or client side, thus there is no cross compatibility issue, KCM potentially requires both end having kernel support, thus need more investigation.   

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by GreaterFire** [comment]
I would only try to implement any other transports if it's supported by Boost::Asio to avoid restructuring the whole project. Also 7% of improvements is not meaningful since trojan can do approximately 100 Gbps right now.
