### ISSUE TITLE
[Feature Request] add support to openwrt

### ISSUE THREAD

**Issue by malikshi** [trojan-gfw/trojan#127]

**Comment by GreaterFire** [comment]
See https://github.com/trojan-gfw/trojan-openwrt

**Comment by GreaterFire** [comment]
Sorry, it's a typo. https://github.com/trojan-gfw/openwrt-trojan

**Comment by malikshi** [comment]
okay self build ?

**Comment by malikshi** [comment]
@GreaterFire 
```
`apps/ca.o: In function `do_revoke':
ca.c:(.text.do_revoke+0x498): relocation truncated to fit: R_AARCH64_LD64_GOTPAGE_LO15 against symbol `strlen' defined in .text section in /root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/lib/libc.so
ca.c:(.text.do_revoke+0x498): warning: Too many GOT entries for -fpic, please recompile with -fPIC
/root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/bin/../lib/gcc/aarch64-openwrt-linux-musl/7.3.0/../../../../aarch64-openwrt-linux-musl/bin/ld: final link failed: Symbol needs debug section which does not exist
collect2: error: ld returned 1 exit status
Makefile:6094: recipe for target 'apps/openssl' failed
make[4]: *** [apps/openssl] Error 1
make[4]: Leaving directory '/root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/openssl1.1-1.1.1c/openssl-1.1.1c'
Makefile:172: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/openssl1.1-1.1.1c/openssl-1.1.1c'
Makefile:158: recipe for target '/root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/openssl1.1-1.1.1c/openssl-1.1.1c/.built' failed
make[2]: *** [/root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/openssl1.1-1.1.1c/openssl-1.1.1c/.built] Error 2
make[2]: Leaving directory '/root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/package/openssl1.1'
time: package/openssl1.1/compile#129.64#20.31#152.59
package/Makefile:107: recipe for target 'package/openssl1.1/compile' failed
make[1]: *** [package/openssl1.1/compile] Error 2
make[1]: Leaving directory '/root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64'
/root/openwrt-sdk-18.06.2-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64/include/toplevel.mk:209: recipe for target 'package/trojan/compile' failed
make: *** [package/trojan/compile] Error 2`
```
error like that

**Comment by GreaterFire** [comment]
@malikshi @wongsyrone

**Comment by wongsyrone** [comment]
Please try the latest version like 18.06.4.

https://downloads.openwrt.org/releases/

**Comment by malikshi** [comment]
Okay, I will try it

**Comment by malikshi** [comment]
still failed like that. can you help me to build for sunxi aarch64  cortexa53

**Comment by malikshi** [comment]
> make[1]: Entering directory '/root/openwrt-18.06.4'
make[2]: Entering directory '/root/openwrt-18.06.4/feeds/packages/libs/boost'
Selected Boost API sysv for architecture x86_64 and cpu " "
make[2]: Leaving directory '/root/openwrt-18.06.4/feeds/packages/libs/boost'
time: package/feeds/packages/boost/host-compile#0.49#0.82#1.35
make[2]: Entering directory '/root/openwrt-18.06.4/package/libs/ncurses'
make[2]: Leaving directory '/root/openwrt-18.06.4/package/libs/ncurses'
time: package/libs/ncurses/host-compile#0.14#0.07#0.23
make[2]: Entering directory '/root/openwrt-18.06.4/package/libs/toolchain'
rm -rf /root/openwrt-18.06.4/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed /root/openwrt-18.06.4/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
mkdir -p /root/openwrt-18.06.4/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
install -d -m0755 /root/openwrt-18.06.4/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib /root/openwrt-18.06.4/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/usr/bin
cp -fpR /root/openwrt-18.06.4/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib/ld-musl-*.so* /root/openwrt-18.06.4/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib/
cp: cannot stat '/root/openwrt-18.06.4/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib/ld-musl-*.so*': No such file or directory
Makefile:618: recipe for target '/root/openwrt-18.06.4/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed' failed
make[2]: *** [/root/openwrt-18.06.4/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory '/root/openwrt-18.06.4/package/libs/toolchain'
time: package/libs/toolchain/compile#0.14#0.04#0.20
package/Makefile:107: recipe for target 'package/libs/toolchain/compile' failed
make[1]: *** [package/libs/toolchain/compile] Error 2
make[1]: Leaving directory '/root/openwrt-18.06.4'
/root/openwrt-18.06.4/include/toplevel.mk:216: recipe for target 'package/trojan/compile' failed

**Comment by wongsyrone** [comment]
> cp: cannot stat '/root/openwrt-18.06.4/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib/ld-musl-.so': No such file or directory

It looks the SDK is broken.

**Comment by malikshi** [comment]
> > cp: cannot stat '/root/openwrt-18.06.4/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib/ld-musl-.so': No such file or directory
> 
> It looks the SDK is broken.

i am tried 3 type, from sdk and git clone openwrt also from release in github openwrt
all same result error like that

**Comment by malikshi** [comment]
Thank you for opening this issue. I hope you guys fix it

**Comment by malikshi** [comment]
Recv-Q made me hang? any solution?

**Comment by ntgeralt** [comment]
[Feature Request] add support to mips/arm.

**Comment by malikshi** [comment]
@ntgeralt did you try build any openwrt trojangfw and success?

**Comment by ntgeralt** [comment]
@malikshi nope.looking forward to work well on MT7621.

**Comment by ffftwo** [comment]
> @malikshi nope.looking forward to work well on MT7621.

我试着改了一下makefile,openwrt snapshot MT7621编译通过了
https://github.com/ffftwo/openwrt-trojan

**Comment by malikshi** [comment]
I need for aarch64 cortexa53

**Comment by wongsyrone** [comment]
> > @malikshi nope.looking forward to work well on MT7621.
> 
> 我试着改了一下makefile,openwrt snapshot MT7621编译通过了
> https://github.com/ffftwo/openwrt-trojan

The Makefiles provided in [this](https://github.com/trojan-gfw/openwrt-trojan) repository link to the static OpenSSL library for convenience, you can definitely link to the official one dynamically if you like, as stated in the FAQ. If your firmware ships OpenSSL v1.1.x or older, you cannot benefit from TLS 1.3.

**Comment by ffftwo** [comment]
> I need for aarch64 cortexa53

So sorry, I was intent to mention ntgeralt.

**Comment by ntgeralt** [comment]
@ffftwo I hope you can make a finished product and explain a little about the way.

**Comment by ffftwo** [comment]
@ntgeralt 刚更新了reame,写在里面了

**Comment by widewind2015** [comment]
@wongsyrone @malikshi by changing '-o3' to '-o0 -g3' in `TARGET_CFLAGS := $(filter-out -O%,$(TARGET_CFLAGS)) -O0 -g3` of Makefile for Openssl, the compile goes a bit further till

`for -fpic, please recompile with -fPIC
/opt/friendlywrt/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.3.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.3.0/../../../../aarch64-openwrt-linux-musl/bin/ld: final link failed: Nonrepresentable section on output

collect2: error: ld returned 1 exit status

Makefile:6096: recipe for target 'apps/openssl' failed

make[5]: *** [apps/openssl] Error 1

make[5]: Leaving directory '/opt/friendlywrt/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/openssl1.1-1.1.1d/openssl-1.1.1d'

Makefile:174: recipe for target 'all' failed

make[4]: *** [all] Error 2
checking for header declaring getopt variables... make[4]: Leaving directory '/opt/friendlywrt/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/openssl1.1-1.1.1d/openssl-1.1.1d'

Makefile:158: recipe for target '/opt/friendlywrt/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/openssl1.1-1.1.1d/openssl-1.1.1d/.built' failed

make[3]: *** [/opt/friendlywrt/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/openssl1.1-1.1.1d/openssl-1.1.1d/.built] Error 2

make[3]: Leaving directory '/opt/friendlywrt/friendlywrt/package/openssl1.1'
Command exited with non-zero status 2

time: package/openssl1.1/compile#142.40#31.92#214.00

package/Makefile:107: recipe for target 'package/openssl1.1/compile' failed

make[2]: *** [package/openssl1.1/compile] Error 2

make[2]: *** Waiting for unfinished jobs....`

**Comment by widewind2015** [comment]
maybe another workaround : compile openssl 1.1.1d as dynamical library which coexists with openssl1.0.1, and trojan will use that library . Is that possible?

**Comment by widewind2015** [comment]
@malikshi @wongsyrone Now this patch works. '-fpic' option is not needed for statically linked trojan. But I will verify if the binary work on Cortex-A53 based OpenWRT18.06.1.

`--- ./openssl1.1/Makefile	2019-11-19 10:25:47.829890048 +0800
+++ Makefile	2019-11-19 17:07:42.560442000 +0800
@@ -92,7 +92,7 @@
 
 OPENSSL_OPTIONS += no-deprecated
 
-TARGET_CFLAGS := $(filter-out -O%,$(TARGET_CFLAGS)) -O3
+TARGET_CFLAGS := $(filter-out -O%,$(TARGET_CFLAGS)) -O0 -g3
 
 
 
@@ -119,8 +119,8 @@
 	)
 
 endef
-
-TARGET_CFLAGS += $(FPIC) -ffunction-sections -fdata-sections
+#$(FPIC)
+TARGET_CFLAGS += -ffunction-sections -fdata-sections
 TARGET_LDFLAGS += -Wl,--gc-sections
 
 define Build/Compile`

**Comment by malikshi** [comment]
@widewind2015 thanks you for the info. please follouw up if it working

**Comment by malikshi** [comment]
It work to compile with your suggestion. But I don't know how it work to running from `init` /etc/unit.d/trojan it's say disabled.

**Comment by widewind2015** [comment]
> It work to compile with your suggestion. But I don't know how it work to running from `init` /etc/unit.d/trojan it's say disabled.

Why not add your script directly by Luci Web Admin which is System->Startup? The script will be generated at /etc/init.d/ accordingly.

**Comment by widewind2015** [comment]
> @widewind2015 thanks you for the info. please follouw up if it working

Yes, it works. At least it has kept working for 4 days on NanoPi R1S Quad Cortex-A53 based.

**Comment by malikshi** [comment]
I didn't tried enable from luci. But when in command line says disabled then it's would be same

**Comment by malikshi** [comment]
@widewind2015 im actived debug mode here the log
>>/etc/init.d/trojan start
trojan is disabled
{ "name": "trojan", "script": "\/etc\/init.d\/trojan", "instances": { }, "triggers": [ ], "data": { } }

**Comment by malikshi** [comment]
@widewind2015 can you gimme example to route all traffic? like transparent mode by shadowsocks?

**Comment by widewind2015** [comment]
> @widewind2015 can you gimme example to route all traffic? like transparent mode by shadowsocks?

You may have a look at [this](https://github.com/trojan-gfw/trojan/issues/135).

**Comment by univert** [comment]
跪求arm版本openwrt 包

**Comment by yatounoneko** [comment]
> 跪求arm版本openwrt 包

L大的lede有集成

**Comment by univert** [comment]
@yatounoneko 去哪里找，有链接么？

**Comment by yatounoneko** [comment]
> @yatounoneko 去哪里找，有链接么？
https://github.com/coolsnowwolf/lede
需自行编译固件

**Comment by univert** [comment]
> 
> 
> > @yatounoneko 去哪里找，有链接么？
> > https://github.com/coolsnowwolf/lede
> > 需自行编译固件

晕啊，我就是需要arm binary包， 没工夫编译

**Comment by lonee6** [comment]
> > > @yatounoneko 去哪里找，有链接么？
> > > https://github.com/coolsnowwolf/lede
> > > 需自行编译固件
> 
> 晕啊，我就是需要arm binary包， 没工夫编译

试试这个

链接：https://eyun.baidu.com/s/3dGNX781 密码：yasC

**Comment by MadZyu** [comment]
> > > > @yatounoneko 去哪里找，有链接么？
> > > > https://github.com/coolsnowwolf/lede
> > > > 需自行编译固件
> > 
> > 
> > 晕啊，我就是需要arm binary包， 没工夫编译
> 
> 试试这个
> 
> 链接：https://eyun.baidu.com/s/3dGNX781 密码：yasC

大佬可以再分享一下吗？链接失效了

**Comment by babylife** [comment]
> > > > @yatounoneko 去哪里找，有链接么？
> > > > https://github.com/coolsnowwolf/lede
> > > > 需自行编译固件
> > 
> > 
> > 晕啊，我就是需要arm binary包， 没工夫编译
> 
> 试试这个
> 
> 链接：https://eyun.baidu.com/s/3dGNX781 密码：yasC

链接失效了，可以再共享下吗？
