### ISSUE TITLE
setup trogan-gfw behind nginx

### ISSUE THREAD

**Issue by zhangsan946** [trojan-gfw/trojan#131]
Dear @GreaterFire,

Thanks for this great project. I have gone though the following link and successfully tested setup trojan before nginx.
https://github.com/trojan-gfw/trojan/issues/67

But as trojan doesn't support bind multiple certificates, and I have the request of hosting different websites(https) for different domains on the same server hosting trojan.  So I hope to setup trojan behind nginx as nginx can support virtual servers. Can you share some sample config of nginx and trogan to help with this scenario. 

Thanks in advance.

In additional, for socks5 problem on windows mentioned in the link below.
https://github.com/trojan-gfw/trojan/issues/76
Based on my understanding, the advantage of sock5 is that it supports remote dns resolving comparing with socks4.  
v2ray has a configuration of "sniffing" which is quite useful under windows. In this case, even ie can work without third-party apps. Hope it helps.

Cheers,
Kevin

**Comment by GreaterFire** [comment]
There are now 2 ways to serve different certificates based on `sni` with trojan. You can either [use `haproxy` to load balance based on `sni`](https://www.haproxy.com/blog/enhanced-ssl-load-balancing-with-server-name-indication-sni-tls-extension/) or [use the `ngx_stream_ssl_preread_module` module of new versions of nginx](https://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html) to put trojan behind nginx. Pay close attention to the "Selecting an upstream based on server name" part if you choose the latter.

For your second request, trojan is merely a protocol implementation and we have no plans to support other inbound protocols.

**Comment by zhangsan946** [comment]
@GreaterFire thanks for your very quick feedback. i will have a test.

**Comment by GreaterFire** [comment]
@zhangsan946 Also, it's spelled trojan, not trogan...

**Comment by klzgrad** [comment]
In theory probe resistance should happen at the same place with the network stack of the frontend. This means if you use SNI to load balance (between your blog and Trojan) and then use Trojan password to load balance again (between authenticated proxy and fake backend), it leaks some info because SNI is clear text and any probe can observe protocol differences between the SNI you use for regular website and for Trojan, because in this case the regular website gives off Nginx's network stack signature but the Trojan SNI gives off Boost.Asio's network stack signature.

You can check https://github.com/trojan-gfw/trojan-nginx to see how probe resistance is handled in Nginx.

**Comment by KunagisaYuki** [comment]
@klzgrad Please upgrade your brain immediately

**Comment by KunagisaYuki** [comment]
@klzgrad 草 回错了，抱歉

**Comment by KunagisaYuki** [comment]
@klzgrad Well as one of the contributor, I don't support the SNI feature, however this will be useful for some of our users. Is it a good idea that we put an alert for this feature in document

**Comment by klzgrad** [comment]
I don't think it matters at this stage. Just be aware, but no rush to be more paranoid than necessary, and upgrade only until this becomes a real issue.

**Comment by zhangsan946** [comment]
@GreaterFire sorry for the typo.
@klzgrad thanks for your info. I am aware of what SNI is, but have no ideas how probe resistance works. will it bring some additial characteristic that GFW can detect if i put trojan behind nginx?

**Comment by KunagisaYuki** [comment]
@zhangsan946 In the shortest word, yes.But actually I don't think these GFW makers will take use of this.

**Comment by cattyhouse** [comment]
if Trojan runs as a backend behind Nginx, is it still necessary to define `"ssl":{}` in Trojan server config? because that is already defined in Nginx config. Can you also document this method? I have v2ray and another private protocol running as reserve proxy already, it would be nice to add Trojan without effecting them.

**Comment by GreaterFire** [comment]
@cattyhouse Nginx will not terminate SSL if you use [`ngx_stream_ssl_preread_module`](https://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html).

**Comment by cattyhouse** [comment]
@GreaterFire yes, i read about that already, what does "Nginx will not terminate SSL" mean. Do i set ssl certs and keys in both nginx confg and trojan config when using this module?

**Comment by GreaterFire** [comment]
How this works is:
1. Nginx receives a TCP connection and gets the TLS Client Hello.
2. Nginx reads the SNI field in the Client Hello.
3. Without doing anything else, Nginx redirects the whole TLS flow to trojan.

**Comment by zhangsan946** [comment]
@GreaterFire Many thanks for your help. I manage to do it by the following config and would like to share. Hope it's gonna help.

1. nginx
stream {
        map $ssl_preread_server_name $name {
                xxx.mydomain.com       trojan;
                default                  nginx;
        }
        upstream trojan {
                server 127.0.0.1:4433;
        }
        upstream nginx {
                server 127.0.0.1:4443;
        }
        server {
                listen 443;
                listen [::]:443;
                proxy_pass  $name;
                ssl_preread on;
        }
}
http {
        server {
                listen 80 default_server;
                listen [::]:80 default_server;
                listen 4443 ssl default_server;
                listen [::]:4443 ssl default_server;
                include snippets/snakeoil.conf;
                root /var/www/html;
                index index.html index.htm index.nginx-debian.html;
                server_name _;
                location / {
                        try_files $uri $uri/ =404;
                }
        }
        server {
                listen 4443 ssl;
                listen [::]:4443 ssl;
                server_name someotherodmain.com;
                ...
        }
}

2. trojan server 
{
    "run_type": "server",
    "local_addr": "127.0.0.1",
    "local_port": 4433,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "password"
    ],
   ...
}

**Comment by GreaterFire** [comment]
@zhangsan946 You are very welcome. Glad I can help.

**Comment by cattyhouse** [comment]
i'm still confused.. here is my current nginx config for v2ray, how can i add trojan behind nginx without effecting v2ray? some questions:

1. stream module's context is in main, do i move the server module from http to stream?
2. i guess i need to remove the https redirection of 80 listening, if not there will be a dead loop right? cause trojan needs 80. also i need to put at least `root` to 80 section? 


```bash
# main
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 400000;
pid /run/nginx.pid;
# include
include /etc/nginx/modules-enabled/*.conf;

# events
events {
    use epoll;
    worker_connections 65535;
    multi_accept on;
}

# http module settings
http {
    sendfile on;
    charset utf-8;
    types_hash_max_size 4096;
    client_header_buffer_size 4k;
    client_max_body_size 4m;
    client_body_buffer_size 128k;
    client_body_in_single_buffer on;
    server_tokens off;
    resolver 1.1.1.1;
    resolver_timeout 10s;
    # ssl 
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:50m;
    ssl_buffer_size 4k;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_ciphers TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;
    ssl_prefer_server_ciphers on;
    # add header
    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
    add_header Referrer-Policy no-referrer;
    # log
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    include /etc/nginx/mime.types;
    include /etc/nginx/conf.d/*.conf;
    
    # 443 listening
    server {
        root /var/www/html;
        index index.html index.htm;
        server_name xxx.xxx.com;
        listen 443 ssl;
        # certs
        ssl_certificate /etc/letsencrypt/live/xxx.xxx.com/fullchain.pem; 
        ssl_certificate_key /etc/letsencrypt/live/xxx.xxx.com/privkey.pem; 
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 

        # proxy module settings
        proxy_http_version 1.1;
        proxy_connect_timeout 5s;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect          off;
        proxy_buffering         off;

        # location for v2ray
        location = /ray {
            proxy_pass              http://127.0.0.1:12345;
        }	
    }
    # 80 listening
    server {
        listen 80;
        server_name xxx.xxx.com;
        return 301 https://xxx.xxx.com$request_uri;
    }

}

```

**Comment by killgcd4ever** [comment]
> @GreaterFire Many thanks for your help. I manage to do it by the following config and would like to share. Hope it's gonna help.
> 
> 1. nginx
>    stream {
>    map $ssl_preread_server_name $name {
>    xxx.mydomain.com       trojan;
>    default                  nginx;
>    }
>    upstream trojan {
>    server 127.0.0.1:4433;
>    }
>    upstream nginx {
>    server 127.0.0.1:4443;
>    }
>    server {
>    listen 443;
>    listen [::]:443;
>    proxy_pass  $name;
>    ssl_preread on;
>    }
>    }
>    http {
>    server {
>    listen 80 default_server;
>    listen [::]:80 default_server;
>    listen 4443 ssl default_server;
>    listen [::]:4443 ssl default_server;
>    include snippets/snakeoil.conf;
>    root /var/www/html;
>    index index.html index.htm index.nginx-debian.html;
>    server_name _;
>    location / {
>    try_files $uri $uri/ =404;
>    }
>    }
>    server {
>    listen 4443 ssl;
>    listen [::]:4443 ssl;
>    server_name someotherodmain.com;
>    ...
>    }
>    }
> 2. trojan server
>    {
>    "run_type": "server",
>    "local_addr": "127.0.0.1",
>    "local_port": 4433,
>    "remote_addr": "127.0.0.1",
>    "remote_port": 80,
>    "password": [
>    "password"
>    ],
>    ...
>    }

Hello, I follow your configuration, but when I encounter such an error, nignx has been printing no host in upstream ""

**Comment by chenicel** [comment]
> > @GreaterFire Many thanks for your help. I manage to do it by the following config and would like to share. Hope it's gonna help.
> > 
> > 1. nginx
> >    stream {
> >    map $ssl_preread_server_name $name {
> >    xxx.mydomain.com       trojan;
> >    default                  nginx;
> >    }
> >    upstream trojan {
> >    server 127.0.0.1:4433;
> >    }
> >    upstream nginx {
> >    server 127.0.0.1:4443;
> >    }
> >    server {
> >    listen 443;
> >    listen [::]:443;
> >    proxy_pass  $name;
> >    ssl_preread on;
> >    }
> >    }
> >    http {
> >    server {
> >    listen 80 default_server;
> >    listen [::]:80 default_server;
> >    listen 4443 ssl default_server;
> >    listen [::]:4443 ssl default_server;
> >    include snippets/snakeoil.conf;
> >    root /var/www/html;
> >    index index.html index.htm index.nginx-debian.html;
> >    server_name _;
> >    location / {
> >    try_files $uri $uri/ =404;
> >    }
> >    }
> >    server {
> >    listen 4443 ssl;
> >    listen [::]:4443 ssl;
> >    server_name someotherodmain.com;
> >    ...
> >    }
> >    }
> > 2. trojan server
> >    {
> >    "run_type": "server",
> >    "local_addr": "127.0.0.1",
> >    "local_port": 4433,
> >    "remote_addr": "127.0.0.1",
> >    "remote_port": 80,
> >    "password": [
> >    "password"
> >    ],
> >    ...
> >    }
> 
> Hello, I follow your configuration, but when I encounter such an error, nignx has been printing no host in upstream ""



> @GreaterFire Many thanks for your help. I manage to do it by the following config and would like to share. Hope it's gonna help.
> 
> 1. nginx
>    stream {
>    map $ssl_preread_server_name $name {
>    xxx.mydomain.com       trojan;
>    default                  nginx;
>    }
>    upstream trojan {
>    server 127.0.0.1:4433;
>    }
>    upstream nginx {
>    server 127.0.0.1:4443;
>    }
>    server {
>    listen 443;
>    listen [::]:443;
>    proxy_pass  $name;
>    ssl_preread on;
>    }
>    }
>    http {
>    server {
>    listen 80 default_server;
>    listen [::]:80 default_server;
>    listen 4443 ssl default_server;
>    listen [::]:4443 ssl default_server;
>    include snippets/snakeoil.conf;
>    root /var/www/html;
>    index index.html index.htm index.nginx-debian.html;
>    server_name _;
>    location / {
>    try_files $uri $uri/ =404;
>    }
>    }
>    server {
>    listen 4443 ssl;
>    listen [::]:4443 ssl;
>    server_name someotherodmain.com;
>    ...
>    }
>    }
> 2. trojan server
>    {
>    "run_type": "server",
>    "local_addr": "127.0.0.1",
>    "local_port": 4433,
>    "remote_addr": "127.0.0.1",
>    "remote_port": 80,
>    "password": [
>    "password"
>    ],
>    ...
>    }

Do you use trojan deployed by docker container? I currently use nginx container. I want to use Docker to deploy trojan, and then use nginx to forward to trojan container, but I do n’t know how to configure

**Comment by zhangsan946** [comment]
change it the ip for docker, it shouldnot be 127.0.0.1 for a container @chenicel

**Comment by klzgrad** [comment]
Why was https://github.com/trojan-gfw/trojan-nginx deleted? I was looking for it for further tests.

**Comment by wongsyrone** [comment]
> Why was https://github.com/trojan-gfw/trojan-nginx deleted? I was looking for it for further tests.

It's now a private repository.

**Comment by hronro** [comment]
@klzgrad 

> It leaks some info because SNI is clear text and any probe can observe protocol differences between the SNI you use for regular website and for Trojan, because in this case the regular website gives off Nginx's network stack signature but the Trojan SNI gives off Boost.Asio's network stack signature.

I'm confused here, nginx won't terminating SSL/TLS, why it would gives Nginx's network stack signature here?

And as an reference, since `trojan-gfw/trojan-nginx` is not accessible any more, this is the request process chart I thought it would be:

```

                       +-------------------+
                       |                   |
                       |Client Request(:443)
                       |                   |
                       +-------------------+
                                 |
                                 |
                                 v
                       +-------------------+
                       |                   |
                       |   Nginx (:443)    |
                       |                   |
                       +-------------------+
                                 |
                                 |
               v-----------------------------------v
      +-------------------+             +-------------------+
      |                   |             |                   |
      |       a.com       |             |       b.com       |
      |                   |             |                   |
      +-------------------+             +-------------------+
               |                                   |
               |                                   |
               v                                   v
      +-------------------+             +-------------------+
      |                   |             |                   |
      |       ...         |             |   Trojan (:1800)  |
      |                   |             |                   |
      +-------------------+             +-------------------+
                                                   |
                                                   |
                               v-------------------------------------v
                      +-------------------+               +-------------------+
                      |                   |               |                   |
                      |authenticated proxy|               |    fake backend   |
                      |                   |               |                   |
                      +-------------------+               +-------------------+
                               |                                     |
                               |                                     |
                               v                                     v
                      +-------------------+               +-------------------+
                      |                   |               |                   |
                      |        ...        |               |   Nginx (:1801)   |
                      |                   |               |                   |
                      +-------------------+               +-------------------+


```

**Comment by klzgrad** [comment]
Signature means more than cipher suites. It can be the way each stack handles error conditions.

**Comment by hronro** [comment]
@klzgrad 
When people say `leak information`, it means leak the information which can make GFW detect the service is used for proxying or not. In this scenario, I don't think GFW can detect it because normal services can also use NGINX as a reverse proxy server for load balancing. GFW can not detect it's a  normal service with NGINX in the front for load balancing, or a trojan service behind NGINX.

**Comment by blip** [comment]
@foisonocean I was similarly puzzled why this setup could leak information. After much contemplation, it starts to make sense: in your example, a.com’s TLS is established through nginx, and b.com though trojan, yet they both resolve to the same IP. So if the two establishments are ever so slightly different, it’s apparent from the outside something fishy is going on.

@klzgrad Is it correct to assume that if the server is multi-homed, that is, a.com and b.com resolve to different IPs, it no longer leaks information?

However, I do think it’s a stretch to believe that sites are susceptible of being blocked with this setup. It should be perfectly normal to tcp load balance https traffics, resulting in establishing TLS in different ways from the same IP. If IPs were to be flagged solely on that ground, there would be a lot of false positives.

**Comment by NightMachinery** [comment]
Is this possible with Caddy, as well?

**Comment by xkjdox** [comment]
error stream :(
