### ISSUE TITLE
[BUG] 同一对trojan服务端和客户端， 对于同一个网址， 我用 python 的 requests包发出的请求超时，而用 chrome 中SwitchyOmega 就能正常访问

### ISSUE THREAD

**Issue by VashonHu** [trojan-gfw/trojan#134]
- [x] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
1.12.3

**Describe the bug**
在同一请求的情况下， 
我用 python 中的 requests 发出的请求， 本地Trojan接收到的日志如下， 这时请求超时
[2019-10-01 19:59:27] [INFO] 127.0.0.1:55157 requested connection to 74.86.118.24:443
[2019-10-01 19:59:57] [INFO] 127.0.0.1:55157 disconnected, 0 bytes received, 517 bytes sent, lasted for 30 seconds
而用 chrome 中的SwitchyOmega就能够正常访问， 而且这次日志中打印的是域名， 而不是 ip， 但是两次我都是用域名访问的
[2019-10-01 20:01:22] [INFO] 127.0.0.1:55189 requested connection to www.bitmex.com:443

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?

**Additional context**

**Comment by VashonHu** [comment]
使用Privoxy 将 socks5转换为 http 代理后问题解决

**Comment by GreaterFire** [comment]
The root problem is that the python requester performed DNS locally but the DNS entry is polluted.
