### ISSUE TITLE
build failed on Android 9  termux 0.75  (arm)

### ISSUE THREAD

**Issue by callengre** [trojan-gfw/trojan#137]
$ apt install wget git clang cmake openssl
$ wget https://mirrors.ustc.edu.cn/termux/dists/stable/main/binary-aarch64/boost_1.70.0-5_aarch64.deb
$ wget https://mirrors.ustc.edu.cn/termux/dists/stable/main/binary-aarch64/boost-dev_1.70.0-4_aarch64.deb
$ chmod 777 boost_1.70.0-5_aarch64.deb
$ chmod 777 boost-dev_1.70.0-4_aarch64.deb
$ dpkg -i ./boost_1.70.0-5_aarch64.deb
(Reading database ... 27095 files and directories currently installed.)
Preparing to unpack ./boost_1.70.0-5_aarch64.deb ...
Unpacking boost (1.70.0-5) over (1.70.0-5) ...
Setting up boost (1.70.0-5) ...
$ dpkg -i ./boost-dev_1.70.0-4_aarch64.deb
Selecting previously unselected package boost-dev.
(Reading database ... 27095 files and directories currently installed.)
Preparing to unpack .../boost-dev_1.70.0-4_aarch64.deb ...
Unpacking boost-dev (1.70.0-4) ...
Replaced by files in installed package boost (1.70.0-5) ...
dpkg: dependency problems prevent configuration of boost-dev:
 boost (1.70.0-5) breaks boost-dev and is installed.

dpkg: error processing package boost-dev (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 boost-dev

$ git clone https://github.com/trojan-gfw/trojan
Cloning into 'trojan'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 2362 (delta 41), reused 50 (delta 28), pack-reused 2288
Receiving objects: 100% (2362/2362), 844.16 KiB | 349.00 KiB/s, done.
Resolving deltas: 100% (1759/1759), done.
$ cd trojan/
$ cmake -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr -DENABLE_MYSQL=OFF .
`-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Boost 1.70.0 at /data/data/com.termux/files/usr/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS system;program_options
-- Found boost_headers 1.70.0 at /data/data/com.termux/files/usr/lib/cmake/boost_headers-1.70.0
-- Found boost_system 1.70.0 at /data/data/com.termux/files/usr/lib/cmake/boost_system-1.70.0
-- No suitable boost_system variant has been identified!
--   libboost_system.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
CMake Error at /data/data/com.termux/files/usr/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Found package configuration file:
/data/data/com.termux/files/usr/lib/cmake/boost_system-1.70.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

Call Stack (most recent call first):
  /data/data/com.termux/files/usr/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  /data/data/com.termux/files/usr/share/cmake-3.15/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:39 (find_package)

-- Configuring incomplete, errors occurred!`
[See also "/data/data/com.termux/files/home/trojan/CMakeFiles/CMakeOutput.log".](https://github.com/trojan-gfw/trojan/files/3686559/CMakeOutput.log)
[CMakeOutput.log](https://github.com/trojan-gfw/trojan/files/3686559/CMakeOutput.log)

**Comment by GreaterFire** [comment]
Hold tight. I'm gonna rewrite the compilation script.

**Comment by callengre** [comment]
This is See build report log, if you want to known more detail , download below CMakeOutput.log .  
https://github.com/trojan-gfw/trojan/files/3686559/CMakeOutput.log
// Think you so much, more error,  cause build envir not normal .

**Comment by callengre** [comment]
Thanks a lot,  Build script was fixed already. 
https://github.com/trojan-gfw/trojan/wiki/Mobile-Platforms
// reference~
