### ISSUE TITLE
[BUG]ipv6网络下udp转发故障

### ISSUE THREAD

**Issue by qiuzi** [trojan-gfw/trojan#139]
双栈网络环境里
`::ffff:192.168.1.149:55887 requested UDP associate to 0.0.0.0:0, open UDP socket ::ffff:192.168.1.1:54069 for relay
 [INFO] ::ffff:192.168.1.149:55887 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
[ERROR] ::ffff:192.168.1.149:55887 cannot establish connection to remote server xxx.xxx:8080: Operation canceled`

tcp正常

**Comment by GreaterFire** [comment]
@qiuzi Seems like your UDP proxifier is implemented incorrectly. A packet capture of the traffic between your proxifier and trojan client is appreciated.

**Comment by GreaterFire** [comment]
@qiuzi Also as a side note, please respect the issue template.
