### ISSUE TITLE
[Feature Request]希望增加reuseport支持

### ISSUE THREAD

**Issue by qiuzi** [trojan-gfw/trojan#141]

**Comment by oasiscifr** [comment]
@qiuzi http://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html
use nginx

**Comment by GreaterFire** [comment]
Please specify.

**Comment by qiuzi** [comment]
如果支持reuseport 能改善性能与使用体验 
原生总比外加实在

**Comment by GreaterFire** [comment]
As you failed to define what this feature really is, I'm closing this issue.

**Comment by xsm1997** [comment]
If I am not misunderstanding, reuseport means let multiple process of Trojan bind on the same TCP port.
It is a feature of Linux.  Multiple process listening on the same port will increase performance in multi-core systems, as the Linux kernel will perform load balancing among multiple TCP connections to Trojan by arranging them to different process of Trojan.
Additionally, shadowsocks-libev supports this feature.
If Trojan add a flag of TCP reuseport in conf, it will be great!

**Comment by 20NE** [comment]
已经支持

**Comment by 20NE** [comment]
supported already
