### ISSUE TITLE
How to hot update the certificate and key.

### ISSUE THREAD

**Issue by SunZGitHub** [trojan-gfw/trojan#144]
I used acme.sh to apply for a certificate for trojan. After 2 months, acme.sh has updated the certificate and copied the new certificate to the directory specified by the trojan configuration file using the following command. 

```bash
acme.sh --install-cert -d mydomain --key-file /path/to/private.key --fullchain-file /path/to/certificate.crt
```

However, when accessing the trojan website in my browser, it still shows that the certificate was applied two months ago. My question is, can I make acme.sh pass a parameter to trojan when updating the certificate without forcing restart trojan. For your convenience, the prototype of the acme.sh installation certificate command is:

```bash
acme.sh  --installcert  -d  <domain>.com   \
        --key-file   /etc/nginx/ssl/<domain>.key \
        --fullchain-file /etc/nginx/ssl/fullchain.cer \
        --reloadcmd  "service nginx force-reload"
```

**Comment by HarukaMa** [comment]
@SunZGitHub Send SIGUSR1 to trojan process. https://github.com/trojan-gfw/trojan/commit/53ca5f80fcd6239c28c8520886692e9186e3fcf6

**Comment by SunZGitHub** [comment]
@HarukaMa Thank you for your reply.

After checking the information on how to send a message to the process on the Internet, I wrote this command line.

```bash
acme.sh --install-cert -d mydomain --key-file /path/to/private.key --fullchain-file /path/to/certificate.crt --reloadcmd "killall -s SIGUSR1 trojan"
```

But it returned the Operation not permitted log.

```bash
[Wed Oct  9 12:19:52 UTC 2019] Installing key to:/path/to/private.key
[Wed Oct  9 12:19:52 UTC 2019] Installing full chain to:/path/to/certificate.crt
[Wed Oct  9 12:19:52 UTC 2019] Run reload cmd: killall -s SIGUSR1 trojan
trojan(13119): Operation not permitted
trojan: no process found
[Wed Oct  9 12:19:52 UTC 2019] Reload error for :
```
Now, I can't figure out where there is a problem.

**Comment by SunZGitHub** [comment]
It worked when I added the `sudo` permission to the reload command.
```bash
acme.sh --install-cert -d mydomain --key-file /path/to/private.key --fullchain-file /path/to/certificate.crt --reloadcmd "sudo killall -s SIGUSR1 trojan"
```



But I am wondering if this will be a problem because `sudo` permissions sometimes require a password.

**Comment by SunZGitHub** [comment]
Solved, the reason is that I used different users to run acme.sh and trojan. The solution is to run the reload command with the same user as trojan. So the final command line is:

```bash
acme.sh --install-cert -d mydomain --key-file /path/to/private.key --fullchain-file /path/to/certificate.crt --reloadcmd "sudo -u nobody killall -s SIGUSR1 trojan"
```

@HarukaMa Thank you again for your guidance.
