### ISSUE TITLE
[BUG] cant run version 1.13.0

### ISSUE THREAD

**Issue by malikshi** [trojan-gfw/trojan#145]
force close when try start trojan
windows 10 pro x64
![Screenshot_229](https://user-images.githubusercontent.com/9080737/66492740-1a381380-eadf-11e9-857b-2e8a1bb4f015.jpg)

**Comment by GreaterFire** [comment]
@malikshi Please install MSVC 2017 runtime 64-bit https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by malikshi** [comment]
thanks @GreaterFire work pretty well
