### ISSUE TITLE
[BUG]Caddy报错

### ISSUE THREAD

**Issue by blog2020** [trojan-gfw/trojan#149]
Caddy配置了https，然后Caddy报错：Listen: listen tcp :443: bind: address already in use

Caddyfile：
domain.example {
        root /var/www
         tls 
}

请问Trojan是不是不能和Caddy一起使用？

**Comment by cattyhouse** [comment]
因为Trojan 本身就监听在 0.0.0.0:443, Caddy只能监听80或者其他端口, 给Trojan跳转用.

**Comment by blog2020** [comment]
> 因为Trojan 本身就监听在 0.0.0.0:443, Caddy只能监听80或者其他端口, 给Trojan跳转用.

没有办法解决了吗？只能2选一吗？

**Comment by cattyhouse** [comment]
请仔细阅读trojan的文档了解其运作方式. 目前没有什么比较好的办法.

**Comment by xt1085** [comment]
Caddy配置了https，然后Caddy报错：Listen: listen tcp :443: bind: address already in use,

你发错地了，去找caddy才对。

**Comment by blog2020** [comment]
> 请仔细阅读trojan的文档了解其运作方式. 目前没有什么比较好的办法.

如果把Trojan的端口改了，这样安全吗？

**Comment by cattyhouse** [comment]
不安全，改为443之外的端口，失去了https伪装的意义。

**Comment by blog2020** [comment]
> 不安全，改为443之外的端口，失去了https伪装的意义。

谢谢你，感谢你那么耐心教导，不像其他人，只会看不起新手，祝你一生平安。

**Comment by AaG7xNnrgbzeyqc5woPS** [comment]
caddy+trojan一起合用,trojan必须绑定在0.0.0.0:443上,转发非trojan流量到 caddy达到伪装的目的.
caddy应该绑定在0.0.0.0:80上,并且会自动重定位到, https://www.example.com.
caddy还应该绑定在 127.0.0.1:443上.接收从trojan转来的https流量.不过我调不通.
我的caddy和trojan 都是部署的docker版本的,用docker logs -f trojan查看trojan的日志,发现转发给 caddy的127.0.0.1:443端口TLS握手失败.我的证书申请成功,单独使用caddy也没有问题,可以使用https://www.example.com访问网站, http://www.example.com也可以自动跳转到443口.就是配合起来有问题啊,有没有高手出一个 trojan+caddy 一起的docker映像呢?
