### ISSUE TITLE
have some question when install

### ISSUE THREAD

**Issue by AndrewRussellGarfield** [trojan-gfw/trojan#15]
Build and Install

Type in

mkdir build
cd build/
cmake ..
make
ctest
sudo make install

root@11:~/trojan/build# make install
make: *** No rule to make target 'install'.  Stop.

**Comment by GreaterFire** [comment]
Can you show me the content of `~/trojan/CMakeLists.txt` and the result of `cmake ..` and `make`?

**Comment by AndrewRussellGarfield** [comment]
root@11:~# cat ~/trojan/CMakeLists.txt
cmake_minimum_required(VERSION 2.8.12)
project(Trojan)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -O2")
set(THREADS_PREFER_PTHREAD_FLAG ON)
add_executable(trojan src/clientsession.cpp src/config.cpp src/log.cpp src/main.cpp src/serversession.cpp src/service.cpp src/session.cpp src/trojanrequest.cpp src/version.cpp)
find_package(Threads REQUIRED)
target_link_libraries(trojan ${CMAKE_THREAD_LIBS_INIT})
find_package(Boost 1.54.0 REQUIRED COMPONENTS atomic chrono date_time system thread)
include_directories(${Boost_INCLUDE_DIR})
target_link_libraries(trojan ${Boost_LIBRARIES})
find_package(OpenSSL 1.0.2 REQUIRED)
include_directories(${OPENSSL_INCLUDE_DIR})
target_link_libraries(trojan ${OPENSSL_LIBRARIES})
if(WIN32)
    target_link_libraries(trojan wsock32 ws2_32)
else()
    install(TARGETS trojan DESTINATION bin)
    configure_file(examples/server.json-example trojan.json COPYONLY)
    install(FILES ${CMAKE_BINARY_DIR}/trojan.json DESTINATION /etc)
    if(EXISTS /etc/systemd/system)
        configure_file(examples/trojan.service-example trojan.service)
        install(FILES ${CMAKE_BINARY_DIR}/trojan.service DESTINATION /etc/systemd/system)
    endif()
    enable_testing()
    add_test(NAME LinuxSmokeTest-basic
             COMMAND sh ${CMAKE_SOURCE_DIR}/tests/LinuxSmokeTest/basic.sh ${CMAKE_BINARY_DIR}/trojan
             WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/tests/LinuxSmokeTest)
    add_test(NAME LinuxSmokeTest-fake-client
             COMMAND sh ${CMAKE_SOURCE_DIR}/tests/LinuxSmokeTest/fake-client.sh ${CMAKE_BINARY_DIR}/trojan
             WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/tests/LinuxSmokeTest)
endif()

root@11:~# cmake ..
CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

root@11:~# make
make: *** No targets specified and no makefile found.  Stop.

**Comment by GreaterFire** [comment]
You have to run `cmake ..` in the build directory.

**Comment by AndrewRussellGarfield** [comment]
root@11:~# cd trojan/
root@11:~/trojan# git checkout stable
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
root@11:~/trojan# mkdir build
mkdir: cannot create directory ‘build’: File exists
root@11:~/trojan# cd build/
root@11:~/trojan/build# cmake ..
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/root/trojan/build/CMakeFiles/CMakeOutput.log".
See also "/root/trojan/build/CMakeFiles/CMakeError.log".
root@11:~/trojan/build# make
make: *** No targets specified and no makefile found.  Stop.

**Comment by GreaterFire** [comment]
It means that you don't even have a C++ compiler installed. Please install `gcc(g++)` first.

**Comment by AndrewRussellGarfield** [comment]
I have installed g ++, but I still get the same error.

**Comment by AndrewRussellGarfield** [comment]
root@11:~/trojan/build# cmake ..
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   atomic
--   chrono
--   date_time
--   system
--   thread
CMake Error at /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.9/Modules/FindOpenSSL.cmake:388 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/trojan/build/CMakeFiles/CMakeOutput.log".
See also "/root/trojan/build/CMakeFiles/CMakeError.log".
root@11:~/trojan/build# make
make: *** No targets specified and no makefile found.  Stop.

**Comment by GreaterFire** [comment]
As is printed out, cmake cannot find OpenSSL by itself. If you have OpenSSL in your system, you can use `-DOPENSSL_ROOT_DIR=/path/to/openssl` to specify.

I recommend you to learn the basics of UNIX (or Linux) before trying to compile trojan. You should be able to solve these problems all by yourself even if the documentation did not mention a word of these.

Or, as an alternative way, you can use the binary and package distributions [here](https://github.com/trojan-gfw/trojan/wiki/Binary-&-Package-Distributions).

**Comment by AndrewRussellGarfield** [comment]
ok. Thanks.

**Comment by AndrewRussellGarfield** [comment]
Thank you. Server has been installed. Only domain names and certificates have not been done yet. Client how to connect to the server, whether there are clients now.

**Comment by GreaterFire** [comment]
Whether trojan is run as server or client depends on the config file. More details [here](https://trojan-gfw.github.io/trojan/config).

**Comment by AndrewRussellGarfield** [comment]
Hello, I have installed letsencrypt certificate. Domain has been registered, the site can visit. I now have a little doubt about the config configuration. keyfile_password this one does not seem to.

**Comment by GreaterFire** [comment]
`keyfile_password` is required only if your private key is protected by a passphrase. Let's encrypt does not encrypt the private key, so it is not useful.

**Comment by AndrewRussellGarfield** [comment]
ok

**Comment by AndrewRussellGarfield** [comment]
I reset my machine, so I have to reload trojan now. However, new problems have emerged.

root@11:~/trojan/build# make
[ 10%] Building CXX object CMakeFiles/trojan.dir/src/config.cpp.o

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/trojan.dir/build.make:86: recipe for target 'CMakeFiles/trojan.dir/src/config.cpp.o' failed
make[2]: *** [CMakeFiles/trojan.dir/src/config.cpp.o] Error 4
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/trojan.dir/all' failed
make[1]: *** [CMakeFiles/trojan.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by GreaterFire** [comment]
It's a compiler bug. Try compile again. If it fails again, update gcc.

**Comment by AndrewRussellGarfield** [comment]
ok

**Comment by AndrewRussellGarfield** [comment]
I have run the server and now connect on my computer. But can not visit Google.

**Comment by AndrewRussellGarfield** [comment]
This is log.

Welcome to trojan 0.3.2
[2017-11-23 09:52:49] fatal: config_file: cannot open file
[2017-11-23 09:52:49] exiting. . .

**Comment by GreaterFire** [comment]
You entered a file which does not exist.

**Comment by AndrewRussellGarfield** [comment]
Still can not use

root@11:~# cat log_file
Welcome to trojan 0.3.2
[2017-11-24 05:26:03] fatal: bind: Address already in use
[2017-11-24 05:26:03] exiting. . .

**Comment by AndrewRussellGarfield** [comment]
This is the server configuration

{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": "....",
    "keyfile": "...",
    "certfile": "...",
    "use_default_dhparam": true,
    "dhparamfile": "",
    "log_level": 1
}

**Comment by GreaterFire** [comment]
It means your 443 port is already in use. Have you already opened a trojan in the background, or do you have other program that is occupying 443? You may want to reboot your system and see whether this problem persists.

**Comment by AndrewRussellGarfield** [comment]
I restarted the vps.
and start the trojan.
Prompt the same mistake.
The server is running lnmp.
Can I use another port?

**Comment by GreaterFire** [comment]
Maybe your nginx is using 443. You can turn off nginx ssl or change trojan port in the config file.

**Comment by AndrewRussellGarfield** [comment]
root@11:~# cat log_file
Welcome to trojan 0.3.2
[2017-11-24 12:24:39] trojan service (server) started at 0.0.0.0:1080

The server is running, I still can not access Google.

**Comment by AndrewRussellGarfield** [comment]
2017-11-24 20:32:08] 127.0.0.1:60915 cannot establish connection to remote server ..........:80

**Comment by AndrewRussellGarfield** [comment]
[2017-11-24 20:32:58] 127.0.0.1:60913 SSL handshake failed with ........:80

**Comment by GreaterFire** [comment]
Your config file must be wrong in some sense.

**Comment by AndrewRussellGarfield** [comment]
Do you have a telegram, so communicate faster.

**Comment by GreaterFire** [comment]
Please provide me your telegram account, thank you. (You may delete it later)

**Comment by AndrewRussellGarfield** [comment]
@tiangaodihou

**Comment by elliott10** [comment]
No CMAKE_CXX_COMPILER could be found.
---
Solved:
```
yum install gcc-c++
```
