### ISSUE TITLE
[BUG] Network Protocol Error on the front page when using HTTP2

### ISSUE THREAD

**Issue by changhe3** [trojan-gfw/trojan#150]
- [ x ] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.13.0

**Describe the bug**
When using http2 protocol, the front page won't open and there is a network protocol error on firefox (ERR_HTTP2_PROTOCOL_ERROR on chrome). This doesn't happen when I changed the config.json to use http1.1

My config for nginx is:
```
server {
    listen 127.0.0.1:80 default_server;

    server_name <my domain name>;

    index /path/to/index.html
    location / {
        # serving some static pages ...
    }

}

server {
    listen 127.0.0.1:80;

    server_name <10.10.10.10>;

    return 301 https://<my domain name>$request_uri;
}

server {
    listen 0.0.0.0:80;
    listen [::]:80;

    server_name _;

    return 301 https://$host$request_uri;
}
```

**Comment by laboeuf** [comment]
```
# sudo nano /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
}
server {
        listen 8080 http2;
        server_name _;
        return 400;
}
```

**Comment by laboeuf** [comment]
```
# sudo nano /usr/local/etc/trojan/config.json
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 8080,
    ...
}
```

**Comment by ghost** [comment]
trojan server开启alpn开启h2

> 
> 
> ```
> # sudo nano /usr/local/etc/trojan/config.json
> {
>     "run_type": "server",
>     "local_addr": "0.0.0.0",
>     "local_port": 443,
>     "remote_addr": "127.0.0.1",
>     "remote_port": 8080,
>     ...
> }
> ```

trojan server 开启alpn h2

**Comment by GreaterFire** [comment]
@changhe3 Did you solve this problem?

**Comment by zhangzhhz** [comment]
I might have had the same problem when adding h2 in server.config.

The symptom is that I cannot connect to my server running at port 80.

> 127.0.0.1 - - [04/Jan/2020:19:30:17 +0000] "PRI * HTTP/2.0" 400 166 "-" "-"

It works fine if I remove h2 from server.config.

> 127.0.0.1 - - [04/Jan/2020:19:35:00 +0000] "GET / HTTP/1.1" 200 202 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"

**Comment by edmund-zhao** [comment]
在nginx server
listen 80 http2;

**Comment by GreaterFire** [comment]
Discussion move to #226

**Comment by Marukon** [comment]
> ```
> # sudo nano /etc/nginx/sites-available/default
> server {
>         listen 80 default_server;
>         server_name _;
>         return 301 https://$host$request_uri;
> }
> server {
>         listen 8080 http2;
>         server_name _;
>         return 400;
> }
> ```

This problem could be solved by this method, thank you.
