### ISSUE TITLE
Problems with wildcard certificate[BUG]

### ISSUE THREAD

**Issue by chnliupu** [trojan-gfw/trojan#151]
- [x] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.13.0

**Describe the bug**
SSL handshake failed with temp.[MyDomain].com:443: certificate verify failed

**To Reproduce**
1. Use acme to generate wildcard certificate
2. Setup server side
3. Configure client site to  "verify": true
Note:
a) It works fine when I use Shadowrocket and turn off 'Allow Insecure' and it also works fine when I use Trojan-gfw client and set "verify": false.
b) I used Chrome and Edge to access the my server on 443, they verified that my wildcard certificate is valid.
c) I tried "verify_hostname": false or set "sni":"*.[MyDomain].com", neither worked.

**Expected behavior**
Work fine.

**Logs**
SSL handshake failed with temp.[MyDomain].com:443: certificate verify failed

**Environment**
Client: Windows 10 64bit
Server: Debian 10 64bit

**Additional context**

**Comment by GreaterFire** [comment]
@chnliupu Wildcard verification should work due to compliance to relevant RFC. Can you post your server configuration? Did you use the fullchain certificate? What's your client's OS?

**Comment by chnliupu** [comment]
> @chnliupu Wildcard verification should work due to compliance to relevant RFC. Can you post your server configuration? Did you use the fullchain certificate? What's your client's OS?

No, I did not use full chain certificate. Problem was solved perfectly after replacing the certificate file with fullchain one. It's not a bug but my mistake. Thank you for your help.
