### ISSUE TITLE
[Feature Request] Add common dns proxy services to the "After=" section of trojan's systemd unit file

### ISSUE THREAD

**Issue by hachikujimayoi298** [trojan-gfw/trojan#152]
- [x] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
I am running dnscrypt-proxy2 along with trojan. One day after restarting my (linux x64) PC, dnscrypt-proxy2 stopped working and says that it can't retrieve source files from github. I fixed it only by stopping both trojan and dnscrypt-proxy, then start trojan after starting dnscrypt-proxy.

**Comment by GreaterFire** [comment]
Since this request is too general, and can be extended to any other services, I recommend you to add it yourself to your service file. The official file will remain the same and is served as just an example.
