### ISSUE TITLE
De-anonymization attacks from GitHub workflow timing correlation

### ISSUE THREAD

**Issue by klzgrad** [trojan-gfw/trojan#153]
Continuous Integration systems display the times when builds are triggered. And the builds are directly triggered by git pushes. If the git pushes as a form of network traffic traverse territory controlled by a man in the middle, then he can correlate the events of build triggering to the IP address of the initiator of the git pushes by synchronicity.

In short, if a public timestamp is triggered by network traffic through MitM, the traffic initiator's IP address can be deduced by the MitM.

**Comment by wi1dcard** [comment]
This is my first time hearing about that potential attacking. However, it sounds really possible.

**Comment by klzgrad** [comment]
Be careful if you push to GitHub with SSH.

**Comment by tomac4t** [comment]
BTW，Github REST API 本身提供了用户事件的 API，其中包括 Push、Release 和 IssueComment 等事件，时间戳精确到秒（Github actions 启动的时间戳要比 Push 事件滞后大约两秒）。即便删除了评论等内容，事件依旧会被保留：https://api.github.com/users/<username>/events?page=1&per_page=100
