### ISSUE TITLE
Hello! I want to make a transparent proxy using trojan-gfw. Local machine can access Internet but same lan can't

### ISSUE THREAD

**Issue by zhouhm** [trojan-gfw/trojan#154]
ipset -N privaddr hash:net
ipset add privaddr 0.0.0.0/8
ipset add privaddr 10.0.0.0/8
ipset add privaddr 100.64.0.0/10
ipset add privaddr 127.0.0.0/8
ipset add privaddr 169.254.0.0/16
ipset add privaddr 172.16.0.0/12
ipset add privaddr 192.0.0.0/24
ipset add privaddr 192.0.2.0/24
ipset add privaddr 192.88.99.0/24
ipset add privaddr 192.168.0.0/16
ipset add privaddr 198.18.0.0/15
ipset add privaddr 198.51.100.0/24
ipset add privaddr 203.0.113.0/24
ipset add privaddr 224.0.0.0/4
ipset add privaddr 240.0.0.0/4
ipset add privaddr 255.255.255.255/32

ipset -N chnroute hash:net
cat /etc/ss-tproxy/chnroute.set | while read line
do
  ipset $line
done

iptables -t nat    -N SSTP_PREROUTING
iptables -t nat    -N SSTP_OUTPUT
iptables -t nat -N SSTP_RULE
iptables -t nat -A SSTP_RULE -p tcp -d my_vps_IP -m multiport --dports 80,443 -j RETURN
iptables -t nat -A SSTP_RULE -m set --match-set privaddr dst -j RETURN
iptables -t nat -A SSTP_RULE -m set --match-set chnroute dst -j RETURN
iptables -t nat -A SSTP_RULE -p tcp -m multiport --dports 1:65535 --syn -j REDIRECT --to-ports 1080
iptables -t nat -A SSTP_OUTPUT -m addrtype --src-type LOCAL ! --dst-type LOCAL -p tcp -j SSTP_RULE
iptables -t nat -A SSTP_PREROUTING -m addrtype ! --src-type LOCAL ! --dst-type LOCAL -p tcp -j SSTP_RULE

iptables -t nat -N SSTP_POSTROUTING
iptables -t nat -A SSTP_POSTROUTING -m addrtype ! --src-type LOCAL -m conntrack --ctstate SNAT,DNAT   -j RETURN
iptables -t nat -A SSTP_POSTROUTING -m addrtype ! --src-type LOCAL -p tcp --syn                       -j MASQUERADE
iptables -t nat -A SSTP_POSTROUTING -m addrtype ! --src-type LOCAL -p udp -m conntrack --ctstate NEW  -j MASQUERADE
iptables -t nat -A SSTP_POSTROUTING -m addrtype ! --src-type LOCAL -p icmp -m conntrack --ctstate NEW -j MASQUERADE

iptables -t nat    -A PREROUTING  -j SSTP_PREROUTING
iptables -t nat    -A OUTPUT      -j SSTP_OUTPUT
iptables -t nat    -A POSTROUTING -j SSTP_POSTROUTING

iptables -t mangle -A PREROUTING  -p udp --dport 53 -j RETURN
iptables -t nat    -A PREROUTING -m addrtype ! --src-type LOCAL -p udp --dport 53 -j REDIRECT --to-ports 53

**Comment by zhouhm** [comment]
Same lan can access China net. 
I thought about the problem over and over again bu I just couldn't find the answer.

**Comment by changhe3** [comment]
Here is a [tutorial](https://github.com/yangchuansheng/love-gfw/blob/master/docs/iptables-linux.md) if you can read Chinese. This [tutorial](https://www.booleanworld.com/depth-guide-iptables-linux-firewall/) on iptables is also quite helpful.

**Comment by zhouhm** [comment]
多谢！

**Comment by lazywen** [comment]
@zhouhm 楼主有没有解决，我完全照着上面的步骤来的，网关可以上外网，但是lan设备上不了，同样的iptables rules换v2ray或者ss-redir就没问题
