### ISSUE TITLE
[Feature Request]能否出一个caddy+trojan教程,最好caddy+trojan打包成 一个docker images

### ISSUE THREAD

**Issue by AaG7xNnrgbzeyqc5woPS** [trojan-gfw/trojan#155]
0,我是caddy+trojan一起配合使用的,主要用作翻墙,caddy做伪装网站,暂时不考虑CDN
1,我的caddy和trojan 都是部署的docker版本的
2,caddy单独使用可以,绑定在80,和443端口。
    可以自动申请域名证书,https://www.example.com访问网站OK,
    http://www.example.com也可以自动跳转到443口.表现合格
3，trojan也绑定上面申请的证书，端口绑定在0.0.0.0:443, 
     caddy绑定在127.0.0.0:443,使用tls加密协议
     trojan将非trojan流量转发到127.0.0.0:443。
4，使用 docker logs -f trojan 监测 trojan发现 trojan 不能和 caddy建立TLS链接，总是失败。
5，刚才看了几篇文章，已经本站上的bug报告，再联想到 trojan转发是到远程网站的80端口。应该是http协议，回头再试试。
6， trojan能否翻墙还没有实验，这个可以先试试。
 
请求：有没有高手出一个 trojan+caddy 一起的docker映像呢?
1，包含网站证书的自动申请和续定。
2，trojan翻墙
3，网站伪装，80：443都可以访问，最后都定向到443端口，看起来就像一个正常的加密网站一样

**Comment by darkred424** [comment]
@AaG7xNnrgbzeyqc5woPS 两个都占443不可能的，然后caddy更新证书必须80和443没有别的程序占用，所以不存在的。比较接近的解法是服务器监听80，trojan监听443转80，用acme配合cron和脚本定期更新证书

**Comment by AaG7xNnrgbzeyqc5woPS** [comment]
> ，然后caddy更新证书必须80和443

caddy更新证书必须80和443，这个没有问题啊，我是在docker  容器里的，容器的80，443端口映射到127.0.0.1:443，0.0.0.0：80。这样 caddy就可以自动更新证书啦！回头试试，在没有一键解决方案前，只能自己摸索啦！

**Comment by unsciorg** [comment]
最好再给你装好～

**Comment by AaG7xNnrgbzeyqc5woPS** [comment]
> 最好再给你装好～
惭愧惭愧，已经找了一个一键脚本装好了，还是蛮好用的。放弃了docker方案，能用就行。就是一个服务器只装一个trojan有点浪费，先不折腾啦

**Comment by gorquan** [comment]
感谢你这个思路，让我解决了caddy和trojan同时占用443的问题

**Comment by rilyuuj** [comment]
> 感谢你这个思路，让我解决了caddy和trojan同时占用443的问题

请教一下如何解决，如果启用caddy自动续订证书的话，会同时占用80，443，而且好像无法设置端口。所有只能将torjan安装到docker，caddy在主机上运行，这是我的思路，不知道理解的对不对。
torjan            0.0.0.0:1443 > 443/tcp
caddy            0.0.0.0:443

**Comment by gorquan** [comment]
> > 感谢你这个思路，让我解决了caddy和trojan同时占用443的问题
> 
> 请教一下如何解决，如果启用caddy自动续订证书的话，会同时占用80，443，而且好像无法设置端口。所有只能将torjan安装到docker，caddy在主机上运行，这是我的思路，不知道理解的对不对。
> torjan 0.0.0.0:1443 > 443/tcp
> caddy 0.0.0.0:443

我现在是trojan和caddy分开两个docker,使用docker-compose启动。
没有证书的时候,让caddy占用443;等获取到证书了,让trojan占用443, caddy占用80即可。
对于续签这个问题应该是ok的,因为续签好像能访问网站就行,待测试。
也就是
``` shell
# 没有证书
caddy 0.0.0.0:443 > 443/tcp  0.0.0.0:80 > 80/tcp
trojan 443/tcp
# 签约证书后
caddy 443/tcp 0.0.0.0:80 > 80/tcp
trojan 0.0.0.0:443 > 443/tcp
```
docker-compose没有init container这个概念，所以需要手动修改端口占用，如果有init container这个概念就可以全自动部署了

**Comment by fsiisx** [comment]
> > > 感谢你这个思路，让我解决了caddy和trojan同时占用443的问题
> > 
> > 
> > 请教一下如何解决，如果启用caddy自动续订证书的话，会同时占用80，443，而且好像无法设置端口。所有只能将torjan安装到docker，caddy在主机上运行，这是我的思路，不知道理解的对不对。
> > torjan 0.0.0.0:1443 > 443/tcp
> > caddy 0.0.0.0:443
> 
> 我现在是trojan和caddy分开两个docker,使用docker-compose启动。
> 没有证书的时候,让caddy占用443;等获取到证书了,让trojan占用443, caddy占用80即可。
> 对于续签这个问题应该是ok的,因为续签好像能访问网站就行,待测试。
> 也就是
> 
> ```shell
> # 没有证书
> caddy 0.0.0.0:443 > 443/tcp  0.0.0.0:80 > 80/tcp
> trojan 443/tcp
> # 签约证书后
> caddy 443/tcp 0.0.0.0:80 > 80/tcp
> trojan 0.0.0.0:443 > 443/tcp
> ```
> 
> docker-compose没有init container这个概念，所以需要手动修改端口占用，如果有init container这个概念就可以全自动部署了

请问你trojan配置里的remote_addr填的什么，我填容器名caddy那边报错

**Comment by gorquan** [comment]
> > > > 感谢你这个思路，让我解决了caddy和trojan同时占用443的问题
> > > 
> > > 
> > > 请教一下如何解决，如果启用caddy自动续订证书的话，会同时占用80，443，而且好像无法设置端口。所有只能将torjan安装到docker，caddy在主机上运行，这是我的思路，不知道理解的对不对。
> > > torjan 0.0.0.0:1443 > 443/tcp
> > > caddy 0.0.0.0:443
> > 
> > 
> > 我现在是trojan和caddy分开两个docker,使用docker-compose启动。
> > 没有证书的时候,让caddy占用443;等获取到证书了,让trojan占用443, caddy占用80即可。
> > 对于续签这个问题应该是ok的,因为续签好像能访问网站就行,待测试。
> > 也就是
> > ```shell
> > # 没有证书
> > caddy 0.0.0.0:443 > 443/tcp  0.0.0.0:80 > 80/tcp
> > trojan 443/tcp
> > # 签约证书后
> > caddy 443/tcp 0.0.0.0:80 > 80/tcp
> > trojan 0.0.0.0:443 > 443/tcp
> > ```
> > 
> > 
> > docker-compose没有init container这个概念，所以需要手动修改端口占用，如果有init container这个概念就可以全自动部署了
> 
> 请问你trojan配置里的remote_addr填的什么，我填容器名caddy那边报错

填写你的容器名字。比如我这里指定caddy的容器名为`caddy_server`, 那么我的config中指定`"remote_addr": "caddy_server"`即可。不过我采用的是docker-compose，如果是单一docker运行的话需要另外测试了。

**Comment by fsiisx** [comment]
> > > > > 感谢你这个思路，让我解决了caddy和trojan同时占用443的问题
> > > > 
> > > > 
> > > > 请教一下如何解决，如果启用caddy自动续订证书的话，会同时占用80，443，而且好像无法设置端口。所有只能将torjan安装到docker，caddy在主机上运行，这是我的思路，不知道理解的对不对。
> > > > torjan 0.0.0.0:1443 > 443/tcp
> > > > caddy 0.0.0.0:443
> > > 
> > > 
> > > 我现在是trojan和caddy分开两个docker,使用docker-compose启动。
> > > 没有证书的时候,让caddy占用443;等获取到证书了,让trojan占用443, caddy占用80即可。
> > > 对于续签这个问题应该是ok的,因为续签好像能访问网站就行,待测试。
> > > 也就是
> > > ```shell
> > > # 没有证书
> > > caddy 0.0.0.0:443 > 443/tcp  0.0.0.0:80 > 80/tcp
> > > trojan 443/tcp
> > > # 签约证书后
> > > caddy 443/tcp 0.0.0.0:80 > 80/tcp
> > > trojan 0.0.0.0:443 > 443/tcp
> > > ```
> > > 
> > > 
> > > docker-compose没有init container这个概念，所以需要手动修改端口占用，如果有init container这个概念就可以全自动部署了
> > 
> > 
> > 请问你trojan配置里的remote_addr填的什么，我填容器名caddy那边报错
> 
> 填写你的容器名字。比如我这里指定caddy的容器名为`caddy_server`, 那么我的config中指定`"remote_addr": "caddy_server"`即可。不过我采用的是docker-compose，如果是单一docker运行的话需要另外测试了。

我也是如此 填的容器名 trojan用443 caddy用80 但是现在trojan能用 正常网站请求也会转发到caddy 但是caddy报错 网站最后不通

**Comment by gorquan** [comment]
> > > > > > 感谢你这个思路，让我解决了caddy和trojan同时占用443的问题
> > > > > 
> > > > > 
> > > > > 请教一下如何解决，如果启用caddy自动续订证书的话，会同时占用80，443，而且好像无法设置端口。所有只能将torjan安装到docker，caddy在主机上运行，这是我的思路，不知道理解的对不对。
> > > > > torjan 0.0.0.0:1443 > 443/tcp
> > > > > caddy 0.0.0.0:443
> > > > 
> > > > 
> > > > 我现在是trojan和caddy分开两个docker,使用docker-compose启动。
> > > > 没有证书的时候,让caddy占用443;等获取到证书了,让trojan占用443, caddy占用80即可。
> > > > 对于续签这个问题应该是ok的,因为续签好像能访问网站就行,待测试。
> > > > 也就是
> > > > ```shell
> > > > # 没有证书
> > > > caddy 0.0.0.0:443 > 443/tcp  0.0.0.0:80 > 80/tcp
> > > > trojan 443/tcp
> > > > # 签约证书后
> > > > caddy 443/tcp 0.0.0.0:80 > 80/tcp
> > > > trojan 0.0.0.0:443 > 443/tcp
> > > > ```
> > > > 
> > > > 
> > > > docker-compose没有init container这个概念，所以需要手动修改端口占用，如果有init container这个概念就可以全自动部署了
> > > 
> > > 
> > > 请问你trojan配置里的remote_addr填的什么，我填容器名caddy那边报错
> > 
> > 
> > 填写你的容器名字。比如我这里指定caddy的容器名为`caddy_server`, 那么我的config中指定`"remote_addr": "caddy_server"`即可。不过我采用的是docker-compose，如果是单一docker运行的话需要另外测试了。
> 
> 我也是如此 填的容器名 trojan用443 caddy用80 但是现在trojan能用 正常网站请求也会转发到caddy 但是caddy报错 网站最后不通

有种预感是你的caddy的配置文件有问题，我之前也好像遇到过。方便的话贴一下你的caddy配置出来看一下。

**Comment by fsiisx** [comment]
> > > > > > > 感谢你这个思路，让我解决了caddy和trojan同时占用443的问题
> > > > > > 
> > > > > > 
> > > > > > 请教一下如何解决，如果启用caddy自动续订证书的话，会同时占用80，443，而且好像无法设置端口。所有只能将torjan安装到docker，caddy在主机上运行，这是我的思路，不知道理解的对不对。
> > > > > > torjan 0.0.0.0:1443 > 443/tcp
> > > > > > caddy 0.0.0.0:443
> > > > > 
> > > > > 
> > > > > 我现在是trojan和caddy分开两个docker,使用docker-compose启动。
> > > > > 没有证书的时候,让caddy占用443;等获取到证书了,让trojan占用443, caddy占用80即可。
> > > > > 对于续签这个问题应该是ok的,因为续签好像能访问网站就行,待测试。
> > > > > 也就是
> > > > > ```shell
> > > > > # 没有证书
> > > > > caddy 0.0.0.0:443 > 443/tcp  0.0.0.0:80 > 80/tcp
> > > > > trojan 443/tcp
> > > > > # 签约证书后
> > > > > caddy 443/tcp 0.0.0.0:80 > 80/tcp
> > > > > trojan 0.0.0.0:443 > 443/tcp
> > > > > ```
> > > > > 
> > > > > 
> > > > > docker-compose没有init container这个概念，所以需要手动修改端口占用，如果有init container这个概念就可以全自动部署了
> > > > 
> > > > 
> > > > 请问你trojan配置里的remote_addr填的什么，我填容器名caddy那边报错
> > > 
> > > 
> > > 填写你的容器名字。比如我这里指定caddy的容器名为`caddy_server`, 那么我的config中指定`"remote_addr": "caddy_server"`即可。不过我采用的是docker-compose，如果是单一docker运行的话需要另外测试了。
> > 
> > 
> > 我也是如此 填的容器名 trojan用443 caddy用80 但是现在trojan能用 正常网站请求也会转发到caddy 但是caddy报错 网站最后不通
> 
> 有种预感是你的caddy的配置文件有问题，我之前也好像遇到过。方便的话贴一下你的caddy配置出来看一下。

现在电脑不在身边，你这边方便的去除隐私发下你的Caddyfile看看

**Comment by gorquan** [comment]
> > > > > > > > 感谢你这个思路，让我解决了caddy和trojan同时占用443的问题
> > > > > > > 
> > > > > > > 
> > > > > > > 请教一下如何解决，如果启用caddy自动续订证书的话，会同时占用80，443，而且好像无法设置端口。所有只能将torjan安装到docker，caddy在主机上运行，这是我的思路，不知道理解的对不对。
> > > > > > > torjan 0.0.0.0:1443 > 443/tcp
> > > > > > > caddy 0.0.0.0:443
> > > > > > 
> > > > > > 
> > > > > > 我现在是trojan和caddy分开两个docker,使用docker-compose启动。
> > > > > > 没有证书的时候,让caddy占用443;等获取到证书了,让trojan占用443, caddy占用80即可。
> > > > > > 对于续签这个问题应该是ok的,因为续签好像能访问网站就行,待测试。
> > > > > > 也就是
> > > > > > ```shell
> > > > > > # 没有证书
> > > > > > caddy 0.0.0.0:443 > 443/tcp  0.0.0.0:80 > 80/tcp
> > > > > > trojan 443/tcp
> > > > > > # 签约证书后
> > > > > > caddy 443/tcp 0.0.0.0:80 > 80/tcp
> > > > > > trojan 0.0.0.0:443 > 443/tcp
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > docker-compose没有init container这个概念，所以需要手动修改端口占用，如果有init container这个概念就可以全自动部署了
> > > > > 
> > > > > 
> > > > > 请问你trojan配置里的remote_addr填的什么，我填容器名caddy那边报错
> > > > 
> > > > 
> > > > 填写你的容器名字。比如我这里指定caddy的容器名为`caddy_server`, 那么我的config中指定`"remote_addr": "caddy_server"`即可。不过我采用的是docker-compose，如果是单一docker运行的话需要另外测试了。
> > > 
> > > 
> > > 我也是如此 填的容器名 trojan用443 caddy用80 但是现在trojan能用 正常网站请求也会转发到caddy 但是caddy报错 网站最后不通
> > 
> > 
> > 有种预感是你的caddy的配置文件有问题，我之前也好像遇到过。方便的话贴一下你的caddy配置出来看一下。
> 
> 现在电脑不在身边，你这边方便的去除隐私发下你的Caddyfile看看

```
https://site
{
    gzip
    log /var/log/site_caddy_443.log
    tls{
        dns cloudflare
    }
}
http://site
{
    gzip
    log /var/log/site_caddy_80.log
}
:80
{
    redir https://site
}
```
其中, site改为你对应的域名
