### ISSUE TITLE
[Feature Request]static built binaries for arm and mipsle

### ISSUE THREAD

**Issue by JimLee1996** [trojan-gfw/trojan#156]
It would be much more convenient to use rasp pi  as client, if  static build binaries are provided.

**Comment by JimLee1996** [comment]
[TrojanX.zip](https://github.com/trojan-gfw/trojan/files/3829481/TrojanX.zip)
参考ShadowsocksX-NG照葫芦画瓢做了个macOS的客户端。

**Comment by GreaterFire** [comment]
Raspbian has compiled binaries. We have no plan to compile for architectures other than `amd64`.
