### ISSUE TITLE
[BUG] Fail to verify the certificate on Mac

### ISSUE THREAD

**Issue by zhangsan946** [trojan-gfw/trojan#157]
- [x] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
A: 1.13.0

**Describe the bug**
A: If client.json's option is set to ssl:{verify:true, cert:"", ...} on Mac, trojan will not be able to proxy the traffic. If set to ssl:{verify:false, cert:"",...}, trojan is working well. On Windows, it works perfect as expected.

Error in trojan log: [ERROR] 127.0.0.1:50495 SSL handshake failed with xxx.xxxxxxxxx.xx:443: certificate verify failed
Certificate: let's encrypted issued free certificate. PS:Chrome & Safari recognizes it on Mac.

PS: I can provide with my trojan server for debug by PM.

**Comment by zhangsan946** [comment]
As per service.cpp, it seems there is only cert store reading implementation for Windows.

**Comment by zhangsan946** [comment]
@GreaterFire pr submited.

**Comment by GreaterFire** [comment]
Discussion moved to #160.

**Comment by alexseedkou-zz** [comment]
Hi all,

I still have the same issue. At first it works very well, but suddenly come up with the error as  certificate verify failed.

FYI, the cert is not expired.

Any help will be appreciated.

**Comment by yamato2199** [comment]
Hi all,
I have this issue with windows in version 1.15.1, the cert is not expired
I have someone using the same server for trojan but not have this issue
Any help will be appreciated.
