### ISSUE TITLE
tun2socks on win10 failed to connect through [Feature Request]

### ISSUE THREAD

**Issue by wanyancan** [trojan-gfw/trojan#159]
- [x] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
When using tun2socks to convert shadowsocks local socks server into tunnel for global proxy, there's no problem. However, if I use trojan's port for tunnel, it won't allow any packages go through.

**Is this problem relevant to what trojan should care about?**
Since Trojan is a protocol implementation, how do I convert it to global proxy as tunnel?

**Describe the solution you'd like**
Make trojan able to be proxy for all native windows programs using sockets because some does not have settings for proxies connection.

**Describe alternatives you've considered**
I wish an alternative won't be shadowsocks back again.

**Additional context**
Any way to use curl or wget to go through trojan port?

**Comment by malikshi** [comment]
Try with netch I using this one and very good.

**Comment by wanyancan** [comment]
Thank you for the info.
I just tried, and it seems to work with ss server directly. 
But when I configure it to use local socks5 proxy server created by ss 4.1.7.1 or trojan, neither works. 
The ping always show 1000 in red color.

**Comment by cncaihua** [comment]
maybe SSTap will be your choice.
https://sourceforge.net/projects/sstap/

**Comment by malikshi** [comment]
@wanyancan I will give u example later

**Comment by malikshi** [comment]
1. add sock5
![Screenshot_547](https://user-images.githubusercontent.com/9080737/70774020-9e429c00-1dab-11ea-8695-f7934b4316b5.jpg)
2. add bypass IP of trojan server
![Screenshot_548](https://user-images.githubusercontent.com/9080737/70774037-aa2e5e00-1dab-11ea-8deb-df0dae04925f.jpg)
3. select profile socks5 that u created and choose BYPASS LAN(TUN/TAP) 
![Screenshot_549](https://user-images.githubusercontent.com/9080737/70774057-b9ada700-1dab-11ea-86db-b888d9604b5b.jpg)
its work pretty well and i often using it for gaming and got no problem as long as your main connection was stable

**Comment by wanyancan** [comment]
I tried with 1.0.9.7 on github. It works! The one on sf is old and not working for me still.
https://github.com/githello123/sstap
