### ISSUE TITLE
trojan: error while loading shared libraries: libboost_atomic.so.1.65.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chenychen** [trojan-gfw/trojan#16]
trojan: error while loading shared libraries: libboost_atomic.so.1.65.1: cannot open shared object file: No such file or directory

**Comment by GreaterFire** [comment]
Can you specify your operating system and environment?

**Comment by klzgrad** [comment]
@GreaterFire I know there's maintenance hell in Boost's shared libraries, so use static linking if you can. How's the binary size with static linking?

**Comment by chenychen** [comment]
# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# env
MANPATH=:/root/.opam/default/man
XDG_SESSION_ID=8318956
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=113.89.55.236 20143 22
OPAM_SWITCH_PREFIX=/root/.opam/default
SSH_TTY=/dev/pts/0
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
PATH=/root/.opam/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/root
SHLVL=1
HOME=/root
LS_OPTIONS=--color=auto
LOGNAME=root
SSH_CONNECTION=113.89.55.236 20143 104.223.96.162 22
XDG_RUNTIME_DIR=/run/user/0
DISPLAY=localhost:10.0
_=/usr/bin/env

[root@ccggvps /usr/bin]# cd /usr/local/lib/
[root@ccggvps /usr/local/lib]# ll libboost*
-rw-r--r-- 1 root staff    2682 Nov 24 10:05 libboost_atomic.a
lrwxrwxrwx 1 root staff      25 Nov 24 10:30 libboost_atomic.so -> libboost_atomic.so.1.65.1
-rwxr-xr-x 1 root staff    8960 Nov 24 10:30 libboost_atomic.so.1.65.1
-rw-r--r-- 1 root staff  113814 Nov 24 10:59 libboost_chrono.a
lrwxrwxrwx 1 root staff      25 Nov 24 10:31 libboost_chrono.so -> libboost_chrono.so.1.65.1
-rwxr-xr-x 1 root staff   34960 Nov 24 10:31 libboost_chrono.so.1.65.1
-rw-r--r-- 1 root staff  172606 Nov 24 10:05 libboost_container.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:31 libboost_container.so -> libboost_container.so.1.65.1
-rwxr-xr-x 1 root staff  119976 Nov 24 10:31 libboost_container.so.1.65.1
-rw-r--r-- 1 root staff  112560 Nov 24 10:06 libboost_context.a
lrwxrwxrwx 1 root staff      26 Nov 24 10:31 libboost_context.so -> libboost_context.so.1.65.1
-rwxr-xr-x 1 root staff   71640 Nov 24 10:31 libboost_context.so.1.65.1
-rw-r--r-- 1 root staff  136244 Nov 24 10:06 libboost_coroutine.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:31 libboost_coroutine.so -> libboost_coroutine.so.1.65.1
-rwxr-xr-x 1 root staff   77648 Nov 24 10:31 libboost_coroutine.so.1.65.1
-rw-r--r-- 1 root staff  169028 Nov 24 10:06 libboost_date_time.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:32 libboost_date_time.so -> libboost_date_time.so.1.65.1
-rwxr-xr-x 1 root staff   95144 Nov 24 10:32 libboost_date_time.so.1.65.1
-rw-r--r-- 1 root staff    1750 Nov 24 10:59 libboost_exception.a
-rw-r--r-- 1 root staff  256012 Nov 24 10:06 libboost_filesystem.a
lrwxrwxrwx 1 root staff      29 Nov 24 10:32 libboost_filesystem.so -> libboost_filesystem.so.1.65.1
-rwxr-xr-x 1 root staff  133272 Nov 24 10:32 libboost_filesystem.so.1.65.1
-rw-r--r-- 1 root staff  917006 Nov 24 10:09 libboost_graph.a
lrwxrwxrwx 1 root staff      24 Nov 24 10:34 libboost_graph.so -> libboost_graph.so.1.65.1
-rwxr-xr-x 1 root staff  464408 Nov 24 10:34 libboost_graph.so.1.65.1
-rw-r--r-- 1 root staff  301220 Nov 24 10:09 libboost_iostreams.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:34 libboost_iostreams.so -> libboost_iostreams.so.1.65.1
-rwxr-xr-x 1 root staff  133120 Nov 24 10:34 libboost_iostreams.so.1.65.1
-rw-r--r-- 1 root staff 3320454 Nov 24 10:12 libboost_locale.a
lrwxrwxrwx 1 root staff      25 Nov 24 10:36 libboost_locale.so -> libboost_locale.so.1.65.1
-rwxr-xr-x 1 root staff 1214752 Nov 24 10:36 libboost_locale.so.1.65.1
-rw-r--r-- 1 root staff 3367382 Nov 24 10:15 libboost_log.a
lrwxrwxrwx 1 root staff      22 Nov 24 10:41 libboost_log.so -> libboost_log.so.1.65.1
-rwxr-xr-x 1 root staff 1217336 Nov 24 10:41 libboost_log.so.1.65.1
-rw-r--r-- 1 root staff 2640378 Nov 24 10:18 libboost_log_setup.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:44 libboost_log_setup.so -> libboost_log_setup.so.1.65.1
-rwxr-xr-x 1 root staff 1115384 Nov 24 10:44 libboost_log_setup.so.1.65.1
-rw-r--r-- 1 root staff  673096 Nov 24 10:21 libboost_math_c99.a
lrwxrwxrwx 1 root staff      27 Nov 24 10:48 libboost_math_c99.so -> libboost_math_c99.so.1.65.1
-rwxr-xr-x 1 root staff  103984 Nov 24 10:48 libboost_math_c99.so.1.65.1
-rw-r--r-- 1 root staff  567232 Nov 24 10:22 libboost_math_c99f.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:48 libboost_math_c99f.so -> libboost_math_c99f.so.1.65.1
-rwxr-xr-x 1 root staff   88104 Nov 24 10:48 libboost_math_c99f.so.1.65.1
-rw-r--r-- 1 root staff  592258 Nov 24 10:22 libboost_math_c99l.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:48 libboost_math_c99l.so -> libboost_math_c99l.so.1.65.1
-rwxr-xr-x 1 root staff   85840 Nov 24 10:48 libboost_math_c99l.so.1.65.1
-rw-r--r-- 1 root staff 2939966 Nov 24 10:19 libboost_math_tr1.a
lrwxrwxrwx 1 root staff      27 Nov 24 10:46 libboost_math_tr1.so -> libboost_math_tr1.so.1.65.1
-rwxr-xr-x 1 root staff  432096 Nov 24 10:46 libboost_math_tr1.so.1.65.1
-rw-r--r-- 1 root staff 2851006 Nov 24 10:20 libboost_math_tr1f.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:46 libboost_math_tr1f.so -> libboost_math_tr1f.so.1.65.1
-rwxr-xr-x 1 root staff  400120 Nov 24 10:46 libboost_math_tr1f.so.1.65.1
-rw-r--r-- 1 root staff 2913238 Nov 24 10:21 libboost_math_tr1l.a
lrwxrwxrwx 1 root staff      28 Nov 24 10:47 libboost_math_tr1l.so -> libboost_math_tr1l.so.1.65.1
-rwxr-xr-x 1 root staff  408104 Nov 24 10:47 libboost_math_tr1l.so.1.65.1
-rw-r--r-- 1 root staff  157422 Nov 24 10:28 libboost_prg_exec_monitor.a
lrwxrwxrwx 1 root staff      35 Nov 24 10:55 libboost_prg_exec_monitor.so -> libboost_prg_exec_monitor.so.1.65.1
-rwxr-xr-x 1 root staff   86336 Nov 24 10:55 libboost_prg_exec_monitor.so.1.65.1
-rw-r--r-- 1 root staff 1457464 Nov 24 10:23 libboost_program_options.a
lrwxrwxrwx 1 root staff      34 Nov 24 10:50 libboost_program_options.so -> libboost_program_options.so.1.65.1
-rwxr-xr-x 1 root staff  610800 Nov 24 10:50 libboost_program_options.so.1.65.1
-rw-r--r-- 1 root staff  640860 Nov 24 10:27 libboost_python.a
lrwxrwxrwx 1 root staff      25 Nov 24 10:53 libboost_python.so -> libboost_python.so.1.65.1
-rwxr-xr-x 1 root staff  370456 Nov 24 10:53 libboost_python.so.1.65.1
-rw-r--r-- 1 root staff   41010 Nov 24 10:27 libboost_random.a
lrwxrwxrwx 1 root staff      25 Nov 24 10:53 libboost_random.so -> libboost_random.so.1.65.1
-rwxr-xr-x 1 root staff   30792 Nov 24 10:53 libboost_random.so.1.65.1
-rw-r--r-- 1 root staff 3311556 Nov 24 10:08 libboost_regex.a
lrwxrwxrwx 1 root staff      24 Nov 24 10:33 libboost_regex.so -> libboost_regex.so.1.65.1
-rwxr-xr-x 1 root staff 1429504 Nov 24 10:33 libboost_regex.so.1.65.1
-rw-r--r-- 1 root staff 1260428 Nov 24 10:28 libboost_serialization.a
lrwxrwxrwx 1 root staff      32 Nov 24 10:54 libboost_serialization.so -> libboost_serialization.so.1.65.1
-rwxr-xr-x 1 root staff  455768 Nov 24 10:54 libboost_serialization.so.1.65.1
-rw-r--r-- 1 root staff  243970 Nov 24 10:28 libboost_signals.a
lrwxrwxrwx 1 root staff      26 Nov 24 10:55 libboost_signals.so -> libboost_signals.so.1.65.1
-rwxr-xr-x 1 root staff  124912 Nov 24 10:55 libboost_signals.so.1.65.1
-rw-r--r-- 1 root staff   60616 Nov 24 10:28 libboost_stacktrace_addr2line.a
lrwxrwxrwx 1 root staff      39 Nov 24 10:55 libboost_stacktrace_addr2line.so -> libboost_stacktrace_addr2line.so.1.65.1
-rwxr-xr-x 1 root staff   46408 Nov 24 10:55 libboost_stacktrace_addr2line.so.1.65.1
-rw-r--r-- 1 root staff   48068 Nov 24 10:28 libboost_stacktrace_backtrace.a
lrwxrwxrwx 1 root staff      39 Nov 24 10:55 libboost_stacktrace_backtrace.so -> libboost_stacktrace_backtrace.so.1.65.1
-rwxr-xr-x 1 root staff   68960 Nov 24 10:55 libboost_stacktrace_backtrace.so.1.65.1
-rw-r--r-- 1 root staff   40030 Nov 24 10:28 libboost_stacktrace_basic.a
lrwxrwxrwx 1 root staff      35 Nov 24 10:55 libboost_stacktrace_basic.so -> libboost_stacktrace_basic.so.1.65.1
-rwxr-xr-x 1 root staff   32896 Nov 24 10:55 libboost_stacktrace_basic.so.1.65.1
-rw-r--r-- 1 root staff    3026 Nov 24 10:28 libboost_stacktrace_noop.a
lrwxrwxrwx 1 root staff      34 Nov 24 10:55 libboost_stacktrace_noop.so -> libboost_stacktrace_noop.so.1.65.1
-rwxr-xr-x 1 root staff    7952 Nov 24 10:55 libboost_stacktrace_noop.so.1.65.1
-rw-r--r-- 1 root staff   60928 Nov 24 10:59 libboost_system.a
lrwxrwxrwx 1 root staff      25 Nov 24 10:30 libboost_system.so -> libboost_system.so.1.65.1
-rwxr-xr-x 1 root staff   19432 Nov 24 10:30 libboost_system.so.1.65.1
-rw-r--r-- 1 root staff 2631558 Nov 24 11:01 libboost_test_exec_monitor.a
-rw-r--r-- 1 root staff  357752 Nov 24 10:06 libboost_thread.a
lrwxrwxrwx 1 root staff      25 Nov 24 10:31 libboost_thread.so -> libboost_thread.so.1.65.1
-rwxr-xr-x 1 root staff  207656 Nov 24 10:31 libboost_thread.so.1.65.1
-rw-r--r-- 1 root staff   21884 Nov 24 10:59 libboost_timer.a
lrwxrwxrwx 1 root staff      24 Nov 24 10:55 libboost_timer.so -> libboost_timer.so.1.65.1
-rwxr-xr-x 1 root staff   21280 Nov 24 10:55 libboost_timer.so.1.65.1
-rw-r--r-- 1 root staff  117672 Nov 24 10:29 libboost_type_erasure.a
lrwxrwxrwx 1 root staff      31 Nov 24 10:58 libboost_type_erasure.so -> libboost_type_erasure.so.1.65.1
-rwxr-xr-x 1 root staff   76304 Nov 24 10:58 libboost_type_erasure.so.1.65.1
-rw-r--r-- 1 root staff 2597534 Nov 24 11:01 libboost_unit_test_framework.a
lrwxrwxrwx 1 root staff      38 Nov 24 10:57 libboost_unit_test_framework.so -> libboost_unit_test_framework.so.1.65.1
-rwxr-xr-x 1 root staff 1063312 Nov 24 10:57 libboost_unit_test_framework.so.1.65.1
-rw-r--r-- 1 root staff 4171002 Nov 24 10:30 libboost_wave.a
lrwxrwxrwx 1 root staff      23 Nov 24 10:59 libboost_wave.so -> libboost_wave.so.1.65.1
-rwxr-xr-x 1 root staff 1839968 Nov 24 10:59 libboost_wave.so.1.65.1
-rw-r--r-- 1 root staff  852582 Nov 24 10:28 libboost_wserialization.a
lrwxrwxrwx 1 root staff      33 Nov 24 10:54 libboost_wserialization.so -> libboost_wserialization.so.1.65.1
-rwxr-xr-x 1 root staff  322096 Nov 24 10:54 libboost_wserialization.so.1.65.1

**Comment by GreaterFire** [comment]
It might be that your system does not look for .so files in /usr/local/lib. Try copy or link relevant .so files to /usr/lib. Or, you can set an environment variable that looks for .so files in that path. I don't remember the variable name, you may Google it.

As @klzgrad suggested, you can also statically link libboost, it would not be so huge. Simply add a line

```
set(Boost_USE_STATIC_LIBS ON)
```

in the CMakeLists.txt and re-cmake and remake the whole project.

**Comment by chenychen** [comment]
tks!
it's ok now!

Welcome to trojan 0.3.2
[2017-11-24 14:53:49] trojan service (server) started at 0.0.0.0:443

**Comment by klzgrad** [comment]
@GreaterFire Boost's C++ libraries are not ABI-stable. I was suggesting you turn it on by default if you don't want people to have this same problem and report here 100 times (and if the binary size doesn't get too large).
