### ISSUE TITLE
[Client]Port TrojanX client for macOS

### ISSUE THREAD

**Issue by JimLee1996** [trojan-gfw/trojan#161]
I've referred to the ShadowsocksX-NG and port a mac client for self-use.

<img width="152" alt="image" src="https://user-images.githubusercontent.com/15334330/68989241-72043000-087e-11ea-9a69-8447745c2421.png">

Use it at your own risk.

[TrojanX.app.zip](https://github.com/trojan-gfw/trojan/files/3853888/TrojanX.app.zip)

https://github.com/JimLee1996/TrojanX.git

I will consider creating a repo after refracting the code.

**Comment by kunlee1105** [comment]
i can't run it...

**Comment by JimLee1996** [comment]
> i can't run it...

Plz post your system info, log and other useful details.

**Comment by sad-castle** [comment]
macOS 10.15.1 稳定使用

**Comment by kunlee1105** [comment]
> > i can't run it...
> 
> Plz post your system info, log and other useful details.

i have fixed the problem...i think it can be easier to use...

**Comment by zycI11** [comment]
Works well on macOS 10.14.5. Great job!

**Comment by babylife** [comment]
prefer runing on my latest MACOS version ,, will you package a version on windows ?

**Comment by dicrm** [comment]
每次重启电脑 都是需要手动点一下关闭再启动，才能起飞~ 不知是不是BUG

**Comment by shadowxw** [comment]
good job

**Comment by ghost** [comment]
Another client for windows, macOS and Linux based on ``shadowsocks-qt`` and ``trojan-qt``
https://github.com/TheWanderingCoel/Trojan-Qt5/releases

**Comment by timelessg** [comment]
It's useful, thanks

**Comment by sj1069** [comment]
Super helpful for those who know little about coding! Thank you!

**Comment by teel-writ-ros** [comment]
> I've referred to the ShadowsocksX-NG and port a mac client for self-use.
> 
> <img alt="image" width="152" src="https://user-images.githubusercontent.com/15334330/68989241-72043000-087e-11ea-9a69-8447745c2421.png">
> 
> Use it at your own risk.
> 
> [TrojanX.app.zip](https://github.com/trojan-gfw/trojan/files/3853888/TrojanX.app.zip)
> 
> I will consider creating a repo after refracting the code.

Thanks a lot! Looking forward to your new repo.

**Comment by JimLee1996** [comment]
https://github.com/JimLee1996/TrojanX.git

**Comment by liuwenbo200285** [comment]
> macOS 10.15.1 稳定使用

这个服务器怎么配置的？

**Comment by KimiYu** [comment]
it can't run on my latest MacOS version 10.15.4 (19E266).

**Comment by ParadiseHell** [comment]
> it can't run on my latest MacOS version 10.15.4 (19E266).

Me too.
