### ISSUE TITLE
Could anyone give some instruction on how to build this project on windows platform?

### ISSUE THREAD

**Issue by hannnnn-l** [trojan-gfw/trojan#162]
Hi all,

Could anyone give some instruction on how to build this project for / on windows platform?

I built this project on cygwin successfully; however, i got stuck when trying to build it from mingw-w64 and vs2019. There should be something wrong in my configuration. 

Can anyone tell me which way (mingw or vs201x) can be setup to build this project? 

Many thanks.

Han

**Comment by f3404923** [comment]
@shuanglengyunji 
You'd better build this in Linux system(e.g ubuntu,centos,debian)

**Comment by hannnnn-l** [comment]
I have achieved it by modified cmake file
