### ISSUE TITLE
[Feature Request]大神是否能出一个docker客户端

### ISSUE THREAD

**Issue by FreeJ233** [trojan-gfw/trojan#163]
大神您好，我像问一下Trojan有没有可能出个Docker的客户端。我有个不成熟的想法，在路由器docker中Trojan与v2ray服务端串联，然后用路由器带的v2ray客户端接受进行分流，如果用openwrt-trojan编译对我们小白来说不太友好。请问我这个方法可以行得通么？

**Comment by lifansama** [comment]
反正trojan也是客户端和服务端一样的文件，只要改改配置就行，官方的trojan-docker可以直接拿来用啊

**Comment by GreaterFire** [comment]
trojan/
