### ISSUE TITLE
搭建tls速度慢,仅300k

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#165]
配置搭好了trojan，历经步骤为安装必要环境，申请letsencrypt证书，修改配置文件(修改了local_addr 和cert key的地址)，trojan客户端是1.13，但是有几个问题
1.经测试vps运营商为hostwind搭建v2ray的tls付费域名速度达50M，现在用的v2ray+mkcp速度是100M,但我用linode搭建tls无论v2ray或trojan速度很慢，速度均在300k至500k，甚至满足不了流畅浏览网页的需求，域名解析服务器用的dnspod或付费域名的服务器也很慢，所有排除的DNS解析的原因
2.看起来trojan客户端并无异常，只是不少是disconnected，windows直接ping域名是可以ping通的，无论是国内或国外的网站ping，都可以ping通
想不出解决办法，所以来提问题
感谢

**Comment by ghost** [comment]
经过改进，开启了bbr加速，trojan速度达到了10M，上述所说的300k是在speedtest测试下的速度，而10m也是。域名使用的是.gq(不知道是否和这个有关)
实际体验来说，油管看4k视频，未开启bbr加速是视频统计信息显示速率为32k，而开启bbr加速后则是800k，仍然达不到预期。
预期上hostwind+v2ray搭建的tls可以流畅观看4k视频，测速达50m，而使用linode v2ray+mkcp测速可以跑满100M，但是一旦搭建tls，无论v2ray或trojan，就满足不了要求，按照现在速度来看，b站速度仍不能流畅播放。
仍在寻找解决办法...

**Comment by xt1085** [comment]
上专线啊别虐待小鸡了

**Comment by ghost** [comment]
> 上专线啊别虐待小鸡了

感觉不是这个原因吧...至少hostwind和linode至少应该可以到同样的效果吧...还可以再试试

**Comment by ghost** [comment]
世界加钱可及

**Comment by ghost** [comment]
> 世界加钱可及

同样的钱...只有我linode这么慢的吗...才10M...别人50M
所以说应该只是这个问题？？？不会吧 想不通

**Comment by ghost** [comment]
莫非移动宽带。。。

**Comment by ghost** [comment]
> 莫非移动宽带。。。

校园网 移动宽带不搭tls翻不出去

**Comment by yihongyuelan** [comment]
> 经过改进，开启了bbr加速，trojan速度达到了10M，上述所说的300k是在speedtest测试下的速度，而10m也是。域名使用的是.gq(不知道是否和这个有关)
> 实际体验来说，油管看4k视频，未开启bbr加速是视频统计信息显示速率为32k，而开启bbr加速后则是800k，仍然达不到预期。
> 预期上hostwind+v2ray搭建的tls可以流畅观看4k视频，测速达50m，而使用linode v2ray+mkcp测速可以跑满100M，但是一旦搭建tls，无论v2ray或trojan，就满足不了要求，按照现在速度来看，b站速度仍不能流畅播放。
> 仍在寻找解决办法...

gq免费域名？lz在哪申请的?freenom？我申请一直提示not available 
我认为trojan的目的 是极尽伪装，当你的运营商开始QoS你的时候，Trojan我认为是一个不错的选择

**Comment by ghost** [comment]
> 
> 
> > 莫非移动宽带。。。
> 
> 校园网 移动宽带不搭tls翻不出去

这个就没办法了，移动的出口本来就小，加钱换宽带吧。

**Comment by ghost** [comment]
> > > 莫非移动宽带。。。
> > 
> > 
> > 校园网 移动宽带不搭tls翻不出去
> 
> 这个就没办法了，移动的出口本来就小，加钱换宽带吧。

但是同样的校园网同学搭的tls就很稳50m，我搭的刚开bbr加速才10m，步骤我俩也检查过，感觉上想不出什么可能，现在我能想到的区别就是免费和付费域名，其余都试错过了

**Comment by ghost** [comment]
> > 经过改进，开启了bbr加速，trojan速度达到了10M，上述所说的300k是在speedtest测试下的速度，而10m也是。域名使用的是.gq(不知道是否和这个有关)
> > 实际体验来说，油管看4k视频，未开启bbr加速是视频统计信息显示速率为32k，而开启bbr加速后则是800k，仍然达不到预期。
> > 预期上hostwind+v2ray搭建的tls可以流畅观看4k视频，测速达50m，而使用linode v2ray+mkcp测速可以跑满100M，但是一旦搭建tls，无论v2ray或trojan，就满足不了要求，按照现在速度来看，b站速度仍不能流畅播放。
> > 仍在寻找解决办法...
> 
> gq免费域名？lz在哪申请的?freenom？我申请一直提示not available
> 我认为trojan的目的 是极尽伪装，当你的运营商开始QoS你的时候，Trojan我认为是一个不错的选择

.gq就是在freenom申请的啊，我申请的时候没遇到过not abaliable的提示，不清楚你是什么原因，或许你可以google一下

**Comment by ghost** [comment]
> 
> 
> > > > 莫非移动宽带。。。
> > > 
> > > 
> > > 校园网 移动宽带不搭tls翻不出去
> > 
> > 
> > 这个就没办法了，移动的出口本来就小，加钱换宽带吧。
> 
> 但是同样的校园网同学搭的tls就很稳50m，我搭的刚开bbr加速才10m，步骤我俩也检查过，感觉上想不出什么可能，现在我能想到的区别就是免费和付费域名，其余都试错过了

同一条线路？

**Comment by yihongyuelan** [comment]
> > > 经过改进，开启了bbr加速，trojan速度达到了10M，上述所说的300k是在speedtest测试下的速度，而10m也是。域名使用的是.gq(不知道是否和这个有关)
> > > 实际体验来说，油管看4k视频，未开启bbr加速是视频统计信息显示速率为32k，而开启bbr加速后则是800k，仍然达不到预期。
> > > 预期上hostwind+v2ray搭建的tls可以流畅观看4k视频，测速达50m，而使用linode v2ray+mkcp测速可以跑满100M，但是一旦搭建tls，无论v2ray或trojan，就满足不了要求，按照现在速度来看，b站速度仍不能流畅播放。
> > > 仍在寻找解决办法...
> > 
> > 
> > gq免费域名？lz在哪申请的?freenom？我申请一直提示not available
> > 我认为trojan的目的 是极尽伪装，当你的运营商开始QoS你的时候，Trojan我认为是一个不错的选择
> 
> .gq就是在freenom申请的啊，我申请的时候没遇到过not abaliable的提示，不清楚你是什么原因，或许你可以google一下

后面自己买了dynadot$0.99的垃圾域名 凑合用着，另外你要是觉得freenom的域名问题。试试把dns解析放到cloudflare，也可以试试bbrplus，或者更暴力的版本

**Comment by ghost** [comment]
> > > > > 莫非移动宽带。。。
> > > > 
> > > > 
> > > > 校园网 移动宽带不搭tls翻不出去
> > > 
> > > 
> > > 这个就没办法了，移动的出口本来就小，加钱换宽带吧。
> > 
> > 
> > 但是同样的校园网同学搭的tls就很稳50m，我搭的刚开bbr加速才10m，步骤我俩也检查过，感觉上想不出什么可能，现在我能想到的区别就是免费和付费域名，其余都试错过了
> 
> 同一条线路？

就是说同样的校园网，我俩的区别在于他用的hostwind v2ray 付费域名，我用的linode v2ray/trojan 免费域名，我们互换电脑使用配置文件，这样应该是保证了在同一网络下，结果是，他配置的tls无论什么网络很快且稳定，我的就无论什么时候都很慢

**Comment by ghost** [comment]
> 
> 
> > > > > > 莫非移动宽带。。。
> > > > > 
> > > > > 
> > > > > 校园网 移动宽带不搭tls翻不出去
> > > > 
> > > > 
> > > > 这个就没办法了，移动的出口本来就小，加钱换宽带吧。
> > > 
> > > 
> > > 但是同样的校园网同学搭的tls就很稳50m，我搭的刚开bbr加速才10m，步骤我俩也检查过，感觉上想不出什么可能，现在我能想到的区别就是免费和付费域名，其余都试错过了
> > 
> > 
> > 同一条线路？
> 
> 就是说同样的校园网，我俩的区别在于他用的hostwind v2ray 付费域名，我用的linode v2ray/trojan 免费域名，我们互换电脑使用配置文件，这样应该是保证了在同一网络下，结果是，他配置的tls无论什么网络很快且稳定，我的就无论什么时候都很慢

你用他的机器搭建试试

**Comment by ghost** [comment]
> > > > 经过改进，开启了bbr加速，trojan速度达到了10M，上述所说的300k是在speedtest测试下的速度，而10m也是。域名使用的是.gq(不知道是否和这个有关)
> > > > 实际体验来说，油管看4k视频，未开启bbr加速是视频统计信息显示速率为32k，而开启bbr加速后则是800k，仍然达不到预期。
> > > > 预期上hostwind+v2ray搭建的tls可以流畅观看4k视频，测速达50m，而使用linode v2ray+mkcp测速可以跑满100M，但是一旦搭建tls，无论v2ray或trojan，就满足不了要求，按照现在速度来看，b站速度仍不能流畅播放。
> > > > 仍在寻找解决办法...
> > > 
> > > 
> > > gq免费域名？lz在哪申请的?freenom？我申请一直提示not available
> > > 我认为trojan的目的 是极尽伪装，当你的运营商开始QoS你的时候，Trojan我认为是一个不错的选择
> > 
> > 
> > .gq就是在freenom申请的啊，我申请的时候没遇到过not abaliable的提示，不清楚你是什么原因，或许你可以google一下
> 
> 后面自己买了dynadot$0.99的垃圾域名 凑合用着，另外你要是觉得freenom的域名问题。试试把dns解析放到cloudflare，也可以试试bbrplus，或者更暴力的版本

这个的话，同学用的godaddy，我试过用godaddy的解析也是很慢，dnspod解析也很慢，cloudfare应该也是，没有试过。用他的机器搭建我觉得应该区分不出什么变量，但是试试bbrplus或许更好，更暴力的版本有哪些呢？
另外请问我上述的描述中还有没有其它可能会导致出现这种问题的？比如说没用nginx，或者少了什么必要的搭建步骤？

**Comment by ghost** [comment]
> 
> 
> > > > > 经过改进，开启了bbr加速，trojan速度达到了10M，上述所说的300k是在speedtest测试下的速度，而10m也是。域名使用的是.gq(不知道是否和这个有关)
> > > > > 实际体验来说，油管看4k视频，未开启bbr加速是视频统计信息显示速率为32k，而开启bbr加速后则是800k，仍然达不到预期。
> > > > > 预期上hostwind+v2ray搭建的tls可以流畅观看4k视频，测速达50m，而使用linode v2ray+mkcp测速可以跑满100M，但是一旦搭建tls，无论v2ray或trojan，就满足不了要求，按照现在速度来看，b站速度仍不能流畅播放。
> > > > > 仍在寻找解决办法...
> > > > 
> > > > 
> > > > gq免费域名？lz在哪申请的?freenom？我申请一直提示not available
> > > > 我认为trojan的目的 是极尽伪装，当你的运营商开始QoS你的时候，Trojan我认为是一个不错的选择
> > > 
> > > 
> > > .gq就是在freenom申请的啊，我申请的时候没遇到过not abaliable的提示，不清楚你是什么原因，或许你可以google一下
> > 
> > 
> > 后面自己买了dynadot$0.99的垃圾域名 凑合用着，另外你要是觉得freenom的域名问题。试试把dns解析放到cloudflare，也可以试试bbrplus，或者更暴力的版本
> 
> 这个的话，同学用的godaddy，我试过用godaddy的解析也是很慢，dnspod解析也很慢，cloudfare应该也是，没有试过。用他的机器搭建我觉得应该区分不出什么变量，但是试试bbrplus或许更好，更暴力的版本有哪些呢？
> 另外请问我上述的描述中还有没有其它可能会导致出现这种问题的？比如说没用nginx，或者少了什么必要的搭建步骤？

难道加个hosts很难吗？？？

**Comment by ghost** [comment]
> > > > > > 经过改进，开启了bbr加速，trojan速度达到了10M，上述所说的300k是在speedtest测试下的速度，而10m也是。域名使用的是.gq(不知道是否和这个有关)
> > > > > > 实际体验来说，油管看4k视频，未开启bbr加速是视频统计信息显示速率为32k，而开启bbr加速后则是800k，仍然达不到预期。
> > > > > > 预期上hostwind+v2ray搭建的tls可以流畅观看4k视频，测速达50m，而使用linode v2ray+mkcp测速可以跑满100M，但是一旦搭建tls，无论v2ray或trojan，就满足不了要求，按照现在速度来看，b站速度仍不能流畅播放。
> > > > > > 仍在寻找解决办法...
> > > > > 
> > > > > 
> > > > > gq免费域名？lz在哪申请的?freenom？我申请一直提示not available
> > > > > 我认为trojan的目的 是极尽伪装，当你的运营商开始QoS你的时候，Trojan我认为是一个不错的选择
> > > > 
> > > > 
> > > > .gq就是在freenom申请的啊，我申请的时候没遇到过not abaliable的提示，不清楚你是什么原因，或许你可以google一下
> > > 
> > > 
> > > 后面自己买了dynadot$0.99的垃圾域名 凑合用着，另外你要是觉得freenom的域名问题。试试把dns解析放到cloudflare，也可以试试bbrplus，或者更暴力的版本
> > 
> > 
> > 这个的话，同学用的godaddy，我试过用godaddy的解析也是很慢，dnspod解析也很慢，cloudfare应该也是，没有试过。用他的机器搭建我觉得应该区分不出什么变量，但是试试bbrplus或许更好，更暴力的版本有哪些呢？
> > 另外请问我上述的描述中还有没有其它可能会导致出现这种问题的？比如说没用nginx，或者少了什么必要的搭建步骤？
> 
> 难道加个hosts很难吗？？？

问题在于我所有google过的解决办法都没有提到过host的问题，这不属于我的常识范围内
不过您的回复让我增加两个思路：1.添加host 2.试bbrplus
感谢您的回复，我之后会去尝试

**Comment by xt1085** [comment]
你去超市买了两双鞋，a和b，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。

**Comment by ghost** [comment]
> 你去超市买了两双鞋，a和b，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。

1.hostwind和linode举例是为了说明两者搭建tls的速度差异，以及我想要的预期速度和说明目前搭建的tls速度远不达标
如果你说的两双鞋指的是v2ray和trojan的话，我是假定如果他使用trojan搭建仍然会很稳定的情况下给出我的问题(另外，如果你用自己的ip，付费域名，用v2ray搭tls很快的话，你会认为同样换了客户端它就会很慢吗)所以暂时先排除这一块考虑
就目前情况来说trojan搭建的tls确实很慢，难道不可以来trojan这里提问题？
2.我理解tls流程 域名--dns解析服务器--访问vps提供的ip
dns解析服务器更换--无法解决问题
所以问题在两段，另外本来搭建过的梯子很快我认为可以证明在vps提供的ip层面是没有问题的
所以只剩下域名的区别，付费域名买的是.com 所以我猜测是这个部分有影响
总的来说
我认为可能是vps提供商的问题和域名问题，来提问是想知道我这个猜测合不合理以及还有没有其它可能导致trojan搭建tls以致速度慢？

**Comment by ghost** [comment]
> 
> 
> > 你去超市买了两双鞋，a和b，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。
> 
> 1.hostwind和linode举例是为了说明两者搭建tls的速度差异，以及我想要的预期速度和说明目前搭建的tls速度远不达标
> 如果你说的两双鞋指的是v2ray和trojan的话，我是假定如果他使用trojan搭建仍然会很稳定的情况下给出我的问题(另外，如果你用自己的ip，付费域名，用v2ray搭tls很快的话，你会认为同样换了客户端它就会很慢吗)所以暂时先排除这一块考虑
> 就目前情况来说trojan搭建的tls确实很慢，难道不可以来trojan这里提问题？
> 2.我理解tls流程 域名--dns解析服务器--访问vps提供的ip
> dns解析服务器更换--无法解决问题
> 所以问题在两段，另外本来搭建过的梯子很快我认为可以证明在vps提供的ip层面是没有问题的
> 所以只剩下域名的区别，付费域名买的是.com 所以我猜测是这个部分有影响
> 总的来说
> 我认为可能是vps提供商的问题和域名问题，来提问是想知道我这个猜测合不合理以及还有没有其它可能导致trojan搭建tls以致速度慢？

https://www.johnrosen1.com/trojan/ remote_addr 填ip sni填域名有请

**Comment by xt1085** [comment]
既然你听不懂，重新给你标一下
你去超市买了两双鞋，a[hostwind]和b[linode]，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。

**Comment by ghost** [comment]
> 
> 
> > 你去超市买了两双鞋，a和b，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。
> 
> 1.hostwind和linode举例是为了说明两者搭建tls的速度差异，以及我想要的预期速度和说明目前搭建的tls速度远不达标
> 如果你说的两双鞋指的是v2ray和trojan的话，我是假定如果他使用trojan搭建仍然会很稳定的情况下给出我的问题(另外，如果你用自己的ip，付费域名，用v2ray搭tls很快的话，你会认为同样换了客户端它就会很慢吗)所以暂时先排除这一块考虑
> 就目前情况来说trojan搭建的tls确实很慢，难道不可以来trojan这里提问题？
> 2.我理解tls流程 域名--dns解析服务器--访问vps提供的ip
> dns解析服务器更换--无法解决问题
> 所以问题在两段，另外本来搭建过的梯子很快我认为可以证明在vps提供的ip层面是没有问题的
> 所以只剩下域名的区别，付费域名买的是.com 所以我猜测是这个部分有影响
> 总的来说
> 我认为可能是vps提供商的问题和域名问题，来提问是想知道我这个猜测合不合理以及还有没有其它可能导致trojan搭建tls以致速度慢？

你让他用你的机器建，你用他的，互换试试。。。

**Comment by lunemoe** [comment]
你的正确做法应该是贴出你的配置，不然没人知道你究竟怎么配置的

**Comment by ghost** [comment]
> 既然你听不懂，重新给你标一下
> 你去超市买了两双鞋，a[hostwind]和b[linode]，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。

是指hostwind和linode的话，就更好说了，如果不是我的配置有问题，那么就可以说linode不要用trojan，否则很慢？即使认为你所建议的是linode和hostwind区别，对解决我的问题没有帮助
如果没有再提供建议的话，恕不再回复

**Comment by ghost** [comment]
抱歉 因为在上课 没有贴出配置

**Comment by ghost** [comment]
> 
> 
> > 既然你听不懂，重新给你标一下
> > 你去超市买了两双鞋，a[hostwind]和b[linode]，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。
> 
> 是指hostwind和linode的话，就更好说了，如果不是我的配置有问题，那么就可以说linode不要用trojan，否则很慢？即使认为你所建议的是linode和hostwind区别，对解决我的问题没有帮助
> 如果没有再提供建议的话，恕不再回复

不如这样，你们都用Trojan搭，不用v2,控制变量一下。。。

**Comment by ghost** [comment]
我主要参考的是这个https://vave.men/trojan.html
客户端：
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 10800,
    "remote_addr": "www.域名.gq", //如果不加www就无法连上
    "remote_port": 443,
    "password": [
        "密码"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:RSA-AES128-GCM-SHA256:RSA-AES256-GCM-SHA384:RSA-AES128-SHA:RSA-AES256-SHA:RSA-3DES-EDE-SHA",
        "sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}
服务器配置
{
    "run_type": "server",
    "local_addr": "::",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "密码1",
        "密码2"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/etc/letsencrypt/live/证书/fullchain.pem",
        "key": "/etc/letsencrypt/live/密钥/privkey.pem",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
}
}

**Comment by ghost** [comment]
> > > 既然你听不懂，重新给你标一下
> > > 你去超市买了两双鞋，a[hostwind]和b[linode]，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。
> > 
> > 
> > 是指hostwind和linode的话，就更好说了，如果不是我的配置有问题，那么就可以说linode不要用trojan，否则很慢？即使认为你所建议的是linode和hostwind区别，对解决我的问题没有帮助
> > 如果没有再提供建议的话，恕不再回复
> 
> 不如这样，你们都用Trojan搭，不用v2,控制变量一下。。。

其实很难，别人都搭好了分享出去了，怎么还能要求再用他再重新搭一次...

**Comment by ghost** [comment]
> > > > 既然你听不懂，重新给你标一下
> > > > 你去超市买了两双鞋，a[hostwind]和b[linode]，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。
> > > 
> > > 
> > > 是指hostwind和linode的话，就更好说了，如果不是我的配置有问题，那么就可以说linode不要用trojan，否则很慢？即使认为你所建议的是linode和hostwind区别，对解决我的问题没有帮助
> > > 如果没有再提供建议的话，恕不再回复
> > 
> > 
> > 不如这样，你们都用Trojan搭，不用v2,控制变量一下。。。
> 
> 其实很难，别人都搭好了分享出去了，怎么还能要求再用他再重新搭一次...

v2和Trojan可以共存啊。。。

**Comment by ghost** [comment]
> > > > > 既然你听不懂，重新给你标一下
> > > > > 你去超市买了两双鞋，a[hostwind]和b[linode]，然后发现b夹脚。然后你找超市，你应该要求给你退或者换，而不是问超市为啥这个b他就夹脚了？更不是去问超市因为a不夹脚，凭啥b就要夹脚。
> > > > 
> > > > 
> > > > 是指hostwind和linode的话，就更好说了，如果不是我的配置有问题，那么就可以说linode不要用trojan，否则很慢？即使认为你所建议的是linode和hostwind区别，对解决我的问题没有帮助
> > > > 如果没有再提供建议的话，恕不再回复
> > > 
> > > 
> > > 不如这样，你们都用Trojan搭，不用v2,控制变量一下。。。
> > 
> > 
> > 其实很难，别人都搭好了分享出去了，怎么还能要求再用他再重新搭一次...
> 
> v2和Trojan可以共存啊。。。

可以是可以，我现在就是共存的...但是即使搭了比我快要么说明是运营商有问题，要么是电脑本身有问题，但无论哪一个...都不是实际的解决方案...
但大家都这么说...估计就只能归结为运营商的问题了

**Comment by maboloshi** [comment]
域名DNS设置 怎么样的？

**Comment by DolorHunter** [comment]
> 
> 
> > 经过改进，开启了bbr加速，trojan速度达到了10M，上述所说的300k是在speedtest测试下的速度，而10m也是。域名使用的是.gq(不知道是否和这个有关)
> > 实际体验来说，油管看4k视频，未开启bbr加速是视频统计信息显示速率为32k，而开启bbr加速后则是800k，仍然达不到预期。
> > 预期上hostwind+v2ray搭建的tls可以流畅观看4k视频，测速达50m，而使用linode v2ray+mkcp测速可以跑满100M，但是一旦搭建tls，无论v2ray或trojan，就满足不了要求，按照现在速度来看，b站速度仍不能流畅播放。
> > 仍在寻找解决办法...
> 
> gq免费域名？lz在哪申请的?freenom？我申请一直提示not available
> 我认为trojan的目的 是极尽伪装，当你的运营商开始QoS你的时候，Trojan我认为是一个不错的选择

freenom 申请域名出现 not available 可能是因为访问IP跟资料填写的地区不符合, 修改资料内的地区即可. 
如果不确定自己访问的IP, 可在确认申请的最后一步网页下方查看登录的IP地址. 请检查是否与资料一致.

**Comment by zhang1122244** [comment]
我也出现了这个问题，楼主解决了吗?

**Comment by GF-Huang** [comment]
显然是你的线路问题，在下长城宽带已是总所周知的垃圾运营商，使用香港出口测试 Trojan 油管看视频一样跑满带宽 100Mbps。

**Comment by Nleo87** [comment]
我家里同样的wife带宽环境，使用购买的订阅使用小火箭和V2rayN都非常的快，但自己按照YouTube的教学 ，用谷歌云搭建的Trojan用起来却非常的慢，测试了好多谷歌云vps，美国200ms,香港60ms的都非常卡，视频也只能跑300k。希望群里有热心大牛给，告诉我问题出在了哪里，，，，，非常感谢你们的帮助

**Comment by GF-Huang** [comment]
> 我家里同样的wife带宽环境，使用购买的订阅使用小火箭和V2rayN都非常的快，但自己按照YouTube的教学 ，用谷歌云搭建的Trojan用起来却非常的慢，测试了好多谷歌云vps，美国200ms,香港60ms的都非常卡，视频也只能跑300k。希望群里有热心大牛给，告诉我问题出在了哪里，，，，，非常感谢你们的帮助

可能是你的 wife 出了问题 [滑稽]

**Comment by boweic** [comment]
有同样问题，发现似乎是域名的问题
同样客户端/服务端，当客户端使用域名连接服务端时，youtube 速度 2000k，当使用 ip 直接连接服务端，速度飚到 30000k

**Comment by Gsam333** [comment]
netstat -antup | grep ssh
试试看检查有没有不明的ssh连接。可用key取消密码登录
