### ISSUE TITLE
[Feature Request]Is it possible for multiple node use authenticator DB while authenticate with different password?

### ISSUE THREAD

**Issue by wqgame** [trojan-gfw/trojan#166]
- [x] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
多节点配置一个远程DB鉴权时，无法对每个节点单独设置密码、单独统计流量。

**Is this problem relevant to what trojan should care about?**
如果能支持不同节点不同密码、流量统计，会更友好。

**Describe the solution you'd like**
1、users表增加一个字段，用于标识节点，如node_identify
2、节点服务器端配置增加一个字段，用于标识节点，如`"node_identify": "node_slave_01"`
3、在节点连接鉴权、关闭连接统计流量时，根据配置的节点标识来区分数据

**Describe alternatives you've considered**
如果无法支持，则可能需要每个节点独立带一个DB，管理上会更复杂。

**Additional context**
无。

**Comment by GreaterFire** [comment]
The design decision here was to provide a central database for user authentication. If you want distributed authentication, you should setup a database for each node.
