### ISSUE TITLE
请问大神有没有手机版？

### ISSUE THREAD

**Issue by mophisalgmail** [trojan-gfw/trojan#167]
请问大神有没有手机版？多谢

**Comment by txdywy** [comment]
有，wiki里写了😆

mophisalgmail <notifications@github.com> 于 2019年11月30日周六 下午6:21写道：

**Comment by 4fm** [comment]
安卓应该还没有PAC

**Comment by 0x07f** [comment]
> 请问大神有没有手机版？多谢

自取不谢https://github.com/oasiscifr/igniter
