### ISSUE TITLE
vps多ip出口的问题，求开发者回复，谢谢！

### ISSUE THREAD

**Issue by mailrock** [trojan-gfw/trojan#168]
你好，我通过单vps配置了两个ip，配置了通配的*.domain.com , 通过通配ssl配置的两个二级域名指定不同的ip，a.domian.com(指定主ip），b.domian.com (指定副ip），然后将老大里trojan服务器段的private.key与fullchain.cer替换，并同步更新客户端的fullchain.cer，两个域名均测试访问成功，但问题来了，在进入ip138.coml两个域名测出来的ip都是主ip的，而另一个域名的副ip则不能作为ip出口。如何设置才能b.domian.com访问ip138.com的时候显示为副ip呢？是不是内部防火墙需要添加什么路由转发的条件？这个我不会。

有没有解决的办法？是不是需要配置vps防火墙内部转发的问题？或者说trojan有没有办法可以配置多用户多端口从而将不同用户的流量转发至服务器上配置的不同的公网ip？具体是规则怎么写？

**Comment by zpccode** [comment]
![image](https://user-images.githubusercontent.com/26158775/70205982-fdc3fa80-1760-11ea-8365-4fe9bc2f5ce5.png)

**Comment by maboloshi** [comment]
@mailrock 你域名DNS怎么设置的？给2个子域名分别设置A记录绑定不同的ip

**Comment by KevinZonda** [comment]
Try iptables NAT forwarding.
If you cannot write iptables, the fastest and most convenient solution is that run trojan on Docker. And the argument -p should write like "-p $outsiteIP:$outsitePort:$inDockerPort".
