### ISSUE TITLE
SSL handshake failed with xxx.xx

### ISSUE THREAD

**Issue by chenychen** [trojan-gfw/trojan#17]
同443端口，使用letsencrypt生成的证书。
选择不使用ssl，能正常连接：
"ssl_verify":false,
"ssl_verify_hostname":false

使用ssl验证，报错SSL handshake failed with xxx.xx

**Comment by GreaterFire** [comment]
Please set the `ca_certs` field in the config file to my provided example (examples/ca_certs.pem-example) or your server certificate file.

**Comment by chenychen** [comment]
{
"run_type":"client",
"ssl_verify":true,
"ssl_verify_hostname":true,
"ca_certs":"E:/trojan-gui-0.1.1-0.3.2-win/trojan-gui/fullchain.pem",
"local_addr":"127.0.0.1",
"local_port":9080,
"remote_addr":"xxxx",
"remote_port":443,
"password":"xxxx",
"log_level":1
}

已经设置了，还是不行。

**Comment by chenychen** [comment]
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": "xxxx",
    "keyfile": "/etc/letsencrypt/live/www.xxxx.tk/privkey.pem",
    "keyfile_password": "",
    "certfile": "/etc/letsencrypt/live/www.xxxx.tk/fullchain.pem",
    "use_default_dhparam": true,
    "dhparamfile": "",
    "log_level": 1
}

**Comment by GreaterFire** [comment]
try examples/ca_certs.pem-example

**Comment by chenychen** [comment]
so handsome you are!
it's ok!
