### ISSUE TITLE
[BUG] 开启h2后，网站图片加载失败，且ssllab显示http failure

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#171]
- [ok ] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
1.13.0
**Describe the bug**
服务器和nginx均开启h2情况下，访问网站图片加载失败，去掉h2支持后加载正常
**To Reproduce**

**Expected behavior**
图片加载正常
**Logs**
If applicable, add logs to help explain your problem.
not trojan request, connecting to 127.0.0.1:80
**Environment**
Where are you running trojan? What is your proxy set up?
debian9 nginx
**Additional context**
h2有bug,开启后ssllab会出现http failure,仅使用http1.1则不会

**Comment by GreaterFire** [comment]
Please provide your nginx configuration.

**Comment by ghost** [comment]
server {
  listen 127.0.0.1:80 http2;
    server_name $domain;
    location / {
      root /usr/share/nginx/html/;
        index index.html;
        }
  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
}

server {
    listen 80;
    listen [::]:80;
    server_name $domain;
    return 301 https://$domain;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 444;
}

**Comment by blankhang** [comment]
http2 不支持 http(80)协议吧....
放到443端口试试

**Comment by ghost** [comment]
> http2 不支持 http(80)协议吧....
> 放到443端口试试

请你自己调试通过再说

**Comment by blankhang** [comment]
> > http2 不支持 http(80)协议吧....
> > 放到443端口试试
> 
> 请你自己调试通过再说

废话 我生产服务器都是443 才开http2 
建议你先好好学习下 http2

**Comment by ghost** [comment]
> > > http2 不支持 http(80)协议吧....
> > > 放到443端口试试
> > 
> > 
> > 请你自己调试通过再说
> 
> 废话 我生产服务器都是443 才开http2
> 建议你先好好学习下 http2

我是指你用Trojan当前端的情况下

**Comment by GreaterFire** [comment]
@blankhang Please don't try to answer this question if you have no idea what the problem is.

@johnrosen1 Can you provide any browser debug info when loading the images?

**Comment by al123xiaaaa** [comment]
h2是个啥？

**Comment by tomac4t** [comment]
Trojan server have an unexpected behaviour if it enable HTTP/2 as @johnrosen1 said.

Trojan version for test: [1.10.0-3](https://packages.debian.org/buster/trojan)

config.json:
```
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "password1",
        "password2"
    ],
    "log_level": 2,
    "ssl": {
        "cert": "/path/to/certificate.crt",
        "key": "/path/to/private.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305$
        "prefer_server_cipher": true,
        "alpn": [
            "h2", //<-- enable HTTP/2, disable by default. 
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": ""
    }
}
```
Trojan servers can't server HTTPS as normal Nginx server if enable HTTP/2, although it doesn't effect the proxy feature. Note that it doesn't use Nginx as reserve proxy:
```
curl -vvv https://example.com/
*   Trying aa.bb.cc.dd...
* TCP_NODELAY set
* Connected to example.com (aa.bb.cc.dd) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=example.com
[...]
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1
> GET / HTTP/2
> Host: example.com
> User-Agent: curl/7.64.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
* Connection #0 to host example.com left intact
curl: (16) Error in the HTTP2 framing layer
```

**Comment by laboeuf** [comment]
需要升级到debian 10，

**Comment by tomac4t** [comment]
> 需要升级到debian 10，

It's not relate to this issue, you can reproduce it even on Debian buster. @laboeuf

**Comment by GreaterFire** [comment]
I'll try to look into this myself. Thanks for reporting it.

**Comment by GreaterFire** [comment]
I can't reproduce this bug. With my configuration everything works fine.

Nginx config:
```nginx
    server {
        listen       127.0.0.1:80 http2;
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
```

Trojan config:
```json
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "password1",
        "password2"
    ],
    "log_level": 0,
    "ssl": {
        "cert": "certificate.crt",
        "key": "private.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
        "cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": ""
    }
}
```

**Comment by ghost** [comment]
> I can't reproduce this bug. With my configuration everything works fine.
> 
> Nginx config:
> 
> ```nginx
>     server {
>         listen       127.0.0.1:80 http2;
>         server_name  localhost;
>         location / {
>             root   /usr/share/nginx/html;
>             index  index.html index.htm;
>         }
>         error_page   500 502 503 504  /50x.html;
>         location = /50x.html {
>             root   /usr/share/nginx/html;
>         }
>     }
> ```
> 
> Trojan config:
> 
> ```json
> {
>     "run_type": "server",
>     "local_addr": "0.0.0.0",
>     "local_port": 443,
>     "remote_addr": "127.0.0.1",
>     "remote_port": 80,
>     "password": [
>         "password1",
>         "password2"
>     ],
>     "log_level": 0,
>     "ssl": {
>         "cert": "certificate.crt",
>         "key": "private.key",
>         "key_password": "",
>         "cipher": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
>         "cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
>         "prefer_server_cipher": true,
>         "alpn": [
>             "h2",
>             "http/1.1"
>         ],
>         "reuse_session": true,
>         "session_ticket": false,
>         "session_timeout": 600,
>         "plain_http_response": "",
>         "curves": "",
>         "dhparam": ""
>     },
>     "tcp": {
>         "prefer_ipv4": false,
>         "no_delay": true,
>         "keep_alive": true,
>         "reuse_port": false,
>         "fast_open": false,
>         "fast_open_qlen": 20
>     },
>     "mysql": {
>         "enabled": false,
>         "server_addr": "127.0.0.1",
>         "server_port": 3306,
>         "database": "trojan",
>         "username": "trojan",
>         "password": ""
>     }
> }
> ```

all right, i will check again

**Comment by ghost** [comment]
> I can't reproduce this bug. With my configuration everything works fine.
> 
> Nginx config:
> 
> ```nginx
>     server {
>         listen       127.0.0.1:80 http2;
>         server_name  localhost;
>         location / {
>             root   /usr/share/nginx/html;
>             index  index.html index.htm;
>         }
>         error_page   500 502 503 504  /50x.html;
>         location = /50x.html {
>             root   /usr/share/nginx/html;
>         }
>     }
> ```
> 
> Trojan config:
> 
> ```json
> {
>     "run_type": "server",
>     "local_addr": "0.0.0.0",
>     "local_port": 443,
>     "remote_addr": "127.0.0.1",
>     "remote_port": 80,
>     "password": [
>         "password1",
>         "password2"
>     ],
>     "log_level": 0,
>     "ssl": {
>         "cert": "certificate.crt",
>         "key": "private.key",
>         "key_password": "",
>         "cipher": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
>         "cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
>         "prefer_server_cipher": true,
>         "alpn": [
>             "h2",
>             "http/1.1"
>         ],
>         "reuse_session": true,
>         "session_ticket": false,
>         "session_timeout": 600,
>         "plain_http_response": "",
>         "curves": "",
>         "dhparam": ""
>     },
>     "tcp": {
>         "prefer_ipv4": false,
>         "no_delay": true,
>         "keep_alive": true,
>         "reuse_port": false,
>         "fast_open": false,
>         "fast_open_qlen": 20
>     },
>     "mysql": {
>         "enabled": false,
>         "server_addr": "127.0.0.1",
>         "server_port": 3306,
>         "database": "trojan",
>         "username": "trojan",
>         "password": ""
>     }
> }
> ```

@GreaterFire HTTP request to this server failed, see below for details.  ssllab still show this error
config is the exact same as yours and web speed is still low comparing to h2 being disabled

**Comment by tomac4t** [comment]
I build the lastest trojan and test it. The problem is gone.

**Comment by aglent** [comment]
> 
> 
> I build the lastest trojan and test it. The problem was gone.

How to build the lastest trojan? thanks

**Comment by tomac4t** [comment]
> How to build the lastest trojan? thanks

Hello @aglent, please see https://github.com/trojan-gfw/trojan/blob/master/docs/build.md.

**Comment by ghost** [comment]
it seems to be a bug of ssllab,close issue

**Comment by WillyPillow** [comment]
EDIT: This is already discussed in #226, sorry for the duplicate.

Upon inspection, this seems to be due to <https://trac.nginx.org/nginx/ticket/808>.

Specifically, since nginx does not support placing h2c (http2 over TCP) and http1.1 on the same port, clients that only support http1.1 would fail. This can be verified by running `curl -v --http1.1 https://example.com` to a server running, say, the configuration posted by @GreaterFire .

It may be possible to mitigate this by changing `remote_port` according to the received ALPN and running nginx on two separate ports. If you guys think that this is an acceptable solution, I can try to cook up a PR in the coming days.
