### ISSUE TITLE
TLS1.3支持 0-RTT吗？

### ISSUE THREAD

**Issue by w22gb8** [trojan-gfw/trojan#172]
用wireshark看新建连接和会话恢复都是1-RTT，trojan需额外配置还是不支持 0-RTT？

**Comment by tomac4t** [comment]
为什么会要 0-RTT，它本身有重放攻击的问题。

**Comment by GreaterFire** [comment]
Sorry. Because of the complications of the OpenSSL API on 0-RTT and other security implications, 0-RTT will not be supported.
