### ISSUE TITLE
[Question] UDP connections.

### ISSUE THREAD

**Issue by xsm1997** [trojan-gfw/trojan#174]
I want to know that using client mode, a UDP request is using encrypted TCP connection or using encrypted UDP connection. I did't see any UDP open port in the server.

Briefly, I want to know that Trojan is SOCKS5-like (open a udp port to handle udp request) or v2ray-like (encapsulate udp request in tcp connection).

**Comment by wi1dcard** [comment]
I believe it's the latter. According to [the docs](https://trojan-gfw.github.io/trojan/protocol), the Trojan protocol is based on TLS. The most common TLS implements are layered on top of TCP.
