### ISSUE TITLE
[Feature Request]I want a socks implementation of user/pass.

### ISSUE THREAD

**Issue by ioxuy** [trojan-gfw/trojan#176]
thank you

**Comment by ioxuy** [comment]
like this:

"run_type": "client",
"local_addr": "0.0.0.0",
"local_port": 1080,
"socks5_authentication":username:password

**Comment by GreaterFire** [comment]
I don't understand the purpose. SOCKS5 is an insecure protocol and should never be exposed to the network other than your own computer. If it's your own computer then you don't need this feature.

**Comment by rahxcn** [comment]
It's likely he has a relay server somewhere on the internet and wanted to use it to tunnel all traffic through it, be it at home or outside on a mobile device, or even occasionally on a stranger's computer.

**Comment by GreaterFire** [comment]
This is too insecure. Won't implement.
