### ISSUE TITLE
[BUG] Please FIX Recv-Q hang

### ISSUE THREAD

**Issue by malikshi** [trojan-gfw/trojan#178]
**Trojan Version**
1.13.0

**Describe the bug**
i have users like 50-100 per server setting with trojan-panel. u often got some feedback that speed are super slow so i try lookup in `netstat/ss` Recv-Q are 129 and all connection would supa slow. could you fix this matter trojan cant handle many connection at same time.

**Comment by oasiscifr** [comment]
@malikshi Maybe you can run multiple trojan instances on each server and use nginx with stream context as a load-balancer.

**Comment by ghost** [comment]
change sysctl configs may help you

**Comment by malikshi** [comment]
i am using optimize from shadowsocks on `/etc/sysctl.conf`
>>vm.vfs_cache_pressure = 50
vm.swappiness= 40
fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.ipv4.conf.all.forwarding=1
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

**Comment by ghost** [comment]
> 
> 
> i am using optimize from shadowsocks on `/etc/sysctl.conf`
> 
> > > vm.vfs_cache_pressure = 50
> > > vm.swappiness= 40
> > > fs.file-max = 51200
> > > net.core.rmem_max = 67108864
> > > net.core.wmem_max = 67108864
> > > net.core.netdev_max_backlog = 250000
> > > net.core.somaxconn = 4096
> > > net.ipv4.tcp_syncookies = 1
> > > net.ipv4.tcp_tw_reuse = 1
> > > net.ipv4.tcp_fin_timeout = 30
> > > net.ipv4.tcp_keepalive_time = 1200
> > > net.ipv4.ip_local_port_range = 10000 65000
> > > net.ipv4.tcp_max_syn_backlog = 8192
> > > net.ipv4.tcp_max_tw_buckets = 5000
> > > net.ipv4.tcp_fastopen = 3
> > > net.ipv4.tcp_mem = 25600 51200 102400
> > > net.ipv4.tcp_rmem = 4096 87380 67108864
> > > net.ipv4.tcp_wmem = 4096 65536 67108864
> > > net.ipv4.tcp_mtu_probing = 1
> > > net.ipv4.conf.all.forwarding=1
> > > net.core.default_qdisc = fq
> > > net.ipv4.tcp_congestion_control = bbr

net.ipv4.tcp_slow_start_after_idle = 0 try this

**Comment by oasiscifr** [comment]
@malikshi And before that, you have to find out what bound the throughput. It could be your downlink brandwidth, CPU, max opened socket number, or the throughput of trojan.

**Comment by malikshi** [comment]
@oasiscifr 
>>net.ipv4.tcp_slow_start_after_idle = 0 try this

i will try it.

>>It could be your downlink brandwidth, CPU, max opened socket number, or the throughput of trojan

for this one, shadowsocks connection are normal. and when one user connected all normal i got 60-100Mbps. the problem are when many users connected its gona speed down for all clients side

**Comment by wongsyrone** [comment]
Please provide the full netstat/ss output.

**Comment by malikshi** [comment]
![Screenshot_662](https://user-images.githubusercontent.com/9080737/74126776-c287f100-4c13-11ea-9fed-779750ae67b4.jpg)
here im stuck again @GreaterFire  @wongsyrone .

**Comment by GreaterFire** [comment]
It's strange as this bug is fixed in `1.12.3`. Can you try the latest version (`1.14.1`)?

**Comment by malikshi** [comment]
> It's strange as this bug is fixed in `1.12.3`. Can you try the latest version (`1.14.1`)?

yeah its confusing me, its latest version i just installed it last night. the other 2 server are fine, 1 kvm(2core) with 1 users multiple login , and 1 openvz6(4core) are good. but this one kvm too with 2 core but always stuck tcp hang, setting `sysctl` are same as other kvm.

**Comment by malikshi** [comment]
i think its cpu related, the one using 
>>CPU model            : Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz
Number of cores      : 2
CPU frequency        : 2297.335 MHz
Total size of Disk   : 20.2 GB (10.1 GB Used)
Total amount of Mem  : 1982 MB (423 MB Used)
Total amount of Swap : 3995 MB (44 MB Used)
System uptime        : 9 days, 21 hour 50 min
Load average         : 0.40, 0.33, 0.36
OS                   : Ubuntu 18.04.4 LTS
Arch                 : x86_64 (64 Bit)
Kernel               : 4.15.0-76-generic

are working pretty well no error like that often.
but this spec vps often got stuck up. any idea @GreaterFire ?
>>CPU model            : QEMU Virtual CPU version (cpu64-rhel6)
Number of cores      : 2
CPU frequency        : 3500.024 MHz
Total size of Disk   : 58.2 GB (6.8 GB Used)
Total amount of Mem  : 1993 MB (480 MB Used)
Total amount of Swap : 4095 MB (1 MB Used)
System uptime        : 8 days, 8 hour 23 min
Load average         : 1.13, 1.10, 2.24
OS                   : Ubuntu 18.04 LTS
Arch                 : x86_64 (64 Bit)
Kernel               : 4.15.0-76-generic
