### ISSUE TITLE
Resolver behavior

### ISSUE THREAD

**Issue by klzgrad** [trojan-gfw/trojan#18]
There is a certain website resolved to one ipv4 address and one ipv6 address. The resolved ipv6 address does not work (`curl -6 https://the.website` times out).

In my testing the trojan server connects to the ipv6 address and does not work. It should be able to connect to the ipv4 address.

So far it's just one case. I used this workaround.

```diff
--- a/src/serversession.cpp
+++ b/src/serversession.cpp
@@ -103,6 +103,14 @@ void ServerSession::in_recv(const string &data) {
                         tcp::resolver::query query(req.address, to_string(req.port));
                         resolver.async_resolve(query, [this, self](const boost::system::error_code error, tcp::resolver::iterator iterator) {
                             if (!error) {
+auto v4it = iterator;
+for (auto v4it = iterator; v4it != tcp::resolver::iterator(); ++v4it) {
+  const auto& addr = v4it->endpoint().address();
+  if (!addr.is_v6()) {
+    iterator = v4it;
+    break;
+  }
+}
                                 out_socket.async_connect(*iterator, [this, self](const boost::system::error_code error) {
                                     if (!error) {
                                         Log::log_with_endpoint(in_endpoint, "tunnel established");
```

This is not limited to ipv4/6 dual stack resolutions. If a domain name resolves to multiple addresses and one of them doesn't work, the resolver needs to do something intelligent to blacklist that not working address.

Not action is required at this time. In the future using chromium's network stack should automatically solve this problem.

**Comment by GreaterFire** [comment]
What this patch does is to connect to IPv4 by default even if there are IPv6 addresses present.

It could be when the connection fails, we move on to the next IP in the DNS answer.

**Comment by GreaterFire** [comment]
I won't fix this bug since it'll be easily fixed with the Chromium version, and the scenario is rather rare.
However, I might add a switch `prefer_ipv4` in the server config.

**Comment by GreaterFire** [comment]
Due to the increased demand on this functionality, I'll introduce it in version `1.10.0`.
