### ISSUE TITLE
[Feature Request] Is it possible to provide luci-app-trojian?

### ISSUE THREAD

**Issue by hzqim** [trojan-gfw/trojan#181]

**Comment by GreaterFire** [comment]
What is it?

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/71551544-f96bc400-2a24-11ea-9659-b07d986e664e.png)

like this

**Comment by wongsyrone** [comment]
Sorry, I don't know Lua and don't have enough time to maintain it.
