### ISSUE TITLE
There's a tracking script embedded in project README, what's the purpose?

### ISSUE THREAD

**Issue by ttimasdf** [trojan-gfw/trojan#182]
If the point of this project is to protect freedom and anonymity, to bypass censorship, then why do you want to track your users?

At the same time, Github has [countermesures for this kind of tracking](https://help.github.com/en/github/authenticating-to-github/about-anonymized-image-urls) for long. So thankfully the trick won't work. All the IP address you collected will be Github's server backend.

This accusation may be personal, but it matters when it comes to privacy. If there's a track in your web page, **why can't there be any sneaky things in your binary release**? Moreover, **is this a government-funded project**?

Related parts in [README.md](https://github.com/trojan-gfw/trojan/blob/98533aa1003979862763f4225266de78581e40bc/README.md)

```md
## Flag Counter

[![Flag Counter](https://s04.flagcounter.com/countxl/svnh/bg_FFFFFF/txt_000000/border_CCCCCC/columns_5/maxflags_20/viewers_Trojan/labels_1/pageviews_1/flags_0/percent_0/)](https://info.flagcounter.com/svnh)
```

ToS from the tracking image provider

> INFORMATION COLLECTED BY A FLAG COUNTER
> 
> A Flag Counter image itself placed on a website does not collect personally identifiable information. We are not able to determine whether a particular person has viewed a particular counter. The counter collects the minimum information that we believe is necessary to provide our service.
> 
> A Flag Counter displays information about the countries and/or regions that have viewed a particular counter publicly, as is its purpose.
> 
> Our counter service is a simple image. When an image loads from our server, the visitor's web browser automatically provides us with certain information including the visitor's IP address, the URL of the referring page (where the image was placed), and the user-agent string of the visitor (which ordinarily contains the type and version of a visitor's web browser and operating system). However, the information we log is limited.
> 
> When the image is requested, our service queries a third-party company's database which is locally hosted on our servers (no information is transmitted to the third-party company. Our service does not use GPS nor do we request or have access to a visitor's precise location). This allows us to determine the country and/or region most likely associated with a particular visitor's IP address, at which time that country and/or region is added as a visit to the counter.
> 
> To prevent a returning visitor from repeatedly adding to a counter's statistics, a combination of the visitor's IP address and the particular counter's username are converted to an encrypted hash (which we cannot reverse), and then the hash itself is placed into a filter (for up to seven days after which it is erased). This method allows our counters to operate without the use of cookies.
> 
> IP addresses of a counter's visitors are not logged or otherwise associated with a particular visit.
> 
> Counters provided as part of our free service:
> Most of our customer use free counters. These counters do not keep a log of information. These counters only increment a tally of the visitor counts we have associated with a particular country/region and/or date.
> 
> Counters provided as part of our paid Flag Counter Pro service:
> Some of our customers have upgraded to our paid Flag Counter Pro service. When an upgraded counter loads, it will log the visit's referring page URL (as provided by their browser1), the detected country and/or region of the visitor, and the visitor's web browser (such as Firefox) and operating system (such as Windows 10) as indicated in the visitor's user-agent string; this limited logged information is made available for a period of up to 90 days.
> 
> We do not build profiles on a counter's visitors nor do we attempt to track or associate visitors from one counter to another. The Flag Counter image does not use cookies. Adding the counter to your website will not cause any cookies or advertising on your website itself.
> 
> 1To prevent recording a potential leakage of personal information from third-party sites, query strings are automatically stripped from a referring page URL.

**Comment by GreaterFire** [comment]
Don't use it if you don't trust it. It's just that simple.
