### ISSUE TITLE
[BUG] Build Failed on GNU/Hurd

### ISSUE THREAD

**Issue by GreaterFire** [trojan-gfw/trojan#183]
https://github.com/trojan-gfw/trojan/blob/18763b7529963efef8dcb01f50389a6f49213ae1/src/core/service.cpp#L29-L31

In GNU/Hurd, `__MACH__` is also defined, but the macOS specific header file doesn't exist.

**Comment by wongsyrone** [comment]
> Some applications put Apple Darwin-specific code inside `#ifdef __MACH__` guards. Such guard is clearly not enough, since not only Apple uses Mach as a kernel. This should be replaced by `#if defined(__MACH__) && defined(__APPLE__)`

https://www.gnu.org/software/hurd/hurd/porting/guidelines.html
