### ISSUE TITLE
[Feature Request]32-bit os release request

### ISSUE THREAD

**Issue by DeIn221** [trojan-gfw/trojan#186]
as title.

**Comment by GreaterFire** [comment]
@DeIn221 The pre-built binaries are generated as a courtesy, and is handled by CI/CD (Azure Pipelines). We take no responsibilities in providing binaries based on user needs.

**Comment by DeIn221** [comment]
> @DeIn221 The pre-built binaries are generated as a courtesy, and is handled by CI/CD (Azure Pipelines). We take no responsibilities in providing binaries based on user needs.

sorry, i can not understand. I just reconfirm you got me. I mean, I want a 32-bit os version of the program. This can't be done, right?

**Comment by wongsyrone** [comment]
> sorry, i can not understand. I just reconfirm you got me. I mean, I want a 32-bit os version of the program. This can't be done, right?

You may compile it per your request. If you have no idea how to do that, ask experts around.

**Comment by DeIn221** [comment]
> > sorry, i can not understand. I just reconfirm you got me. I mean, I want a 32-bit os version of the program. This can't be done, right?
> 
> You may compile it per your request. If you have no idea how to do that, ask experts around.

i am not compile it, just run it, i mean a version of release.i hope it could run it on my 32-bit computer.

**Comment by GreaterFire** [comment]
@DeIn221 We will not provide such release. Sorry.

**Comment by foxundermoon** [comment]
[trojan.zip](https://github.com/trojan-gfw/trojan/files/4052246/trojan.zip)  for arm v7  32
