### ISSUE TITLE
[BUG] 32位 ARM merlin 系统上运行不了。

### ISSUE THREAD

**Issue by lonee6** [trojan-gfw/trojan#189]
Welcome to trojan 1.14.0
[2019-12-30 17:27:22] [FATAL] fatal: set_option: Protocol not available
[2019-12-30 17:27:22] [FATAL] exiting. . . 

交叉编译的，在R6300V2上运行不了。

**Comment by wongsyrone** [comment]
What's your Linux kernel version?

**Comment by lonee6** [comment]
uname -a
Linux R6300V2 2.6.36.4brcmarm #1 SMP PREEMPT Tue Sep 25 19:50:36 CST 2018 armv7l Merlin-Koolshare

**Comment by lonee6** [comment]
可能是内核太老用不了？
刚才找wd my colud mirror试了一下，可以用，CPU也是arm V7
但系统内核是3.1的

uname -a
Linux NAS 3.10.39 #1 SMP Thu Aug 29 20:35:52 PDT 2019 2014T30p5 Build-gitad56653 armv7l GNU/Linux

2.6的是不是就没办法用了？

**Comment by wongsyrone** [comment]
> 2.6.36.4

Please use a recent kernel.

**Comment by lonee6** [comment]
> > 2.6.36.4
> 
> Please use a recent kernel.

这是梅林的固件，升级不了内核。但是，SS和V2Ray都是可以正常使用的。
如果确实是因为内核版本用不了trojan，那只好想别的办法了。

**Comment by zhaibin18** [comment]
> Welcome to trojan 1.14.0
> [2019-12-30 17:27:22] [FATAL] fatal: set_option: Protocol not available
> [2019-12-30 17:27:22] [FATAL] exiting. . .
> 
> 交叉编译的，在R6300V2上运行不了。

求编译方法，我想用buildroot作为编译工具想静态编译，但是没有成功。

**Comment by GreaterFire** [comment]
Could you provide your trojan config? I'm trying to figure out which `set_option` call failed, whether it's `socket_acceptor.set_option(tcp::acceptor::reuse_address(true))` or `socket_acceptor.set_option(reuse_port(true))`.

**Comment by wongsyrone** [comment]
> SO_REUSEPORT (since Linux 3.9)

https://lwn.net/Articles/542629/
http://man7.org/linux/man-pages/man7/socket.7.html

**Comment by GreaterFire** [comment]
@wongsyrone `SO_REUSEPORT` can be disabled via config. That's why I asked for config.

**Comment by lonee6** [comment]
> Could you provide your trojan config? I'm trying to figure out which `set_option` call failed, whether it's `socket_acceptor.set_option(tcp::acceptor::reuse_address(true))` or `socket_acceptor.set_option(reuse_port(true))`.

`{
    "run_type": "client",
    "local_addr": "0.0.0.0",
    "local_port": 1080,
    "remote_addr": "107.175.x.x",
    "remote_port": 443,
    "password": [
        "xxxxxxxx"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:RSA-AES128-GCM-SHA256:RSA-AES256-GCM-SHA384:RSA-AES128-SHA:RSA-AES256-SHA:RSA-3DES-EDE-SHA",
        "cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "xxxx.com",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": true,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": true,
        "fast_open": true,
        "fast_open_qlen": 20
    }
}`

**Comment by lonee6** [comment]
这个改reuse_port": true设置成false，问题解决了。

R6300V2:/lib# ./trojan -c config.json 
Welcome to trojan 1.14.0
[2020-01-02 16:10:47] [WARN] trojan service (client) started at 0.0.0.0:1080

**Comment by zhaibin18** [comment]
> 这个改reuse_port": true设置成false，问题解决了。
> 
> R6300V2:/lib# ./trojan -c config.json
> Welcome to trojan 1.14.0
> [2020-01-02 16:10:47] [WARN] trojan service (client) started at 0.0.0.0:1080

恭喜，求编译方法或者来个编译好的bin，谢谢啦。

**Comment by lonee6** [comment]
> > 这个改reuse_port": true设置成false，问题解决了。
> > R6300V2:/lib# ./trojan -c config.json
> > Welcome to trojan 1.14.0
> > [2020-01-02 16:10:47] [WARN] trojan service (client) started at 0.0.0.0:1080
> 
> 恭喜，求编译方法或者来个编译好的bin，谢谢啦。

https://github.com/trojan-gfw/trojan/issues/127#issuecomment-569949850

**Comment by babylife** [comment]
求编译好的bin文件 感谢

**Comment by loveklmn** [comment]
Your work is important. Everyone would be appreciated if you are willing to share.

**Comment by rampageX** [comment]
trojan.v1.14.1.arm7l.static.rar，用 tomatoware 静态编译，适用于 Asus RT-AC68U，Netgear R7000 等基于博通 arm 方案的路由器，在 Asus 原版固件，Asus merlin 以及 Tomato，DD-WRT 下测试通过。

**需要在客户端配置文件中指定 cert 的位置：**
1. Asus Merlin
`"cert": "/rom/etc/ssl/certs/certificates.crt",`
2. Tomato
`"cert": "/rom/cacert.pem",`

下载：
https://dfile.app/QmQYXEcqgt5EsutpLNJeEsiP5TscbZuA68y6F7HKCEwjQk.rar

版本：
> trojan: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
> 
> Welcome to trojan 1.14.1
> Boost 1_71, OpenSSL 1.1.1d  10 Sep 2019
> [Disabled] MySQL Support
>  [Enabled] TCP_FASTOPEN Support
> [Disabled] TCP_FASTOPEN_CONNECT Support
>  [Enabled] SSL KeyLog Support
>  [Enabled] NAT Support
>  [Enabled] TLS1.3 Ciphersuites Support
> [Disabled] TCP Port Reuse Support
> OpenSSL Information
> 	Build Flags: compiler: arm-linux-gcc -fPIC -pthread -Wa,--noexecstack -Wall -O3 -march=armv7-a -mtune=cortex-a9 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG

**Comment by justin4765** [comment]
> tomatoware
你好，可以帮忙编译一个Asus RT-AC86U适用的包么？谢谢

**Comment by justin4765** [comment]
> trojan.v1.14.1.arm7l.static.rar，用 tomatoware 静态编译，适用于 Asus RT-AC68U，Netgear R7000 等基于博通 arm 方案的路由器，在 Asus 原版固件，Asus merlin 以及 Tomato，DD-WRT 下测试通过。
> 
> **需要在客户端配置文件中指定 cert 的位置：**
> 
> 1. Asus Merlin
>    `"cert": "/rom/etc/ssl/certs/certificates.crt",`
> 2. Tomato
>    `"cert": "/rom/cacert.pem",`
> 
> 下载：
> https://dfile.app/QmQYXEcqgt5EsutpLNJeEsiP5TscbZuA68y6F7HKCEwjQk.rar
> 
> 版本：
> 
> > trojan: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
> > Welcome to trojan 1.14.1
> > Boost 1_71, OpenSSL 1.1.1d  10 Sep 2019
> > [Disabled] MySQL Support
> > [Enabled] TCP_FASTOPEN Support
> > [Disabled] TCP_FASTOPEN_CONNECT Support
> > [Enabled] SSL KeyLog Support
> > [Enabled] NAT Support
> > [Enabled] TLS1.3 Ciphersuites Support
> > [Disabled] TCP Port Reuse Support
> > OpenSSL Information
> > Build Flags: compiler: arm-linux-gcc -fPIC -pthread -Wa,--noexecstack -Wall -O3 -march=armv7-a -mtune=cortex-a9 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG

你好，可以帮忙编译一个Asus RT-AC86U适用的包么？谢谢

**Comment by rampageX** [comment]
@justin4765 这个不能用？

**Comment by justin4765** [comment]
@rampageX  试过了，不能，我的是官改梅林

**Comment by rampageX** [comment]
@justin4765 试试这个，不行那就只有自己编译了：（https://github.com/RMerl/am-toolchains/tree/master/brcm-arm-hnd）

https://dfile.app/QmaLj5v2T5A7REzSJkXhru3KVGnWmSeZsowUrTnD9zQLFB.gz

**Comment by loveklmn** [comment]
@rampageX 想请教一下如何使用这个

**Comment by PatrickQianussys** [comment]
各位大神，请帮忙看下这个问题
我的config.json 里面，配置成这样 "local_addr":"0.0.0.0","local_port":23456 ，在路由器上面 trojan -c config.json 也成功开始，使用 PC上面的 chrome 192.168.50.1:23456  能够成功访问 google 之类网站。

但是不知为何，我用命令trojan -c config.json替换掉 ssconfig.sh 里面的 "ss-local -l 23456"，当我在路由器界面启动 ss 节点之后，PC上的Chrome使用 192.168.50.1:23456，仍然能够访问google，但是不知为何，直接连接不能访问google.

**Comment by idealism-xxm** [comment]
> 各位大神，请帮忙看下这个问题
> 我的config.json 里面，配置成这样 "local_addr":"0.0.0.0","local_port":23456 ，在路由器上面 trojan -c config.json 也成功开始，使用 PC上面的 chrome 192.168.50.1:23456 能够成功访问 google 之类网站。
> 
> 但是不知为何，我用命令trojan -c config.json替换掉 ssconfig.sh 里面的 "ss-local -l 23456"，当我在路由器界面启动 ss 节点之后，PC上的Chrome使用 192.168.50.1:23456，仍然能够访问google，但是不知为何，直接连接不能访问google.

我 fork 了一份改写了一下，目前支持使用 trojan 了
[https://github.com/idealism-xxm/fancyss/](https://github.com/idealism-xxm/fancyss/)

**Comment by PatrickQianussys** [comment]
> > 各位大神，请帮忙看下这个问题
> > 我的config.json 里面，配置成这样 "local_addr":"0.0.0.0","local_port":23456 ，在路由器上面 trojan -c config.json 也成功开始，使用 PC上面的 chrome 192.168.50.1:23456 能够成功访问 google 之类网站。
> > 但是不知为何，我用命令trojan -c config.json替换掉 ssconfig.sh 里面的 "ss-local -l 23456"，当我在路由器界面启动 ss 节点之后，PC上的Chrome使用 192.168.50.1:23456，仍然能够访问google，但是不知为何，直接连接不能访问google.
> 
> 我 fork 了一份改写了一下，目前支持使用 trojan 了
> https://github.com/idealism-xxm/fancyss/

多谢，可以用，很方便

**Comment by babylife** [comment]
> > 各位大神，请帮忙看下这个问题
> > 我的config.json 里面，配置成这样 "local_addr":"0.0.0.0","local_port":23456 ，在路由器上面 trojan -c config.json 也成功开始，使用 PC上面的 chrome 192.168.50.1:23456 能够成功访问 google 之类网站。
> > 但是不知为何，我用命令trojan -c config.json替换掉 ssconfig.sh 里面的 "ss-local -l 23456"，当我在路由器界面启动 ss 节点之后，PC上的Chrome使用 192.168.50.1:23456，仍然能够访问google，但是不知为何，直接连接不能访问google.
> 
> 我 fork 了一份改写了一下，目前支持使用 trojan 了
> https://github.com/idealism-xxm/fancyss/

非常好用，谢谢作者

**Comment by babylife** [comment]
> trojan.v1.14.1.arm7l.static.rar，用 tomatoware 静态编译，适用于 Asus RT-AC68U，Netgear R7000 等基于博通 arm 方案的路由器，在 Asus 原版固件，Asus merlin 以及 Tomato，DD-WRT 下测试通过。
> 
> **需要在客户端配置文件中指定 cert 的位置：**
> 
> 1. Asus Merlin
>    `"cert": "/rom/etc/ssl/certs/certificates.crt",`
> 2. Tomato
>    `"cert": "/rom/cacert.pem",`
> 
> 下载：
> https://dfile.app/QmQYXEcqgt5EsutpLNJeEsiP5TscbZuA68y6F7HKCEwjQk.rar
> 
> 版本：
> 
> > trojan: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
> > Welcome to trojan 1.14.1
> > Boost 1_71, OpenSSL 1.1.1d  10 Sep 2019
> > [Disabled] MySQL Support
> > [Enabled] TCP_FASTOPEN Support
> > [Disabled] TCP_FASTOPEN_CONNECT Support
> > [Enabled] SSL KeyLog Support
> > [Enabled] NAT Support
> > [Enabled] TLS1.3 Ciphersuites Support
> > [Disabled] TCP Port Reuse Support
> > OpenSSL Information
> > Build Flags: compiler: arm-linux-gcc -fPIC -pthread -Wa,--noexecstack -Wall -O3 -march=armv7-a -mtune=cortex-a9 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG

大神考虑定期更新这个梅林版本二进制嘛，太牛了

**Comment by rampageX** [comment]
@babylife https://github.com/rampageX/arm-static-bins/tree/master/trojan

**Comment by babylife** [comment]
> @babylife https://github.com/rampageX/arm-static-bins/tree/master/trojan

威武 谢谢老大

**Comment by 0neday** [comment]
> @babylife https://github.com/rampageX/arm-static-bins/tree/master/trojan

```
EchoLife_WAP /mnt/jffs2/app/trojan # ./trojan -c trojan-forward-dns.json
Welcome to trojan 1.16.0
[2021-02-09 13:05:38] [WARN] SO_REUSEPORT is not supported
EchoLife_WAP /mnt/jffs2/app/trojan # uname -a
Linux EchoLife_WAP 3.10.53-HULK2 #1 SMP Fri Apr 13 19:54:43 CST 2018 armv7l GNU/Linux
EchoLife_WAP /mnt/jffs2/app/trojan #
```
could add REUSEPORT for armv7 kernel 3.10+
