### ISSUE TITLE
[Feature Request] Mobile Clients

### ISSUE THREAD

**Issue by YangtseSu** [trojan-gfw/trojan#19]
Is there any plan to release a Android client?

**Comment by GreaterFire** [comment]
Positive. We are indeed considering porting trojan to mobile platforms. But due to the complications of doing it, we do not have a definite development and release plan.

**Comment by RiccaAtAlicia** [comment]
@Greaterfire If your Linux client isn't using iptables, you can just recompile it with bionic, then find a library to rewrite socks proxy into so-called VPN

**Comment by GreaterFire** [comment]
@RiccaAtAlicia  
We've been able to compile and run trojan "as-is" with Termux. Apps that support SOCKS5 (such as Telegram) can utilize it. Maybe we can use tun2socks to further proxify other apps, but this practice is complicated and is not what we want. We want a user-friendly app.

**Comment by GreatEmerald** [comment]
Also iOS, but that might be even more complicated...

**Comment by GreaterFire** [comment]
For all of you who are concerned, the development of [an android client](https://github.com/trojan-gfw/igniter) is undergoing. Currently it contains a minimally usable prototype but is not production ready. You can try it out if you are interested.

**Comment by Rucc1** [comment]
https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha3

**Comment by GreaterFire** [comment]
@Rucc1 Note that the pre-alpha versions are still extremely buggy and insecure and should only be used for testing purposes.

**Comment by undirectlookable** [comment]
I notice the testflight version of [Shadowrocket](https://itunes.apple.com/us/app/shadowrocket/id932747118?mt=8) has supported today.

**Comment by GreaterFire** [comment]
Closing this issue since there exists usable [client implementations](https://github.com/trojan-gfw/trojan/wiki/Mobile-Platforms).
