### ISSUE TITLE
[Feature Request] trojan-gfw的docker 是否考虑支持多架构?

### ISSUE THREAD

**Issue by E8x6UDEm** [trojan-gfw/trojan#198]
首先谢谢开发者的工作,让我们还可以穿越这堵高墙.非常感谢!
dockerfile的仓库没有开issuse,所以发到这里了.
trojan-gfw 的 docker 是否会考虑支持多架构呢? 
我尝试在 arm64 armv7下,相同的dockerfile文件,编译后都可以正常运行.
支持多架构 应该是开启 buildx 并设置,抱歉,对 docker push 等还不熟悉.

**Comment by GreaterFire** [comment]
I actually have no immediate knowledge on how to build docker images for various architectures. I might do it when I have time.

**Comment by E8x6UDEm** [comment]
明白.或许我可以尝试学一下,然后提交pr.
