### ISSUE TITLE
功能建议：添加开机自启

### ISSUE THREAD

**Issue by realcirno** [trojan-gfw/trojan#199]
希望加入开机后自启选项，或者可能UI过于简陋可以添加到配置中，将最小化按钮动作改为从任务栏隐藏到右下角，而不是任务栏中，因为很容易点X儿关闭。

**Comment by yatounoneko** [comment]
这玩意有UI？？你自己写个.bat或.sh放进系统自启列表里。。。难道不会更方便？？

**Comment by realcirno** [comment]
> 这玩意有UI？？你自己写个.bat或.sh放进系统自启列表里。。。难道不会更方便？？

只是提个建议而已。。。。。
