### ISSUE TITLE
[Feature Request] Are there plans to develop macOS windows or other GUI clients?

### ISSUE THREAD

**Issue by zhoubowen-sky** [trojan-gfw/trojan#202]
Are there plans to develop macOS windows or other GUI clients?
I'm a Go developer(and android)，I can participate if possible.

**Comment by GreaterFire** [comment]
There is this https://github.com/trojan-gfw/trojan-qt but is suspended by the original author.

**Comment by zhoubowen-sky** [comment]
I am implementing the Trojan protocol in go language, and I will open it's source code in the near future. 
To some extent, Go program can adapt to more platforms easilty.

**Comment by zhoubowen-sky** [comment]
> There is this https://github.com/trojan-gfw/trojan-qt but is suspended by the original author.

I am implementing the Trojan protocol in go language, and I will open it's source code in the near future.
To some extent, Go program can adapt to more platforms easilty.
