### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by os9sur** [trojan-gfw/trojan#205]
root@localhost:~ $ systemctl status trojan
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-01-09 05:36:56 EST; 251ms ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 14078 ExecStart=/usr/local/bin/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 14078 (code=exited, status=1/FAILURE)

Jan 09 05:36:56 localhost.localdomain systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
Jan 09 05:36:56 localhost.localdomain systemd[1]: trojan.service: Failed with result 'exit-code'.

**Comment by quminghaonanya** [comment]
how did you solve the problem ,would you mind sharing your experience with me? 
I met the same problem.

**Comment by quminghaonanya** [comment]
I have sovled this problem,just by trunning off nginx and start trojan. :)
