### ISSUE TITLE
[Feature Request] 如果我想在我的mk7621 路由器编译客户端，具体可行吗？

### ISSUE THREAD

**Issue by lei1996** [trojan-gfw/trojan#208]
- [ ] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
如果我想在我的mk7621 路由器编译客户端，具体可行吗？

**Comment by KnightNic** [comment]
我直接编译到OpenWrt固件

**Comment by lei1996** [comment]
@KnightNic  编译的话，有操作文档么？

**Comment by KnightNic** [comment]
> @KnightNic 编译的话，有操作文档么？

可以参考下https://github.com/coolsnowwolf/lede，里面集成了trojan，编译前选一下就可以

**Comment by txdywy** [comment]
youtube上有视频

lei1996 <notifications@github.com> 于 2020年1月17日周五 下午11:26写道：

**Comment by lei1996** [comment]
@KnightNic  @txdywy  
lede 的固件我已经在编译了。应该一会就能成功。
之前考虑的是，在padavan 固件上 编译。
https://github.com/hanwckf/rt-n56u
请问有方式可以操作么？

**Comment by maskedeken** [comment]
> 
> 
> @KnightNic @txdywy
> lede 的固件我已经在编译了。应该一会就能成功。
> 之前考虑的是，在padavan 固件上 编译。
> https://github.com/hanwckf/rt-n56u
> 请问有方式可以操作么？

可以用我静态编译的mipsel版本，在老毛子上可以绿色运行
[https://github.com/maskedeken/trojan-gfw/releases](https://github.com/maskedeken/trojan-gfw/releases)
