### ISSUE TITLE
[BUG] 1.14.0编译提示

### ISSUE THREAD

**Issue by xisa-gh** [trojan-gfw/trojan#209]
- [ ] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.14.0

**Describe the bug**
系统信息及编译环境
Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
Boost 1.72.0
OpenSSL 1.1.1d
Cmake 3.15.0
gcc 6.3.0

编译时提示以下信息，重复发生。Ctest成功，也可以正常使用
[ 38%] Building CXX object CMakeFiles/trojan.dir/src/proto/socks5address.cpp.o
/root/trojan/src/proto/socks5address.cpp: In member function ‘bool SOCKS5Address::parse(const string&, size_t&)’:
/root/trojan/src/proto/socks5address.cpp:49:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (data.length() > 1 + domain_len + 2) {
                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~

**Comment by GreaterFire** [comment]
No need to worry. This is just a warning and is fixed in https://github.com/trojan-gfw/trojan/commit/92ef1691670efa4759fa757750841715e0c27d4f.
