### ISSUE TITLE
Any documentation to compile for IOS ?

### ISSUE THREAD

**Issue by moldis** [trojan-gfw/trojan#211]
HI,
I am looking for documentation to compile for IOS or maybe for MacOS (i can convert it to IOS later).

I am able to convert Golang libs, but was not able to make it for trojan

Thanks, Artem

**Comment by moldis** [comment]
Great project btw, you made really nice work

**Comment by GreaterFire** [comment]
This project is a command-line interface program. What do you mean by compiling it for iOS?
macOS pre-built binaries are provided in [Releases](https://github.com/trojan-gfw/trojan/releases/latest).

**Comment by moldis** [comment]
@GreaterFire You have separate repo for Android building,  my question is - is it possible to have same guide / instruction / repo but for IOS version ?

**Comment by moldis** [comment]
I am looking for client side library, not server side

**Comment by GreaterFire** [comment]
The android app is a completely different project than trojan itself, so it's in its own repo.
iOS currently supports the trojan protocol. See wiki for details.
We don't provide client/server library. This project is a standalone program.

**Comment by moldis** [comment]
Understood, thank you.
