### ISSUE TITLE
[关于前端网页的问题]

### ISSUE THREAD

**Issue by edmund-zhao** [trojan-gfw/trojan#213]
1.可否使用wordpress作为前端网站呢？

以下是我的安装方法：环境为：Debian10 DO
apt update
apt install apache2
apt install gnupg
cd /tmp
wget https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
dpkg -i mysql-apt-config*
apt update
apt install mysql-server
mysql_secure_installation
apt install php libapache2-mod-php php-mysql
vi /etc/apache2/mods-enabled/dir.conf
systemctl reload apache2
systemctl stop apache2
apt-get install git
apt -y install build-essential cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev
git clone https://github.com/letsencrypt/letsencrypt
cd letsencrypt
./certbot-auto --help all
./letsencrypt-auto certonly --standalone --email  @gmail.com -d wordpress.pcprincipal.com
git clone https://github.com/trojan-gfw/trojan.git
cd trojan/
mkdir build
cd build/
cmake .. -DENABLE_MYSQL=OFF -DENABLE_SSL_KEYLOG=ON -DFORCE_TCP_FASTOPEN=ON -DSYSTEMD_SERVICE=AUTO
make
ctest
sudo make install
vi /usr/local/etc/trojan/config.json
./trojan -c /usr/local/etc/trojan/config.json
echo 3 > /proc/sys/net/ipv4/tcp_fastopen

wget http://wordpress.org/latest.tar.gz
tar -xzvf latest.tar.gz

mysql -u root -p
CREATE DATABASE wordpress;
CREATE USER wordpress@localhost;
SET PASSWORD FOR wordpress@localhost=PASSWORD(“passports”)
GRANT ALL PRIVILEGES ON wordpress.* TO wordpress@localhost IDENTIFIED BY ‘passports’
FLUSH PRIVILEGES;
QUIT;

vi /etc/systemd/system/trojan.service 
「
* [Unit]
* After=network.target 
*  
* [Service]
* ExecStart=/root/trojan/build/trojan -c /usr/local/etc/trojan/config.json
* Restart=always
*  
* [Install]
* WantedBy=multi-user.target

 」
systemctl start trojan
systemctl enable trojan

**Comment by edmund-zhao** [comment]
以解决

**Comment by ghost** [comment]
请问你是如何处理的？最近我也遇到这个问题，谢谢.

**Comment by atrandys** [comment]
最近做了一个一键trojan+wordpress脚本，可参考https://www.atrandys.com/2020/233.html
