### ISSUE TITLE
Exception: EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by jhb92** [trojan-gfw/trojan#215]
I want to tracking async operation,so in main firstline ,i type follow

#define BOOST_ASIO_ENABLE_HANDLER_TRACKING

and start debug, exception throwed, and can't continue. what's wrong?

**Comment by wongsyrone** [comment]
Are you sure you passed in the correct parameters?

**Comment by GreaterFire** [comment]
It is not sufficient to add the definition to just `main.cpp`. You should add `add_definitions(-DBOOST_ASIO_ENABLE_HANDLER_TRACKING)` to `CMakeLists.txt`.
