### ISSUE TITLE
How does trojan resist active probing by GFW

### ISSUE THREAD

**Issue by chinyichun** [trojan-gfw/trojan#216]
Dear trojan development team:

This maybe somewhat of a noob question: but how does trojan resist GFW masquerading as a trojan client to actively probe a VPS for the presence of trojan over and above the regular nginx? GFW has been known to masquerade itself as tor obfs2 client to actively probe tor obfs2 bridges in the past.

Thanks.

**Comment by GreaterFire** [comment]
Please read the protocol part of the docs.
