### ISSUE TITLE
Did Not Connect: Potential Security Issue

### ISSUE THREAD

**Issue by jhb92** [trojan-gfw/trojan#217]
I use clion build own binanry on mac pro book without any problem, but when i start as client ,listen local 1088 port,access google.com from firefox , firefox prompt me  "Did Not Connect: Potential Security Issue"  , more info as follow:

"
Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to www.youtube.com because this website requires a secure connection.

What can you do about it?

www.youtube.com has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

"

please help me . **is my compile problem or other?**  my cmakelists as follow:

cmake_minimum_required(VERSION 3.7.2)
project(trojan)
#set(Boost_DEBUG 1)
set(Boost_USE_STATIC_LIBS ON)
set(Boost_INCLUDE_DIR /Users/jianghaibin/Downloads/boost_1_66_0)
set(Boost_LIBRARY_DIR /Users/jianghaibin/Downloads/boost_1_66_0/stage/lib)
#openssl
set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} /usr/local/opt/openssl/include)
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} /usr/local/opt/openssl/lib)
set(OPENSSL_INCLUDE_DIR /usr/local/opt/openssl/include)
#mysql client
set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} /usr/local/opt/mysql-client/include/mysql)
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} /usr/local/opt/mysql-client/lib)
set(MYSQL_INCLUDE_DIR /usr/local/opt/mysql-client/include/mysql)
add_definitions(-DBOOST_ASIO_ENABLE_HANDLER_TRACKING)
#
.....others from source code without change anything .......

**Comment by GreaterFire** [comment]
Please provide the log from both server and client.

**Comment by jhb92** [comment]
I access www.google.com

server log

Jan 16 00:22:29 xxx.top trojan[25605]: [2020-01-16 00:22:29] [INFO] 223.104.210.68:9216 authenticated as PASSWORD
Jan 16 00:22:29 xxx.top trojan[25605]: [2020-01-16 00:22:29] [INFO] 223.104.210.68:9216 requested connection to 75.126.150.210:443
Jan 16 00:22:32 xxx.top trojan[25605]: [2020-01-16 00:22:32] [INFO] 223.104.210.68:9218 authenticated as PASSWORD
Jan 16 00:22:32 xxx.top trojan[25605]: [2020-01-16 00:22:32] [INFO] 223.104.210.68:9218 requested connection to 75.126.150.210:443
Jan 16 00:22:34 xxx.top trojan[25605]: [2020-01-16 00:22:34] [INFO] 223.104.210.68:9217 authenticated as PASSWORD
Jan 16 00:22:34 xxx.top trojan[25605]: [2020-01-16 00:22:34] [INFO] 223.104.210.68:9217 requested connection to 75.126.150.210:443

client log

[2020-01-16 00:22:19] [WARN] trojan service (client) started at 127.0.0.1:1088
[2020-01-16 00:22:28] [INFO] 127.0.0.1:58576 requested connection to 75.126.150.210:443
[2020-01-16 00:22:29] [INFO] 127.0.0.1:58578 requested connection to 75.126.150.210:443
[2020-01-16 00:22:29] [INFO] 127.0.0.1:58576 disconnected, 0 bytes received, 517 bytes sent, lasted for 1 seconds
[2020-01-16 00:22:31] [INFO] 127.0.0.1:58580 requested connection to 75.126.150.210:443
[2020-01-16 00:22:34] [INFO] 127.0.0.1:58578 disconnected, 0 bytes received, 517 bytes sent, lasted for 5 seconds
[2020-01-16 00:23:56] [INFO] 127.0.0.1:58580 disconnected, 0 bytes received, 517 bytes sent, lasted for 85 seconds

**Comment by jhb92** [comment]
**cmake log**

/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /Users/xxx/Desktop/trojan/server/trojan
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xxx/Desktop/trojan/server/trojan/cmake-build-debug

[Finished]

**build log**

====================[ Build | all | Debug ]=====================================
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --build /Users/xxx/Desktop/trojan/server/trojan/cmake-build-debug --target all -- -j 4
[  5%] Building CXX object CMakeFiles/trojan.dir/src/core/authenticator.cpp.o
[ 11%] Building CXX object CMakeFiles/trojan.dir/src/core/config.cpp.o
[ 16%] Building CXX object CMakeFiles/trojan.dir/src/core/log.cpp.o
[ 22%] Building CXX object CMakeFiles/trojan.dir/src/core/service.cpp.o
[ 27%] Building CXX object CMakeFiles/trojan.dir/src/core/version.cpp.o
/Users/xxx/Desktop/trojan/server/trojan/src/core/service.cpp:168:30: warning: 'SecKeychainSearchCreateFromAttributes' is deprecated: first deprecated in macOS 10.7 - SecKeychainSearch is not supported [-Wdeprecated-declarations]
                    status = SecKeychainSearchCreateFromAttributes (pSecKeychain, kSecCertificateItemClass, NULL, &pSecKeychainSearch);
                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychainSearch.h:60:10: note: 'SecKeychainSearchCreateFromAttributes' has been explicitly marked deprecated here
OSStatus SecKeychainSearchCreateFromAttributes(CFTypeRef __nullable keychainOrArray, SecItemClass itemClass, const SecKeychainAttributeList * __nullable attrList, SecKeychainSearchRef * __nonnull CF_RETURNS_RETAINED searchRef)
         ^
/Users/xxx/Desktop/trojan/server/trojan/src/core/service.cpp:172:34: warning: 'SecKeychainSearchCopyNext' is deprecated: first deprecated in macOS 10.7 - SecKeychainSearch is not supported [-Wdeprecated-declarations]
                        status = SecKeychainSearchCopyNext (pSecKeychainSearch, &pSecKeychainItem);
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychainSearch.h:71:10: note: 'SecKeychainSearchCopyNext' has been explicitly marked deprecated here
OSStatus SecKeychainSearchCopyNext(SecKeychainSearchRef searchRef, SecKeychainItemRef * __nonnull CF_RETURNS_RETAINED itemRef)
         ^
[ 33%] Building CXX object CMakeFiles/trojan.dir/src/main.cpp.o
/Users/xxx/Desktop/trojan/server/trojan/src/main.cpp:19:9: warning: 'BOOST_ASIO_ENABLE_HANDLER_TRACKING' macro redefined [-Wmacro-redefined]
#define BOOST_ASIO_ENABLE_HANDLER_TRACKING
        ^
<command line>:1:9: note: previous definition is here
#define BOOST_ASIO_ENABLE_HANDLER_TRACKING 1
        ^
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/core/service.cpp:20:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/core/service.h:26:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/udp.hpp:22:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver.hpp:29:
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: warning: local variable 'tmp' will be copied despite being returned by name [-Wreturn-std-move]
    return tmp;
           ^~~
/Users/xxx/Desktop/trojan/server/trojan/src/core/service.cpp:60:108: note: in instantiation of member function 'boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>::begin' requested here
        tcp::endpoint listen_endpoint = *resolver.resolve(config.local_addr, to_string(config.local_port)).begin();
                                                                                                           ^
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: note: call 'std::move' explicitly to avoid copying
    return tmp;
           ^~~
           std::move(tmp)
[ 38%] Building CXX object CMakeFiles/trojan.dir/src/proto/socks5address.cpp.o
[ 44%] Building CXX object CMakeFiles/trojan.dir/src/proto/trojanrequest.cpp.o
3 warnings generated.
[ 50%] Building CXX object CMakeFiles/trojan.dir/src/proto/udppacket.cpp.o
[ 55%] Building CXX object CMakeFiles/trojan.dir/src/session/clientsession.cpp.o
[ 61%] Building CXX object CMakeFiles/trojan.dir/src/session/forwardsession.cpp.o
[ 66%] Building CXX object CMakeFiles/trojan.dir/src/session/natsession.cpp.o
1 warning generated.
[ 72%] Building CXX object CMakeFiles/trojan.dir/src/session/serversession.cpp.o
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/clientsession.cpp:20:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/clientsession.h:23:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/session.h:26:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/udp.hpp:22:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver.hpp:29:
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: warning: local variable 'tmp' will be copied despite being returned by name [-Wreturn-std-move]
    return tmp;
           ^~~
/Users/xxx/Desktop/trojan/server/trojan/src/session/clientsession.cpp:231:41: note: in instantiation of member function 'boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>::begin' requested here
                auto iterator = results.begin();
                                        ^
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: note: call 'std::move' explicitly to avoid copying
    return tmp;
           ^~~
           std::move(tmp)
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/forwardsession.cpp:20:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/forwardsession.h:23:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/session.h:26:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/udp.hpp:22:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver.hpp:29:
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: warning: local variable 'tmp' will be copied despite being returned by name [-Wreturn-std-move]
    return tmp;
           ^~~
/Users/xxx/Desktop/trojan/server/trojan/src/session/forwardsession.cpp:66:33: note: in instantiation of member function 'boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>::begin' requested here
        auto iterator = results.begin();
                                ^
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: note: call 'std::move' explicitly to avoid copying
    return tmp;
           ^~~
           std::move(tmp)
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/natsession.cpp:20:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/natsession.h:23:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/session.h:26:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/udp.hpp:22:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver.hpp:29:
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: warning: local variable 'tmp' will be copied despite being returned by name [-Wreturn-std-move]
    return tmp;
           ^~~
/Users/xxx/Desktop/trojan/server/trojan/src/session/natsession.cpp:114:33: note: in instantiation of member function 'boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>::begin' requested here
        auto iterator = results.begin();
                                ^
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: note: call 'std::move' explicitly to avoid copying
    return tmp;
           ^~~
           std::move(tmp)
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/serversession.cpp:20:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/serversession.h:23:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/session.h:26:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/udp.hpp:22:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver.hpp:29:
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: warning: local variable 'tmp' will be copied despite being returned by name [-Wreturn-std-move]
    return tmp;
           ^~~
/Users/xxx/Desktop/trojan/server/trojan/src/session/serversession.cpp:180:37: note: in instantiation of member function 'boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>::begin' requested here
            auto iterator = results.begin();
                                    ^
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: note: call 'std::move' explicitly to avoid copying
    return tmp;
           ^~~
           std::move(tmp)
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: warning: local variable 'tmp' will be copied despite being returned by name [-Wreturn-std-move]
    return tmp;
           ^~~
/Users/xxx/Desktop/trojan/server/trojan/src/session/serversession.cpp:289:37: note: in instantiation of member function 'boost::asio::ip::basic_resolver_results<boost::asio::ip::udp>::begin' requested here
            auto iterator = results.begin();
                                    ^
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: note: call 'std::move' explicitly to avoid copying
    return tmp;
           ^~~
           std::move(tmp)
1 warning generated.
1 warning generated.
[ 77%] Building CXX object CMakeFiles/trojan.dir/src/session/session.cpp.o
[ 83%] Building CXX object CMakeFiles/trojan.dir/src/session/udpforwardsession.cpp.o
1 warning generated.
[ 88%] Building CXX object CMakeFiles/trojan.dir/src/ssl/ssldefaults.cpp.o
[ 94%] Building CXX object CMakeFiles/trojan.dir/src/ssl/sslsession.cpp.o
2 warnings generated.
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/udpforwardsession.cpp:20:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/udpforwardsession.h:23:
In file included from /Users/xxx/Desktop/trojan/server/trojan/src/session/session.h:26:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/udp.hpp:22:
In file included from /Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver.hpp:29:
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: warning: local variable 'tmp' will be copied despite being returned by name [-Wreturn-std-move]
    return tmp;
           ^~~
/Users/xxx/Desktop/trojan/server/trojan/src/session/udpforwardsession.cpp:65:33: note: in instantiation of member function 'boost::asio::ip::basic_resolver_results<boost::asio::ip::tcp>::begin' requested here
        auto iterator = results.begin();
                                ^
/Users/xxx/Downloads/boost_1_66_0/boost/asio/ip/basic_resolver_results.hpp:256:12: note: call 'std::move' explicitly to avoid copying
    return tmp;
           ^~~
           std::move(tmp)
1 warning generated.
[100%] Linking CXX executable trojan
[100%] Built target trojan

Build finished

**ctest log** 

MacBook-Pro:trojan xxx$ ctest
Test project /Users/xxx/Desktop/trojan/server/trojan
    Start 1: LinuxSmokeTest-basic
1/2 Test #1: LinuxSmokeTest-basic .............***Failed    0.02 sec
    Start 2: LinuxSmokeTest-fake-client

**Comment by GreaterFire** [comment]
Seems like you resolved DNS locally. Which browser did you use and how did you configure your browser to use trojan?

**Comment by jhb92** [comment]
i use firefox and foxyproxy, Proxy Type socks5 ,Proxy IP address or DNS name is 127.0.0.1 port is 1088,Send DNS through SOCKS5 proxy is off.

the  bin downloaded from github can run soomthly , while the bin i build can run but can't proxy.

**Comment by GreaterFire** [comment]
@jhb92 Please turn on send DNS through SOCKS5

**Comment by jhb92** [comment]
woooo.  turn on DNS and ok. why ?

**Comment by GreaterFire** [comment]
Maybe your local DNS is poisoned.

**Comment by jhb92** [comment]
@GreaterFire thank you very much, your are excellent。
