### ISSUE TITLE
links in overview.md don't work

### ISSUE THREAD

**Issue by chinyichun** [trojan-gfw/trojan#218]
@GreaterFire 

Thanks for responding to my previous question regarding active probing by GFW.

I have read the docs and understood how trojan resists active and passive probing by GFW. However, while reading the docs I noticed that in overview.md, there are two links called "next page" in the following passage that don't work:

> The next page introduces the trojan protocol and how it hides itself from active and passive detections.

> Homepage | Next Page

Upon closer examination I realized that each of the "next page" links link to "https://github.com/trojan-gfw/trojan/blob/master/docs/protocol" rather than "https://github.com/trojan-gfw/trojan/blob/master/docs/protocol.md".

If that can be fixed then it provides a much better user navigation experience.

Thanks.

**Comment by GreaterFire** [comment]
Not an issue. Please visit the documentation from https://trojan-gfw.github.io/trojan/.
