### ISSUE TITLE
[BUG] 在shadowsocket上用，显示此网站无法提供安全连接，换客户端pharos也一样

### ISSUE THREAD

**Issue by haiou7** [trojan-gfw/trojan#221]
iOS12.4.4在shadowsocket上，显示此网站无法提供安全连接，换客户端pharos也一样不行。
网页显示。
此网站无法提供安全连接
m.youtube.com 发送的响应无效。
ERR_SSL_PROTOCOL_ERROR

是不是证书的问题？

**Comment by GreaterFire** [comment]
Please at least attach some log.
