### ISSUE TITLE
是否可以像kcptun作为内层使用？

### ISSUE THREAD

**Issue by yjd** [trojan-gfw/trojan#224]
ss client(local) --- trojan client(local) --- trojan server(remote) --- ss server(remote) --- internet

trojian测试正常后。
我尝试在ss client 添加 发送到本地 127.0.0.1:1080
服务器端修改trojan配置的：
"remote_addr": "127.0.0.1",
"remote_port": 7788, //ss server 端口

没成功

**Comment by GreaterFire** [comment]
Please checkout the forward mode of trojan. However, I don't think your scheme is any necessary.

**Comment by yjd** [comment]
原因是昨天测试安卓客户端没成功，才考虑使用ss的客户端来统一管理。
刚才重新测试手机端可以正常使用。这个需求就没那么重要。
forward 模式看说明没看懂。
    "target_addr": "127.0.0.1",
    "target_port": 5901,
我理解是在client端转发到上级代理吗？
如果是，那中间是由ss发数据这个就是用不上了。
一直用ss和ss kcptun 最近晚高峰经常被isp qos。才从昨天开始测试这个。

刚好今天又有这个需求了，重新测试可以用了。

chrome -- ss client(local) --- trojan client(local) --- trojan server(remote) --- ss server(remote) --- internet

这样可以服务端只运行一份，客户端运行2个，一个独立用浏览器代理插件。一个可以用ss客户端切换。
