### ISSUE TITLE
Is it possible to get IP access log ?

### ISSUE THREAD

**Issue by linfengOu** [trojan-gfw/trojan#228]
Hi, thanks for providing such a brilliant tool !
Is there any log file that logs IP address accessed to Trojan server ?
 I know it's possible to use netstat or ss to monitor, but if there's a log file then it would be much easier.

Thanks.

**Comment by GreaterFire** [comment]
@oliver4u The log that trojan outputs literally contains this info. How did you run your trojan service?

**Comment by linfengOu** [comment]
@GreaterFire Thanks for the info. I missed --log parameter before.
Thanks again for this great tool.
