### ISSUE TITLE
json cert 的路径应该怎么写？ invalid code sequence

### ISSUE THREAD

**Issue by yjd** [trojan-gfw/trojan#230]
按文档说明是需要替换成/，但是写绝对路径和多级目录的相对路径，
运行都提示错误  invalid code sequence

>      "verify": true,
>       "verify_hostname": false,
>       "cert": "e:/ss/trojan/certificate.cer",

**Comment by GreaterFire** [comment]
@yjd Please provide full config and log. Redact as needed.

**Comment by yjd** [comment]
环境：
Windows trojan客户端配置

导致问题：
跟这个证书路径有关
当配置为

> verify": true
> "cert": "certificate.cer"

certificate.cer不写路径，在cmd下未切换到trojian软件执行目录时，执行：
 e:\ss\trojan\trojan.exe -c e:\ss\trojan\config.json
错误日志：

> C:\Users> e:\ss\trojan\trojan.exe -c e:\ss\trojan\config.json
> Welcome to trojan 1.14.1
> [2020-01-29 14:07:12] [FATAL] fatal: e:\ss\trojan\config.json(14): invalid escape sequence
> [2020-01-29 14:07:12] [FATAL] exiting. . .

把cert 配置为完整路径 e:\ss\trojan\certificate.cer 测试现象依旧。
如果第三方程序调用windows的WinExe API 函数来运行就和上面测试现象一样。
也就是存在工作目录不在软件目录。trojan跑起来都自己取证书有问题。

解决：
1，批处理运行先 cd /d %~dp0 切换到软件目录再执行 trojan.exe -c config.json
2，调用WinExe函数前程序内部先切换到trojian的目录再运行也可以解决
3，使用ShellExecute函数，指定工作目录。也可解决

trojan自身能修复这个这个小瑕疵会更好👍

**Comment by GreaterFire** [comment]
@yjd I repeat: please provide full config **with your "\\" replaced with "/"** and the corresponding log.

**Comment by yjd** [comment]
问题原因找到，https://github.com/trojan-gfw/trojan/releases zip包里提供的模板文件都是ANSI(936)。
我路径带中文。而trojan默认应该是按UTF-8编码读取，导致上面的问题。

```
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "xx",
    "remote_port": 443,
    "password": [
        "xx"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": false,
        "cert": "D:/中文/trojan/certificate.cer",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}

```
改UTF-8和默认自带GBK日志：

> C:\Users>D:\中文\trojan\trojan.exe -c D:\中文\trojan\config.json
> Welcome to trojan 1.14.1
> [2020-01-29 16:41:43] [WARN] trojan service (client) started at 127.0.0.1:8077
> [2020-01-29 16:41:47] [WARN] got signal: 2
> [2020-01-29 16:41:47] [WARN] trojan service stopped
> 
> C:\Users>D:\中文\trojan\trojan.exe -c D:\中文\trojan\config.json
> Welcome to trojan 1.14.1
> [2020-01-29 16:42:15] [FATAL] fatal: D:\中文\trojan\config.json(14): invalid code sequence
> [2020-01-29 16:42:15] [FATAL] exiting. . .
>
