### ISSUE TITLE
systemd usage

### ISSUE THREAD

**Issue by malikshi** [trojan-gfw/trojan#232]
trojan version 1.14.1
vps: ubuntu 18.04
trojan+trojan panel running pretty well
but i want log to save in other location so i can check log in realtime, not like this `systemctl status trojan` 
so i try to implement like this `/usr/local/bin/trojan -l /var/log/mytrojan -c /usr/local/etc/trojan/config.json` its running well. but when i try on `/etc/systemd/system/trojan.service` with execstart
>> "ExecStart=/usr/local/bin/trojan -l /var/log/mytrojan -c /usr/local/etc/trojan/config.json"

shown error result
>>  Main PID: 28010 (code=exited, status=1/FAILURE)
Jan 29 20:12:50 trojanvps systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
Jan 29 20:12:50 trojanvps  systemd[1]: trojan.service: Failed with result 'exit-code'.

**Comment by GreaterFire** [comment]
@malikshi Please show your entire service file.

**Comment by malikshi** [comment]
normal one
>>[Unit]
Description=$NAME
Documentation=https://trojan-gfw.github.io/$NAME/config https://trojan-gfw.github.io/$NAME/
After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service
[Service]
Type=simple
StandardError=journal
ExecStart="/usr/local/bin/trojan" "/usr/local/etc/trojan/config.json"
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=3s
[Install]
WantedBy=multi-user.target



that i want to log in different file location not in syslog like `/var/log/mytrojan`
>>[Unit]
Description=$NAME
Documentation=https://trojan-gfw.github.io/$NAME/config https://trojan-gfw.github.io/$NAME/
After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service
[Service]
Type=simple
StandardError=journal
ExecStart="/usr/local/bin/trojan -l /var/log/mytrojan -c /usr/local/etc/trojan/config.json"
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=3s
[Install]
WantedBy=multi-user.target

but have error like this

>>Main PID: 28010 (code=exited, status=1/FAILURE)
Jan 29 20:12:50 trojanvps systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
Jan 29 20:12:50 trojanvps systemd[1]: trojan.service: Failed with result 'exit-code'.

**Comment by GreaterFire** [comment]
Please remove the quotation mark around your command.
```diff
- ExecStart="/usr/local/bin/trojan -l /var/log/mytrojan -c /usr/local/etc/trojan/config.json"
+ ExecStart=/usr/local/bin/trojan -l /var/log/mytrojan -c /usr/local/etc/trojan/config.json
```

**Comment by RazorSammo** [comment]
My trojan.service file is like this

[Unit]
Description=trojan
Documentation=https://trojan-gfw.github.io/trojan/config https://trojan-gfw.github.io/trojan/
After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service

[Service]
Type=simple
StandardError=journal
User=trojan
ExecStart=/usr/local/bin/trojan /usr/local/etc/trojan/config.json
ExeReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=3s

[Install]
WantedBy=multi-user.target

But when I run sudo systemctl status trojan 
It shows the same Error

**Comment by RazorSammo** [comment]
> Please remove the quotation mark around your command.
> 
> ```diff
> - ExecStart="/usr/local/bin/trojan -l /var/log/mytrojan -c /usr/local/etc/trojan/config.json"
> + ExecStart=/usr/local/bin/trojan -l /var/log/mytrojan -c /usr/local/etc/trojan/config.json
> ```

I tried but not work :(
