### ISSUE TITLE
What dose “Client ciphers are taken from Firefox 71.0” mean?

### ISSUE THREAD

**Issue by koolwiki** [trojan-gfw/trojan#233]
Could you please explain what dose “Client ciphers are taken from Firefox 71.0. Server ciphers are taken from https://ssl-config.mozilla.org/ intermediate settings” mean for version1.14.1? 

Dose it means the tls cipher fingerprint of tronjan 1.14.1 are identical to firefox now?

Thank you!

**Comment by GreaterFire** [comment]
Just cipher list. Not anything else.
