### ISSUE TITLE
trojan service Edit error?配置错误？？

### ISSUE THREAD

**Issue by RazorSammo** [trojan-gfw/trojan#234]
我按照教程配置了trojan
(I followed the tutorial to edit trojan config.json)

1.安装(Install trojan)：
sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/trojan-gfw/trojan-quickstart/master/trojan-quickstart.sh)"
sudo chown -R trojan:trojan /usr/local/etc/trojan
sudo cp /usr/local/etc/trojan/config.json /usr/local/etc/trojan/config.json.bak
2.打开配置(open config.json)
sudo nano /usr/local/etc/trojan/config.json
3.修改config(edit config.json)
cert：/usr/local/etc/certfiles/certificate.crt
key：/usr/local/etc/certfiles/private.key
4.保存退出后，修改trojan.service 用户改为trojan
(save and quit, then add "User=trojan" to trojan.service
5.重新加载 
(reload)
sudo systemctl daemon-reload
6.赋予trojan 监听443端口
(make trojan listen 443 port)
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/trojan
7.重启trojan
(restart trojan)
sudo systemctl restart trojan

以上步骤均未报错
(and all the steps was no error report)

但当我查看trojan状态时
(but when I check the status of trojan)
sudo systemctl status trojan

显示：
(it shows me like this)
trojan.service - trojan
Loaded : loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: enabled)
Active : activating (auto-restart) (Result: exit -code) since Sun 2020-02-02 08:19:23 UTC; 46ms ago
Docs: https://trojan-gfw.github.io/trojan/config
          https://trojan-gfw.github.io/trojan/
Process: 6453 ExecStart=/usr/local/bin/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILUE)
Main PID: 6453 (code=exited, status=1/FAILURE)

Feb 02 08:19:23 myHost systemd[1]: trojan.service : Main process exited, code=exited, status=1/FAILURE
Feb 02 08:19:23 myHost systemd[1]: trojan.service: Failed with result 'exit-code'.

其中显示failed ，原因是 exit-code 这个是什么原因啊
(it shows "failed with result 'exit-code', what's that mean, plz help me )

**Comment by RazorSammo** [comment]
My trojan.service file is like this 

[Unit]
Description=trojan
Documentation=https://trojan-gfw.github.io/trojan/config https://trojan-gfw.github.io/trojan/
After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service

[Service]
Type=simple
StandardError=journal
User=trojan
ExecStart=/usr/local/bin/trojan /usr/local/etc/trojan/config.json
ExeReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=3s

[Install]
WantedBy=multi-user.target

**Comment by regloft** [comment]
新手表示同样遇到问题，不解。改用：
sudo -u trojan trojan -c /etc/trojan/config.json
可行。

**Comment by raydied4** [comment]
> 新手表示同样遇到问题，不解。改用：
> sudo -u trojan trojan -c /etc/trojan/config.json
> 可行。

还是不行？
sudo -u trojan trojan -c /etc/trojan/config.json
Welcome to trojan 1.14.1
[2020-03-08 16:20:21] [FATAL] fatal: /etc/trojan/config.json: cannot open file
[2020-03-08 16:20:21] [FATAL] exiting. . .

**Comment by raydied4** [comment]
> My trojan.service file is like this
> 
> [Unit]
> Description=trojan
> Documentation=https://trojan-gfw.github.io/trojan/config https://trojan-gfw.github.io/trojan/
> After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service
> 
> [Service]
> Type=simple
> StandardError=journal
> User=trojan
> ExecStart=/usr/local/bin/trojan /usr/local/etc/trojan/config.json
> ExeReload=/bin/kill -HUP $MAINPID
> Restart=on-failure
> RestartSec=3s
> 
> [Install]
> WantedBy=multi-user.target

 activating

你怎么解决？

**Comment by regloft** [comment]
你好，看了你的systemd报错，估计是权限问题。可能你需要先 sudo chown trojan:trojan
/etc/trojan/config.json，然后再 sudo -u trojan trojan -c /etc/trojan/config.json

raydied4 <notifications@github.com> 于2020年3月9日周一 上午12:26写道：

**Comment by InsomniaWenting** [comment]
Modify trojan.service

--ExecStart=/usr/local/bin/trojan /usr/local/etc/trojan/config.json
++ExecStart=/usr/local/bin/trojan -c /usr/local/etc/trojan/config.json

Please also confirm the path of trojan & config.jason also.

**Comment by GreaterFire** [comment]
@InsomniaWenting -c is optional.
Also this file only serves as an example.
