### ISSUE TITLE
如何在trojan服务器增加特定网站的DNS

### ISSUE THREAD

**Issue by imtv** [trojan-gfw/trojan#235]
如何在trojan服务器增加特定网站的DNS

**Comment by GreaterFire** [comment]
@imtv /etc/resolv.conf

**Comment by imtv** [comment]
@GreaterFire 
我试了，没有效果，而且格式是这样吧：
nameserver 1.1.1.1
另外能给特定网站加吗？

**Comment by GreaterFire** [comment]
@imtv We are not generic Linux support. I'm sorry.

**Comment by imtv** [comment]
@GreaterFire /etc/resolv.conf  is also not support？

**Comment by GreaterFire** [comment]
What I meant is, GitHub Issues is for bug report and feature request, not for generic tech support. I'm sorry but I have to close this. You should try to get help elsewhere.

**Comment by imtv** [comment]
@GreaterFire Can i modify config.json to change DNS ？
