### ISSUE TITLE
[BUG] 启动trojan之后，windows代理不能用了。

### ISSUE THREAD

**Issue by SalicylicAcid** [trojan-gfw/trojan#236]
[√] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
version 1.14.1

**Describe the bug**
启动trojan后，Windows代理设置失效，无法开启和修改内容。关闭trojan后恢复正常。
![image](https://user-images.githubusercontent.com/37034452/73653682-bb695c00-46c4-11ea-9686-b58f8e765837.png)

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?
windows 10 pro 2004

**Additional context**
希望尽早推出图形化应用界面。

**Comment by GreaterFire** [comment]
@SalicylicAcid This is not the correct way of setting proxy. Please do it in your browser.
