### ISSUE TITLE
为什么到现在trojan都没有一个像shadowsocksX那样的mac版客户端

### ISSUE THREAD

**Issue by isyume** [trojan-gfw/trojan#237]
为什么到现在trojan都没有一个像shadowsocksX那样的mac版客户端，而是用了所谓的脚本调用二进制文件后在chrome还要用插件。

**Comment by shogunpeter** [comment]
顺便求一个图形化的win客户端

**Comment by tomac4t** [comment]
有 [Qt 版本](https://github.com/trojan-gfw/trojan-qt)，不过没必要，因为它只是代理程序，你不会频繁打开它的，大部分代理程序都是这样的。Mac 上应该也有类似与 systemd 的管理服务，所以不必用脚本:-)

**Comment by GreaterFire** [comment]
No such plan. CLI is sufficient.

**Comment by GreaterFire** [comment]
@shogunpeter Please, don't impose on the developers. No one is obligated to write you any software. If you'd like, you should make a GUI yourself.

**Comment by trkwyk** [comment]
> No such plan. CLI is sufficient.

Hello. May I ask how to run it in the background and disable it from printing the logs in terminal? I'm running it on macOS.

**Comment by GreaterFire** [comment]
@trkwyk No, you may not ask here.

**Comment by Win2Socks** [comment]
> 顺便求一个图形化的win客户端

现在有了 :slightly_smiling_face: https://github.com/Win2SocksSoftware/TrojanPlugin

**Comment by ghost** [comment]
> 为什么到现在trojan都没有一个像shadowsocksX那样的mac版客户端，而是用了所谓的脚本调用二进制文件后在chrome还要用插件。

全平台的客户端: https://github.com/TheWanderingCoel/Trojan-Qt5

**Comment by teel-writ-ros** [comment]
https://github.com/JimLee1996/TrojanX
