### ISSUE TITLE
Hello, have you plan to do SIP003 Plugin on Android platform?

### ISSUE THREAD

**Issue by player20033** [trojan-gfw/trojan#238]
by make new android client probably not better to using exists clients to help using trojan.
I am not sure, and I am trying to use your trojan on my server.

**Comment by GreaterFire** [comment]
@player20033 I'm sorry. The current SIP003 support is just a toy and we will not work towards a usable plugin.

But seriously, why use Shadowsocks still?

**Comment by player20033** [comment]
Just peoples theirs self problems like lazy or some what, nothing more.
