### ISSUE TITLE
macOS: [FATAL] fatal: config.json(5): expected value

### ISSUE THREAD

**Issue by chuckleong21** [trojan-gfw/trojan#239]
This error appears every time after I changed the following fields respectively in the config.json file:

```
remote_addr: my_addr,
password: my_password,
cert: /etc/ssl/cert.pem
```
2020-02-05 14:30:54] [FATAL] fatal: config.json(5): expected value
[2020-02-05 14:30:54] [FATAL] exiting. . .

However, `start.command` was successfully running when no params were changed. **What is this error and how do I fix it?**

**Comment by jzgenius** [comment]
"cert": "/etc/ssl/cert.pem"

**Comment by GreaterFire** [comment]
Please quote all your strings.
```json
"remote_addr": "my_addr",
"password": ["my_password"],
"cert": "/etc/ssl/cert.pem",
```
Also, please download the latest version of trojan.
