### ISSUE TITLE
Consider adding GnuTLS support

### ISSUE THREAD

**Issue by nametoolong** [trojan-gfw/trojan#24]
GnuTLS has some nice features which could help circumventing GFW. GnuTLS does [hide record lengths](https://www.gnutls.org/manual/html_node/On-Record-Padding.html) and can be configured to emulate OpenSSL signatures, and therefore could be useful against TLS over TLS detections and other attacks.  
One caveat: GnuTLS is considered to be lacking in security reviews.

**Comment by GreaterFire** [comment]
> The TLS protocol allows for extra padding of records in CBC ciphers

CBC ciphers are considered weak and are not being used today. If we use CBC ciphers for this functionality, it might be easier to identify trojan (just by looking at chosen cipher).

GnuTLS might or might not work with Boost. If it does work, then no code needs to be changed; but if it doesn't, any change of code is futile. I'll try it and give you an answer.

**Comment by nametoolong** [comment]
It won't easily be used to identify trojan, although it may potentially leak some information. Most browsers still accepts `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA` and `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` as secure ciphersuites up-to-date.
