### ISSUE TITLE
Can I define which protocol trojan uses? (ipv4, ipv6)

### ISSUE THREAD

**Issue by HolgerHuo** [trojan-gfw/trojan#240]
My server has both ipv4 and ipv6 addresses and my domain is also resolved to both addresses using A record and AAAA record. I'm using mac client and it could connect successfully through ipv6. but nowadays it seems that my ipv6 isp is quite unstable (china unicom). My ipv6 connection sometimes dropped but I still got the link-local address, but in fact, I couldn't ping6 my server ipv6 address, or any other ipv6 addresses. I tried to delete the record of my AAAA ipv6 address. But trojan can't resolve the hostname now, instead of connecting through ipv4. it seems that if there is ipv6 connection, trojan will connect through ipv6. Would you please add a configuration on ipv4/ipv6 protocols?  thank u.

**Comment by GreaterFire** [comment]
@HolgerHuo You can try putting your server's IPv4 address in the remote_addr field and your domain name in the sni field. The certificate will be correctly verified.

**Comment by HolgerHuo** [comment]
Copy that, thank you so much!
