### ISSUE TITLE
unknow protocol

### ISSUE THREAD

**Issue by Alvin9999** [trojan-gfw/trojan#242]
![trojan](https://user-images.githubusercontent.com/12132898/74001323-23aa8d00-49a6-11ea-9fb7-0dc733f1fa2a.PNG)

最近trojan很不稳定，用几个小时后就变的很慢，再用几个小时甚至网页都打不开。请帮忙分析下，谢谢。用的是最新的客户端。

**Comment by GreaterFire** [comment]
@Alvin9999 https://github.com/trojan-gfw/trojan/wiki/What-the-heck-do-these-logs-mean%3F

**Comment by Alvin9999** [comment]
收到，感谢，我试试看

**Comment by Alvin9999** [comment]
客户端对应的浏览器代理设置的是socks5 127.0.0.1和1080端口。服务器换了一台新的。还是同样的报错。

用的是网络上的一键搭建trojan脚本，域名搭建了很多次了。

**Comment by Alvin9999** [comment]
新服务器只部署了trojan，没有部署其它代理。

**Comment by Alvin9999** [comment]
@GreaterFire 需要您的帮助。

**Comment by GreaterFire** [comment]
@Alvin9999 We typically do not resolve user issues on GitHub. The GitHub Issue is for bug report and feature request. By the look of things, you certainly have a configuration error.

**Comment by Alvin9999** [comment]
没办法，所以向您求助了。配置错误指的是服务端还是客户端呢？

**Comment by GreaterFire** [comment]
@Alvin9999 Please specify in detail how you setup the socks5 proxy.

**Comment by Alvin9999** [comment]
请看截图

![2222](https://user-images.githubusercontent.com/12132898/74003940-47260580-49af-11ea-83db-a8efecb08d76.PNG)

**Comment by GreaterFire** [comment]
@Alvin9999 Please use a newer version of SwitchyOmega. I know the old versions have bugs.

**Comment by Alvin9999** [comment]
![333333](https://user-images.githubusercontent.com/12132898/74004252-37f38780-49b0-11ea-9593-7076a307a596.PNG)

刚重新安装的第一个，测试后还是同样的报错。

**Comment by GreaterFire** [comment]
@Alvin9999 Please provide a packet capture of your session.

**Comment by Alvin9999** [comment]
![31](https://user-images.githubusercontent.com/12132898/74004451-c5cf7280-49b0-11ea-85e1-e6043cdf73fe.PNG)
![32](https://user-images.githubusercontent.com/12132898/74004457-c831cc80-49b0-11ea-9819-43a7e8acedaf.PNG)

图1是刚打开软件后的截图，就有报错了。图2是打开google时的截图。

**Comment by GreaterFire** [comment]
@Alvin9999 I need a packet capture. Not the log of trojan. If you can't provide such packet capture, I can't help you.

**Comment by Alvin9999** [comment]
CONNECT translate.googleapis.com:443 HTTP/1.1
Host: translate.googleapis.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36


HTTP/1.1 504 Fiddler - Receive Failure
Date: Fri, 07 Feb 2020 05:59:53 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, must-revalidate
Timestamp: 13:59:53.783

[Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 0 bytes.

**Comment by GreaterFire** [comment]
@Alvin9999 PLEASE STOP YOUR FIDDLER and use ProxyOmega instead.

**Comment by Alvin9999** [comment]
请问怎么获取session呢

**Comment by qogris** [comment]
The cause of this issue is that trojan received http protocol rather than SOCKS5. So...the following request is, could you please also add privoxy into one dockerfile. I just want to use my Synology NAS to sync with Google Drive, but as I know, Synology only works on http/https proxy, thanks.
