### ISSUE TITLE
[ASK] create account

### ISSUE THREAD

**Issue by malikshi** [trojan-gfw/trojan#243]
**Trojan Version**
latest version 1.14.1
**Describe the bug**
not really bug but i cant understood how Authenticator works especially hash password

**Logs**
>> Feb  7 18:12:11 cbtp trojan[9059]: [2020-02-07 18:12:11] [WARN] IP:PORT valid trojan request structure but possibly incorrect password (15ea5abf0d742d8d5d48d50d936fb70dfbc33cea68910d359549055e)

i tried to make bash script to create account via terminal. addtrojan.sh
>>CLIENT_NAME="$1"
    if [ "$CLIENT_NAME" == "" ]; then
        echo "INPUT USERNAME"
        read -p "Client name: " -e CLIENT_NAME
    fi
CLIENT_PASS="$2"
    if [ "$CLIENT_PASS" == "" ]; then
        echo "INPUT PASSWORD"
        read -p "Client Pass: " -e CLIENT_PASS
    fi
#hash password
pwd=$(echo -n "$CLIENT_PASS" | sha224sum | awk '{print $1}')
echo "USE trojan; INSERT INTO users (username, password, quota) VALUES ('$CLIENT_NAME', '$pwd' , '-1');" | mysql -utrojan -ppassmysql;

reference: [tutor1](https://www.atrandys.com/2020/2269.html) and [tutor2](https://trojan-gfw.github.io/trojan/authenticator)

**Comment by GreaterFire** [comment]
SQL has builtin SHA support. Please use that.

**Comment by malikshi** [comment]
is it like this
>> mysql> SELECT SHA2('abc', 224);
        -> '23097d223405d8228642a477bda255b32aadbce4bda0b3f7e36c9da7'

i tried it hash same result as using `echo -n "password" | sha224sum | awk '{print $1}` or am i wrong?

**Comment by GreaterFire** [comment]
@malikshi You are correct.

**Comment by malikshi** [comment]
@GreaterFire i setting up trojan config server, and add users according to reference you mentioned, but still invalid/incorrect password

**Comment by GreaterFire** [comment]
@malikshi Please paste your server config.

**Comment by malikshi** [comment]
>>{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "adasdd",
                "qnSHWam"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/usr/local/etc/acme/certificate.crt",
        "key": "/usr/local/etc/acme/private.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
                "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": true,
        "no_delay": true,
        "keep_alive": true,
                "reuse_port": true,
        "fast_open": true,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": true,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "dbname",
        "username": "dbusers",
        "password": "dbpasswords"
    }
}

**Comment by GreaterFire** [comment]
@malikshi This should work. Is your dbname trojan?

**Comment by malikshi** [comment]
@GreaterFire  yup dbname trojan. userdb trojan

**Comment by GreaterFire** [comment]
@malikshi In your SQL statement, why is your password $pwd?

**Comment by GreaterFire** [comment]
@malikshi Oh I see

**Comment by GreaterFire** [comment]
@malikshi Can you show me the content of trojan.users table? Also did you restart trojan server after you modify the trojan config?

**Comment by malikshi** [comment]
try create users with u/p: testest
>>USE trojan; INSERT INTO users (username, password, quota) VALUES ('testest', '02d4b8ad3e5a91ce8a30a50217bfff071cc6098745a69dcf2ae44614' , -1);

here log error
Feb  8 00:22:04 cbtp trojan[19056]: [2020-02-08 00:22:04] [WARN] ip:6008 valid trojan request structure but possibly incorrect password (2d73dbb1e15cb1b6d71d579abe84cbe0b29446ffb06ca0fec20b5455)
Feb  8 00:22:04 cbtp trojan[19056]: [2020-02-08 00:22:04] [WARN] IP:6008 not trojan request, connecting to 127.0.0.1:80
Feb  8 00:22:04 cbtp trojan[19056]: [2020-02-08 00:22:04] [INFO] IP:6008 disconnected, 343 bytes received, 118 bytes sent, lasted for 1 second

**Comment by GreaterFire** [comment]
@malikshi See. You did have an incorrect password. Your password in the database starts with 02d but the password you gave starts with 2d7.

**Comment by malikshi** [comment]
data table users
![Screenshot_657](https://user-images.githubusercontent.com/9080737/74050765-40c47780-4a09-11ea-9a63-2527aafcbb8c.jpg)

**Comment by GreaterFire** [comment]
@malikshi Your password in the client config should be the plain password. Is that correct?

**Comment by malikshi** [comment]
"password": [
        "testest:testest"
    ],

is it wrong?

**Comment by GreaterFire** [comment]
@malikshi No. It should be testest, excluding your username

**Comment by GreaterFire** [comment]
@malikshi What you wrote is the trojan-panel format

**Comment by malikshi** [comment]
@GreaterFire  so what format for password format for this mariadb only. i try not using trojan-panel

**Comment by GreaterFire** [comment]
@malikshi Just the password itself. Do not include your username and the colon.

**Comment by malikshi** [comment]
owh i see. i need recode again for android apk xD. im using trojan-panel format in android
thank you very much for the explanation :)
