### ISSUE TITLE
fatal: load_verify_file: No such file or directory

### ISSUE THREAD

**Issue by ooking** [trojan-gfw/trojan#249]
King@mbp trojan % ./start.command
Welcome to trojan 1.14.1
[2020-02-13 17:05:42] [FATAL] fatal: load_verify_file: No such file or directory
[2020-02-13 17:05:42] [FATAL] exiting. . . 

请问这是因为没有安装 Boost 还是版本不对？

**Comment by ooking** [comment]
brew install boost  了 1.72 仍然出错

**Comment by GreaterFire** [comment]
Please paste your config here.

**Comment by Evisolpxe** [comment]
通常是cilent没有设置好cert路径导致的。

把config.json {‘ssl"-"cert"} 改成证书绝对路径重启试试

**Comment by he323219002** [comment]
mac系统同样遇到这个问题

**Comment by GreaterFire** [comment]
@he323219002 Please, post your configs. No one's going anywhere if you just complain like that.

**Comment by maidousj** [comment]
遇到同样错误，需要把config文件和/usr/src/trojan-cli/fullchain.cer 拷贝到本地客户端所在路径。
