### ISSUE TITLE
Add PSK cipher suites for certificate-less setup

### ISSUE THREAD

**Issue by testcaoy7** [trojan-gfw/trojan#25]
Please consider adding PSK cipher suites for certificate-less setup.
Recommendation:
TLS_PSK_WITH_AES_128_GCM_SHA256 and TLS_PSK_WITH_AES_256_GCM_SHA384 in RFC5487

**Comment by GreaterFire** [comment]
I might not want to implement this because it does not look like normal HTTPS behavior. Most websites use certificates.

**Comment by testcaoy7** [comment]
@GreaterFire
 In recent days, servers use IPLC and IEPL connection become more common. Those connections have no censorship.
A PSK certificate-less setup in IPLC has certain advantages. To reduce cost, a lot of IPLC-VPS comes with NAT. They do not has public IP address and you cannot issue a Lets Encrypt certificate in those machine. A PSK setup can be used in NAT-VPS. You will get a trojan server like shadowsocks but the encryption will be provided by TLS and OpenSSL.

**Comment by GreaterFire** [comment]
@testcaoy7 In that case, just use Shadowsocks.
