### ISSUE TITLE
[Feature Request]服务端重定向流量

### ISSUE THREAD

**Issue by yavon007** [trojan-gfw/trojan#250]
希望增加功能，Trojan服务端支持把流量发送到指定的地址和端口。

**Comment by GreaterFire** [comment]
We support this.
https://trojan-gfw.github.io/trojan/protocol

**Comment by yavon007** [comment]
是我表述的不够清楚，我的意思是通过Trojan在两台VPS之间建设一个流量隧道，服务端不再提供代理功能，而是把流量发送到指定的地址与端口。

**Comment by GreaterFire** [comment]
Use socat for that purpose.

**Comment by yavon007** [comment]
Oh, my dear big man.I mean, A is trojan of NAT conf.B is trojan of Server conf.C is a SS agent.I send SS traffic to A and forward traffic to A NAT conf port,A send traffic to B by trojan protocol.Address and port that B can forward to C after receiving traffic.Like forward conf,server_forward.大体就这个，塑料机翻英语。
