### ISSUE TITLE
How force use tls1.3?

### ISSUE THREAD

**Issue by PHCSJC** [trojan-gfw/trojan#251]
Hi,your project is very great, I know trojan support tls1.3, but I want to know how force use tls1.3? don't use tls 1.2

thanks!

**Comment by GreaterFire** [comment]
There is no way to do this unless you tweak the code. We have no plan on supporting this right now.

**Comment by PHCSJC** [comment]
ok, thanks! wait this function!

**Comment by PHCSJC** [comment]
@GreaterFire  reopen? why?

**Comment by unknowndevQwQ** [comment]
> @GreaterFire reopen? why?

wait

**Comment by JoshDaone** [comment]
What's the expected behavior of comment the cipher out from the config.json and only keeps the `cipher_tls13`?
```
// "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
"cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
```

**Comment by GreaterFire** [comment]
@PHCSJC It's reopened because we are considering implementing it.

**Comment by GreaterFire** [comment]
Due to complexities, we decided not to implement this. Sorry.
