### ISSUE TITLE
[BUG]?使用Trojan会导致vps堵塞，v2ray可以正常代理

### ISSUE THREAD

**Issue by zatol** [trojan-gfw/trojan#253]
![使用Trojan会导致vps堵塞，v2ray可以正常代理]()

- [ ] I certify that I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.14.0

**Describe the bug**
<img width="510" alt="1-1912041R602F9" src="https://user-images.githubusercontent.com/6405354/74510132-0ba2b280-4f3e-11ea-9c89-a807370fb8c3.png">
根据trojan的网络流程，当使用trojan客户端代理上网时，请求Trojan服务端上的443端口上的网页服务时，会导致死循环吗？即由Internet转发过来后的other请求协议头会跟Trojan客户端的头协议一致，从而导致死循环吗？我描述可能不正确，但是我的现象是使用Trojan代理上网时请求部署Trojan服务的网页服务时，会导致整个vps的堵塞感，当断开时，间隔一段时间，不使用Trojan代理，直接请求网页服务，又可以正常访问了。

**Logs**
Feb 14 14:50:22 instance-1 trojan[14188]: [2020-02-14 14:50:22] [WARN] 172.69.63.44:40908 not trojan request, connecting to 127.0.0.1:80
Feb 14 14:50:22 instance-1 trojan[14188]: [2020-02-14 14:50:22] [INFO] 141.101.69.190:55900 disconnected, 6781 bytes received, 429 bytes sent, lasted for 120 seconds
Feb 14 14:50:22 instance-1 trojan[14188]: [2020-02-14 14:50:22] [INFO] *.*.*.*:5063 authenticated as ********
Feb 14 14:50:22 instance-1 trojan[14188]: [2020-02-14 14:50:22] [INFO] *.*.*.*:5063 requested UDP associate to 0.0.0.0:0
Feb 14 14:50:22 instance-1 trojan[14188]: [2020-02-14 14:50:22] [WARN] 141.101.69.172:23102 not trojan request, connecting to 127.0.0.1:80
Feb 14 14:50:22 instance-1 trojan[14188]: [2020-02-14 14:50:22] [INFO] *.*.*.*:5064 authenticated as ********
Feb 14 14:50:22 instance-1 trojan[14188]: [2020-02-14 14:50:22] [INFO] *.*.*.*:5064 requested UDP associate to 0.0.0.0:0
Feb 14 14:50:22 instance-1 trojan[14188]: [2020-02-14 14:50:22] [INFO] 141.101.69.164:29746 disconnected, 6578 bytes received, 401 bytes sent, lasted for 120 seconds
Feb 14 14:50:23 instance-1 trojan[14188]: [2020-02-14 14:50:23] [INFO] *.*.*.*:5065 authenticated as ********
Feb 14 14:50:23 instance-1 trojan[14188]: [2020-02-14 14:50:23] [INFO] *.*.*.*:5065 requested connection to 220.249.244.23:33445
Feb 14 14:50:23 instance-1 trojan[14188]: [2020-02-14 14:50:23] [INFO] *.*.*.*:5066 authenticated as ********
Feb 14 14:50:23 instance-1 trojan[14188]: [2020-02-14 14:50:23] [INFO] *.*.*.*:5066 requested connection to 220.249.244.23:33445
Feb 14 14:50:24 instance-1 trojan[14188]: [2020-02-14 14:50:24] [WARN] 108.162.229.139:28256 not trojan request, connecting to 127.0.0.1:80
Feb 14 14:50:25 instance-1 trojan[14188]: [2020-02-14 14:50:25] [INFO] 108.162.229.241:48976 disconnected, 3971 bytes received, 444 bytes sent, lasted for 120 seconds
Feb 14 14:50:25 instance-1 trojan[14188]: [2020-02-14 14:50:25] [INFO] 141.101.69.28:17422 disconnected, 9137 bytes received, 418 bytes sent, lasted for 121 seconds
Feb 14 14:50:25 instance-1 trojan[14188]: [2020-02-14 14:50:25] [INFO] 108.162.229.183:53062 disconnected, 6572 bytes received, 401 bytes sent, lasted for 120 seconds
Feb 14 14:50:26 instance-1 trojan[14188]: [2020-02-14 14:50:26] [WARN] 141.101.69.168:61534 not trojan request, connecting to 127.0.0.1:80
Feb 14 14:50:26 instance-1 trojan[14188]: [2020-02-14 14:50:26] [WARN] 141.101.69.162:9518 not trojan request, connecting to 127.0.0.1:80
Feb 14 14:50:26 instance-1 trojan[14188]: [2020-02-14 14:50:26] [WARN] 141.101.69.26:25608 not trojan request, connecting to 127.0.0.1:80
Feb 14 14:50:27 instance-1 trojan[14188]: [2020-02-14 14:50:27] [INFO] *.*.*.*:4932 disconnected, 46 bytes received, 85 bytes sent, lasted for 181 seconds
Feb 14 14:50:27 instance-1 trojan[14188]: [2020-02-14 14:50:27] [INFO] *.*.*.*:5069 authenticated as ********
Feb 14 14:50:27 instance-1 trojan[14188]: [2020-02-14 14:50:27] [INFO] *.*.*.*:5069 requested connection to 203.205.255.220:8080
Feb 14 14:50:29 instance-1 trojan[14188]: [2020-02-14 14:50:29] [WARN] 162.158.78.67:12936 not trojan request, connecting to 127.0.0.1:80
Feb 14 14:50:29 instance-1 trojan[14188]: [2020-02-14 14:50:29] [WARN] 141.101.69.36:56106 not trojan request, connecting to 127.0.0.1:80
Feb 14 14:50:30 instance-1 trojan[14188]: [2020-02-14 14:50:30] [INFO] 141.101.69.86:28782 disconnected, 3979 bytes received, 444 bytes sent, lasted for 121 seconds

**Environment**
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch

**Comment by GreaterFire** [comment]
The backend HTTP server should listen on both 127.0.0.1:80 and 0.0.0.0:80 and have different behaviors (0.0.0.0:80 will redirect to https while 127.0.0.1:80 serves the content). Is this the case for you? If it is then there shouldn't be any kind of infinite loop.

**Comment by zatol** [comment]
> The backend HTTP server should listen on both 127.0.0.1:80 and 0.0.0.0:80 and have different behaviors (0.0.0.0:80 will redirect to https while 127.0.0.1:80 serves the content). Is this the case for you? If it is then there shouldn't be any kind of infinite loop.

谢谢您的回复，目前这样的现象没有发生了，可能是我的vps的问题，再次感谢

**Comment by alegoho** [comment]
> > The backend HTTP server should listen on both 127.0.0.1:80 and 0.0.0.0:80 and have different behaviors (0.0.0.0:80 will redirect to https while 127.0.0.1:80 serves the content). Is this the case for you? If it is then there shouldn't be any kind of infinite loop.
> 
> 谢谢您的回复，目前这样的现象没有发生了，可能是我的vps的问题，再次感谢

请问你问题有解决吗？我的情况跟你一样
