### ISSUE TITLE
fatal: config.json: cannot open file

### ISSUE THREAD

**Issue by iwoow** [trojan-gfw/trojan#255]
fatal: config.json: cannot open file

**Comment by iwoow** [comment]
Installing trojan 1.14.1 to /usr/local/bin/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
Installing trojan systemd service to /etc/systemd/system/trojan.service...



**Welcome to trojan 1.14.1
[2020-02-14 20:10:52] [FATAL] fatal: config.json: cannot open file
[2020-02-14 20:10:52] [FATAL] exiting. . .** 

/usr/local/etc/trojan/config.json
`{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "********",
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/www/server/panel/vhost/cert/********/fullchain.pem",
        "key": "/www/server/panel/vhost/cert/********/privkey.pem",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": ""
    }
}`

**Comment by GreaterFire** [comment]
Please run trojan as
```
trojan /path/to/config.json
```

**Comment by MaBoCoMark** [comment]
trojan.exe trojan /path/to/config.json
Welcome to trojan 1.16.0
[2020-12-11 22:46:03] [FATAL] fatal: too many positional options have been specified on the command line
[2020-12-11 22:46:03] [FATAL] exiting. . .

**Comment by sjzlida** [comment]
yes! I got it ,thanks.
