### ISSUE TITLE
[Question] Implementation details about hex(SHA224(password))

### ISSUE THREAD

**Issue by GF-Huang** [trojan-gfw/trojan#256]
Different languages have different implementations, but I can't be sure that my implementation is correct. So I need data for unit testing.

Could you show me an example how the `password` generate?

For example: 
password `"123456789"`  
SHA224(password) `46 2C 1C 93 3B F9 71 09 9A C7 71 E7 83 85 5A D8 76 35 48 B6 B5 85 4B 09 86 4A 53 44`
hex(SHA224(password)) `"462c1c933bf971099ac771e783855ad8763548b6b5854b09864a5344"`

**Comment by GreaterFire** [comment]
```
$ printf 123456789 | sha224sum
9b3e61bf29f17c75572fae2e86e17809a4513d07c8a18152acf34521  -
```
