### ISSUE TITLE
[BUG]nginx https direct access error

### ISSUE THREAD

**Issue by sunlewuyou** [trojan-gfw/trojan#257]
**Trojan Version**
trojan 1.14.1

**Describe the bug**
Using nginx, directly accessing https: // will result in the error shown below, while accessing http: // port 80 will be no problem.
![image](https://user-images.githubusercontent.com/19728435/74556094-2c97f180-4f98-11ea-9169-739f12f8a508.png)

**Comment by sunlewuyou** [comment]
I found some information, but I don't know how to solve this problem, thanks!
![image](https://user-images.githubusercontent.com/19728435/74556789-c44a0f80-4f99-11ea-99f7-e98ce0b2ff17.png)
URL: https://scotthelme.co.uk/a-new-security-header-referrer-policy/

**Comment by tomac4t** [comment]
It is no related to Referrer Policy and Trojan. Please check why request `style.css` fails (see your console).

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/74558905-1ab94d00-4f9e-11ea-9a5a-a49a64335c93.png)

**Comment by GreaterFire** [comment]
Please make your website load its assets via HTTPS.

**Comment by sunlewuyou** [comment]
A stupid question: Is it configured in nginx.conf?
Can you give an example? Thank you!

**Comment by GreaterFire** [comment]
Nope. It's specific to your website. I can't help you because it's not a trojan issue.

**Comment by sunlewuyou** [comment]
OK, I already know what to do, thank you for your prompt reply! Thanks again!
