### ISSUE TITLE
[FATAL] fatal: bind: Address already in use

### ISSUE THREAD

**Issue by StrollStars** [trojan-gfw/trojan#259]
Such as the title.
System: Ubuntu 19.04
HTTP server: Apache
Error still after I turn off apache or change trojan port.

**Comment by malikshi** [comment]
dont forget to restart apache2 service and trojan after change it

**Comment by StrollStars** [comment]
> dont forget to restart apache2 service and trojan after change it

Thanks for your help, I did the following and still reported the error.
1.restart apache2
2.change trojan port
3.restart trojan

**Comment by malikshi** [comment]
Sent screenshot of `netstat -ntlp`
And config you trojan server also apache port config
