### ISSUE TITLE
[BUG]How could I set up on Edge or IE ?

### ISSUE THREAD

**Issue by Jasson101** [trojan-gfw/trojan#261]
Sorry I'm a beginner. I set up Trojan on Google crome, everything is going well. However I tried use socks5 on Windows10 to use other App. It didn't work. How could I use 全局代理 like SSR ？ PLease someone helps me !

**Comment by Jasson101** [comment]
I have another question. Befor yesterday my trojan speed is up to 30Mb/s ，but today is like 500Kb/s to go abroad. The ping to my VPS is around 300s to 2500s . IDK what is going on. What maybe the problem?

**Comment by KunagisaYuki** [comment]
@Jasson101 Use your Windows proxy settings in your ie or system settings.
Again, issues is a place for *Trojan related* problems.

**Comment by Jasson101** [comment]
> @Jasson101 Use your Windows proxy settings in your ie or system settings.
> Again, issues is a place for _Trojan related_ problems.

I tried, didn't work. Could u give me specific info?  Please

**Comment by KunagisaYuki** [comment]
@Jasson101 Some simple searching can answer the problem, for example, you can read this: https://amp.reddit.com/r/techsupport/comments/4j0l35/windows_10_route_all_traffic_through_socks5_proxy/
And you should know that the shadowsocks gui's global proxy do the equivalent thing.(Which means that if correctly configured they will have the same effect.)

**Comment by Jasson101** [comment]
neigher of them way work. But thanks , you can close the issues



在 2020-02-16 23:13:51，"KunagisaYuki" <notifications@github.com> 写道：

@Jasson101 Some simple searching can answer the problem, for example, you can read this: https://amp.reddit.com/r/techsupport/comments/4j0l35/windows_10_route_all_traffic_through_socks5_proxy/
And you should know that the shadowsocks gui's global proxy do the equivalent thing.(Which means that if correctly configured they will have the same effect.)
