### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Super-Gil** [trojan-gfw/trojan#262]
- [*] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
1.4.1

**Describe the bug**
All the websites works fine except wikipedia.org on Mac OS but it works perfectly fine on my Windows machine, it says failed to connect to the server in the Terminal. I had checked all the related settings...

**To Reproduce**
1. It disconnected the connection

**Expected behavior**
The website should work fine.

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?
MacOS 10.15

**Additional context**

**Comment by Super-Gil** [comment]
Sorry the version should be 1.14.1, the latest one

**Comment by ghost** [comment]
https://github.com/johnrosen1/trojan-gfw-script try this please

**Comment by GreaterFire** [comment]
@Super-Gil Please post your log.

**Comment by Super-Gil** [comment]
> 
> 
> @Super-Gil Please post your log.

Sorry but where can I find the log please?
