### ISSUE TITLE
[BUG] Can not access 'google.com' on Safari

### ISSUE THREAD

**Issue by 0xxxD** [trojan-gfw/trojan#266]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
1.14.1

**Describe the bug**
Can not access 'google.com' on Safari macOS
But Chrome is great, and access other website is ok on Safari so far.
Safari Version 13.0.5 (15608.5.11)

my config.json as below:
`{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "mydomain",
    "remote_port": 443,
    "password": [
        "mypassword"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "/etc/ssl/cert.pem",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}
`

**To Reproduce**
1. launch trojan by './start.command'
2. open Proxifier App
3. using Safari access google.com

**Expected behavior**
access  normally on all browser

**Logs**
If applicable, add logs to help explain your problem.
./start.command
Welcome to trojan 1.14.1
[2020-02-20 04:20:36] [WARN] trojan service (client) started at 127.0.0.1:1080
[2020-02-20 04:20:44] [INFO] 127.0.0.1:55143 requested connection to 216.58.200.238:443
[2020-02-20 04:20:44] [INFO] 127.0.0.1:55146 requested connection to 216.58.200.238:443
[2020-02-20 04:20:44] [INFO] 127.0.0.1:55149 requested connection to 112.90.216.111:443
[2020-02-20 04:20:44] [INFO] 127.0.0.1:55143 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-02-20 04:20:44] [INFO] 127.0.0.1:55149 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-02-20 04:20:44] [INFO] 127.0.0.1:55155 requested connection to 31.13.69.160:443
[2020-02-20 04:20:45] [INFO] 127.0.0.1:55155 disconnected, 0 bytes received, 517 bytes sent, lasted for 1 seconds
[2020-02-20 04:20:48] [INFO] 127.0.0.1:55146 disconnected, 7274 bytes received, 1486 bytes sent, lasted for 4 seconds

**Environment**
Where are you running trojan? What is your proxy set up?
 I am using 'Proxifier' to export socks5:1080 to all Stuff on macOS 10.15.3 (19D76)

**Additional context**
I suspect the bug  is relate to the 'cert' field in config.json file

**Comment by GreaterFire** [comment]
Not a bug.

**Comment by 0xxxD** [comment]
@GreaterFire I know it isn't a bug, so what is wrong in my usage? tell me plz..

**Comment by GreaterFire** [comment]
@0xxxD See CONTRIBUTING.md

**Comment by Jason5Lee** [comment]
How do you solve it? I have the same problem on MacOS.
