### ISSUE TITLE
[Feature Request] Client side authentication support

### ISSUE THREAD

**Issue by XenMe** [trojan-gfw/trojan#267]
when Trojan run in client mode (run-type set to client), it expose SOCKS5 to local network users.

Can we add authentication support for SOCKS5 to prevent unauthorized access? 

This allow us easily expose the SOCKS5 to internet to your friends. Without authentication support, we have to nested Trojan with another tool like V2Ray.

**Comment by XenMe** [comment]
as for the concerns that socks5 is an insecure protocol, but it's secure enough for local usage, and we don't use it for GFW, but for general purpose, such as share it to your friends temporarily for a few days. This doesn't need a strong secure protocol, but do need to prevent unauthorized access.

So hope this can provide more judgement to implement this enhancement.

**Comment by ghost** [comment]
you can achieve this in another way,thus it is not necessary to implement.

**Comment by XenMe** [comment]
It's a nice to have feature which shouldn't introduce too much complex.

**Comment by tomac4t** [comment]
Chrome/Firefox doesn't support native Socks5 authentication.

**Comment by GreaterFire** [comment]
We do not recommend exposing a SOCKS5 port to any network other than your local machine, even if it needs authentication. Thus, we'll not bother implementing it.
