### ISSUE TITLE
Does trojan support the unlocking of netflix

### ISSUE THREAD

**Issue by oyanli** [trojan-gfw/trojan#268]
Hello
Does trojan support the unlocking of netflix, as in the following method, I tried it, there is no way to unlock, and the default DNS server of the VPS cannot be unlocked, but v2ray is ok. Is there any other way to support unlocking?

https://github.com/myxuchangbin/dnsmasq_sniproxy_install

**Comment by diilaro** [comment]
yeah i have the same question
