### ISSUE TITLE
[Feature Request]Does trojan support the unlocking of netflix

### ISSUE THREAD

**Issue by oyanli** [trojan-gfw/trojan#269]
Hello
Does trojan support the unlocking of netflix, as in the following method, I tried it, there is no way to unlock, and the default DNS server of the VPS cannot be unlocked, but v2ray is ok. Is there any other way to support unlocking?

https://github.com/myxuchangbin/dnsmasq_sniproxy_install

**Comment by oasiscifr** [comment]
@oyanli Whether you can access Netflix services depends on the IP of your server. It has nothing to do with trojan.
