### ISSUE TITLE
Add support for TLS1.3

### ISSUE THREAD

**Issue by testcaoy7** [trojan-gfw/trojan#27]
TLS1.3 has a lot of security and performance improvements such as 0-RTT, and HKDF. Please consider implement TLS1.3 for hardened security.

**Comment by GreaterFire** [comment]
I will be considering TLS 1.3 when main stream OpenSSL supports it.

**Comment by testcaoy7** [comment]
Good to know.

**Comment by GreaterFire** [comment]
TLS 1.3 is approved by IETF.

**Comment by GreaterFire** [comment]
Detailed information about this adaptation is in the [wiki](https://github.com/trojan-gfw/trojan/wiki/Adaptation-to-New-Specifications-(TLS-1.3-and-HTTP-2)).
