### ISSUE TITLE
[Question]When trojan handle incoming TLS , website cannot use https (nginx)

### ISSUE THREAD

**Issue by Houiin** [trojan-gfw/trojan#270]
- [√] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.14.1

**Describe the bug**
I can only use http to access the website behind trojan through port 80.

I let Trojan handle incoming TLS and SSL is not enabled in nginx. **My website can only be accessed through port 80(no https)**, if I use `https://www.mydomain.com` I will get  ***ERR_EMPTY_RESPONSE***  (port 443 is already occupied by trojan). Trojan connect port `80` again when encountering other protocols

I try to set the `remote port` of the `config.json` of the trojan server to `4333` (like `"remote_port" : 4333,`) and modify nginx configuration file to `listen 4333 ssl http2`. 

## Trojan Server : `config.json`
```
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 4333,
    "password": [
        "password1",
...
```
## Nginx Configuration file
```
server
{
    listen 80;
    listen 4333 ssl http2;   # #### HERE IS WHAT I CHANGED  ##########
    server_name   www.mydomain.com;
 
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/website/root/path
    
# ~ If I remove this part of the mandatory HTTPS, my site will be accessed using http (`port 80`) ##
    if ($scheme = http ) {
        rewrite ^(/.*)$ https://$host$1 permanent;
    }

    ssl_certificate    /path/to/fullchain;
    ssl_certificate_key    path/to/key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;
...
}
```
But it doesn't work , **trojan server dos not connect port `4333` when encountering other protocols.** I can only access my website via `https://mydomain.com:4333`.How can I access the website using `https://mydomain.com`? 

If I change trojan's `local_port`  to a port other than 443, I will be able to configure https with nginx and trojan will work.  But Will trojan be more easily discovered by GFW because of non-443 port?

**Comment by GreaterFire** [comment]
Yes, we'll not support connecting to TLS backends.

**Comment by Houiin** [comment]
No matter how I modify the `remote_port` in the `config.json` on the server, I can only access the website through port 80

If my port 80 is also occupied and the web page needs to be accessed through port 8080, how do I set it up?:kissing_smiling_eyes:

**Comment by zhangzhhz** [comment]
@Houiin , let trojan listen at 443, change "remote_addr" to "127.0.0.1" and "remote_port" to 80 (or any port you prefer). Then change your Nginx's site configurations to listen at 80 without SSL.

Just google it. It also appears that you are not very familiar with Nginx. Spend some time on it.

**Comment by Houiin** [comment]
@zhangzhhz Thank you very much for your reply, but I still have some questions.

I have let trojan listen at 443, changed "remote_addr" to "127.0.0.1" and "remote_port" to 80 . But if I change the remote_port to any other port (e.g. 8080) and change nginx listen to 8080.  Trojan works well but  I can only access the web site using `www.domain.com:8080` instead of `www.domain.com`

Since non-trojan traffic is forwarded to port 8080, and nginx also listens on port 8080, I can visit www.domain.com directly to display the content of the website.  Is it right?

**Comment by zhangzhhz** [comment]
@Houiin , take a look at https://trojan-tutor.github.io/2019/04/10/p41.html#%E9%85%8D%E7%BD%AEnginx
