### ISSUE TITLE
how to use trojan from terminal in Mac OS

### ISSUE THREAD

**Issue by fan3cn** [trojan-gfw/trojan#273]
Hi, I am wondering how to use trojan from terminal in Mac OS, I checked that the local port listened by trojan is 8070, then I try to set the local proxy by:
export http_proxy=http://127.0.0.1:8070
export https_proxy=$http_proxy
But, it doesn't work.
Any solution?

**Comment by zhenchao125** [comment]
you can try: export all_proxy=socks5://127.0.0.1:8070

**Comment by fan3cn** [comment]
> you can try: export all_proxy=socks5://127.0.0.1:8070

it doesn't work neither.

**Comment by lilunxm12** [comment]
not all programs play nicely with socks5 proxy. you may want to try proxychains-ng

**Comment by tomac4t** [comment]
> it doesn't work neither.

Please unset your wrong `http_proxy` first and try @zhenchao125 said. You shouldn't ask this question here, because it is not MacOS support forum. We watch the repo and received these notifications are pretty annoying.

**Comment by stevenkitter** [comment]
I want to know too? anybody use it?
