### ISSUE TITLE
[Feature Request]希望增加api进行账号密码和流量统计

### ISSUE THREAD

**Issue by FenghenHome** [trojan-gfw/trojan#274]
参考：https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-manager.asciidoc

Send UDP commands in the following format to the manager-address provided to ss-manager(1):
command: [JSON data]

To add a port:
add: {"password":"7cd308cc059"}

To remove a port:
remove: {"password": "7cd308cc059"}

The format of the traffic statistics:
stat: {"7cd308cc059":11370}

**Comment by wongsyrone** [comment]
It introduces traffic characteristics if we respond to specific commands.

**Comment by GreaterFire** [comment]
Please read [this](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md) first.

This functionality is not really necessary to be included in the trojan core as trojan supports authentication via MySQL. You can easily offload your requirements to some other tools.

**Comment by FenghenHome** [comment]
如果单数据库多个节点，那么就存在远程数据库校验问题，远程数据库校验是很耗时的，还请帮忙改进一下

**Comment by rankjie** [comment]
Adding an API for stat/user query allows fine control over user authentication.
IMO, direct integration with MySQL is not necessary and limits service providers.
