### ISSUE TITLE
[Feature Request]mysql secure connection (TLS)

### ISSUE THREAD

**Issue by mem0rz** [trojan-gfw/trojan#277]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
trojan and the database of trojan panel perhaps exist on separate networks and they are in a high-risk network they could be sniff by gfw , I assume tls protocol could sloves this risk.
**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.
Just about secure.
**Describe the solution you'd like**
the libmysqlclient has a mysql_ssl_set function.
And add a config about where is certificate authoritie if use trust third-party ca user can inputs /etc/ssl/certs/ca-certificates.crt(in debian).
**Describe alternatives you've considered**
maybe use mysql odbc?
**Additional context**

**Comment by GreaterFire** [comment]
Try [stunnel](https://www.stunnel.org/) in between your MySQL server and Trojan server.

**Comment by mem0rz** [comment]
> 
> 
> Try [stunnel](https://www.stunnel.org/) in between your MySQL server and Trojan server.


I finished the code for secure connection to mysql. =,=Could I merge?
Many guys build they database in the wall, but the trojan is outside the wall. When trojan server connect to database GFW has the ability to eavesdrop the contents of mysql  communication. If We use secure tunnel to communication, which would be identified as cross wall. This will cause connection to be blocked by GFW, affecting the running of trojan.

**Comment by GreaterFire** [comment]
@cybmp3 Make a PR and I'll review

**Comment by ghost** [comment]
@cybmp3 When I refer to the online tutorials, almost all suggest to use two-way authentication to configure the database, that is, the server must also authenticate the slave. Can you update the code to support this feature?

By reffering to [dev.mysql.com](https://dev.mysql.com/doc/refman/8.0/en/mysql-ssl-set.html), change may be 
```mysql_ssl_set(&con, NULL, NULL, config.mysql.cafile.c_str(), NULL, NULL);```
 to 
```mysql_ssl_set(&con, config.mysql.keyfile.c_str(), config.mysql.certfile.c_str(), config.mysql.cafile.c_str(), NULL, NULL);```
 in `src/core/authenticator.cpp`, and some related files.
