### ISSUE TITLE
[question]如何填写openwrt上客户端的参数

### ISSUE THREAD

**Issue by shake** [trojan-gfw/trojan#278]
<img width="520" alt="快照3" src="https://user-images.githubusercontent.com/78207/75413641-0e030480-5961-11ea-952a-96031d243e42.png">

我现在使用 a.example.com 域名，注册了证书，也部署好trojan的服务器端。

我的pc端，没问题。

openwrt上，这些参数要如何填写？TLS Host，也是填写 a.example.com？

**Comment by shake** [comment]
刚才看了一下官方网站，感觉在openwrt上的配置，应该是一个转发端，不知道理解是否正确。

**Comment by shake** [comment]
我发错版块，sorry

**Comment by DongfeiSay** [comment]
我也想问
