### ISSUE TITLE
Can I put Trojan BEHIND Nginx?

### ISSUE THREAD

**Issue by OmmyZhang** [trojan-gfw/trojan#279]
As I have multiple domains and multiple certificates for my webserver, I hope to put Trojan behind Nginx. (Also, it seems more organize to let Nginx use the 443 port and put all other things behind.) 

Is it possible?

**Comment by OmmyZhang** [comment]
I see, maybe I can use ``ngx_stream_ssl_preread_module``.
It would be great if Trojan can support http/socket file connect.

**Comment by wuwentao** [comment]
have the same multiple domain issue as you.
still keeps on v2ray ws+tls+nginx mode now...
