### ISSUE TITLE
虽然不像是trojan的bug，但是这里请教下大佬

### ISSUE THREAD

**Issue by ldwnt** [trojan-gfw/trojan#282]
是这样的，google cloud hk asia-east2-b的机器，ping值稳定在30-50间，访问其他google服务都挺正常，耗流量的youtube也不卡，但是google maps基本处于半瘫痪状态。每次能正常访问半小时左右，然后就会卡住很长时间，查询地点的操作都做不了。换google cloud tw的机器，或者bandwagonhost la的机器，也是这种症状，看起来像是google maps自己的问题？

**Comment by chenjie** [comment]
@ldwnt 没有具体evidence的issue建议你还是直接close把
