### ISSUE TITLE
[FATAL] fatal: bind: Address already in use

### ISSUE THREAD

**Issue by sinovale** [trojan-gfw/trojan#283]
Hi guys,
I met an issue shows that "[FATAL] fatal: bind: Address already in use" after I typing command "journalctl -e -u trojan.service". It loooks like trojan not works well. 
For details, my config files and issue reports also attached. could you please check it? Thanks so much.
Jeff 
<img width="583" alt="journalctl -e -u trojan service" src="https://user-images.githubusercontent.com/61626265/75618822-74c92d80-5bae-11ea-9138-a9f9e8e3292a.png">
<img width="552" alt="netstat -ntulp" src="https://user-images.githubusercontent.com/61626265/75618823-7561c400-5bae-11ea-8ee5-6c8b89e82f1e.png">
<img width="586" alt="nginx_config" src="https://user-images.githubusercontent.com/61626265/75618824-75fa5a80-5bae-11ea-8cd7-a961d668145b.png">
<img width="630" alt="trojan service" src="https://user-images.githubusercontent.com/61626265/75618825-7692f100-5bae-11ea-8007-57fd03ac023b.png">

<img width="1049" alt="config json" src="https://user-images.githubusercontent.com/61626265/75618821-71ce3d00-5bae-11ea-90a1-1d36e8f8c785.png">

**Comment by KunagisaYuki** [comment]
@sinovale This means your port that in the configure file is occupied by another program,like nginx or something else. Stop these programs or change an application port will make it works.

**Comment by sinovale** [comment]
> @sinovale This means your port that in the configure file is occupied by another program,like nginx or something else. Stop these programs or change an application port will make it works.

Hi @KunagisaYuki Thank you for your reply. I'm not sure which port you mean. local address or remote address, and local port or remote port. Thanks again.

**Comment by bylond** [comment]
> > @sinovale This means your port that in the configure file is occupied by another program,like nginx or something else. Stop these programs or change an application port will make it works.
> 
> Hi @KunagisaYuki Thank you for your reply. I'm not sure which port you mean. local address or remote address, and local port or remote port. Thanks again.

Trojan needs to listen to the 443 port, both for IPv4 and IPv6 address by default. In your case, the 443 port for IPv6 address is taken by ngrokd. You need to set the parameter "prefer_ipv4" in trojan configuration to be "true". Or you can kill ngrokd and then start Trojan.

**Comment by sinovale** [comment]
@bylond Thanks for your reply. Follow your guide. Then I set "prefer_ipv4" to "true" and restart trojan. However, it still failed. But, if I kill the ngrokd progress, it works.

**Comment by bylond** [comment]
> @bylond Thanks for your reply. Follow your guide. Then I set "prefer_ipv4" to "true" and restart trojan. However, it still failed. But, if I kill the ngrokd progress, it works.

I thought the parameter "prefer_ipv4" means "ipv4 only". Anyway, glad you find the solution.

**Comment by sinovale** [comment]
If I change 'local_port' from 443 to any other port like 4433, is it safe for GFW detect?

**Comment by JoshDaone** [comment]
> If I change 'local_port' from 443 to any other port like 4433, is it safe for GFW detect?

Ideally non-standard HTTPS TCP port is good for mainland web server control, so u can change the monitoring TCP port to others.

**Comment by sinovale** [comment]
@JoshDaone @bylond @KunagisaYuki Hi guys, thanks again for your reply.
