### ISSUE TITLE
[BUG] FATAL exit error duing OS startup with mysql enabled config.json

### ISSUE THREAD

**Issue by wuwentao** [trojan-gfw/trojan#284]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
Welcome to trojan 1.14.1
Boost 1_72, OpenSSL 1.1.1d  10 Sep 2019
 [Enabled] MySQL Support (10.4.3)
 [Enabled] TCP_FASTOPEN Support
 [Enabled] TCP_FASTOPEN_CONNECT Support
 [Enabled] SSL KeyLog Support
 [Enabled] NAT Support
 [Enabled] TLS1.3 Ciphersuites Support
 [Enabled] TCP Port Reuse Support
OpenSSL Information
	Build Flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
**Describe the bug**

**To Reproduce**
1. enable mysql in config.json
2. not add trojan as service ,just run it in /etc/rc.local 
3. command in rc.local:  /srv/trojan/trojan -c /srv/trojan/config.json -l /var/log/trojan.log  &
4. error log can be found:

[2020-03-01 17:21:45] [WARN] got signal: 2
[2020-03-01 17:21:45] [WARN] trojan service stopped
[2020-03-01 17:24:41] [INFO] connecting to MySQL server 127.0.0.1:3306
[2020-03-01 17:24:41] [FATAL] fatal: Can't connect to MySQL server on '127.0.0.1' (115)
[2020-03-01 17:24:41] [FATAL] exiting. . .

5. reason: all the user/pw for mysql is right, just mysql servie startup slower then rc.local command line, casued this fatal error

**Expected behavior**
if mysql enabled, the startup timeout should large than mysql disabled mode.

**Logs**
[2020-03-01 17:21:45] [WARN] got signal: 2
[2020-03-01 17:21:45] [WARN] trojan service stopped
[2020-03-01 17:24:41] [INFO] connecting to MySQL server 127.0.0.1:3306
[2020-03-01 17:24:41] [FATAL] fatal: Can't connect to MySQL server on '127.0.0.1' (115)
[2020-03-01 17:24:41] [FATAL] exiting. . .

**Environment**
ubutu18.04 LTS
mysqld  Ver 5.7.29-0ubuntu0.18.04.1 for Linux on x86_64 ((Ubuntu))

**Additional context**

**Comment by GreaterFire** [comment]
Please make sure that your mysql server is **ready** before trojan launches.
