### ISSUE TITLE
[Feature Request]  trojan client for ubuntu

### ISSUE THREAD

**Issue by longlu** [trojan-gfw/trojan#286]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
yes, unable to use it on linux
**Is this problem relevant to what trojan should care about?**

yes

**Describe the solution you'd like**
a trogan client to use on linux /ubuntu

**Comment by GreaterFire** [comment]
@longlu See Wiki
