### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by CURAS** [trojan-gfw/trojan#29]
When I connect my own server with client, it will show these error infos.
server:
![image](https://user-images.githubusercontent.com/14164381/38183302-03db08b8-3672-11e8-8b8e-6e2abda8bd62.png)
client:
![image](https://user-images.githubusercontent.com/14164381/38183611-5862a312-3674-11e8-9f8b-2fa62d47abba.png)

I set `cert.pem` for cert, `privkey.pem` for key and keep empty for key password in my server's configuration file, which are provided by Let's Encrypt. And I also set `cert.pem` for cert in my client's configuration file.
![image](https://user-images.githubusercontent.com/14164381/38183329-3b24c200-3672-11e8-882b-50a5756d7768.png)

I don't know if I choose a wrong certificate, and when I choose `fullchain.pem`, these error infos disappeared again.

**Comment by GreaterFire** [comment]
What is your `ssl.cert` in the client config?

**Comment by CURAS** [comment]
My client's config
![image](https://user-images.githubusercontent.com/14164381/38381533-a32ce444-3939-11e8-991b-7559d7ab8918.png)

My client's folder
![image](https://user-images.githubusercontent.com/14164381/38381265-db6c5a3e-3938-11e8-9b95-db26f6a4c37b.png)

My server's config
![image](https://user-images.githubusercontent.com/14164381/38381595-d8a58b76-3939-11e8-88e9-1c77d93f55d3.png)

**Comment by GreaterFire** [comment]
There are multiple reports of this issue. I will look into it and reply shortly. Thank you for your patience.

**Comment by GreaterFire** [comment]
After careful investigation, I found that you cannot use `fullchain.pem` to verify the remote certificate -- only a CA certificate can do the verifying work. That's why a self-signed certificate can verify itself: it is its own CA. So I recommend you to use CA certificate, like the one I provided (`examples/ca_certs.pem-example`), which is a CA list extracted from Mozilla Firefox. Or if you are using Let's Encrypt, you can use [DST Root CA X3](https://www.identrust.com/certificates/trustid/root-download-x3.html).

**Comment by CURAS** [comment]
I have tried both the certificates you provided, but I'm sorry to said the problem still exists.
By the way, it works well in my browser.
![image](https://user-images.githubusercontent.com/14164381/38405502-cca642a2-39a2-11e8-8c42-58448393c2fb.png)

**Comment by GreaterFire** [comment]
BTW, under Windows, replace all the `\` in the path with `/`. It must work.

**Comment by GreaterFire** [comment]
@CURAS This issue is finally resolved. In v1.2.0, you'll be able to verify using the original certificate.
