### ISSUE TITLE
Release 1.14.1 cannot run in alpine:latest (e7d92cdc71fe) in Docker

### ISSUE THREAD

**Issue by davidshen84** [trojan-gfw/trojan#293]
When I try to run `trojan` in alpine, I got `not found` error. I even followed **https://hub.docker.com/r/trojangfw/trojan/dockerfile** and added the dependencies, but I still got the same error.

However, if I build my docker image from `ubuntu`, `trojan` runs successfully and can be connected.

I guess the `not found` error does not mean that the shell cannot find `trojan`, but something that `trojan` depends on. But because **alpine** is so limited, it doesn't give much information for troubleshooting.

**Comment by davidshen84** [comment]
```Dockerfile
FROM alpine:latest
LABEL alpine=latest
LABEL trojan=v1.14.1

RUN apk add --no-cache \
	libstdc++ \
        boost-system \
        boost-program_options \
        mariadb-connector-c
WORKDIR /var/trojan
RUN wget https://github.com/trojan-gfw/trojan/releases/download/v1.14.1/trojan-1.14.1-linux-amd64.tar.xz
RUN tar -xvf trojan-1.14.1-linux-amd64.tar.xz --strip-components=1
COPY config.json /var/trojan/config.json

EXPOSE 1080
#ENTRYPOINT ["./trojan"]
ENTRYPOINT ["/bin/sh"]
```

**Comment by mritd** [comment]
To be clear, alpine uses musl c instead of glibc.
So you need to compile trojan from source.
But why not use the official Dockerfile?

**Comment by davidshen84** [comment]
I see. Thx.
