### ISSUE TITLE
[Feature Request]请教下为什么我编译出来的1.几兆。在别的机器上运行报缺boost.so 文件

### ISSUE THREAD

**Issue by lins** [trojan-gfw/trojan#295]
请教下为什么我编译出来的1.几兆。官方下载的4点几兆。我编译的在别的机器上运行报缺boost.so 文件。是我编译的姿势不对么？ 本地编译了本地linux 可以执行，放到别的机器上跑不了

**Comment by wongsyrone** [comment]
Learn more about compilation

**Comment by lins** [comment]
请教如何静态编译，set (OPENSSL_USE_STATIC_LIBS TRUE)  编译后报错 
/usr/bin/ld: /usr/local/lib/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
请教下，谢谢
