### ISSUE TITLE
关于Vultr服务器的Trojan访问谷歌学术的问题

### ISSUE THREAD

**Issue by Alcatraz1337** [trojan-gfw/trojan#298]
你好，开发者：
我按照[教程](https://trojan-tutor.github.io/2019/04/10/p41.html)在Vultr服务器上搭建了Trojan。但是在Shadowsocks时期，谷歌学术就已经在禁止Vultr的一些服务器访问了。
我按照网上给的教程（多数都是解决SS怎么使用ipv6来访问的），修改了服务器上的hosts文件，加入了谷歌学术的ipv6地址。同时在vultr也给服务器添加了ipv6地址，在cloudflare也添加了新的这个ipv6地址，同时也修改了Trojan的config.json中的local_addr。但是最后在访问谷歌学术的时候，还是无法访问，显示已断开连接（ERR_CONNECTION_CLOSED）。
希望开发者们能够指出我操作中出现的错误！万分感谢！

Dear Developers,
I have followed the [Tutorial](https://trojan-tutor.github.io/2019/04/10/p41.html) and have deployed a Trojan based on a Vultr server. And Google Scholar has been banning Vultr's IPs since long a go.
I have also follow some tutorials (mainly how to fix the problem while using shadowsocks), edited the hosts file in the server, also assigned an IPv6 address to the Vultr server and add the new address to Cloudflare. And also edit the trojan's config.json file. But it won't work fine. The browser shows "ERR_CONNECTION_CLOSED"
Hope you can help me out!
Appreciated!

**Comment by justchenhao** [comment]
Have the issue been solved?

**Comment by Alcatraz1337** [comment]
> Have the issue been solved?

Nope, it has been _closed_

**Comment by GreaterFire** [comment]
@Alcatraz1337 Please read CONTRIBUTING.md.

**Comment by Alcatraz1337** [comment]
> @Alcatraz1337 Please read CONTRIBUTING.md.

Thanks for your reply! I’ll check it out later. Appreciate it!

**Comment by GreaterFire** [comment]
Please do it **now**. [CONTRIBUTING.md](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md)
