### ISSUE TITLE
提供的docker镜像启动失败

### ISSUE THREAD

**Issue by RonsonNamek** [trojan-gfw/trojan#299]
https://registry.hub.docker.com/r/trojangfw/trojan
这里提供的镜像平台与标签不符。我的NAS是x86_64平台，无法运行此镜像。希望大佬能提供x86_64平台的trojan

**Comment by GreaterFire** [comment]
What the fuck is the difference between amd64 and x86_64?

**Comment by Chigusa0w0** [comment]
@RonsonNamek amd64 is an alias of x86-64

**Comment by RonsonNamek** [comment]
好吧，抱歉我不知道这两者的区别，但我的docker镜像确实无法运行，错误提示：
standard_init_linux.go:222: exec user process caused "exec format error"

**Comment by GreaterFire** [comment]
If you want to get help, please provide **all** the information you possibly can.

**Comment by RonsonNamek** [comment]
我使用的是群晖NAS，
DSM版本：DSM 6.2.2-24922 Update 4
uname -a 的结果：
Linux diskstation 4.4.59+ #24922 SMP PREEMPT Mon Aug 19 12:13:37 CST 2019 x86_64 GNU/Linux synology_apollolake_918+
Docker 是套件中心里安装的
这是Docker启动时挂载的目录
![image](https://user-images.githubusercontent.com/5227189/76110293-4073c800-6019-11ea-8be5-fe9a370fd8db.png)
容器的环境变量：
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
![image](https://user-images.githubusercontent.com/5227189/76110533-a4968c00-6019-11ea-9d41-b7dac691b9ae.png)

**Comment by GreaterFire** [comment]
Did you map the config file to the trojan executable?
![](https://user-images.githubusercontent.com/5227189/76110293-4073c800-6019-11ea-8be5-fe9a370fd8db.png)

**Comment by RonsonNamek** [comment]
当没有挂载目录时，日志提示找不到 config.json，但是当我配置了挂载目录后，提示 exec format error
下面这个是log
![image](https://user-images.githubusercontent.com/5227189/76111160-bc224480-601a-11ea-85ec-2a7a8dd80398.png)

**Comment by GreaterFire** [comment]
It's not a bug of trojan or Dockerfile. Please fix your configuration yourself. [Source](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md)

**Comment by RonsonNamek** [comment]
![image](https://user-images.githubusercontent.com/5227189/76111226-df4cf400-601a-11ea-9350-c9e3d8b1fa9d.png)
这是 config.json 所在目录
