### ISSUE TITLE
[Feature Request] more user control function request

### ISSUE THREAD

**Issue by shuangzhijinghua** [trojan-gfw/trojan#300]
1.is possible to provide  WebAPI method instead of MySQL method to get user information? WebAPI method can be provide more access control / security on server side like a RADIUS server.
2.User censor ability. a funtion to cut off connection which defined RegEx. rule, such as block BT traffic. using IPTables to block access is not a good way in large traffic environment.

A question:
When user information has been change, the data which server has been loaded can be reload automatic ? such as a user change his password / or user state change to disabled.

**Comment by GreaterFire** [comment]
Read [this](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md) for guidelines of feature requests. Also, it's a duplicate feature request that we are not going to implement.
