### ISSUE TITLE
创建非root新用户是无法输入密码[BUG]

### ISSUE THREAD

**Issue by Daniel1929** [trojan-gfw/trojan#302]
**Trojan Version**
在xshell设置新的非root用户时，在设置密码时无法输入，请问大神是怎么回事？

root@zysj:~# sudo passwd trojanfreetg
New password:
BAD PASSWORD: it is too simplistic/systematic
New password:
BAD PASSWORD: it is WAY too short
New password:

**Comment by lilunxm12** [comment]
这跟trojan有关系???
第一条是说密码太简单,第二条说太短,就算不认识英语也可以查查字典不是?
盲猜是因为你不知道输密码的时候会不显示位数所以直接按了enter
都会github提issue了连这点不知道就有点奇怪了.....
多利用搜索引擎,不要浪费大火时间
