### ISSUE TITLE
`certificate verify failed` on MacOS client and `no shared cipher` on VPS

### ISSUE THREAD

**Issue by givingwu** [trojan-gfw/trojan#304]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
Server:
![image](https://user-images.githubusercontent.com/13431452/76156978-57abd600-613d-11ea-9ae6-5e70b10a6812.png)
OS version:
`CentOS Linux release 7.7.1908 (Core)`

Client(MacOS):
![image](https://user-images.githubusercontent.com/13431452/76156980-5e3a4d80-613d-11ea-8f3c-bc4b16dbb88a.png)

They look like nothing different, well.

**Describe the bug**
1. How to resolve `certificate verify failed` on MacOS client?
2. How to resolve `no shared cipher` on VPS?

Maybe they are the same question, i do not know , hum...

**To Reproduce**
1. I use [this shell script](https://github.com/atrandys/trojan/blob/master/trojan_centos7.sh) to install and initialize Trojan on VPS.
2. I use [this way](https://github.com/trojan-gfw/trojan/wiki/Binary-&-Package-Distributions#macos) to install Trojan on Client.
3. and i configured the **SwitchyOmega** as following screenshot:
![image](https://user-images.githubusercontent.com/13431452/76157036-72327f00-613e-11ea-91cb-2b2a62162d23.png)
Server:
![image](https://user-images.githubusercontent.com/13431452/76157059-e2d99b80-613e-11ea-8a27-eb82b8ff2f91.png)

Client:
![image](https://user-images.githubusercontent.com/13431452/76157052-b887de00-613e-11ea-8351-aed99aa0afee.png)

**Expected behavior**
It could works on macOS.

**Environment**
Server:
![image](https://user-images.githubusercontent.com/13431452/76157102-68f5e200-613f-11ea-9cee-44aced10c50f.png)

Client:
![image](https://user-images.githubusercontent.com/13431452/76157110-83c85680-613f-11ea-8bfc-719e3272d61f.png)

**Additional context**
1. I think this is not a bug, it looks like what i did wrong or the shell script did.
2. I tried to search the solutions but cannot found any related issue especially on macOS.

**Comment by lilunxm12** [comment]
Try comment out h2 on client configuration or add h2 to your server.

**Comment by givingwu** [comment]
> Try comment out h2 on client configuration or add h2 to your server.

I tried your solution, but it still cannot work.

**Comment by rampageX** [comment]
Same here.

I build arm64 trojan on my N1 box, no errors occurred throughout the process，but i can not connect the server with `certificate verify failed` error.

I think it will be the wrong openssl compile process but not sure what's wrong:

`openssl ciphers -s -v 'ECDHE:!COMPLEMENTOFDEFAULT'` i got tls1.3 ciphers.

`openssl s_client -connect server_domain:443` -- `Verify return code: 20 (unable to get local issuer certificate)` error

`openssl s_client -connect server_domain:443 -CAfile=/etc/ssl/certs/ca-certificates.crt` -- OK

and trojan:

> trojan -v
> Welcome to trojan 1.14.1
> Boost 1_67, OpenSSL 1.1.1d  10 Sep 2019
>  [Enabled] MySQL Support (10.1.44-MariaDB)
>  [Enabled] TCP_FASTOPEN Support
>  [Enabled] TCP_FASTOPEN_CONNECT Support
>  [Enabled] SSL KeyLog Support
>  [Enabled] NAT Support
>  [Enabled] TLS1.3 Ciphersuites Support
>  [Enabled] TCP Port Reuse Support
> OpenSSL Information
> 	Build Flags: compiler: gcc -fPIC -pthread -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DVPAES_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DNDEBUG

error:

> [ERROR] 192.168.2.1:51954 SSL handshake failed with server_ip:443: certificate verify failed

Change ` "verify": true,` to ` "verify": false,` in trojan.json can do the connect, but i dont think this is the right way.

Add: `"cert": "/etc/ssl/certs/ca-certificates.crt",` to trojan.json also work, but why Release version no need do this?

**Comment by givingwu** [comment]
@rampageX  I tried your solution too, but nothing happened, it still cannot works. I think may the problem is  script. it use [acme.sh](https://github.com/atrandys/trojan/blob/master/trojan_centos7.sh#L71) to generates SSH .cem & .key, but they do not work as well...

**Comment by rampageX** [comment]
@vuchan In client config, `"cert"` is not your server domain `fullchain.cer`, it must be system ca-certificates, in macOS may `/usr/local/etc/openssl/cert.pem` or not, you can download with:
`curl https://curl.haxx.se/ca/cacert.pem` and use the `cacert.pem` point to you `"cert" =` in client config file.

**Comment by givingwu** [comment]
> @vuchan In client config, `"cert"` is not your server domain `fullchain.cer`, it must be system ca-certificates, in macOS may `/usr/local/etc/openssl/cert.pem` or not, you can download with:
> `curl https://curl.haxx.se/ca/cacert.pem` and use the `cacert.pem` point to you `"cert" =` in client config file.

Thanks very much, that's it. I have use 'cert' from the server domain `fullchain.cer`. i will try to fix that as your mentioned.
