### ISSUE TITLE
360病毒拦截

### ISSUE THREAD

**Issue by kongdd** [trojan-gfw/trojan#305]
windows客户端 version 1.41，360报trojan.exe是病毒：

木马名称：HEUR/QVM202.0.BE05.Malware.Gen
所在路径：trojan-cli\trojan\trojan.exe

md5sum ./trogan.exe
> 1723a4d90ac0399782927000aed685df  ./trojan.exe

**Comment by wangdongustc** [comment]
Maybe it's because of the name. This should not be a bug for this trojan project.
