### ISSUE TITLE
[BUG] Can not access trojan client port from other devices in local network

### ISSUE THREAD

**Issue by wangxing7714436** [trojan-gfw/trojan#307]
**Trojan Version**
1.14.1
**Describe the bug**
I open a server on a pc in my internal network and try to make this pc as a transparent proxy server. But the chrome on proxy pc can access trojan port, other devices in the internal network can not access the port while v2ray and other services on proxy pc works well and trojan itself works on proxy pc. I've check the firewall on proxy pc and make sure the port assgin to trojan service is in white list.

**To Reproduce**
tried relaunch with the same config many times.

**Expected behavior**
I dont know if this is a bug or program the is designed like this.

**Logs**
no log on screeen

**Environment**
win10 on proxy pc

**Additional context**
no

**Comment by GreaterFire** [comment]
Listen on `0.0.0.0`.
