### ISSUE TITLE
How do I stop trojan from auto-start?

### ISSUE THREAD

**Issue by buzzen** [trojan-gfw/trojan#308]
After some time of using trojan I don't want to use it anymore, how can I stop it from running? I can kill the process but everytime I start my computer it reappeared. I can't find trojan in startup applications, I can't find it in /etc/systemd/system. Where is it? Pls help.

**Comment by lilunxm12** [comment]
sudo systemctl disable trojan

**Comment by ConstasJ** [comment]
Ehh......I think you can use`sudo systemctl ststus trojan`to look up where is the service,and you can use the command`sudo systemctl disable trojan`to let it not auto-start.
If you just want to stop it,use`sudo systemctl stop trojan`
(if you use Ubuntu or Debian,this is the all.But if you use CentOS or other system,I can't help you.)
