### ISSUE TITLE
I am unable to download videos from YouTube with internet download manager

### ISSUE THREAD

**Issue by EA-DICE** [trojan-gfw/trojan#309]
A few days ago, i was using the trojan-Qt5(gui client)and i can change local server to type to https and http,so i can use internet download manager to download videos from youtube successfully.i close socks 5 cuz it seems that windows 10 doesn't support socks5 port,and i don't know if trojan client support http,https port.if it supports,how can i use it?

**Comment by EA-DICE** [comment]
![image](https://user-images.githubusercontent.com/42771283/76274866-c06d8c80-62bc-11ea-8242-f916f2a54443.png)
![image](https://user-images.githubusercontent.com/42771283/76274879-c6fc0400-62bc-11ea-8356-1f309bc198ee.png)

**Comment by ghost** [comment]
When using trojan cli client, just select "使用socks" and type socks5 server address and socks5 server port. (Do not select 使用HTTP代理 or 使用HTTPS代理).

**Comment by EA-DICE** [comment]
嗯谢谢

**Comment by EA-DICE** [comment]
正在测试

**Comment by EA-DICE** [comment]
socks5服务器地址指的是127.0.0.1？

**Comment by ghost** [comment]
yes

**Comment by EA-DICE** [comment]
端口是1080对吧

**Comment by ghost** [comment]
yes. By default it's 127.0.0.1 1080

**Comment by EA-DICE** [comment]
it doesn't work
![image](https://user-images.githubusercontent.com/42771283/76276741-a8e4d280-62c1-11ea-8aac-537dade9a66c.png)
![image](https://user-images.githubusercontent.com/42771283/76276761-b306d100-62c1-11ea-81b6-2749f35d4a50.png)

**Comment by ghost** [comment]
try select ``Proxy DNS``

**Comment by EA-DICE** [comment]
your solution is useful,now everything is ok!thank you so much

**Comment by ghost** [comment]
You're welcome.
