### ISSUE TITLE
[Feature Request] How to limit 1 point login?

### ISSUE THREAD

**Issue by daidaiworm** [trojan-gfw/trojan#310]
[Feature Request] How to limit 1 point login?

Tried both json and mysql mode, it seems that there is no limitation for multi point login.
If people share same trojan login info, all the devices can login in.

Is there any method to set such a regulation or limitation?

If it can set a num inside mysql, it'll be perfect.

Again. Great work for Coding such a necessary application!

**Comment by GreaterFire** [comment]
Sorry, we did not have plan for this feature.

**Comment by x0r2d2** [comment]
@GreaterFire
Hello. Any chance that "device limit" feature will be implemented in near future?
Thanks.

**Comment by GreaterFire** [comment]
@hybtoy No.
