### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by yuantongziran** [trojan-gfw/trojan#314]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
No.

**Is this problem relevant to what trojan should care about?**
Yes.

**Describe the solution you'd like**
I'm using windows client. I'd like to run it as a background task. Can you make another .exe file which has some additional code to make it running as a background task. 

**Describe alternatives you've considered**
A GUI is also acceptable : )

**Comment by Chigusa0w0** [comment]
See #91
