### ISSUE TITLE
开发者你好，win10 X86好像使用不了，请问我应该下哪个版本，小白一枚，勿怪

### ISSUE THREAD

**Issue by future54** [trojan-gfw/trojan#316]
如题，请帮忙解答，谢谢！

**Comment by future54** [comment]
vcX86已经安装了，但trojan应用程式打不开，不能运行！

**Comment by GreaterFire** [comment]
We do not provide binaries for 32-bit systems anymore. Please upgrade your system.

**Comment by future54** [comment]
好吧！

**Comment by redstoneleo** [comment]
用32位电脑的用户也不少，希望考虑考虑出一个32位的，谢谢！

**Comment by Chigusa0w0** [comment]
@redstoneleo No. No more than 1% of all PC users using x86. Upgrade your hardware.
