### ISSUE TITLE
[BUG]cpu突然占用过高

### ISSUE THREAD

**Issue by huntcraft** [trojan-gfw/trojan#318]
**Trojan Version**
1.14.1

**Describe the bug**
运行一段时间后，Trojan 使用 CPU会到100%，内存占用也一直在升高。
每次要远程上去重启 Trojan 才能使用，过几小时时间，又会占用到100%的CPU。

安装过程：

1. 按照 trojan-panel 的wiki 里的，先安装了 Nginx 和证书
2. 用 trojan-quickstart 安装 
3. 加上bbr

没有安装任何其他软件。
下面两张截图

![服务器上的信息](https://user-images.githubusercontent.com/1448359/76680402-26db0d80-6623-11ea-813e-16dd3cccd959.png)

![VPS的面板](https://user-images.githubusercontent.com/1448359/76680420-3eb29180-6623-11ea-92d2-91dd2fef48bd.png)

面板的CPU两个峰值，是在重启 Trojan 后降下来的。

**Comment by GreaterFire** [comment]
Can you provide some log at that time?

**Comment by huntcraft** [comment]
当时看了日志，大部分 [Error] 的内容是 handshake timeout， 7200s 左右。
但当时也不知道怎么导出日志，所以没有保存。
我去重装系统，再试一次。

**Comment by ghost** [comment]
@huntcraft 
```
	cat > '/etc/sysctl.d/99-sysctl.conf' << EOF
#net.ipv4.ip_forward = 1
#net.ipv4.conf.all.forwarding = 1
#net.ipv4.conf.default.forwarding = 1
################################
#net.ipv6.conf.all.forwarding = 1
#net.ipv6.conf.default.forwarding = 1
#net.ipv6.conf.lo.forwarding = 1
################################
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
################################
net.ipv6.conf.all.accept_ra = 2
net.ipv6.conf.default.accept_ra = 2
################################
net.core.netdev_max_backlog = 100000
net.core.netdev_budget = 50000
net.core.netdev_budget_usecs = 5000
#fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.rmem_default = 65536
net.core.wmem_default = 65536
net.core.somaxconn = 4096
################################
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.tcp_rfc1337 = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_tw_buckets = 2000000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
net.ipv4.tcp_mtu_probing = 0
##############################
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_max_syn_backlog = 30000
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_ecn = 1
net.ipv4.tcp_frto = 0
##############################
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
vm.swappiness = 5
net.ipv4.ip_unprivileged_port_start = 0
EOF
```
sysctl --system

please try this

**Comment by malikshi** [comment]
you can nginx sni/pre-ssl for minimizing CPU usage but ram usage would be high. I tested it with these details,
trojan latest build, 1.15.1
Specs VPS

- 4core
- openvz6 with ubuntu 16 64bit,
- ram 1GB with 512MB swap
- multiple instances,

![Screenshot_848](https://user-images.githubusercontent.com/9080737/77576653-1fabdd80-6f08-11ea-9195-ce8573c18ca8.jpg)

**Comment by tomac4t** [comment]
I don't see these parameter tuning can help this problem, and DON'T ENABLE TCP FAST OPEN, because it has a unique traffic fingerprint. @johnrosen1

**Comment by ghost** [comment]
@tomac4t well it does help because these parameter help shorten the wait time of tcp handshake timeout which is useful for migariting ddos attacks.

**Comment by GreaterFire** [comment]
I'd rather think it's a bug than a system parameter problem. Setting IP parameters won't help.

**Comment by GreaterFire** [comment]
@huntcraft Typically this kind of resource exhaustion happens because something is causing a loop, such as accessing itself over and over again. Check for your configurations to see if they contain such a loop.

**Comment by huntcraft** [comment]
@GreaterFire 
1，关于 loop。是否存在 loop 我都不知道怎么查，对这些不熟悉。
2，关于配置。在 trojan 安装好以后，只修改了 `config.json` 文件中的密码，以及域名证书的路径，共4行。

为了重现这种状况，前天在同一个服务器，重装 ubuntu 系统，用之前的步骤的安装 trojan。
但是到现在也没出现异常情况。
唯一的差异，之前安装的是 1.14.1，这次是 1.15.1。

可能，暂时无法重现了。
如果还出现这样的问题，我把 VPS 的 root 用户给你吧。:grin:

----
说下更多的背景。

在某供应商买了一个月的 VPS，开始是搭建v2ray，但经常断开连接。在使用了v2ray 几天后，决定尝试 trojan。在安装好 trojan 后的一周内，让朋友一起试用了，效果非常好。然后买同款 VPS 一年(有优惠)。

所以，当时是同时用着两个 trojan 的服务器。在第二个VPS用了大概10天左右，开始出现这个问题。
当时的疑惑：
1，为什么同款VPS，一个会出问题，一个不会。
2，为什么出问题的服务器，在前面大概10天都是正常的。

**Comment by GreaterFire** [comment]
Thanks for your reporting. Please reopen this issue when you encounter the said problem again!

**Comment by blackness3** [comment]
@huntcraft 
我在最近的使用过程中也出现了好几次这种情况，前几次以为是服务器的问题，因为当时服务器重启也不行，cpu还是占用100%，今天又出现这个情况，我通过ssh查询进程的时候发现trojan 占用CPU接近100%，我怀疑是trojan占用cpu导致我在服务商官网的控制面板上执行的重启命令未执行。我今天通过ssh重启了trojan服务就立马好了。不知道现在你的问题解决没有，我有个解决思路是写个脚本定时监控cpu，如果占用过高就执行trojan重启命令。不知道可行么，我先试试

**Comment by wenwuwu** [comment]
我用 google compute engine 也是cpu 100% 占用。
<img width="1156" alt="屏幕快照 2020-05-14 下午3 48 25" src="https://user-images.githubusercontent.com/15991545/81907469-678edd00-95fa-11ea-914d-3ff5a0776d1d.png">

**Comment by Nick-lizheng** [comment]
我用vlutr也是100%,OS版本是Debian 8, version是1.15.1

**Comment by jackiehejian** [comment]
Centos 7, 出现同样的问题，重装了两次系统，基本都是使用了两三天之后cpu占用率基本到100%，不知如何解决。
Centos7,  I have met the same issue. After reinstalling twice,  the usage of CPU was nearly 100% within  2-3 days. Don't know how to fix this problem.

**Comment by EastPearlStar2019** [comment]
still as it is , using 1.16.0.

**Comment by ansiz** [comment]
CentOS下也有类似问题，目前靠定时重启

**Comment by eroica-zhao** [comment]
在gcp上尝试了各种系统，debian 10，ubuntu18，centos7/8。。。都有这个cpu占用高，导致服务器停止响应的问题。
一直不敢用，等待版本更新等一年了，没看到更新。
眼巴巴等debian升级到11再试试看。。。

**Comment by imliuruiqi** [comment]
@GreaterFire 
sry for the spam. It seems that more users are encountering this issue recently, maybe we should reopen it.

**Comment by eroica-zhao** [comment]
在debian 11上验证，1.16版依然存在这个问题。
后来尝试降级到1.15.1，运行几天下来很稳定，是否能请作者排查1.15.1到1.16之间的改动？
期待后续更新并能解决该问题。

**Comment by ljcljc** [comment]
yes. I have the same issue again.
