### ISSUE TITLE
fatal: use_certificate_chain_file: no start line

### ISSUE THREAD

**Issue by iamindian** [trojan-gfw/trojan#32]
the above error always popups after starting projan server.  anyone can help?

**Comment by iamindian** [comment]
i seems that it is the certificate file issue.

**Comment by GreaterFire** [comment]
Did you solve the problem?

**Comment by iamindian** [comment]
yes, I solved the problem. i solved it by using the certification issued by CA. The certification request not issued by CA can not be used. Thx anyway!

**Comment by jessenhello** [comment]
> yes, I solved the problem. i solved it by using the certification issued by CA. The certification request not issued by CA can not be used. Thx anyway!

how to get the certification issued by CA ?
