### ISSUE TITLE
Nat 模式总是会出现不能翻墙成功的情况

### ISSUE THREAD

**Issue by sonofsky2010** [trojan-gfw/trojan#320]
我在路由器上使用了nat模式，iptables已经配好。但是经常会出现突然间某台设备不能上google和YouTube了。别的机器确可以正常连接。使用client模式的时候，没有出现过这个问题。有时候还会出现能上YouTube，但是不能google的情况。

**Comment by rampageX** [comment]
NAT 模式需要本地处理好 DNS 污染。
