### ISSUE TITLE
[BUG]在一个很特定的情况下，服务器Trojan会出问题

### ISSUE THREAD

**Issue by spark135246** [trojan-gfw/trojan#321]
* ### 重现条件
  * Vutlr服务器，日本机房（其他机房没试过）
  * 手机端使用igniter，（那个版本都一样）
  * 手机端安卓开启Bypass China
  * 手机端安卓使用Edge访问Google

上面的测试条件全部满足才会产生

* ### 我自己的测试
  * 没有问题
    * 搬瓦工服务器无论如何都不会产生问题
    * Vultr服务器，客户端取消使用Bypass China，一直使用不产生问题
    * Vultr服务器，客户端使用Bypass China的情况下，不使用Edge没有问题
    * Vultr服务器，客户端使用Bypass China的情况下，使用Edge但是不访问Google,访问youtube之类的没有问题
    * Vultr服务器，电脑端访问google不会产生问题，用了这段时间一直没有问题
    * Vultr服务器，ipad使用shadowrocket，用了这段时间一直没有问题
  * 有问题
    * Debian10、9或者centos7都一样，满足上面的重现条件就会出问题
    * 使用使用BBr、BBR2、BBR Plus、不使用加速，满足重现条件就会有问题

* ### 崩溃现象
  * 直接访问伪装网站的端口是能够正常显示的
  * 服务端443直接访问不会返回伪装网站，同时提示超时Timeout
  * 443端口一直超时，此时已经无法再使用Trojan代理，但是服务器使用`systemctl status trojan`命令服务端Trojan依旧运行
  * Vultr服务端崩溃后，安卓igniter改用搬瓦工服务器的Trojan，依旧能够使用

我不知道这是服务器还是客户端的问题，总之就是这么一个神奇的情况。

**Comment by orangejoker765** [comment]
Trojan X 的自定义规则需要怎么输入呢

**Comment by spark135246** [comment]
> Trojan X的自定义规则需要怎么输入呢

Trojan X是什么？不明白您的意思

**Comment by orangejoker765** [comment]
是Mac上的一个客户端，支持Trojan协议

**Comment by spark135246** [comment]
> 是Mac上的一个客户端，支持Trojan协议

不好意思，Mac没用过不知道怎么使。

**Comment by heham** [comment]
同样在安卓端出现这个问题，昨天服务端115后有点变化，但是还是会出现。

**Comment by spark135246** [comment]
服务端trojan升级至1.15.1及以上，问题解决
