### ISSUE TITLE
[BUG][FATAL] fatal: config.json: cannot open file

### ISSUE THREAD

**Issue by wenkeming** [trojan-gfw/trojan#322]
**Trojan Version**
1.14.1

**Describe the bug**
[FATAL] fatal: config.json: cannot open file

**To Reproduce**
open trojan with terminal then get the error blow:
`[FATAL] fatal: config.json: cannot open file`
there is a config.json in the same folder.

**Environment**
MacOS

**Comment by YowFung** [comment]
I get the same issue when I run trojan on docker
