### ISSUE TITLE
[Question] Does Trojan tranfer udp packet in plain text?

### ISSUE THREAD

**Issue by p4gefau1t** [trojan-gfw/trojan#324]
I read over the source. But I found that Trojan client just simply send the UDP packet to the remote server without any encryption, instead of using the TLS tunnel. 

我阅读了源码之后，发现似乎trojan客户端的UDP流量在没有加密的情况下发送到了服务器上，并没有使用tls隧道

**Comment by GreaterFire** [comment]
@p4gefau1t It is encrypted, within the TLS tunnel.
