### ISSUE TITLE
[Feature Request]Can it support reverse proxy by other server

### ISSUE THREAD

**Issue by xiaoshao9704** [trojan-gfw/trojan#326]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
I try to reverse proxy trojan server but it return 400

**Is this problem relevant to what trojan should care about?**
I think if trojan support reverse proxy will reduce loss

**Describe the solution you'd like**
I think if trojan support reverse proxy will reduce loss

**Describe alternatives you've considered**
I want get a useful nginx conf to reverse proxy trojan

**Comment by Chigusa0w0** [comment]
Trojan protocol, [by design](https://trojan-gfw.github.io/trojan/protocol), do NOT support reverse proxy by HTTP server.
You may want to use NGINX `upstream` with `ngx_stream_ssl_preread_module` to achieve your purpose.
