### ISSUE TITLE
How to check the version of trojan?

### ISSUE THREAD

**Issue by scu-ljy** [trojan-gfw/trojan#330]
Can you tell me how to check the version of trojan?

**Comment by ghost** [comment]
``./trojan --version``
Output:
```
Welcome to trojan 1.14.1
Boost 1_72, OpenSSL 1.1.1d  10 Sep 2019
[Disabled] MySQL Support
 [Enabled] TCP_FASTOPEN Support
[Disabled] TCP_FASTOPEN_CONNECT Support
 [Enabled] SSL KeyLog Support
[Disabled] NAT Support
 [Enabled] TLS1.3 Ciphersuites Support
[Disabled] TCP Port Reuse Support
OpenSSL Information
	Build Flags: compiler: clang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG
```

**Comment by scu-ljy** [comment]
> `./trojan --version`
> Output:
> 
> ```
> Welcome to trojan 1.14.1
> Boost 1_72, OpenSSL 1.1.1d  10 Sep 2019
> [Disabled] MySQL Support
>  [Enabled] TCP_FASTOPEN Support
> [Disabled] TCP_FASTOPEN_CONNECT Support
>  [Enabled] SSL KeyLog Support
> [Disabled] NAT Support
>  [Enabled] TLS1.3 Ciphersuites Support
> [Disabled] TCP Port Reuse Support
> OpenSSL Information
> 	Build Flags: compiler: clang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG
> ```

Thank you!
