### ISSUE TITLE
想知道在ubuntu下，能否启用全局代理，如何设置？

### ISSUE THREAD

**Issue by 469312306** [trojan-gfw/trojan#331]
配合chrome的switchyomega插件，使得在chrome浏览器中可以使用。现在，我想要ubuntu系统全局都使用trojan进行代理，像bash、git、wget等通通都走trojan代理。我搜索了google，没能解决我的问题。我想问：1.ubuntu系统本身是否支持？要如何设置？2.如果系统本身不支持，有哪些其他插件可以帮助完成这一功能？谢谢。

**Comment by AmberisMyShiba** [comment]
I recommend a very good tool for you: [ss-tproxy](https://github.com/zfl9/ss-tproxy). The author is @zfl9.I think this is the best global proxy tool I have used.

**Comment by RisingSunStudio** [comment]
既然可以出来溜达了，为什么自己不刷个路由，不就可以实现了
