### ISSUE TITLE
[FATAL] fatal: bind: Address already in use

### ISSUE THREAD

**Issue by zhengsr3** [trojan-gfw/trojan#332]
If I want to solve this, what should I do or what information should I provide

**Comment by defp** [comment]
绑定的地址已经被占用了

**Comment by zhengsr3** [comment]
那应该如何操作才能重新使用trojan呢？

**Comment by lidashuang** [comment]
不想帮你，你提供的信息太少

**Comment by zhengsr3** [comment]
十分抱歉，由于我不够专业，我不大确定应该提供什么样的信息，可以跟我说一下我需要提供什么信息么，谢谢！！！！

**Comment by defp** [comment]
比如用的啥操作系统

不行重启试试

**Comment by zhengsr3** [comment]
谢谢指导！但是电脑重启过了没用，电脑操作系统mac os10.12.6，服务器是搬瓦工上的，Debian 10 x86_64！，谢谢！！

**Comment by ghost** [comment]
所以你这个问题是在客户端还是服务端

发自我的iPhone

**Comment by zhengsr3** [comment]
客户端上的，我在mac上运行start.command，结果如截图显示
<img width="598" alt="屏幕截图 2020-03-17 11 55 09" src="https://user-images.githubusercontent.com/43190502/76820764-04293e80-6847-11ea-8c06-3e1cbb99336d.png">

**Comment by ghost** [comment]
端口是多少，1080么？试试``lsof -i:1080``看看是什么在占用

**Comment by zhengsr3** [comment]
local port 是1080
<img width="612" alt="屏幕截图 2020-03-17 12 07 32" src="https://user-images.githubusercontent.com/43190502/76821076-e6100e00-6847-11ea-8d9e-3feba9565895.png">

**Comment by ghost** [comment]
换个local port或者``kill -9 483``杀掉v2ray

**Comment by zhengsr3** [comment]
！！！成功了，太感谢了！！

**Comment by ghost** [comment]
没事

**Comment by loveklmn** [comment]
Please remove the `bug` label and close this question.
