### ISSUE TITLE
Can't configure trojan as the system proxy in Ubuntu | 无法设为系统代理

### ISSUE THREAD

**Issue by xf05888** [trojan-gfw/trojan#333]
I configure a trojan server and a client on Ubuntu 19.10.

The Firefox can use this socks proxy normally, but I can't set trojan as the system proxy,
I tried both **Automatic Mode and Manual Mode**, but still can't ping Google successfully.

P.S. At first the automatic mode can be used normally, but only for a few minutes.

**Comment by ghost** [comment]
export all_proxy=socks5://127.0.0.1:1080

**Comment by xf05888** [comment]
Still can't work:
```
PING www.google.com(tsa03s01-in-x04.1e100.net (2404:6800:4008:802::2004)) 56 data bytes
^C
--- www.google.com ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7159ms

```

**Comment by ghost** [comment]
if you want to ping google successfully, you should use ``tun2socks`` or proxifier

**Comment by ghost** [comment]
@xf05888 curl https://www.google.com
