### ISSUE TITLE
[BUG] URL scheme 建议

### ISSUE THREAD

**Issue by Scyllaly** [trojan-gfw/trojan#334]
翻了 trojan-url 项目才找到 了 URL Scheme，发现并不支持备注功能，可否 改进URL-SCHME

现有的为：`trojan://password@remote_host:remote_port`

建议：可否改进并标准化为： `trojan://password@remote_host:remote_port#base64(remarks)` 
主要目的是为了增加一个节点备注功能

**Comment by free798** [comment]
胖虎，怎么跑到trojan这里来了

**Comment by Scyllaly** [comment]
@free798 我在新面板里适配Trojan，结果发现Trojan 的 URL Scheme 做订阅比较麻烦，我发现没有办法做到用户识别，如果要做的话，只能把UUID 填入到 password 里，通过password 来 识别用户身份。观察到 shadowrocket 的 trojan url scheme 尾部是带有 #xxx 作为节点备注的。所以特地来请教一下作者，是否要有考虑要完善一下 trojan 的 url scheme...

**Comment by fefz** [comment]
fuck off

**Comment by ghost** [comment]
@ssrpanel if you want to improve the url , please do it yourself instead of ask others do it for you !

**Comment by dzxx36gyy** [comment]
I think need to consider use base64 for password to avoid "@" appear in password which cloud disturb the identify of the client.

**Comment by GreaterFire** [comment]
@dzxx36gyy @ is escaped

**Comment by GreaterFire** [comment]
@dzxx36gyy @ is escaped

**Comment by dzxx36gyy** [comment]
> @dzxx36gyy @ is escaped

Yes, i think this improve is needed.

**Comment by GreaterFire** [comment]
@dzxx36gyy No

**Comment by dzxx36gyy** [comment]
Okay...

**Comment by GreaterFire** [comment]
@dzxx36gyy https://github.com/trojan-gfw/trojan-url/blob/master/README.md

PLEASE. Read the whole spec again to see how illegal characters are handled.

**Comment by GreaterFire** [comment]
@ssrpanel Our URL scheme conforms to the definition of a URL: to and only to locate the resource. We'll not put any irrelevant information not used to locate a resource, such as an alias (or remark, as you suggested) of the server, in our URL scheme.

**Comment by dzxx36gyy** [comment]
Find trojan's solution of the illegal characters, my fault.
