### ISSUE TITLE
[Feature Request] 远程mysql用户校验速度优化

### ISSUE THREAD

**Issue by FenghenHome** [trojan-gfw/trojan#335]
大佬您好，当前单数据库多个节点部署，存在远程数据库校验问题，远程数据库校验是很耗时的，还请帮忙改进一下

**Comment by dzxx36gyy** [comment]
我自己加了个验证结果缓存，不过好像没啥太大差异…

**Comment by FenghenHome** [comment]
> 我自己加了个验证结果缓存，不过好像没啥太大差异…

可否给我试一下
