### ISSUE TITLE
关于哪个端口

### ISSUE THREAD

**Issue by wobud** [trojan-gfw/trojan#336]
我想请问一下大佬们，我用代理服务器访问目的网站，目的网站下发的流量是到代理服务器的哪个端口？

我看了一下forword文件，不是很懂。

之所以有这个疑问，是看了下面链接的文章，然后有了一个想法。如果是固定端口，我又用trojan代理服务器访问国内网站，墙检测入境请求的端口就能发现是代理访问了。

这是国内好事者申请的一个相关专利 https://patents.google.com/patent/CN108566380A/zh  《一种代理上网行为识别与检测方法》

**Comment by zerubeus** [comment]
Why are you writing in Chinese?
