### ISSUE TITLE
可以用其他语言实现一个trojan客户端吗？

### ISSUE THREAD

**Issue by boluoyu** [trojan-gfw/trojan#337]
我看到原版是用 C++ 语言实现的客户端，感觉在手机端不容易部署App ，是不是其他语言，如Java 和 Swift 解析 trojan 协议就可以实现一个客户端，最近我想自己用 Java 和 Swift 实现一下 trojan 协议，这样可以方便在安卓或 IOS 上装一个，不知道难不难实现？

**Comment by loveklmn** [comment]
`Shadowrocket` and `pharos` now support `trojan`.
