### ISSUE TITLE
[BUG]when installing trojan-panel

### ISSUE THREAD

**Issue by zhengsr3** [trojan-gfw/trojan#338]
I tried installing trojan-panel, but when I run the following code:
"
php artisan migrate
"
the following words come up:
"
 Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'trojan'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = trojan and table_name = migrations)

  at /var/www/trojan-panel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'trojan'@'localhost' (using password: NO)")
      /var/www/trojan-panel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=trojan", "trojan", "", [])
      /var/www/trojan-panel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  Please use the argument -v to see more details.
"
然后现在我登上我的域名时，显示500
我想知道如果我想解决这个，应该做什么／提供什么信息，谢谢！！！！！

**Comment by GreaterFire** [comment]
Trojan-Panel is a hobby project and will not be supported here.
