### ISSUE TITLE
[Feature Request]How can another cumputer use my trojan service in lan

### ISSUE THREAD

**Issue by Hokia** [trojan-gfw/trojan#339]
If my PC starts trojan service at 127.0.0.1:1080. My ip is 192.168.1.2 in lan. How can another PC connect by 192.168.1.2:1080.
Thanks.

**Comment by ghost** [comment]
"local_addr": "192.168.1.2",

**Comment by KevinZonda** [comment]
SOCKS5 proxy may work.

Computer A runs trojan on port P.

Computer B uses application connect the Computer A's SOCKS5 port. (like 192.168.1.103:1080)

**Comment by GreaterFire** [comment]
Have your client listen on 0.0.0.0.
