### ISSUE TITLE
[BUG] the same server not work in windows10, but work well in Linux and Android

### ISSUE THREAD

**Issue by kecaiwu** [trojan-gfw/trojan#340]
trojan 1.14.1

**Describe the bug**
The same server is work in Linux and Android, however, we use this server in win10, that does not work. I can not visit the google.com

[trojan.log](https://github.com/trojan-gfw/trojan/files/4348269/trojan.log)

**Environment**
Windows10

**Comment by GreaterFire** [comment]
Did you enter the incorrect password?
