### ISSUE TITLE
能否发布一个32位的版本？

### ISSUE THREAD

**Issue by Etisgod** [trojan-gfw/trojan#341]
你好，trojan在win7 32位上不能运行，能否发布一个32位版本，谢谢！

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/trojan/issues/316#issuecomment-599016371

**Comment by tiodot** [comment]
x86可以下载 [V2ray-with-trojan](https://yhvps.com/usr/uploads/app/v2rayN-win-with-trojan-v2.zip)
在华为的matebook e2019亲测可以
如果运行有问题，可能需要安装一下  [Visual C++ 2015 (x64、x86均安装)](https://www.microsoft.com/zh-CN/download/details.aspx?id=48145) 选择x86版本

来源： [微软windows电脑Trojan客户端使用教程](https://jc.go2world.icu/2019/09/29/windows_trojan/)
