### ISSUE TITLE
[BUG]ystemd: trojan.service: main process exited, code=killed, status=11/SEGV

### ISSUE THREAD

**Issue by xhrm** [trojan-gfw/trojan#342]
ystemd: trojan.service: main process exited, code=killed, status=11/SEGV

**Trojan Version**
1.14.1

**Logs**
Mar 19 16:01:20 [localhost] kernel: trojan[3813]: segfault at 0 ip 0000000000479d4f sp 00007fff2d5a0700 error 4 in trojan[400000+396000]
Mar 19 16:01:20 [localhost] systemd: trojan.service: main process exited, code=killed, status=11/SEGV
Mar 19 16:01:20 [localhost] trojan: Welcome to trojan 1.14.1
Mar 19 16:01:20 [localhost] trojan: [2020-03-19 16:01:20] [FATAL] fatal: config.json: cannot open file
Mar 19 16:01:20 [localhost] trojan: [2020-03-19 16:01:20] [FATAL] exiting. . .
Mar 19 16:01:20 [localhost] systemd: trojan.service: control process exited, code=exited status=1
Mar 19 16:01:20 [localhost] systemd: Unit trojan.service entered failed state.
Mar 19 16:01:20 [localhost] systemd: trojan.service failed.
Mar 19 16:20:28 [localhost] systemd: Created slice User Slice of root.
Mar 19 16:20:28 [localhost] systemd: Starting User Slice of root.
Mar 19 16:20:28 [localhost] systemd-logind: New session 104 of user root.
Mar 19 16:20:28 [localhost] systemd: Started Session 104 of user root.
Mar 19 16:20:28 [localhost] systemd: Starting Session 104 of user root.
Mar 19 16:20:29 [localhost] systemd: Started trojan.
Mar 19 16:20:29 [localhost] systemd: Starting trojan...
Mar 19 16:20:29 [localhost] trojan: Welcome to trojan 1.14.1
Mar 19 16:20:29 [localhost] trojan: [2020-03-19 16:20:29] [WARN] trojan service (server) started at 0.0.0.0:443

**Comment by rampageX** [comment]
fatal: **config.json: cannot open file**

**Comment by xhrm** [comment]
Return to normal after command execution

Error is also reported every other time

systemctl restart trojan

**Comment by xuleoBJ** [comment]
cannot run win 10 fatal: bind: 以一种访问权限不允许的方式做了一个访问套接字的尝试

**Comment by KevinZonda** [comment]
Confirm that **config.json** can be open.

**Comment by xhrm** [comment]
> 确认**config.json**可以打开。

确认可以打开 config.json

**Comment by KevinZonda** [comment]
> 
> 
> > 确认**config.json**可以打开。
> 
> 确认可以打开 config.json

Can trojan run correctly by manually(without systemd)?

**Comment by GreaterFire** [comment]
Can you provide a coredump?

**Comment by GreaterFire** [comment]
Please reopen this issue when you have a coredump.
