### ISSUE TITLE
[Feature Request]How about a pre-proxy function

### ISSUE THREAD

**Issue by climboy1** [trojan-gfw/trojan#344]
If the server A runs trojan is unavailable for Netflix. It can jump to server B, which runs SSR with poor speed in Mainland but fast with server A .

**Comment by Chigusa0w0** [comment]
See #131

**Comment by EHfive** [comment]
> See #131

I request reopening this issue.

I think @climboy1 means put a proxy (like a socks5 server) to front of trojan (server type in this case), so we can use other proxying tools like [v2ray](https://github.com/v2ray/v2ray-core), [clash](https://github.com/Dreamacro/clash) to routing outgoing traffics.

Although we could achieve this by configuring iptables (v2ray transparent proxy, ...), `pre-proxy`(socks5 at ease) is much eaiser to setup and portable on cross-platform.
