### ISSUE TITLE
[BUG]fatal: bind: Address already in use.

### ISSUE THREAD

**Issue by gqyann** [trojan-gfw/trojan#345]
macos启动trojan显示：fatal: bind: Address already in use
杀掉那个程序后，1080端口还是会被这个程序重新占用，为什么？  那个程序是ss-local
<img width="715" alt="截屏2020-03-2016 38 32" src="https://user-images.githubusercontent.com/33282734/77147924-62655400-6ac9-11ea-87e4-740a4eabcdae.png">

**Comment by KevinZonda** [comment]
Are you running Shadowsocks too? ss-local is a process of Shadowsocks-Client.
BTW, why not run Trojan on another port, like 54372 and etc?

**Comment by gqyann** [comment]
So, should the port of the server be changed too? It would be too troublesome to re-install the server. I am worried that it will not work well the second time.



---Original---

**Comment by KevinZonda** [comment]
> So, should the port of the server be changed too? It would be too troublesome to re-install the server. I am worried that it will not work well the second time.

Just change trojan **client** config. 

1. Change the value whose key called **"local_port"** to another port. 
2. Restart trojan.
3. Set the System proxy.

**Comment by gqyann** [comment]
thank you very much.it's ok



---Original---
