### ISSUE TITLE
访问谷歌学术失败

### ISSUE THREAD

**Issue by ppw08** [trojan-gfw/trojan#346]
买的HK的vps搭梯子，访问谷歌学术时显示如下错误，请问有人知道怎么解决吗

403. That’s an error.

Your client does not have permission to get URL / from this server

**Comment by wangxiaodong1021** [comment]
遇到同样的问题

**Comment by KevinZonda** [comment]
I think the problem comes from Google's own anti-abuse policy.

In other words, this IP do some abusive access to Google Scholar. So Google Scholar blocked your IP.

**Comment by shengbinyu** [comment]
how to solve the problem?

**Comment by XOKP** [comment]
If Google find your IP abusive, you have to switch to another IP to try or change your host provider.

**Comment by shengbinyu** [comment]
Thank you; I have use ipv6 instead of ipv4 to visit google Scholar by change hosts file, and success.


Sent from Mail Master


在2020年03月22日 16:08，XOKP<notifications@github.com> 写道：

If Google find your IP abusive, you have to switch to another IP to try or change your host provider.

**Comment by justchenhao** [comment]
> Thank you; I have use ipv6 instead of ipv4 to visit google Scholar by change hosts file, and success. Sent from Mail Master 在2020年03月22日 16:08，XOKP<notifications@github.com> 写道： If Google find your IP abusive, you have to switch to another IP to try or change your host provider. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you! Would you like to provide the details to do that? Could I access google scholar via changing hosts file if my network does not support ipv6?

**Comment by huainanhaoyuelengqianshan** [comment]
> > Thank you; I have use ipv6 instead of ipv4 to visit google Scholar by change hosts file, and success. Sent from Mail Master 在2020年03月22日 16:08，XOKP[notifications@github.com](mailto:notifications@github.com) 写道： If Google find your IP abusive, you have to switch to another IP to try or change your host provider. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Thank you! Would you like to provide the details to do that? Could I access google scholar via changing hosts file if my network does not support ipv6?

no,you must have a ipv6 address.

**Comment by TangBoheng** [comment]
`Your client does not have permission to get URL / from this server. (Client IP address: 2001:19f0:6001:341b:5400:2ff:fee1`
already change ipv6 address, but still fall to access, any suggestion?Thanks

**Comment by TangBoheng** [comment]
> If Google find your IP abusive, you have to switch to another IP to try or change your host provider.

`Your client does not have permission to get URL / from this server. (Client IP address: 2001:19f0:6001:341b:5400:2ff:fee1`
already change ipv6 address, and change some ips ,but still fall to access. I have no idea whether vutur have been blocked entirly, any suggestion?Thanks
