### ISSUE TITLE
Trojan server doesn’t work behind https load balancing.

### ISSUE THREAD

**Issue by msdurex** [trojan-gfw/trojan#354]
Trojan server seems like doesn’t work behind Google Cloud’s https load balancing. 

Question: is this feature doesn’t support or I should change something in Trojan servers?

**Comment by GreaterFire** [comment]
@msdurex We do not support it.

**Comment by msdurex** [comment]
Bummer, some of Cloud Servers only support IPv6 over load balancer. Thanks for the reply anyway.
