### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RayLiu-1217** [trojan-gfw/trojan#355]
我在一台美国洛杉矶系统为Linux（centos7）的VPS上尝试搭建trojan，经历重重困难，终于搭建成功了，但问题来了，一切都能正常运行，时间也是同步的，seLinux以及防火墙也都关闭了，但是就是无法正常连接，无论是在电脑端使用，还是安卓端都无法正常使用，无法连接，ping正常，解析也正常，实在不知道为什么了。

**Comment by rampageX** [comment]
什么日志都没有你让人怎么回答你？
