### ISSUE TITLE
[BUG] Shell 环境下 Trojan 的版本信息无法传入变量

### ISSUE THREAD

**Issue by GEM7** [trojan-gfw/trojan#356]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.15.1

**Describe the bug**
Shell 环境下 Trojan 的版本信息无法传入变量。
键入`/usr/local/bin/trojan -v`可以正常显示版本信息，但利用管道送入变量后为空值。

**To Reproduce**
1. 进入shell 环境 (bash or zsh)
2. 输入 `VER="$(/usr/local/bin/trojan -v)"`
3. 查看变量, `echo $VER`
4. 出现错误 ，变量 VER 为空
5. 其他软件可顺利取出版本信息，如 gcc。

**Expected behavior**
VER 变量中储存有和直接输入`/usr/local/bin/trojan -v`所返回的相同的信息。

**Logs**
N/A

**Environment**
Debian 10

**Additional context**
N/A

**Comment by Chigusa0w0** [comment]
Trojan prefer to use `stderr` for log output. Which means you may need some redirections to capture the output into a variable.

**Comment by GreaterFire** [comment]
@GEM7 Try VER="$(trojan -v 2>&1)"

**Comment by GEM7** [comment]
> @GEM7 Try VER="$(trojan -v 2>&1)"

Thanks, that worked for me!
