### ISSUE TITLE
[Feature Request] How can I block the request URL from trojan without the firewall?

### ISSUE THREAD

**Issue by du5** [trojan-gfw/trojan#357]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

such as regular expression

```code
(.*\.\|\|)(dafahao\|minghui\|dongtaiwang\|epochtimes\|ntdtv\|falundafa\|wujieliulan)\.(org\|com\|net)
````

domain suffix

```
youtube.com
```

**Comment by GreaterFire** [comment]
@du5 We don't and will not support this feature.

**Comment by du5** [comment]
@GreaterFire  Can you tell me add where it's better? I try it do myself, Thanks.

**Comment by Chigusa0w0** [comment]
@du5 You may apply a filter before DNS resolve. As a reminder, you may need to blacklist related IP addresses of websites as well. https://github.com/trojan-gfw/trojan/blob/master/src/session/serversession.cpp#L186

**Comment by du5** [comment]
@LimiQS Thanks for you'er help!

**Comment by GreaterFire** [comment]
There is one more problem with this. If the site you are blocking is behind a CDN (such as Cloudflare), and the communication between your client and the CDN is encrypted (SNI as well) and the IP address is obtained via DoH (so you have no way of knowing which site the client is accessing, let alone the IP address is a CDN address), you're not going to be able to block traffic like this.

Such complication is one of the reasons we don't implement it.

**Comment by du5** [comment]
> There is one more problem with this. If the site you are blocking is behind a CDN (such as Cloudflare), and the communication between your client and the CDN is encrypted (SNI as well) and the IP address is obtained via DoH (so you have no way of knowing which site the client is accessing, let alone the IP address is a CDN address), you're not going to be able to block traffic like this.
> 
> Such complication is one of the reasons we don't implement it.

Because I provide a public agent, some politically sensitive web pages must be banned. Thank you for your answers.
