### ISSUE TITLE
[BUG]Ubuntu 16.04 在运行 ./trojan 后 可以ping通 google 但是浏览器打不开google

### ISSUE THREAD

**Issue by TDHworkspace** [trojan-gfw/trojan#358]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?

**Additional context**

**Comment by ghost** [comment]
@TDHworkspace Thanks for the report but without a stracktrace and steps to reproduce there is nothing we can do.
