### ISSUE TITLE
Support QSH (Quantum Safe) extension for TLS

### ISSUE THREAD

**Issue by testcaoy7** [trojan-gfw/trojan#36]
China is pursuing quantum supremacy and we should prepare for it.

IETF has an idea called Quantum-Safe Hybrid (QSH) Ciphersuite for TLS.
Here is the document:
[https://tools.ietf.org/html/draft-whyte-qsh-tls13-02](url) (For TLS 1.3)
[https://tools.ietf.org/html/draft-whyte-qsh-tls12-02](url) (For TLS 1.2)

WolfSSL library has implemented QSH ciphersuite.
[https://www.wolfssl.com/quantum-safe-wolfssl-2/](url)

**Comment by GreaterFire** [comment]
**No** cryptographic algorithm is implemented inside trojan. They are all provided by the OpenSSL library. When OpenSSL supports these new algorithms, trojan will automatically support them.

I'll keep track of the standards for these algorithms and the progress of OpenSSL's adoption.
