### ISSUE TITLE
Trojan 和 V2ray（ ws+tls+web ）是否存在共用 443 端口的可能性？

### ISSUE THREAD

**Issue by jmyz0455** [trojan-gfw/trojan#360]
受到这个 [提问](https://github.com/trojan-gfw/trojan/issues/67) 的启发，想尝试一下 Trojan 和 V2ray（ ws+tls+web ）共用 443 这个端口，这样防火墙只需对外开放 443 和 22 端口，其他一律拒绝。

根据我对链接里的理解，让 Trojan 开在 443 端口（对应配置 "local_addr": "0.0.0.0", "local_port": 443 ），然后把非 Trojan 协议的流量转发到 444 端口（对应配置 "remote_addr": "127.0.0.1", "remote_port": 444 ），然后让 nginx 监听这个 444 端口，大概配置是：

```
server {
    listen 444 ssl;
    server_name MyDomain.com;
    root /usr/www/html;
    access_log  /usr/log/access.log;
    ...
    location /websocket/
    {
        proxy_pass http://127.0.0.1:445;
        ...
    }
}
```

然后带 /websocket/ 路径的流量就会转发到 445 端口，其余的流量会直接访问 /data/www/html 里的网页文件。让 v2ray 开在 445 端口并配置相应的路径和 ws 协议，相当于 Trojan ➡️Nginx ➡️v2ray 这样（端口 443 → 444 → 445 ）。

我尝试过是不行的，Trojan 上网没问题，网页打不开（页面显示 400 Bad Request The plain HTTP request was sent to HTTPS port ） ，v2ray 无法连接（客户端日志多数报错：400 Bad Request > websocket: bad handshake），不过 /usr/log/access.log 会有大量 `"GET /websocket/ HTTP/1.1" 400 255 "-" "Go-http-client/1.1"` 的输出，v2ray 服务端日志没有动静，感觉 Trojan ➡️Nginx 转发的这一步是没问题的，问题在于 nginx 接收到流量之后出现了错误（Trojan 和 Nginx 我都是配置的同一个域名的 ssl 证书，不知道为什么页面说我是原始 http 请求）。

所以抛开我的配置是否有问题这点，纯理论上说 Trojan 和 V2ray（ws+tls+web） 是否存在共用 443 端口的可能性？如果可以，请问我的错误又出在哪里？

**Comment by Chigusa0w0** [comment]
https://github.com/trojan-gfw/trojan/issues/67#issuecomment-466006130 
> Which means you should read and write __*plain HTTP data*__ on port 555 in your case.

Here in your case it's port 444. Use `listen 444;` (no `ssl`, but you may add `http2`) instead.

**Comment by siwind** [comment]
> 受到这个 [提问](https://github.com/trojan-gfw/trojan/issues/67) 的启发，想尝试一下 Trojan 和 V2ray（ ws+tls+web ）共用 443 这个端口，这样防火墙只需对外开放 443 和 22 端口，其他一律拒绝。
> 
> 根据我对链接里的理解，让 Trojan 开在 443 端口（对应配置 "local_addr": "0.0.0.0", "local_port": 443 ），然后把非 Trojan 协议的流量转发到 444 端口（对应配置 "remote_addr": "127.0.0.1", "remote_port": 444 ），然后让 nginx 监听这个 444 端口，大概配置是：
> 
> ```
> server {
>     listen 444 ssl;
>     server_name MyDomain.com;
>     root /usr/www/html;
>     access_log  /usr/log/access.log;
>     ...
>     location /websocket/
>     {
>         proxy_pass http://127.0.0.1:445;
>         ...
>     }
> }
> ```
> 
> 然后带 /websocket/ 路径的流量就会转发到 445 端口，其余的流量会直接访问 /data/www/html 里的网页文件。让 v2ray 开在 445 端口并配置相应的路径和 ws 协议，相当于 Trojan ➡️Nginx ➡️v2ray 这样（端口 443 → 444 → 445 ）。
> 
> 我尝试过是不行的，Trojan 上网没问题，网页打不开（页面显示 400 Bad Request The plain HTTP request was sent to HTTPS port ） ，v2ray 无法连接（客户端日志多数报错：400 Bad Request > websocket: bad handshake），不过 /usr/log/access.log 会有大量 `"GET /websocket/ HTTP/1.1" 400 255 "-" "Go-http-client/1.1"` 的输出，v2ray 服务端日志没有动静，感觉 Trojan ➡️Nginx 转发的这一步是没问题的，问题在于 nginx 接收到流量之后出现了错误（Trojan 和 Nginx 我都是配置的同一个域名的 ssl 证书，不知道为什么页面说我是原始 http 请求）。
> 
> 所以抛开我的配置是否有问题这点，纯理论上说 Trojan 和 V2ray（ws+tls+web） 是否存在共用 443 端口的可能性？如果可以，请问我的错误又出在哪里？


###  你对trojan和v2ray工作模式的理解有误
对于v2ray(假设运行于10000端口)而言，不需要开放防火墙端口，流量示例：
```
http request  --> nginx(0.0.0.0:80) --> nginx(0.0.0.0:443) --> web-pages | v2ray(127.0.0.1:10000)-fq
https request --> nginx(0.0.0.0:443) -->web-pages | v2ray(127.0.0.1:10000)-fq
```
对于trojan, 典型流量过程如下：
```
http request  --> nginx(0.0.0.0:80) --> trojan(0.0.0.0:443) -->serve fq | return-to-nginx(127.0.0.1:80)
https request -->trojan(0.0.0.0:443) -->serve fq | return-to-nginx(127.0.0.1:80)
```
所以不可能（端口冲突）也没必要公用端口。

#### 所以只需要开放(80) 443端口即可

**Comment by Chigusa0w0** [comment]
> 所以不可能（端口冲突）

It is possible to serve Trojan and Vmess+WS on the same port (Raw TLS v. WebSocket) without port conflict as long as make Trojan handle TLS termination and chain Nginx & V2Ray behind, though not recommended.

Their problem is that they want to terminate TLS twice (Trojan & Nginx), but there is only one layer of TLS which is already terminated in Trojan.

**Comment by siwind** [comment]
I misunderstood the problem.  The question is , whether there is only port(443) open that can serve both HTTP/trojan/v2ray services together.

**Comment by jmyz0455** [comment]
本人英语和编程都不太好，根据 [LimiQs](https://github.com/trojan-gfw/trojan/issues/360#issuecomment-605383053) 的回答，我讲讲我的愚见 @siwind 

先抛开 80 端口，我们只讨论 443 端口。继续用我的 Trojan ➡️Nginx ➡️v2ray 假设（端口 443 → 444 → 445 ），首先三个软件在占用的端口上不冲突，然后把这三个端口套用到你的示例，将会是这样的：
```
https request --> trojan(0.0.0.0:443)
--> serve fq | return-to-nginx(127.0.0.1:444) 
--> serve web | path-proxy_pass-v2ray(127.0.0.1:445)
```
不过我没有继续尝试下去，因为 LimiQs 说 Trojan 配置 remote_port 转发出来的流量不能用 ssl 了，只能用 http2 ，我在了解到没有 tls 的 http2 会使用一种称为 h2c 的明文进行通讯，这意味着加密功能有所损失，所以放弃了这种想法。

**Comment by Chigusa0w0** [comment]
> 这意味着加密功能有所损失

Nope, your outbound communication is still under the protection of TLS. Please be aware that Trojan will re-encrypt your information before they return to your client. You will not lose confidentiality.

**Comment by jmyz0455** [comment]
> Nope, your outbound communication is still under the protection of TLS. Please be aware that Trojan will re-encrypt your information before they return to your client. You will not lose confidentiality.

Understood, thank you for your answer.

**Comment by siwind** [comment]
> 本人英语和编程都不太好，根据 [LimiQs](https://github.com/trojan-gfw/trojan/issues/360#issuecomment-605383053) 的回答，我讲讲我的愚见 @siwind
> 
> 先抛开 80 端口，我们只讨论 443 端口。继续用我的 Trojan ➡️Nginx ➡️v2ray 假设（端口 443 → 444 → 445 ），首先三个软件在占用的端口上不冲突，然后把这三个端口套用到你的示例，将会是这样的：
> 
> ```
> https request --> trojan(0.0.0.0:443)
> --> serve fq | return-to-nginx(127.0.0.1:444) 
> --> serve web | path-proxy_pass-v2ray(127.0.0.1:445)
> ```
> 
> 不过我没有继续尝试下去，因为 LimiQs 说 Trojan 配置 remote_port 转发出来的流量不能用 ssl 了，只能用 http2 ，我在了解到没有 tls 的 http2 会使用一种称为 h2c 的明文进行通讯，这意味着加密功能有所损失，所以放弃了这种想法。

在trojan这个地方， 同时对收到的报文进行解密和返回给客户的报文进行加密, 如果不是trojan的流量，trojan作为客户端代理，和nginx之间通信从效率上考虑只能采用http/http2, 而不是https(涉及握手，秘钥交换等过程并且nginx开启额外的https服务端口)，这样的话，后续nginx转给v2ray的报文就可能不符合v2ray预期的报文(nginx-http --> v2ray, 不对了)。

另外即使能实现，但是trojan和v2ray在同样的端口实现同样的功能，好像是没有必要的。如果443不能用， 那么trojan和v2ray同样歇菜。 整个连接的特征已经由TLS保证了，所以同时在一个端口服务trojan/v2ray好像也是多余的~

**Comment by jmyz0455** [comment]
> 在trojan这个地方， 同时对收到的报文进行解密和返回给客户的报文进行加密, 如果不是trojan的流量，trojan作为客户端代理，和nginx之间通信从效率上考虑只能采用http/http2, 而不是https(涉及握手，秘钥交换等过程并且nginx开启额外的https服务端口)，这样的话，后续nginx转给v2ray的报文就可能不符合v2ray预期的报文(nginx-http --> v2ray, 不对了)。
> 
> 另外即使能实现，但是trojan和v2ray在同样的端口实现同样的功能，好像是没有必要的。如果443不能用， 那么trojan和v2ray同样歇菜。 整个连接的特征已经由TLS保证了，所以同时在一个端口服务trojan/v2ray好像也是多余的~

按你这样说，的确是多余的，毕竟 fq 最重要的连接特征已经被 tls 保护了，暂时让 gfw 无法识别，我纯粹是好奇问问。

而且 Trojan 不支持 Cloudflare DNS 代理流量，所以 Trojan 和 V2ray 放同一个主机上也不建议，如果两者都用的话最好就是分开两台机，V2ray 用 CF DNS 代理，Trojan 就不用。

**Comment by siwind** [comment]
> > 在trojan这个地方， 同时对收到的报文进行解密和返回给客户的报文进行加密, 如果不是trojan的流量，trojan作为客户端代理，和nginx之间通信从效率上考虑只能采用http/http2, 而不是https(涉及握手，秘钥交换等过程并且nginx开启额外的https服务端口)，这样的话，后续nginx转给v2ray的报文就可能不符合v2ray预期的报文(nginx-http --> v2ray, 不对了)。
> > 另外即使能实现，但是trojan和v2ray在同样的端口实现同样的功能，好像是没有必要的。如果443不能用， 那么trojan和v2ray同样歇菜。 整个连接的特征已经由TLS保证了，所以同时在一个端口服务trojan/v2ray好像也是多余的~
> 
> 按你这样说，的确是多余的，毕竟 fq 最重要的连接特征已经被 tls 保护了，暂时让 gfw 无法识别，我纯粹是好奇问问。
> 
> 而且 Trojan 不支持 Cloudflare DNS 代理流量，所以 Trojan 和 V2ray 放同一个主机上也不建议，如果两者都用的话最好就是分开两台机，V2ray 用 CF DNS 代理，Trojan 就不用。


想法还是不错的，只是现有的实现暂时支持不了罢了~
（除非修改v2ray/trojan代码彼此适应这种情况，不过那个复杂了~）

**Comment by onlyJinx** [comment]
我用trojan群里老哥给的思路实现共用443的,流量大概这样走的
![image](https://user-images.githubusercontent.com/21324835/77903896-35c5ef00-72b6-11ea-9932-79c49e7c85ae.png)

**Comment by mrgeneralgoo** [comment]
经过实践是可以公用 443 的，核心在于 Nginx 在 4 层完成流量分发。
参考资料：https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html

**Comment by OxygenLiu** [comment]
> 经过实践是可以公用 443 的，核心在于 Nginx 在 4 层完成流量分发。
> 参考资料：https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html

实测可用！

**Comment by yuanli-cn** [comment]
> 经过实践是可以公用 443 的，核心在于 Nginx 在 4 层完成流量分发。
> 参考资料：https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html
谢谢，这个应该是目前共用443的比较好的解决方案了。
但其实还是有点繁琐，如果TLS能在NGINX那边搞定，那就不需要给trojan和vmess都单独配置cert。问题是trojan的配置一定需要cert。
