### ISSUE TITLE
流量限制功能在youtube网站失效

### ISSUE THREAD

**Issue by Jrohy** [trojan-gfw/trojan#361]
设置了流量限制后使用已超，像fb,twitter等都不能用，但油管还是一直能用，即使新开一个油管页面也是依然能访问

**Comment by GreaterFire** [comment]
If your YouTube page is reusing a TCP connection. You have to wait for it to disconnect before you can't use it anymore.

**Comment by Jrohy** [comment]
测了貌似只有重新打开浏览器, tcp链接才是新的，如果不重开浏览器就一直复用之前的，然后可以一直刷油管😂

**Comment by Jrohy** [comment]
希望能修复下这个，油管走的流量多限制不了的话会被刷爆
