### ISSUE TITLE
关于linux客户端模式问题

### ISSUE THREAD

**Issue by rainmanzheng** [trojan-gfw/trojan#362]
HI，我尝试在centos7上使用客户端，配置文件按照example中client文件进行修改。同样的配置在win客户端正常，而在centos上却**SSL handshake failed with **example.com:443:** certificate verify failed**，请问是什么原因？  谢谢。

**Comment by siwind** [comment]
windows上可以验证服务器端证书，Linux上的话，需要在客户端配置文件的 cert: ""填入正确的证书的文件位置(例如; /etc/trojan/client.crt); 或者把 "verify": true, 改为 "verify": false （不推荐）~

**Comment by rainmanzheng** [comment]
@siwind 原来如此，现在可以了！ 感谢大佬！

**Comment by siwind** [comment]
> @siwind 原来如此，现在可以了！ 感谢大佬！
(根据下面朋友指出修订如下)
### 推荐的方法

#### 请指向linux系统ca证书
请参阅不同发行版。
一般情况下，这个文件是：" **/etc/ssl/certs/ca-certificates.crt** "
centos/fedora/readhat系发行版： " **/etc/ssl/certs/ca-bundle.crt**  "
(trojan的说明指出如果它查找ca根证书失败,可能报告的是上面的错误)，此时或者安装
受信任根证书或者指出它的路径。

#### 另一种简单的配置
(同样适用于自签名证书等)
你可以在windows上面，通过浏览器把这个证书保存下来(方法见下面)，然后放到linux下面，把cert: 处填上这个文件路径即可。
例如: 
```
"cert": "/etc/trojan/client.cer",
```

### Windows下面导出证书
具体做法是： 用浏览器打开你的域名(例如https://example.com), 然后在地址栏那里点那个小锁显示证书， 在弹出的"证书"对话框中，选择"详细信息"选项卡，下面的“复制到文件”就可以把证书下载到本地，注意导出时，选择" **Base64编码格式** "的证书 (nginx/apache等使用格式)  即可。
然后把这个文件上传到linux， 例如： /etc/trojan/client.cer

对于Lets Encrypt的3个月证书，可以不用我们域名的证书，而是选择签发我们域名的**上级**Lets'encry证书，这个证书至少时间长度有1年以上。
具体方法和上面类似，也是点小锁，在“证书”的"证书路径"处，可以看到我们的3个月域名证书以及上级的签发证书。选择上一级的“**Let's Encrypt Authority X3**”证书，点击“查看证书”打开这个 Let's Encrypt证书，在详细信息里面，导出它。 和上面一样放到Linux下面即可。

### linux 示例
```
{
    "run_type": "client",
    "local_addr": "0.0.0.0",  //or IPv6 "::0"
    "local_port": 1080,
    "remote_addr": "example.com",
    "remote_port": 443,
    "password": [
        "password"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "/etc/trojan/client.cer",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "",
        "alpn": [
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}
```

**Comment by rampageX** [comment]
正确的方法是指向系统 ca 证书，你这样难道每个服务器的证书你都去保存，修改一次？ 

CentOS 应该是：

"cert": "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"

**Comment by siwind** [comment]
> 正确的方法是指向系统 ca 证书，你这样难道每个服务器的证书你都去保存，修改一次？
> 
> CentOS 应该是：
> 
> "cert": "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"

因为不是每个linux下面都有系统证书的。 每个trojan服务器，对应的客户端配置都保存一个特定证书(和配置文件保存在一起即可)，这个没有什么问题~

还有一种情况是临时用的自签名证书(没有免费证书的情况下，很少见)， 这个时候即使系统有证书也不受信任，采用上述方法导出的证书，在使用trojan时就没有问题~

**Comment by rampageX** [comment]
@siwind 自签那是另外一回事，你这种搞法要是上机场几百个服务器你轮流保存一次？每连一个服务器你去改一次 trojan 配置文件？
不是每个 Linux 下都有证书就更好笑了，除非你不用 https。

**Comment by siwind** [comment]
> @siwind 自签那是另外一回事，你这种搞法要是上机场几百个服务器你轮流保存一次？每连一个服务器你去改一次 trojan 配置文件？
> 不是每个 Linux 下都有证书就更好笑了，除非你不用 https。

不是每个人都运营机场的，也就是普通用户用用而已。 上面导出的证书只要是同一个根证书签名的，都是一样的，不需要一个个配置,  对自签名证书也适用。linux下面没有证书是指初始安装时候没有配置系统证书或者系统证书里面没有这个受信任的trojan根证书而已。 要配置那也不难，可能不同发行版添加/配置方法不一定相同 ~

**Comment by zyichang** [comment]
奇怪的是我wget成功了下载了网页文件，但是ping不成功。我是使用proxychains 在终端运行。我用的证书是cer 或者直接false。请问这是什么情况。谢谢！

**Comment by omaidb** [comment]
> 正确的方法是指向系统 ca 证书，你这样难道每个服务器的证书你都去保存，修改一次？ 
> 
> 
> 
> CentOS 应该是：
> 
> 
> 
> "cert": "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"

这个是centos7的证书吗，有人测试过可用吗？我晚点回去试下

**Comment by YusCoding** [comment]
> 正确的方法是指向系统 ca 证书，你这样难道每个服务器的证书你都去保存，修改一次？
> 
> CentOS 应该是：
> 
> "cert": "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"

有用嘞！感谢大佬！！！我特意ls -al /etc/pki/ca-trust/extracted/pem/ 检查了下我服务器有没有这个证书，有的！然后个楼主同样的问题，配置了证书位置后可以正常代理了！！！
