### ISSUE TITLE
socks5打开chrome之后无法正常访问网页

### ISSUE THREAD

**Issue by zzhu2019** [trojan-gfw/trojan#363]
配置好server和client之后 两者连接正常 但是在跑客户端的mac使用socks5打开chrome之后无法访问任何网页 显示
-------------------------
This site can’t be reached
域名’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
-------------------------
client日志
<img width="853" alt="image" src="https://user-images.githubusercontent.com/38281790/77844638-dd6def00-71da-11ea-886c-35d9f351615b.png">
server日志（部分）
<img width="1362" alt="Screen Shot 2020-03-29 at 4 33 22 PM" src="https://user-images.githubusercontent.com/38281790/77844681-20c85d80-71db-11ea-8c1b-eade2dfae148.png">
打开chrome的terminal显示
<img width="839" alt="Screen Shot 2020-03-29 at 4 36 09 PM" src="https://user-images.githubusercontent.com/38281790/77844720-671dbc80-71db-11ea-9394-74c8779339d2.png">
请问可能是什么问题导致的？谢谢。

**Comment by GreaterFire** [comment]
I don't see any problem here. Seems to work fine.

**Comment by zzhu2019** [comment]
> I don't see any problem here. Seems to work fine.

Does it mean that the connection is made properly and works well? Also, does the terminal for opening chrome printout make any sense? I have tried to rebuilt the server environment for a few days but still doesn't work here :(

**Comment by GreaterFire** [comment]
There is legit traffic between your server and your client. The Chrome log seems irrelevant. I can't diagnose the problem here.

**Comment by zzhu2019** [comment]
> There is legit traffic between your server and your client. The Chrome log seems irrelevant. I can't diagnose the problem here.

It seems like the way I use socks5 to open Chrome is wrong. After I downloaded SwitchyOmega, it works. Thanks anyway :)
