### ISSUE TITLE
 [FATAL] fatal: use_certificate_chain_file: No such file or directory

### ISSUE THREAD

**Issue by machenxiang** [trojan-gfw/trojan#364]
**Trojan Version**
1.14.1

**Describe the bug**
mcx@mcx-Lenovo-Rescuer-15ISK:~/shadowsocks/trojan$ sudo ./trojan 
Welcome to trojan 1.14.1
[2020-03-29 17:03:52] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2020-03-29 17:03:52] [FATAL] exiting. . . 

**Environment**
Ubuntu 16.04

**Comment by GreaterFire** [comment]
Please set a correct certificate in the config.

**Comment by xclidongbo** [comment]
How can I  set a correct certificate?

**Comment by GreaterFire** [comment]
Post your config here.

**Comment by xclidongbo** [comment]
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "password1",
        "password2"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/path/to/certificate.crt",
        "key": "/path/to/private.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "cafile": ""
    }
}

**Comment by GreaterFire** [comment]
This issue is about client config. You gave a server config.

**Comment by GreaterFire** [comment]
Set a correct certificate file in `ssl.cert` field.

**Comment by xclidongbo** [comment]
@GreaterFire  a shadowsocks server. I can`t have promission to see. But Thanks.

**Comment by ghost** [comment]
请教，前端用了tls分流器，trojan如何不用443和证书的配置参数

**Comment by shunzhihengren** [comment]
@GreaterFire where is the ssl.cert ?Where can I find it?

**Comment by 0xj0hn** [comment]
> @GreaterFire where is the ssl.cert ?Where can I find it?

you have to create it

**Comment by beaheey** [comment]
> "cert": "/path/to/certificate.crt",
> "key": "/path/to/private.key",

update your certificates path here
