### ISSUE TITLE
[BUG]访问域名下的文件夹时会返回一个带端口的网址

### ISSUE THREAD

**Issue by onlyJinx** [trojan-gfw/trojan#365]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
1.15.1
**Describe the bug**

web服务器: nginx
web端口: 89(方便复现)
trojan端口: 443
防火墙只开放443/80

我的网站下放着一个文件夹aria2,当我访问域名(https://xxx.top) 时是能正常访问的,但是我访问网站下面的aria2文件夹时他会返回一个域名:端口的形式给我
https://xxx.top/aria2 会被指向到 http://xxx.top:89/aria2/
最后的情况就是被我的防火墙给拦截, 要我在访问的链接最后加上一个/结尾才可以,例如这样子 https://xxx.top/aria2/

![image](https://user-images.githubusercontent.com/21324835/77846054-dd272100-71e5-11ea-9aef-3cd06d12e254.png)
![image](https://user-images.githubusercontent.com/21324835/77846073-f92ac280-71e5-11ea-9635-a77942845058.png)

补一张正常访问时候的图片

![image](https://user-images.githubusercontent.com/21324835/77846118-53c41e80-71e6-11ea-88f1-eb1d85088679.png)

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?
Centos7 x64
**Additional context**

**Comment by GreaterFire** [comment]
Please configure NGINX and aria2 correctly. This is not a bug of trojan.
