### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dmcdark** [trojan-gfw/trojan#367]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
1.15.1
**Describe the bug**
Windows 提示有病毒：Trojan:Win32/Wacatac.D!ml

**To Reproduce**
我昨天还用的好好的，今天早上突然出现的，是我电脑中毒了吗？还是windows defender更新了病毒库误杀？

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?
Windows 10 x64 1909

**Additional context**
![Snipaste_2020-03-30_14-40-54](https://user-images.githubusercontent.com/34125260/77882938-ae1bb880-7294-11ea-85ed-ea167574df41.png)

**Comment by Chigusa0w0** [comment]
This is a false positive.
