### ISSUE TITLE
访问链接获取结果失败

### ISSUE THREAD

**Issue by feng5064** [trojan-gfw/trojan#368]
请访问下面的链接获取结果(Please visit the following link to get the result )     *
*                       https://www.feng5064.xyz/M53AWjym***9EMCeorNw.html 
不能打开该网页。
`[root@feng5064 ~]# systemctl status trojan
* trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: d                                     isabled)
   Active: active (running) since Mon 2020-03-30 13:42:45 HKT; 1h 46min ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
 Main PID: 383 (trojan)
   CGroup: /system.slice/trojan.service
           `-383 /usr/local/bin/trojan /usr/local/etc/trojan/config.json

Mar 30 13:31:06 feng5064 systemd[1]: Stopping trojan...
Mar 30 13:31:06 feng5064 systemd[1]: Stopped trojan.
Mar 30 13:42:42 feng5064 systemd[1]: Stopping trojan...
Mar 30 13:42:42 feng5064 systemd[1]: Stopped trojan.
Mar 30 13:42:45 feng5064 systemd[1]: Started trojan.
Mar 30 13:42:45 feng5064 trojan[383]: Welcome to trojan 1.15.1
Mar 30 13:42:45 feng5064 trojan[383]: [2020-03-30 13:42:45] [WARN] trojan s...43
Hint: Some lines were ellipsized, use -l to show in full.
[root@feng5064 ~]# systemctl status nginx
* nginx.service - The NGINX HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/nginx.service.d
           `-override.conf
   Active: active (running) since Mon 2020-03-30 13:42:45 HKT; 1h 46min ago
  Process: 406 ExecStartPost=/bin/sleep 0.1 (code=exited, status=0/SUCCESS)
  Process: 395 ExecStart=/usr/sbin/nginx (code=exited, status=0/SUCCESS)
  Process: 381 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=0/SUCCESS)
 Main PID: 403 (nginx)
   CGroup: /system.slice/nginx.service
           |-403 nginx: master process /usr/sbin/nginx
           `-409 nginx: worker process

Mar 30 13:31:09 feng5064 systemd[1]: Started The NGINX HTTP and reverse proxy server.
Mar 30 13:42:42 feng5064 systemd[1]: Stopping The NGINX HTTP and reverse proxy server...
Mar 30 13:42:42 feng5064 systemd[1]: Stopped The NGINX HTTP and reverse proxy server.
Mar 30 13:42:45 feng5064 systemd[1]: Starting The NGINX HTTP and reverse proxy server...
Mar 30 13:42:45 feng5064 nginx[381]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Mar 30 13:42:45 feng5064 nginx[381]: nginx: configuration file /etc/nginx/nginx.conf test is successful
Mar 30 13:42:45 feng5064 systemd[1]: Started The NGINX HTTP and reverse proxy server.
[root@feng5064 ~]#
`

**Comment by Chigusa0w0** [comment]
The log you provided in this issue does not contain enough information to determine the cause of the problem you mentioned. Please provide more information. If the log exceeds the maximum length allowed by GitHub, please upload a log file as an attachment or use public services such as [pastebin.com](https://pastebin.com).

**Comment by ghost** [comment]
@feng5064 https://tools.ipip.net/ping.php and do not use centos

**Comment by Chigusa0w0** [comment]
Since this is an issue of a third-party software. This issue is closed.
