### ISSUE TITLE
trojan.exe was recognized as a virus by the security center of win10

### ISSUE THREAD

**Issue by kookooko** [trojan-gfw/trojan#369]
trojan.exe was recognized as a virus by the security center of win10
![du](https://user-images.githubusercontent.com/20093737/77891565-b7f8e800-72a3-11ea-8be8-e7896476b2ee.png)

**Comment by Chigusa0w0** [comment]
False positive.
https://www.virustotal.com/gui/file/352bdd16ff2f02539f3889d281d6bf885aedc202129fc791bc449a40cb059b42
