### ISSUE TITLE
Add custom DNS support to config file 

### ISSUE THREAD

**Issue by testcaoy7** [trojan-gfw/trojan#37]
Please add custom DNS support to config file.
Instead using DNS provided by OS, this will allow user to config custom DNS server in trojan.

**Comment by GreaterFire** [comment]
Please provide a reason for adding this functionality.

**Comment by testcaoy7** [comment]
Sometimes server resolv.conf will be overwritten.

**Comment by GreaterFire** [comment]
Sorry, I cannot follow your reasoning. Can you describe your use case in a greater detail?

**Comment by testcaoy7** [comment]
What if I want to use a DNS server that blocks ads with trojan and at the same time I don't want to change the DNS servers listed in the resolv.conf?

It will be nice if trojan can custom its own DNS.

**Comment by GreaterFire** [comment]
https://stackoverflow.com/questions/40979517/querying-custom-dns-server-using-boost-asio-resolver?rq=1

It's not possible for `boost::asio::ip::basic_resolver` to resolve IP addresses via custom DNS servers. To implement this function, one needs to use another library (possibly synchronous, reducing efficiency) or implement their own DNS protocol, which is implausible in current stage of development of trojan.

If you figured out how to do it, you are welcomed to fire a Pull Request. But anyway, it's not a program's (in this case, trojan's) responsibility to choose which DNS server to use.

**Comment by yjmp14** [comment]
Hi, I also think add custom DNS support is a good idea, as I know SS, SSR, V2Ray and Ocserv all support this function. Maybe now in 2020 is a proper time to add it?

**Comment by wongsyrone** [comment]
If you implement it, we would like to merge.
