### ISSUE TITLE
[Feature Request] Pass static link FLAG when compiling

### ISSUE THREAD

**Issue by SuzukiHonoka** [trojan-gfw/trojan#370]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

It is convenient for link the libraries as static for low storage devices.

**Is this problem relevant to what trojan should care about?**

NO

**Describe the solution you'd like**

Add static link flag to CMake list.

**Describe alternatives you've considered**

I have found the [offical guide](https://cmake.org/cmake/help/latest/command/target_link_libraries.html) but I don't know how to use it.

**Additional context**
`/usr/local/bin/trojan: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=3cfed80be4bebb569e0e85ec0397b1375aef6ba5, stripped
`

**Comment by LimiQS** [comment]
See #317 and #156

**Comment by Chigusa0w0** [comment]
See #317 and #156
