### ISSUE TITLE
请问谁用过forward功能

### ISSUE THREAD

**Issue by causlayer** [trojan-gfw/trojan#371]
"run_type": "forward",
    "local_addr": "127.0.0.1",
    "local_port": 5901,
    "remote_addr": "example.com",
    "remote_port": 443,
    "target_addr": "127.0.0.1",
    "target_port": 5901,
    "password": [
        "password1"
    ],
    "udp_timeout": 60,
    "log_level": 1,

请问"target_addr": "127.0.0.1"是相对example.com吗？另外请求是不是客户端->trojan(forward)->target-addr，最终是通过target_addr的target_port端口获取数据。
了解的朋友给讲一下，谢谢。

**Comment by Chigusa0w0** [comment]
https://trojan-gfw.github.io/trojan/config#a-valid-forwardjson

**Comment by alongL** [comment]
https://p4gefau1t.github.io/trojan-go/advance/forward/
maybe this page explain more about forward mode.
and can help you to use forward.
