### ISSUE TITLE
[Feature Request] 可不可以加一个类似SS那样的正向代理功能

### ISSUE THREAD

**Issue by silentmoooon** [trojan-gfw/trojan#374]
请问一下可不可以加一个类似SS那样的正向代理功能。
有时候会处在一个需要设置代理才能访问外部网络的环境下,比如我们公司的网络。
然后trojan如果本身不能设置代理,就没法连网了~

**Comment by Chigusa0w0** [comment]
> Note that we are trying to keep this project as small as possible because it is the core of the trojan ecosystem and will be included in other projects. For a feature to be considered, make sure that the feature you request is really necessary to be included in this very project.

**Comment by Chigusa0w0** [comment]
You may use third-party softwares or deploy a connection redirecting service to do what you want.
