### ISSUE TITLE
Docker 部署 Trojan 报错 config.json 打不开。

### ISSUE THREAD

**Issue by jmyz0455** [trojan-gfw/trojan#379]
我用以下命令在 Docker 上部署 Trojan ：
’‘’
sudo docker run \
    --name mytrojan -d -p 443:443 \
     -v /usr/share/trojan:/usr/local/etc/trojan \
    trojangfw/trojan trojan -c:/usr/local/etc/trojan/config.json
‘’‘
然后报错 `fatal: :/usr/local/etc/trojan/config.json: cannot open file` ，这个 `/usr/local/etc/trojan/config.json` 文件是有的，路径没问题，因为说打不开，我把这个文件权限改到 777，一样不行。
我还在纠结路径&权限的问题，但神奇的是，不用 -c 参数，直接用以下命令就可以了：
’‘’
sudo docker run \
    --name mytrojan -d -p 443:443 \
     -v /usr/share/trojan:/usr/local/etc/trojan \
    trojangfw/trojan
‘’‘
文件路径、权限都没变（644），居然就可以了，难道 -c 参数我写得不对还是哪里搞错了。

**Comment by GreaterFire** [comment]
`-c:/usr/local/etc/trojan/config.json`
You had an extra `:` in your command.
