### ISSUE TITLE
[Feature Request] io_context多线程处理

### ISSUE THREAD

**Issue by luodaoyi** [trojan-gfw/trojan#381]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

好像io_context只会有一个主线程处理

我觉得搞成电脑默认的内核数量比较好

```cpp
boost::thread::hardware_concurrency()
```

好像是这行代码:

https://github.com/trojan-gfw/trojan/blob/3d608e868c1d4fe5b07266d4b8bc5bfd01e9291d/src/core/service.cpp#L291

**Comment by GreaterFire** [comment]
This is not that easy and due to the complications in handling race conditions, we are not going to implement it. See #179 for more details.

You can use `reuse_port` and open up multiple instances of trojan instead.
