### ISSUE TITLE
[BUG]请问Trojan直接链接是不是很慢？而且有被墙的情况

### ISSUE THREAD

**Issue by 0CrazyGuy9** [trojan-gfw/trojan#382]
有一台VPS，100Mbps的。IP是：x.x.x.x

v2ray，nginx+ws+CLOUDFLARE，下载速度9MB/s
trojan，申请好证书，直接挂上。客户端链接，200KB/s。

是怎么回事呢？因为我的机器到VPS本来就很慢的，可能是这个原因。
但v2ray代理后，ws+cloudflare很快很快。是不是trojan必须要本地机器与VPS本身通信快才有可能快？

**Comment by 0CrazyGuy9** [comment]
trojan 下载
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 80.5M    0  639k    0     0   3852      0  6:05:18  0:02:50  6:02:28 12580
curl: (56) Failure when receiving data from the peer`

v2ray ws+nginx+cloudflare
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80.5M  100 80.5M    0     0   867k      0  0:01:35  0:01:35 --:--:-- 1478k`

**Comment by 0CrazyGuy9** [comment]
还有就是trojan在国内有些问题，例如https://www.youtube.com 解释不到IP，估计是用系统DNS，是怎么回事呢？

在国内访问（链接同一个VPS）访问网站https://www.baidu.com
curl --socks5 192.168.22.3:1080 https://www.baidu.com -Ik
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Tue, 07 Apr 2020 16:15:51 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

在国内访问（链接同一个VPS）访问网站https://www.youtube.com/
curl --socks5 192.168.22.3:1080 https://www.youtube.com/ -Ik
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed

在外国访问（链接同一个VPS）访问网站https://www.youtube.com/
curl --socks5 192.168.22.2:1080 https://www.youtube.com -Ik
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache
Content-Type: text/html; charset=utf-8
P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
Expires: Tue, 27 Apr 1971 19:44:06 GMT
Strict-Transport-Security: max-age=31536000
Date: Tue, 07 Apr 2020 16:01:00 GMT
Server: YouTube Frontend Proxy
X-XSS-Protection: 0
Set-Cookie: YSC=K_-cKFLqk9k; path=/; domain=.youtube.com; secure; httponly; samesite=None
Set-Cookie: GPS=1; path=/; domain=.youtube.com; expires=Tue, 07-Apr-2020 16:31:00 GMT
Set-Cookie: VISITOR_INFO1_LIVE=FVKlZ3aWYZI; path=/; domain=.youtube.com; secure; expires=Sun, 04-Oct-2020 16:01:00 GMT; httponly; samesite=None
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
Accept-Ranges: none
Vary: Accept-Encoding

**Comment by 0CrazyGuy9** [comment]
使用V2ray的代理（在国内）
curl --socks5 192.168.22.10:1080 https://www.youtube.com/ -Ik
HTTP/1.1 200 OK
P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
Strict-Transport-Security: max-age=31536000
Cache-Control: no-cache
Expires: Tue, 27 Apr 1971 19:44:06 GMT
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 07 Apr 2020 16:07:17 GMT
Server: YouTube Frontend Proxy
X-XSS-Protection: 0
Set-Cookie: VISITOR_INFO1_LIVE=ZJaxikuzzIk; path=/; domain=.youtube.com; secure; expires=Sun, 04-Oct-2020 16:07:16 GMT; httponly; samesite=None
Set-Cookie: YSC=Svfz7AIbdRU; path=/; domain=.youtube.com; secure; httponly; samesite=None
Set-Cookie: GPS=1; path=/; domain=.youtube.com; expires=Tue, 07-Apr-2020 16:37:16 GMT
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
Accept-Ranges: none
Vary: Accept-Encoding

**Comment by 0CrazyGuy9** [comment]
Let's免费证书

服务端配置：
`
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 44443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "123456789",
        "a123456789"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "mydomain.crt",
        "key": "mydomain.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "cafile": ""
    }
}

`

客户端配置：
`
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "mydomain.com",
    "remote_port": 80,
    "password": [
        "123456789"
    ],
    "log_level": 0,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}

`

**Comment by GreaterFire** [comment]
IT DOESN'T MAKE ANY SENSE to compare raw TCP speed with CDN speed. Also you put your server on port `44443` which might also be a factor.

Note that GitHub issue is [not for this kind of questions](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md).

**Comment by 0CrazyGuy9** [comment]
> IT DOESN'T MAKE ANY SENSE to compare raw TCP speed with CDN speed. Also you put your server on port `44443` which might also be a factor.
> 
> Note that GitHub issue is [not for this kind of questions](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md).

必须要使用443？

**Comment by GreaterFire** [comment]
I beg you to read the contributing guidelines.
