### ISSUE TITLE
Linux客户端代理问题

### ISSUE THREAD

**Issue by sherlockwho** [trojan-gfw/trojan#385]
我在linux系统上使用trojan的客户端，同时设置了系统的代理模式，但是在使用的过程中我发现只有浏览器可以使用代理，其他应用都不能，不知道有没有办法解决。
另外我直接在系统设置中设置的代理，没有设置分流，但是好像trojan会自动分流，这个分流策略是可以手动设置的吗？
感谢各位的辛勤工作！

**Comment by Chigusa0w0** [comment]
Trojan will not treat traffic differently.
Trojan itself do not provide any system-wide proxy function. So this topic is considered off-topic.
