### ISSUE TITLE
增加ws支持 [Feature Request]

### ISSUE THREAD

**Issue by luoqiz** [trojan-gfw/trojan#386]
有些国外网站需要ws连接实时处理数据，希望可以增加此协议支持。

**Comment by Billyzou0741326** [comment]
In my limited understanding, ws is based upon the tcp protocol, which is exactly what trojan uses to establish connections. The socks5 protocol sitting on the client side will also handle ws connections just like it does any other requests. 

Correct me if I'm wrong, but in short, trojan already proxies ws connections.

**Comment by GreaterFire** [comment]
Please read the doc if you don't know how trojan works. Your request is too vague and implausible.
