### ISSUE TITLE
[BUG]start fail

### ISSUE THREAD

**Issue by kkblock** [trojan-gfw/trojan#387]
➜  soft systemctl status trojan@config
● trojan@config.service - trojan
     Loaded: loaded (/usr/lib/systemd/system/trojan@.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2020-04-10 13:00:56 CST; 3min 25s ago
       Docs: man:trojan(1)
             https://trojan-gfw.github.io/trojan/config
             https://trojan-gfw.github.io/trojan/
    Process: 7067 ExecStart=/usr/bin/trojan /etc/trojan/config.json (code=exited, status=127)
   Main PID: 7067 (code=exited, status=127)

4月 10 13:00:56 alex systemd[1]: trojan@config.service: Scheduled restart job, restart counter is at 5.
4月 10 13:00:56 alex systemd[1]: Stopped trojan.
4月 10 13:00:56 alex systemd[1]: trojan@config.service: Start request repeated too quickly.
4月 10 13:00:56 alex systemd[1]: trojan@config.service: Failed with result 'exit-code'.
4月 10 13:00:56 alex systemd[1]: Failed to start trojan.

**Comment by tomac4t** [comment]
`status=127` means that `/usr/bin/trojan` is not existing.

**Comment by Chigusa0w0** [comment]
Please provide Trojan log.

**Comment by tomac4t** [comment]
不，他没有日志，因为 `/usr/bin/trojan` 根本不存在，所以这个问题与 trojan 无关。@LimiQS

> If a command is not found, the child process created to execute it returns a status of 127. If a command is found but is not executable, the return status is 126. 

https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

**Comment by GreaterFire** [comment]
Not a bug.

**Comment by guoPengSong** [comment]
> 不，他没有日志，因为 `/usr/bin/trojan` 根本不存在，所以这个问题与 trojan 无关。@LimiQS
> 
> > If a command is not found, the child process created to execute it returns a status of 127. If a command is found but is not executable, the return status is 126.
> 
> https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

我想问一下这种情况该怎么解决，我也是这种情况，我的trojan昨天还是能用的

**Comment by guoPengSong** [comment]
> ➜ soft systemctl status trojan@config
> ● [trojan@config.service](mailto:trojan@config.service) - trojan
> Loaded: loaded (/usr/lib/systemd/system/trojan@.service; enabled; vendor preset: disabled)
> Active: failed (Result: exit-code) since Fri 2020-04-10 13:00:56 CST; 3min 25s ago
> Docs: man:trojan(1)
> https://trojan-gfw.github.io/trojan/config
> https://trojan-gfw.github.io/trojan/
> Process: 7067 ExecStart=/usr/bin/trojan /etc/trojan/config.json (code=exited, status=127)
> Main PID: 7067 (code=exited, status=127)
> 
> 4月 10 13:00:56 alex systemd[1]: [trojan@config.service](mailto:trojan@config.service): Scheduled restart job, restart counter is at 5.
> 4月 10 13:00:56 alex systemd[1]: Stopped trojan.
> 4月 10 13:00:56 alex systemd[1]: [trojan@config.service](mailto:trojan@config.service): Start request repeated too quickly.
> 4月 10 13:00:56 alex systemd[1]: [trojan@config.service](mailto:trojan@config.service): Failed with result 'exit-code'.
> 4月 10 13:00:56 alex systemd[1]: Failed to start trojan.

解决了吗，怎么解决

**Comment by kousyougi** [comment]
我剛剛遇到一樣的錯誤碼，是 Arch Linux。
我查出來，我的狀況是讀證書的時候，證書在 /root/.acme.sh/ 下面。應該是權限的問題。
這台電腦只裝trojan，就直接修改 usr/lib/systemd/system/trojan.service 裡面的
User=nobody 改成 User=root
就可以正常運行了。
