### ISSUE TITLE
Is it recommended to enable TCP Fast Open feature?

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#388]
As title. I'd like to ask whether it is recommended to enable TCP Fast Open feature.

1: Would it bring improvement to latency and speed?
2: Would it increase the chance of being detected by GFW?

Thank you so much!

**Comment by GreaterFire** [comment]
It's generally very discouraged to enable this feature. There are barely any improvements on the latency and it adds to the chance your traffic is being detected.

**Comment by vbuterin2** [comment]
But TCP fast open feature can greatly improve the speed of traffic, although it adds to the chances of being detected.
