### ISSUE TITLE
[Feature Request] To support websocket like trojan-go

### ISSUE THREAD

**Issue by txdywy** [trojan-gfw/trojan#393]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
Hope trojan will support websocket so that it can deploy through CDN proxy

**Is this problem relevant to what trojan should care about?**
Make trojan more powerful and flexible

**Describe the solution you'd like**
Prefer trojan can support websocket like the way https://github.com/p4gefau1t/trojan-go did which is compatibale with trojan itself

**Describe alternatives you've considered**
Or other way to support websocket

**Additional context**
https://github.com/p4gefau1t/trojan-go

**Comment by Chigusa0w0** [comment]
@txdywy Specialize a TCP based protocol to a WS based protocol will not "make Trojan more powerful and flexible" and may introduce vulnerability and overhead.

**Comment by txdywy** [comment]
> @txdywy Specialize a TCP based protocol to a WS based protocol will not "make Trojan more powerful and flexible" and may introduce vulnerability and overhead.

To make it portable with ws to support more CDNs would reduce the server connection requitements to local network.

**Comment by Chigusa0w0** [comment]
@txdywy This is a topic that has been repeatedly discussed, and we have decided not to compromise the characteristics of the Trojan protocol in order to support that. If you need specific unsupported features, you may fork and develop it yourself.
