### ISSUE TITLE
Problems with wildcard certificate

### ISSUE THREAD

**Issue by heiludong** [trojan-gfw/trojan#394]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
Trojan 1.51. 

**Describe the bug**
SSL handshake failed with vvv.mydomain.com:443: certificate verify failed
**To Reproduce**
1. acme.sh generate wildcard certificate for mydomain.com which dns resolver is godaddy.
2. Use fullchain and key file to set up server and client. Client remote_addr is 'vvv.mydomain.com
3. When connected, "certificate verify failed".
4. If client remote addr set to "mydomain.com", trojan works well.
5. acme.sh generate certificat for vvv.vvv.mydomain.com. set up with the fullchain and the key. client remote_addr is "vvv.vvv.mydomain.com", server local_addr is "0.0.0.0", it works well.

**Expected behavior**
With wildcard certificate, I expect vvv.mydomain.com can be certified.

**Logs**
[2020-04-19 01:17:47] [INFO] 192.168.7.8:52300 requested connection to fonts.gstatic.com:443
[2020-04-19 01:17:49] [ERROR] 192.168.7.8:52296 SSL handshake failed with vvv.mydomain.com:443: certificate verify failed
**Environment**
Server on Ubuntu 18.04. Client on openwrt snapshot.

**Additional context**
Nginx works as expected with the wildcard certificate.

**Comment by GreaterFire** [comment]
@hasenlu Wildcard certificates do work. We need more info regarding your certificate. Can you upload the fullchain here?

**Comment by hasenlu** [comment]
[fullchain.cer.gz](https://github.com/trojan-gfw/trojan/files/4497382/fullchain.cer.gz)
Thanks.

**Comment by GreaterFire** [comment]
```
$ openssl x509 -in fullchain.cer -text -noout 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:19:1f:fd:b1:55:5b:80:45:a2:86:45:e6:cc:7b:f4:8a:65
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Apr 18 04:58:05 2020 GMT
            Not After : Jul 17 04:58:05 2020 GMT
        Subject: CN = caidaddy.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:b7:bb:b1:ee:43:b6:ec:63:2c:96:b1:59:8f:fc:
                    66:4b:a9:31:f0:05:af:16:f7:86:b6:ed:7c:0e:a5:
                    0f:30:0a:5f:e1:ff:b9:52:5e:d6:80:dc:25:79:08:
                    fc:75:72:2a:46:b7:64:0c:ad:03:8c:8e:9a:06:67:
                    8c:1b:25:4f:8d:54:9d:4d:ce:bd:fc:95:50:d0:98:
                    c4:67:16:58:24:e4:44:fe:18:cb:c5:2d:f3:23:51:
                    d3:47:93:4e:70:1a:14:09:28:23:5b:61:87:fb:38:
                    eb:60:03:c1:0c:49:78:62:1c:f8:99:7a:52:90:a1:
                    75:dc:c7:64:6b:9e:bc:51:61:bb:ac:28:49:b8:b6:
                    f4:47:7f:b3:bb:9d:a0:f3:19:63:37:60:11:28:47:
                    76:30:9b:eb:ac:25:46:93:45:18:4d:c8:c4:cd:14:
                    4b:af:d3:47:8e:2a:7a:dc:4b:2c:9e:4f:66:0f:3f:
                    8d:61:3b:8f:8f:39:db:3c:09:8b:55:d5:df:09:e2:
                    c1:97:ed:ed:5c:4f:4d:94:81:d9:3f:30:d5:c8:f4:
                    b2:87:f2:45:81:fe:63:0b:f2:a7:1d:a1:a8:11:74:
                    50:50:27:c2:cc:f6:ed:28:56:d1:5e:5b:90:91:54:
                    0f:eb:87:95:83:86:1d:97:5c:66:79:28:87:f3:75:
                    60:17
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                40:52:D6:07:A7:39:44:58:DB:A8:CB:BD:EF:01:E4:6E:45:B1:C1:F9
            X509v3 Authority Key Identifier: 
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access: 
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name: 
                DNS:caidaddy.com, DNS:www.caidaddy.com
...
```
Your certificate is not a wildcard certificate. It only certifies `caidaddy.com` and `www.caidaddy.com`. To get a wildcard certificate, you need a certificate that certifies `caidaddy.com` and `*.caidaddy.com`.

**Comment by hasenlu** [comment]
@GreateFire, Could you delete the comment kindly? Thanks.

**Comment by hasenlu** [comment]
Closed  due to I don't get real wildcard certificate. Thanks a lot.
