### ISSUE TITLE
前置代理的支持

### ISSUE THREAD

**Issue by gudong321** [trojan-gfw/trojan#396]
在中国，不论是大型科技公司，国企，还是高校院所，经常处于各种代理环境，希望trojan可以提供Http等前置代理功能，方便广大用户。

**Comment by rampageX** [comment]
Use `glider` proxy chain: [glider](https://github.com/nadoo/glider) 

`glider -listen :7777 -forward http://a.b.c.d:port,trojan://password@www.trojan-1.xyz:443`

**Comment by GreaterFire** [comment]
You can also just use proxychains-ng.

**Comment by gudong321** [comment]
> Use `glider` proxy chain: [glider](https://github.com/nadoo/glider)
> 
> `glider -listen :7777 -forward http://a.b.c.d:port,trojan://password@www.trojan-1.xyz:443`

Thank you very much！

**Comment by gudong321** [comment]
> can also just use proxychains-ng

Thank you！Easy is best！

**Comment by 0xfk0** [comment]
> You can also just use proxychains-ng.

Proxychains will not work without a patch disabling epoll (see https://github.com/trojan-gfw/trojan/pull/712).
