### ISSUE TITLE
hide the main window and use a tray icon on Windows

### ISSUE THREAD

**Issue by goldenbull** [trojan-gfw/trojan#400]
On Windows system, we would like a background process to hide the main console window and stay in tray icon area.

**Comment by goldenbull** [comment]
seems there is a simple solution:
create a script `run.vbs` with the content:
```
Set Shell = CreateObject("WScript.Shell")
Shell.Run "trojan.exe", 0, False
```
the `trojan.exe` process will run in background without console window or trayicon. Can be killed in task manager.

**Comment by LsnmxNB** [comment]
快捷方式最小化就行了，最完美解决方案，如果不想开机启动这玩意到处跑就固定这玩意任务栏位置自己看图
<img width="439" alt="Snipaste_2020-04-24_17-20-46" src="https://user-images.githubusercontent.com/42826027/80197029-b0cdbb80-8650-11ea-9765-4b2674f88095.png">
<img width="651" alt="Snipaste_2020-04-24_17-21-38" src="https://user-images.githubusercontent.com/42826027/80197042-b3301580-8650-11ea-9035-1316de519068.png">

https://i.loli.net/2020/04/24/R6DbUzEmYMo2vKh.png
https://i.loli.net/2020/04/24/vziJnDFy7XNftx6.png

**Comment by Chigusa0w0** [comment]
Dup #91
