### ISSUE TITLE
[BUG]某些网站，比如www.atrandys.com无法访问

### ISSUE THREAD

**Issue by flyhigao** [trojan-gfw/trojan#401]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
trojan的客户端和服务端都是1.15.1
浏览器包括mac和ubuntu19上的chrome，safari ， 手机上的chrome。
线路：电信（移动）+ aliyun_sg, 电信(移动)+bandwagon DC6

**Describe the bug**
客户端是OPENWRT上的passwall插件，
服务端的配置是example中的默认配置。
有一些网站始终打不开，比如www.atrandys.com
如果使用相同vps上的v2r服务，则一切正常。

========以下服务端配置：
    "ssl": {
        "cert": "/usr/src/trojan-cert/fullchain.cer",
        "key": "/usr/src/trojan-cert/private.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
           "h2",
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "fast_open": false,
        "fast_open_qlen": 20
    },

===========以下passwall客户端配置：
   "ssl": {
     "verify_hostname": true,
     "curves": "",
     "session_ticket": false,
     "reuse_session": true,
     "verify": false,
     "alpn": [
       "h2",
       "http\/1.1"
     ],
     "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
     "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384"
   },
   "tcp": {
     "fast_open_qlen": 20,
     "fast_open": false,
     "keep_alive": true,
     "reuse_port": true,
     "no_delay": true
   }

请问各位，你们是否有这个问题，是否能访问到？

**Comment by flyhigao** [comment]
补充一下，我v2ray使用的是 TCP + TLS + Web 方式构建，构建方式如下：
https://guide.v2fly.org/advanced/tcp_tls_web.html#%E8%83%8C%E6%99%AF
PS：上述网址，trojan同样无法打开。

**Comment by Chigusa0w0** [comment]
Invalid

**Comment by wazzx** [comment]
> 补充一下，我v2ray使用的是 TCP + TLS + Web 方式构建，构建方式如下：
> https://guide.v2fly.org/advanced/tcp_tls_web.html#%E8%83%8C%E6%99%AF
> PS：上述网址，trojan同样无法打开。
这个不是什么bug，你用的是第三方的passwall客户端所以有这个问题，本人是trojan直接用nat模式gfw列表按照格式加入atrandys.com既可以了

**Comment by flyhigao** [comment]
我是开了全局模式，还有这种情况。不过算了，不用了。
