### ISSUE TITLE
[Feature Request] trojan client/nat should not require a cert file

### ISSUE THREAD

**Issue by sgon00** [trojan-gfw/trojan#402]
I am running trojan in `nat` run_type at openwrt. I found out I had to provide the `"cert"` file in order to make ssl handshake work. Without providing the cert, the connection to trojan server will result in SSL Handshake Failure error. 

But all other https clients such as browsers can download the cert automatically from the trojan https server. cert is always public available, I don't know why this cert here is mandatory. 

It causes too much troubles because free cert is only valid for 3 months. and once every three months, I have to manually change the cert in my router. 

I hope trojan client/nat at openwrt can get the cert automatically from trojan server instead of setting it manually. 

It's a feature request, and thank you very much for considering it.

**Comment by ffftwo** [comment]
set ssl verify to false
https://github.com/trojan-gfw/trojan/blob/master/examples/nat.json-example

**Comment by Chigusa0w0** [comment]
This is a security feature. See [this article](https://labs.nettitude.com/tutorials/tls-certificate-pinning-101/). You may toggle off the feature by editing your configure file.

**Comment by wongsyrone** [comment]
Did you installed ca-certificates or ca-bundle on openwrt via opkg?

**Comment by sgon00** [comment]
@wongsyrone Thank you very much for the help. I forgot I did have to install CA certs on openwrt. After installing ca-certificates and ca-bundle, I can remove the `"cert"` value and leave it empty with `"verify": true,`. 

Btw, I read the config doc https://trojan-gfw.github.io/trojan/config again , I think the following words can be modified and improved: 

> If you leave this field blank, OpenSSL will try to look for a system CA store and will be likely to fail

I didn't realize that is a CA problem because the doc tells me looking for a system CA store will be likely to fail. But the truth is it won't fail.

**Comment by madneal** [comment]
@sgon00  I came across the similar problem with you. And I even config the cert, but still didn't work. Could you provide some suggestions? Thanks.

![image](https://user-images.githubusercontent.com/12164075/91178237-73b92900-e717-11ea-94ab-73696992cce8.png)

**Comment by sgon00** [comment]
@madneal It has been some time that I configured trojan. I am not really a trojan expert and you don't provide any error logs either. So I am not sure what your real problem is. Are you using CA cert or self-signed cert? I finally end up using CA cert from https://letsencrypt.org/. In such way, there is no need to provide the cert in the client side. And you should make sure install `ca-certificates` or/and `ca-bundle` in openwrt.

**Comment by madneal** [comment]
@sgon00 I install trojan server side by this [script](https://raw.githubusercontent.com/atrandys/trojan/master/trojan_mult.sh). It helped me to generate cert. I have installed ca-certificated and ca-bundle in openwrt. But I cannot acess google, but only youtube is OK.

**Comment by GreaterFire** [comment]
@madneal We don't answer any questions regarding the problems of any third-party scripts.

**Comment by sgon00** [comment]
@madneal maybe something wrong with your dns request? You have to debug and find what the real problem is. I don't have time to check other people's script. I installed and setup everything manually. To avoid dns poisoning, you should use tcp dns request when accessing and resolving domain names and the tcp dns request is better go through the trojan proxy (tunnel). In order to do this, you have to setup iptables rules properly in openwrt. The above is my approach. Some people may use encrypted dns, but it didn't work well in my region. Btw, gfw keeps blocking my server's 443 port in my region (some other people don't have this problem in other regions), so you'd better use another random bigger port number. All the above is just my guess. You have to debug and figure out what your real problem is.

**Comment by madneal** [comment]
@sgon00 Really thank for your reply. Seems problem with the cache. It solves when I restart my mac.
