### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mobeyond** [trojan-gfw/trojan#405]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
trojan-1.15.1-win.zip

**Describe the bug**
Windows 10 Security Alertthat the "Trojan" contains backdoor called "Trojan:Win32/Wacatac.D!ml"
**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?

**Additional context**

**Comment by GreaterFire** [comment]
@mobeyond The trojan binary is not a trojan horse. If in doubt, you can compile your own.
