### ISSUE TITLE
[BUG] Connection refused and certificate verify failed on mac

### ISSUE THREAD

**Issue by alexseedkou-zz** [trojan-gfw/trojan#407]
- [ x ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.14.1

**Describe the bug**
1) Recently when I tried to connect the server, I got an error with certificate verify failed on mac. So I just turn the filed of `verify` to `false` in ssl in `config.json` to fix the issue temporally.

2) On 2nd day after the quick fix of the  issue, I got connection refused error on client side. So I restart the server and try to connect it again and it works, this restart also fixed the certificate verify failed error since I changed `verify` to `true` in ssl in `config.json` and it works great.

3) Another two days after the above fix, I got connection refused again.

**Logs**
1)**log for certificate verify failed:** [ERROR] 127.0.0.1:50495 SSL handshake failed with xxx.xxxxxxxxx.xx:443: certificate verify failed

2) **log for connection refused:** [ERROR] 127.0.0.1:61700 cannot establish connection to remote server YOUR_DOMAIN:443: Connection refused

**Additional context**
FYI, it seems the server is not down since I can still access the nginx welcome page that hosted on my server. The certificate I use is Let's encrypted and it is not expired.

Any help will be appreciate

**Comment by tjysdsg** [comment]
Same problem happened on my machine, v1.15.1

**Comment by knoxville9** [comment]
Same problem happened on my win7  , v1.15.1

**Comment by knoxville9** [comment]
> Same problem happened on my machine, v1.15.1

certification was expired , update it  will be fixed

**Comment by alexseedkou-zz** [comment]
I have mentioned the cert is not expired, it still have 1 year valid.

> > Same problem happened on my machine, v1.15.1
> 
> certification was expired , update it will be fixed

**Comment by tjysdsg** [comment]
> Same problem happened on my machine, v1.15.1

Turns out it's my SSL certificate expiring causing the problem. It fixes the issue once I renew the certificate.

Ubuntu 18.04 Trojan v1.15.1

**Comment by malikshi** [comment]
trojan can running on mikrotik chr ? @GreaterFire

**Comment by XieJiSS** [comment]
@alexseedkou Maybe you were MITM-ed

**Comment by alexseedkou-zz** [comment]
> @alexseedkou Maybe you were MITM-ed

I have no idea what is this, but anyway it works now

**Comment by XieJiSS** [comment]
> > @alexseedkou Maybe you were MITM-ed
> 
> I have no idea what is this, but anyway it works now

That stands for Man-In-The-Middle Attack, sorry I haven't noticed that you're not in mainland China
