### ISSUE TITLE
[Feature Request]能否支持驗證客戶端證書？

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#409]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Describe the solution you'd like**
能否支持強制驗證客戶端證書，像VPN那樣。
![Screenshot](https://user-images.githubusercontent.com/17502357/80859672-19421b80-8c95-11ea-963b-3387cf587990.jpg)

**Comment by okudayukiko** [comment]
手機版Igniter能否像Shadowsocks-Android那樣提供「略過局域網」功能？能否像Shadowsocks-Android那樣支持為服務器命名（有時只填服務器地址不方便分辨服務器所在國家）？
Trojan能否支持多證書（如Nginx支持RSA+ECDSA）、GeoIP（Igniter支持不代理中國IP，望Trojan支持以國家代碼不代理某個國家的IP段）？用OpenSSL追了下，Trojan不支持多證書（如RSA+ECDSA）。
以下配置只支持ECDHE-RSA，不支持ECDHE-ECDSA：
`{`
`"run_type": "server",`
`"ssl": { `
`"cert": "/path/to/rsa.crt",`
`"key": "/path/to/rsa.key",`
`"cert": "/path/to/ecdsa.crt",`
`"key": "/path/to/ecdsa.key"`
`}`
`}`
以下配置直接報錯：
`"cert": ["rsa.crt","ecdea.crt"],`
`"key": ["rsa.key","ecdsa.key"],`
Trojan不能監聽IPv6 ::0。以下配置只監聽IPv4 0.0.0.0，不監聽IPv6 ::0。
`{`
`"local_addr": "0.0.0.0",`
`"local_addr": "::0",`
`}`
用以下配置無法啟動Trojan（但運行`trojan -t`還是提示The config file looks good）：
`{`
`"local_addr:": ["0.0.0.0","::0"],`
`}`
Trojan版本：1.10.0（Debian 10 APT的版本）

**Comment by Chigusa0w0** [comment]
Please read the document.

**Comment by charley008** [comment]
..
