### ISSUE TITLE
本地证书过期后还能继续使用？

### ISSUE THREAD

**Issue by granbelm** [trojan-gfw/trojan#410]
emm刚刚发现服务端的ssl过期了，update完后发现本地的旧的证书依旧可以使用trojan？？？
这是正常情况吗？不更新本地证书安全吗？

**Comment by GreaterFire** [comment]
@granbelm This should not happen. Please post your configs. And also, did you restart the server after renewing your certificates?

**Comment by granbelm** [comment]
Of Course, I have rebooted my sever.
![image](https://user-images.githubusercontent.com/64766322/80937494-f2f0bd00-8e07-11ea-8e86-cc401be8f870.png)

**Comment by GreaterFire** [comment]
@granbelm This is normal, because you are using a full chain on your client side, which has the same CA of your new certificate. OpenSSL will pass the certificate test because of that. If you use only the certificate (not full chain) then Trojan will complain. Hopes this makes sense to you.

**Comment by granbelm** [comment]
Thank you very much. BTW, I want to ask a stupid problem since I know little about SSL.
So it means that trojan using the CA certificate to encrypt the data when it has a full-chain cer?

**Comment by GreaterFire** [comment]
No. It uses your certificate's public key.

**Comment by granbelm** [comment]
Thanks for answering me !

**Comment by ldwnt** [comment]
> @granbelm This is normal, because you are using a full chain on your client side, which has the same CA of your new certificate. OpenSSL will pass the certificate test because of that. If you use only the certificate (not full chain) then Trojan will complain. Hopes this makes sense to you.

I'm using Trojan-Go v0.10.5 and my certificate expires. Instead of having trojan working, I get this error: 
```
[ERROR] 2022/08/14 22:37:36 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | simplesocks failed to dial using underlying tunnel | no available mux client found | mux failed to dial | tls failed to handshake with remote server | x509: certificate has expired or is not yet valid: current time 2022-08-14T22:37:36+08:00 is after 2022-08-13T23:59:59Z
```
Is there any way to bypass this? The attampts to renew the certificate always fail for both letsencrypt and zerossl today. And I really need to access google..

The option verify: false seems to work, but I'm not sure the consequences of using that option

Get the certificate renewed using the standalone mode with letsencrypt (zerossl just fails with sleep 10 and retry), but client reports
```
[ERROR] 2022/08/14 23:23:16 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | simplesocks failed to dial using underlying tunnel | no available mux client found | mux failed to dial | tls failed to handshake with remote server | x509: certificate signed by unknown authority
```
