### ISSUE TITLE
[BUG]無法設定TLS 1.3 Ciphersuites

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#415]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
Welcome to trojan 1.10.0
Boost 1_67, OpenSSL 1.1.1b 26 Feb 2019
**Describe the bug**
GFW已經能干擾TLS_CHACHA20_POLY1305_SHA256 Ciphersuites。修改Trojan設定檔無法禁用TLS1.3 TLS_CHACHA20_POLY1305_SHA256 Ciphersuites。
`{`
`"run_type": "server",`
`"local_port: "443",`
`"ssl" :{`
`"cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384"`
`}`
`}`
用`openssl s_client -tls1_3 -ciphersuites TLS_CHACH20_POLY1305_SHA256 localhost:443`檢測一下發現TLS_CHACHA20_POLY1305_SHA256仍然啟用。
**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?
Debian 10
**Additional context**

**Comment by Chigusa0w0** [comment]
Upgrade your trojan client.

**Comment by okudayukiko** [comment]
> Upgrade your trojan client.

使用Ubuntu 20.04的Trojan則無此Bug。
`root@ubuntu:~# trojan -v`
`Welcome to trojan 1.14.1`
`Boost 1_71, OpenSSL 1.1.1f 31 Mar 2020`
使用Debian 10 APT的Trojan則有此Bug。

**Comment by Chigusa0w0** [comment]
TLS 1.3 support added AFTER 1.10.0.
>The version of trojan you are using.
>Welcome to trojan 1.10.0
>Boost 1_67, OpenSSL 1.1.1b 26 Feb 2019
