### ISSUE TITLE
有什么办法降低 trojan 运行时内存？

### ISSUE THREAD

**Issue by boluoyu** [trojan-gfw/trojan#416]
我把 trojan 编译成可以在 iPhone 上运行了，速度也挺快，但有一个问题，IPhone 上的 NetworkExtension  Packet Tunnel  有一个严格限制，内存不能超过15M，一旦达到15M ，子进程就会被kill 掉，所以多刷几个网页就会掉线，具体讨论可以看 https://forums.developer.apple.com/thread/73148 。 Packet tunnel 本身内存就占用6M 左右，所以 trojan 内存不能超过8M ，而在 mac 上也能观察到， trojan 初始内存3、4M ， 运行时间长了，就会变大，最终会有22M 左右。我需要做哪些编译优化，或者代码优化，或者说应该怎么做快速释放内存，让 trojan 内存限制在8M 以下呢？

**Comment by Chigusa0w0** [comment]
As most platforms trojan supported usually have abundant memory and this seems not related to a memory leak. We don't have a lot information to provide about how to lower the memory usage. And the usage may caused by underlying dependencies.
If your purpose is to find a working App on iPhone, you may try Pharos or ShadowRocket

**Comment by boluoyu** [comment]
@LimiQS  谢谢，还是想自己编译出一个，一方面可以学习，一方面可以定制化自己的App，而且Pharos 需要国外帐号，麻烦

**Comment by nahddw** [comment]
@boluoyu 有进展吗? 能否给一个联系方式

**Comment by bt-clint** [comment]
@boluoyu 可以分享你编译出来的trojan库吗，我目前也在学习这一块，谢谢了

**Comment by boluoyu** [comment]
> @boluoyu 有进展吗? 能否给一个联系方式

@nahddw 我是 ios 开发零基础，是编译出来了，也可以在 iphone 正常运行，但如果手机运行东西多的话，还是会崩，但有朋友的手机运行崩的概率小，跟运行环境有关。用到NEKit 包，看一下源码这个框架对Ios 线程数没做限制，由系统自动配置，下载的资源比较多时，线程数也变大，导致内存超过限制。trojan 本身也有7、8M ，最近比较忙，就没时间去优化它了。如果想交流的话，Q:

**Comment by chengsluo** [comment]
@nahddw nice~

**Comment by huanglei1926** [comment]
> 我把 trojan 编译成可以在 iPhone 上运行了，速度也挺快，但有一个问题，IPhone 上的 NetworkExtension Packet Tunnel 有一个严格限制，内存不能超过15M，一旦达到15M ，子进程就会被kill 掉，所以多刷几个网页就会掉线，具体讨论可以看 https://forums.developer.apple.com/thread/73148 。 Packet tunnel 本身内存就占用6M 左右，所以 trojan 内存不能超过8M ，而在 mac 上也能观察到， trojan 初始内存3、4M ， 运行时间长了，就会变大，最终会有22M 左右。我需要做哪些编译优化，或者代码优化，或者说应该怎么做快速释放内存，让 trojan 内存限制在8M 以下呢？

@boluoyu 您好,请问能指导一下如何编译出iOS版本吗?我这边也想自己弄一个,但是没有头绪.

**Comment by boluoyu** [comment]
> > 我把 trojan 编译成可以在 iPhone 上运行了，速度也挺快，但有一个问题，IPhone 上的 NetworkExtension Packet Tunnel 有一个严格限制，内存不能超过15M，一旦达到15M ，子进程就会被kill 掉，所以多刷几个网页就会掉线，具体讨论可以看 https://forums.developer.apple.com/thread/73148 。 Packet tunnel 本身内存就占用6M 左右，所以 trojan 内存不能超过8M ，而在 mac 上也能观察到， trojan 初始内存3、4M ， 运行时间长了，就会变大，最终会有22M 左右。我需要做哪些编译优化，或者代码优化，或者说应该怎么做快速释放内存，让 trojan 内存限制在8M 以下呢？
> 
> @boluoyu 您好,请问能指导一下如何编译出iOS版本吗?我这边也想自己弄一个,但是没有头绪.

@huanglei1926 如果想交流的话，Q:三四⑦⑧⑨零五⑨④
