### ISSUE TITLE
[BUG] local_addr的Bug

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#417]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
Welcome to trojan 1.14.1
Boost 1_71, OpenSSL 1.1.1f 31 Mar 2020

**Describe the bug**
配置：
`{`
`"run_type": "server",`
`"local_port": "443"`
`}`
如果用`"local_addr": ["0.0.0.0", "::0"]`那麼只監聽IPv6 ::0，不監聽IPv4 0.0.0.0。用`openssl s_client 127.0.0.1:443`返回`connect:errno=111`錯誤，用`openssl s_client [::1]:443`則返回成功。
如果用`local_addr": "0.0.0.0",`
`"local_addr": "::0"`則只監聽0.0.0.0，不監聽::0，用`openssl s_client 127.0.0.1:443`返回成功，用`openssl s_client [::1]:443`則返回錯誤。

**Environment**
Where are you running trojan? What is your proxy set up?
Ubuntu 20.04

**Comment by Chigusa0w0** [comment]
Misconfiguration is not a bug. Do not set multiple `local_addr`.
https://trojan-gfw.github.io/trojan/config
