### ISSUE TITLE
[Feature Request] 能否提供關閉TLS 1.3的選項？

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#418]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Describe the solution you'd like**
TLS 1.2通過Cipher（eg：TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256）設定金鑰交換算法，而TLS 1.3通過group設定金鑰交換算法。TLS 1.3預設允許DHE密鑰交換。有時用TLS 1.3反而比用TLS 1.2慢（相比V2+Nginx），尤其是看720P Video。
 https://tools.ietf.org/id/draft-ietf-tls-tls13-21.html#negotiated-groups
解決辦法：只能關閉TLS 1.3，或者修改`openssl.cnf`。
Trojan能否提供關閉TLS1.3的選項？

**Comment by Chigusa0w0** [comment]
See CONTRIBUTING.md
> Note that we are trying to keep this project as small as possible because it is the core of the trojan ecosystem and will be included in other projects. For a feature to be considered, make sure that the feature you request is really necessary to be included in this very project.

**Comment by GreaterFire** [comment]
@okudayukiko If you really want to disable TLS 1.3, you can use OpenSSL 1.1.0 instead of 1.1.1.

**Comment by okudayukiko** [comment]
> @okudayukiko If you really want to disable TLS 1.3, you can use OpenSSL 1.1.0 instead of 1.1.1.

剛剛試了下OpenSSL的TLS 1.3似乎不完善，OpenSSL TLS 1.3 server效能比OpenSSL TLS 1.2 server慢。使用OpenSSL的程式也是如此。解決辦法只能在`openssl.cnf`設定`MaxProtocol = TLSv1.2`
