### ISSUE TITLE
[Feature Request]support pac file

### ISSUE THREAD

**Issue by XenoAmess** [trojan-gfw/trojan#421]
as title.
suggest support pac file format like ss did.

**Comment by oasiscifr** [comment]
@XenoAmess Why

**Comment by XenoAmess** [comment]
> @XenoAmess Why

because useful.

**Comment by tomac4t** [comment]
Duplicate of #54

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/trojan/pull/54#issuecomment-453370302
