### ISSUE TITLE
[BUG]最近突然连不上，但是手机上shadowrockets还可以连上服务器，所以应该不是服务器设置的问题。配置文件也一直没变，检查了一下也没有错误配置，所以应该也不是配置文件的问题。客户端版本是1.15.1，操作系统是win10.

### ISSUE THREAD

**Issue by dongdongbi12** [trojan-gfw/trojan#423]
版本是1.15.1
操作系统是win10
一直显示0 received

**Comment by curiosity2** [comment]
请问问题解决了吗，为什么closed掉了，同样的问题，手机能用，windows不能用，之前还是好好的什么都没动就不行了
![捕获](https://user-images.githubusercontent.com/11660784/93037559-4e17a380-f675-11ea-9015-ebf840d02d53.PNG)
