### ISSUE TITLE
Add the domain verification

### ISSUE THREAD

**Issue by ruanhuilingscuec** [trojan-gfw/trojan#425]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
Using IP or other domain can also access port 443 services, leaking SSL certificate domain names.

**Is this problem relevant to what trojan should care about?**
yes, doing so can avoid crawler scans, like Censys.

**Describe the solution you'd like**
Determine whether the access domain is a bound domain name, return null if it is not. like nginx 444 status code.

**Comment by tomac4t** [comment]
Nginx return empty response (`return 444`) after TLS handshake ending. At this time, the client have received the TLS certificate and nothing could do with the server.

**Comment by Chigusa0w0** [comment]
Standard TLS handshake process must be kept to make Trojan's behaviour identical to other TLS services.
You may use third-party tools to do what you want, to behave harmless in the view of adversary.
