### ISSUE TITLE
[Feature Request]能否增加DTLS支持？

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#426]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Describe the solution you'd like**
能否增加DTLS支持？Shadowsocks可以支持TCP，UDP，TCP+UDP。現在Trojan比SS TCP+UDP慢。

**Comment by Chigusa0w0** [comment]
Please read RFC 6347 Section 3.

**Comment by tomac4t** [comment]
支持小众的协议无异于添加特征，这是违背本项目初衷的。支持 DTLS 不如支持主流趋势的 QUIC，见：https://github.com/trojan-gfw/trojan/issues/50
