### ISSUE TITLE
[BUG]trojan run segment faile in x86_64 android termux

### ISSUE THREAD

**Issue by zhoushiqian** [trojan-gfw/trojan#427]
**Trojan Version**
v1.9.0

**Describe the bug**
rojan run segment fault in x86_64 android termux

**To Reproduce**
1, 
dpkg -i boost_1.69.0_x86_64.deb
dpkg -i boost-dev_1.69.0_x86_64.deb
pkg install openssl
pkg install mariadb

2, 
change CMakeLists.txt
 option(ENABLE_MYSQL "Build with MySQL support" ON)
 if(ENABLE_MYSQL)
-    find_package(MySQL REQUIRED)
-    include_directories(${MYSQL_INCLUDE_DIR})
-    target_link_libraries(trojan ${MYSQL_LIBRARIES})
+    find_package(MariaDBClient REQUIRED)
+    include_directories(${MariaDBClient_INCLUDE_DIRS})
+    target_link_libraries(trojan ${MariaDBClient_LIBRARIES})
     add_definitions(-DENABLE_MYSQL)
3, mkdir build
    cd build
    cmake ..
    make
$ cmake ..
-- Found Boost: /data/data/com.termux/files/usr/include (found suitable version "1.69.0", minimum required is "1.66.0") found components:  system program_options
-- Configuring done
-- Generating done
-- Build files have been written to: /data/data/com.termux/files/home/code/trojan/build
$ make
Scanning dependencies of target trojan

[  5%] Building CXX object CMakeFiles/trojan.dir/src/core/authenticator.cpp.o

[ 11%] Building CXX object CMakeFiles/trojan.dir/src/core/config.cpp.o

[ 16%] Building CXX object CMakeFiles/trojan.dir/src/core/log.cpp.o
[ 22%] Building CXX object CMakeFiles/trojan.dir/src/core/service.cpp.o
[ 27%] Building CXX object CMakeFiles/trojan.dir/src/core/version.cpp.o
[ 33%] Building CXX object CMakeFiles/trojan.dir/src/main.cpp.o
[ 38%] Building CXX object CMakeFiles/trojan.dir/src/proto/socks5address.cpp.o
[ 44%] Building CXX object CMakeFiles/trojan.dir/src/proto/trojanrequest.cpp.o
[ 50%] Building CXX object CMakeFiles/trojan.dir/src/proto/udppacket.cpp.o
[ 55%] Building CXX object CMakeFiles/trojan.dir/src/session/clientsession.cpp.o
[ 61%] Building CXX object CMakeFiles/trojan.dir/src/session/forwardsession.cpp.o
[ 66%] Building CXX object CMakeFiles/trojan.dir/src/session/natsession.cpp.o
[ 72%] Building CXX object CMakeFiles/trojan.dir/src/session/serversession.cpp.o
[ 77%] Building CXX object CMakeFiles/trojan.dir/src/session/session.cpp.o
[ 83%] Building CXX object CMakeFiles/trojan.dir/src/session/udpforwardsession.cpp.o
[ 88%] Building CXX object CMakeFiles/trojan.dir/src/ssl/ssldefaults.cpp.o
[ 94%] Building CXX object CMakeFiles/trojan.dir/src/ssl/sslsession.cpp.o
[100%] Linking CXX executable trojan
[100%] Built target trojan

**Expected behavior**

**Logs**
$ ./trojan --help
[1]   Segmentation fault      ./trojan --help

[2]+  Stopped                 ./trojan --help

$ gdb ./trojan
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-android".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./trojan...
(No debugging symbols found in ./trojan)
(gdb) b main
Breakpoint 1 at 0x50600
(gdb) run
Starting program: /data/data/com.termux/files/home/code/trojan/build/trojan

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b267d3 in ?? () from /data/data/com.termux/files/usr/lib/libc++_shared.so
(gdb)

**Environment**
termux-0.7 x86_64

**Comment by ericlancebrown** [comment]
After a bit of searching, this is a Termux issue all the way from 0.5 to 0.8 or so. Happens with some builds. Try updating your Termux branch and see what happens. They're on 0.94 now :)

BTW, [have you tried Igniter](https://github.com/trojan-gfw/igniter)? It's a Trojan app for Android. Still under construction according to their repo, but worth a shot.
