### ISSUE TITLE
[Feature Request] 能否考虑增加限制单个用户带宽的功能

### ISSUE THREAD

**Issue by yl-miao** [trojan-gfw/trojan#428]
已经有了多用户，能否考虑增加限制单个用户带宽的功能呢？

**Comment by mianmianmi** [comment]
是的，这也是我想问的。

**Comment by Chigusa0w0** [comment]
Multi-user related component of Trojan is planned to re-architect. Currently we prefer not to do any minor improvement about that part. Ref. https://github.com/trojan-gfw/trojan/pull/384#issuecomment-611024670
