### ISSUE TITLE
[BUG][FATAL] fatal: SSL connection error: unable to get issuer certificate

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#430]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.15.1

**Describe the bug**
When I enabled One-Way TLS for MariaDB of my panel server according to [this tutor](https://mariadb.com/kb/en/securing-connections-for-client-and-server/). I can access my panel server from my trojan server by using mysql cli. However when I config the trojan to access the MySQL of panel server, I encountered the error `[FATAL] fatal: SSL connection error: self signed certificate`. When I switch my SSL certificate to let’s encrypt, the mysql cli also works well. However, I encountered `fatal: SSL connection error: unable to get issuer certificate` this time.

**To Reproduce**
1. Configure trojan and panel on panel server according to [自建梯子教程 --Trojan版本](https://trojan-tutor.github.io/2019/04/10/p41.html) and [Trojan-Panel配置](https://trojan-tutor.github.io/2019/06/08/p43.html).
2. Configure trojan on trojan server according to [自建梯子教程 --Trojan版本](https://trojan-tutor.github.io/2019/04/10/p41.html).
3. Enabling TLS on panel server according to [Securing Connections for Client and Server](https://mariadb.com/kb/en/securing-connections-for-client-and-server/) and [How to Secure Connections to MariaDB with SSL Encryption](https://www.alibabacloud.com/blog/how-to-secure-connections-to-mariadb-with-ssl-encryption_595079), but just one-way TLS because trojan does not implement  two-way TLS ([refer](https://github.com/trojan-gfw/trojan/issues/277)).
4. Connect to the MySQL of panel server from trojan using `mysql -u trojan -h panel.exam.com -p` work well.
5. Configure trojan as follows
```
    "mysql": {
        "enabled": true,
        "server_addr": "panel.exam.com",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "pass",
        "cafile": "/etc/mysql/certs/ca-cert.pem"
    }

```
encountered the error `[FATAL] fatal: SSL connection error: self signed certificate`.
6. replace ca-cert.pem, server-cert.pem, and server-key.pem with ca.cer, exam.com.cer, and exam.com.key.
7. Connect to the MySQL of panel server from trojan using `mysql -u trojan -h panel.exam.com -p` work well.
8. Configure trojan as follows
```
    "mysql": {
        "enabled": true,
        "server_addr": "panel.exam.com",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "pass",
        "cafile": "/etc/mysql/certs/ca.cer"
    }
```
encountered the error `fatal: SSL connection error: unable to get issuer certificate`.

**Expected behavior**
Trojan correctly connected to the MariaDB database of the panel server.

**Logs**
```
May 19 15:25:59 host trojan[8102]: [2020-05-19 15:25:59] [INFO] connecting to MySQL server exam.com:3306
May 19 15:25:59 host trojan[8102]: [2020-05-19 15:25:59] [FATAL] fatal: SSL connection error: unable to get issuer certificate
May 19 15:25:59 host trojan[8102]: [2020-05-19 15:25:59] [FATAL] exiting. . .
```

**Environment**
Ubuntu 20.04 LTS.

**Additional context**
Nothing.

**Comment by aurora-w** [comment]
Same problem, SSL handshake failed with www. …………………… certificate verify failed

**Comment by ghost** [comment]
Solved according to this QA: [MariaDB over SSL not working, "certificate verify failed"](https://stackoverflow.com/questions/42145925/mariadb-over-ssl-not-working-certificate-verify-failed), but I don't know why.
