### ISSUE TITLE
Wrong entity in Individual Contributor License Agreement

### ISSUE THREAD

**Issue by EHfive** [trojan-gfw/trojan#431]
>  https://cla-assistant.io/trojan-gfw/trojan
>
> SAP Individual Contributor License Agreement
>
> Thank you for your interest in contributing to open source software projects (“Projects”) made available by SAP SE or its affiliates (“SAP”). This Individual Contributor License Agreement (“Agreement”) sets out the terms governing any source code, object code, bug fixes, configuration changes, tools, specifications, documentation, data, materials, feedback, information or other works of authorship that you submit or have submitted, in any form and in any manner, to SAP in respect of any of the Projects (collectively “Contributions”). If you have any questions respecting this Agreement, please contact opensource@sap.com.
> ......

"SAP" or "SAP SE" should be replaced with "Trojan" or something else?

Nevermind if this project is under SAP SE.

**Comment by EHfive** [comment]
Archive: http://web.archive.org/web/20200520154919/https://cla-assistant.io/trojan-gfw/trojan

**Comment by GreaterFire** [comment]
Done. https://cla-assistant.io/trojan-gfw/trojan
