### ISSUE TITLE
Can you add database support for redis or memcached?

### ISSUE THREAD

**Issue by zdm2008** [trojan-gfw/trojan#432]
Can you add database support for redis or memcached?

Most proxy hosts have 1 core and 1 GB of memory, so it is not realistic to run Mysql.

Redis or memcached in the case of small data, it only needs the memory of 100KB to run it.

**Comment by zdm2008** [comment]
I suggest adding redis support, which leverages virtual memory and persists data to disk.

**Comment by Chigusa0w0** [comment]
#384

**Comment by DenrianWeiss** [comment]
@zdm2008 I have a forked version for this: DenrianWeiss/trojan-cluster, I would like to merge this feature back after authenticator reform.
