### ISSUE TITLE
[Feature Request]支持Nginx开启proxy_protocol

### ISSUE THREAD

**Issue by gitHubXss** [trojan-gfw/trojan#433]
根据 https://github.com/trojan-gfw/trojan/issues/131#issuecomment-536916385 的介绍，使用`ssl_preread on `后，会导致后端拿到的IP都是`127.0.0.1`，可否支持在Nginx开启`proxy_protocol on`

```
server {
    listen 443;

    ssl_preread on;
    proxy_pass $name;
    proxy_protocol on;
}
```

**Comment by Chigusa0w0** [comment]
#377

**Comment by wolfsilver** [comment]
> #377

不好意思，这两个不一样吧，#377说的是Trojan转发的协议不能添加，我说的是nginx转给Trojan的协议多了这种协议报头之后，就不能解析了

**Comment by wolfsilver** [comment]
> #377

`proxy_protocol on;` 这个会在tcp数据前添加一段报头标识来源，我理解，通过校验是否存在这种包头，然后过滤掉就可以了

https://developers.cloudflare.com/spectrum/getting-started/proxy-protocol/

**Comment by Chigusa0w0** [comment]
The same principle still applies. Since Trojan has no way to know which protocol it transfers, whether it supports PROXY protocol, and itself do not care about source IP, it will simply erase the data instead of insert it into the connection. This will render the support pointless.
To add support to PROXY protocol means special treat to a set of protocols. Which is not preferred in current design guideline.

**Comment by owendswang** [comment]
我觉得这只是个简单的Nginx设置问题，就是在Stream分发是开启proxy_protocol，然后在将数据分给trojan之前，将proxy_protocol加上的东西去掉就好了，就是多一步分发就可以了，具体如下：

```
stream {
    log_format basic '$remote_addr - $remote_user [$time_local] '
                     '$protocol $status $bytes_sent $bytes_received '
                     '$session_time';
    map $ssl_preread_server_name $backend {
        trojan6.domain.com unix:/run/nginx-trojan-stream.sock;
        trojan.domain.com unix:/run/nginx-trojan-stream.sock;
        default 127.0.0.1:443;
    }
    server {
        listen unix:/run/nginx-trojan-stream.sock proxy_protocol;
        proxy_pass 127.0.0.1:8443;
    }
    server {
        listen 0.0.0.0:443;
        listen [::]:443;
        proxy_pass $backend;
        ssl_preread on;
        proxy_protocol on;
    }
}

http {
    log_format combined '$proxy_protocol_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent"';
    server {
        listen 127.0.0.1:80 proxy_protocol;
        listen [::1]:443 ssl proxy_protocol;
        ...
    }
}
```

http的log_format中，原来的将原来的$remote_addr替换成$proxy_protocol_addr就成了。

stream中的第一个server就是为了接收带proxy_protocol的stream，然后发出不带proxy_protocol的stream给trojan。

另外，我用的是在Ubuntu 20.04上的Nginx v.1.18.0，来自官方apt源的。

**Comment by CoterJiesen** [comment]
测试了还是不行，有人成功过吗？
