### ISSUE TITLE
[BUG] macOS [FATAL] config.json(5)

### ISSUE THREAD

**Issue by gravityr** [trojan-gfw/trojan#434]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
trojan-1.15.1-macos.zip

**Describe the bug**
Download the trojan-1.15.1-macos.zip and modified remote address, password and leave others unchanged, click start.command and keep getting [fatal] config.json(5)

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?

**Additional context**

**Comment by Chigusa0w0** [comment]
Without further information, we cannot help you about that.

**Comment by HanMufu** [comment]
Yeah I have the same problem. It says [FATAL] fatal: config.json: cannot open file. I tried chmod but nothing happens.
