### ISSUE TITLE
如何共享给局域网

### ISSUE THREAD

**Issue by petsgre** [trojan-gfw/trojan#436]
我用手机设置开启了wifi代理 到trojan服务器的端口
192.xx.xx.xx:1080
但是无法联网

**Comment by Chigusa0w0** [comment]
Third party issue should not open in core project. As Trojan itself do not redirect any traffic.

**Comment by BirdSnail** [comment]
如果你正在使用**trojan windows**客户端，请确保使用的`conf.json`配置文件中本机地址属性不为`"local_addr": "127.0.0.1"`。
127.0.0.1意味着只会监听来自本机的流量，局域网中其他机器是无法访问的。

要想共享给局域网中其他机器，请指定本机地址为`"local_addr": "0.0.0.0"`
![image](https://user-images.githubusercontent.com/39896910/142347929-5b9c8547-7a9f-4927-b2e1-9b827352bf4e.png)
