### ISSUE TITLE
Where could I find the log file?

### ISSUE THREAD

**Issue by rfbzs** [trojan-gfw/trojan#438]
Actually I didn't see a log output path neither in the client config nor in the server config. I could only check the log output from the CLI. Does trojan not generate the log file by default?

**Comment by Chigusa0w0** [comment]
https://github.com/trojan-gfw/trojan/blob/master/src/main.cpp#L76

**Comment by yf-hk** [comment]
So, if not specified in the command line argument, will it disable log?
