### ISSUE TITLE
Does pre-built binary have TLS1.3?

### ISSUE THREAD

**Issue by testcaoy7** [trojan-gfw/trojan#44]
Does pre-built binary have TLS1.3?

I tried use "TLS13-AES-128-GCM-SHA256" in "cipher" and it did not work.

**Comment by GreaterFire** [comment]
Not in `1.7.0`, but will be in `1.8.0`.

Please be patient. Thank you.

**Comment by GreaterFire** [comment]
Also, it's not `TLS13-AES-128-GCM-SHA256`. Please look at [OpenSSLWiki](https://wiki.openssl.org/index.php/TLS1.3#Ciphersuites):

> OpenSSL has implemented support for five TLSv1.3 ciphersuites as follows:
>
> - TLS_AES_256_GCM_SHA384
> - TLS_CHACHA20_POLY1305_SHA256
> - TLS_AES_128_GCM_SHA256
> - TLS_AES_128_CCM_8_SHA256
> - TLS_AES_128_CCM_SHA256

**Comment by testcaoy7** [comment]
I see. Thank you.
