### ISSUE TITLE
[BUG] SSL handshake failed with x.x.x.x:443: invalid padding

### ISSUE THREAD

**Issue by shawwwn** [trojan-gfw/trojan#440]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.15.1

**Describe the bug**
I used **fixscrip**(or similar LD_PRELOAD hacks) to bind trojan server's outbound connection to a openvpn's tun interface.

I found that if I set `"verify": true`  in my client's config, I will have:
```
SSL handshake failed with x.x.x.x:443: invalid padding
```
on the client side.

On the server side it's:
```
SSL handshake failed: tlsv1 alert decrypt error
```

If I set `"verify": false`, everything works.

I initially thought fixscrip may have tampered with tcp packets, so I use Linux's network namespace to do this. Still getting the same result.

**Last thought**
Would you consider adding a "bind to upstream proxy/ip" feature?

**Comment by ericlancebrown** [comment]
Almost seems like your key pair is mismatched. Is your private key you used for decryption the key pair of your public key you used for encryption?

It could also be that your version of OpenSSL is wrong. Essentially, the error is that your key pair can't decrypt that first bit of data. Try looking at your .pem keys and make sure they're correct.

**Comment by shawwwn** [comment]
> Almost seems like your key pair is mismatched. Is your private key you used for decryption the key pair of your public key you used for encryption?

I use a self-issued CA(not sure if that's the issue) but my key pair matches.
Everything works fine when I'm not binding outbound traffic to another interface.
When I do, either by LD_PRELOAD hack or `netns`, I get an handshake error.

IIRC, simply forwarding traffic shouldn't break SSL.
Is this a bug or there is something I didn't know.

**Comment by ericlancebrown** [comment]
> > Almost seems like your key pair is mismatched. Is your private key you used for decryption the key pair of your public key you used for encryption?
> 
> I use a self-issued CA(not sure if that's the issue) but my key pair matches.
> Everything works fine when I'm not binding outbound traffic to another interface.
> When I do, either by LD_PRELOAD hack or `netns`, I get an handshake error.
> 
> IIRC, simply forwarding traffic shouldn't break SSL.
> Is this a bug or there is something I didn't know.
> 

Have you looked into configuring SNI?

It could be that you're having issues with your browser not being able to decipher your TLS certificates. This would allow you to have multiple certificates point to one address.

TLS 1.3 has a lot of issues with ipv4 exhaustion. Could be a workaround?

**Comment by shawwwn** [comment]
> Have you looked into configuring SNI?

No, I have not configured SNI.
The key pair I issued is with my ip address as the CN since I don't own a domain.

I took a peek at the source code and I don't think this is relevant since the outbound traffic is handled by another socket(so TLS of the inbound socket doesn't apply?).
I'm not a networking expert so I could be missing something thou.

**Comment by GreaterFire** [comment]
I need packet capture data to look into this.

**Comment by GreaterFire** [comment]
Please re-open this issue when you have this information.
