### ISSUE TITLE
[BUG] RemoteAddr填入ip地址，sni填入真实域名时会出现SSL handshake failed：Stream Truncated

### ISSUE THREAD

**Issue by maskedeken** [trojan-gfw/trojan#442]

**Comment by Chigusa0w0** [comment]
Please provide more information or we could not help you out.

**Comment by PHINEXLISY** [comment]
https是基于ssl跟http协议的，在配置sni之前，如果你的RemoteAddr填写了ip，就会去ip:443的地址进行握手，当然会失败。如果你的服务器有多个证书，你可以尝试使用nginx的ngx_stream_ssl_preread_module模块。详细配置可以手摸手

**Comment by ericlancebrown** [comment]
Seems to be a browser issue. It means the connection was closed abruptly. If you're using Chrome, Google believes this increases performance.

[Try the solution from this issue here!](https://github.com/boostorg/beast/issues/915#issuecomment-348503145)

**Comment by Chigusa0w0** [comment]
Closed due to inactivity. You may reopen when further information is available.
