### ISSUE TITLE
强制443 tls nginx在trojan前难道不可行吗?

### ISSUE THREAD

**Issue by herozzm** [trojan-gfw/trojan#443]
我需要访问正常网站 https://a.com 这个网站是一个正常使用的网站
同时在这个域名下面搭建了trojan，想使用 https://a.com/torjan 来链接trojan使用，这样可以做到逼真的伪装，这个需求到底要如何实现？
如果换成trojan在nginx前，是否能承载web真实网站访问的压力？然后如何将https://a.com/ 分流到nginx？而https://a.com/torjan 留在trojan来处理？

**Comment by ericlancebrown** [comment]
**Server.json**
```JSON
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "password1",
        "password2"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/path/to/certificate.crt",
        "key": "/path/to/private.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "cafile":
    }
}
```

**Notice these bits of code?**
```JSON
"local_addr": "0.0.0.0",
"local_port": 443,
"reuse_port": false,
```

Essentially, Trojan is connecting to 443 from any local IP address (Meaning of local_addr 0.0.0.0). Normally, with "reuse_port: true", you can run connections from say 192.168.1.2:443 as well as 192.168.1.3:443, 192.168.1.4:443, etc. That would be thanks to "SO_REUSEPORT support that is a build default. 

I suggest tinkering with that setting first and seeing if you get anywhere.

**Comment by herozzm** [comment]
> **Server.json**
> 
> ```json
> {
>     "run_type": "server",
>     "local_addr": "0.0.0.0",
>     "local_port": 443,
>     "remote_addr": "127.0.0.1",
>     "remote_port": 80,
>     "password": [
>         "password1",
>         "password2"
>     ],
>     "log_level": 1,
>     "ssl": {
>         "cert": "/path/to/certificate.crt",
>         "key": "/path/to/private.key",
>         "key_password": "",
>         "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
>         "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
>         "prefer_server_cipher": true,
>         "alpn": [
>             "http/1.1"
>         ],
>         "alpn_port_override": {
>             "h2": 81
>         },
>         "reuse_session": true,
>         "session_ticket": false,
>         "session_timeout": 600,
>         "plain_http_response": "",
>         "curves": "",
>         "dhparam": ""
>     },
>     "tcp": {
>         "prefer_ipv4": false,
>         "no_delay": true,
>         "keep_alive": true,
>         "reuse_port": false,
>         "fast_open": false,
>         "fast_open_qlen": 20
>     },
>     "mysql": {
>         "enabled": false,
>         "server_addr": "127.0.0.1",
>         "server_port": 3306,
>         "database": "trojan",
>         "username": "trojan",
>         "password": "",
>         "cafile":
>     }
> }
> ```
> 
> **Notice these bits of code?**
> 
> ```json
> "local_addr": "0.0.0.0",
> "local_port": 443,
> "reuse_port": false,
> ```
> 
> Essentially, Trojan is connecting to 443 from any local IP address (Meaning of local_addr 0.0.0.0). Normally, with "reuse_port: true", you can run connections from say 192.168.1.2:443 as well as 192.168.1.3:443, 192.168.1.4:443, etc. That would be thanks to "SO_REUSEPORT support that is a build default.
> 
> I suggest tinkering with that setting first and seeing if you get anywhere.

关键点是要做https://a.com/torjan 和https://a.com 分流，这个才是关键，你的配置中没有涉及这块的分流

**Comment by zhangzhhz** [comment]
为什么要 Nginx 在前面？trojan 在前面是
 trojan 的根本宗旨。
https://trojan-tutor.github.io/2019/04/10/p41.html#%E9%85%8D%E7%BD%AEnginx

一定要 Nginx 在前面，看一下前几天一个 issue 里的方法：https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html

**Comment by herozzm** [comment]
> 为什么要 Nginx 在前面？trojan 在前面是
> trojan 的根本宗旨。
> https://trojan-tutor.github.io/2019/04/10/p41.html#%E9%85%8D%E7%BD%AEnginx
> 
> 一定要 Nginx 在前面，看一下前几天一个 issue 里的方法：

https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html
有正式网站生产环境，nginx在web方面的能力久经考验，trojan就做好自己本分工作即可，何须去接管443所有的流量？

**Comment by herozzm** [comment]
> 为什么要 Nginx 在前面？trojan 在前面是
> trojan 的根本宗旨。
> https://trojan-tutor.github.io/2019/04/10/p41.html#%E9%85%8D%E7%BD%AEnginx
> 
> 一定要 Nginx 在前面，看一下前几天一个 issue 里的方法：
> https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html

好吧就算trojan在前，如果实现这个分流的需求呢？将https://a.com/ 分流到nginx？而https://a.com/torjan 留在trojan来处理？

**Comment by DenrianWeiss** [comment]
@herozzm trojan does not work in this way, however you can use sni based method (not recommended)

**Comment by zhangzhhz** [comment]
参考我回复中第一个联结做分流。

**Comment by herozzm** [comment]
> 参考我回复中第一个联结做分流。

我的理解是这样，不知道对不对：
同样的https://a.com 443链接，如果是trojian客户端发起则停留在trojan处理，否则将这个443请求转到nginx，根本无需用path路径来区分？

**Comment by zhangzhhz** [comment]
> > 参考我回复中第一个联结做分流。
> 
> 我的理解是这样，不知道对不对：
> 同样的https://a.com 443链接，如果是trojian客户端发起则停留在trojan处理，否则将这个443请求转到nginx，根本无需用path路径来区分？

对的，不需要路径来区分。

**Comment by herozzm** [comment]
> > > 参考我回复中第一个联结做分流。
> > 
> > 
> > 我的理解是这样，不知道对不对：
> > 同样的https://a.com 443链接，如果是trojian客户端发起则停留在trojan处理，否则将这个443请求转到nginx，根本无需用path路径来区分？
> 
> 对的，不需要路径来区分。

谢谢，已解决

**Comment by alongL** [comment]
看起来trojan-go像是支持这种模式的：trojan-go可以放在nginx后面
https://p4gefau1t.github.io/trojan-go/advance/websocket/
