### ISSUE TITLE
 openwrt x86 无法使用 trojan linux 64

### ISSUE THREAD

**Issue by herozzm** [trojan-gfw/trojan#444]
```bash
/usr/bin/trojan/trojan -v
-ash: /usr/bin/trojan/trojan: not found
```

**Comment by ericlancebrown** [comment]
Are you sure that it was installed into /usr/bin/trojan?

Obviously the error is that it cant find trojan. Whats your ls -l of that folder?

**Comment by herozzm** [comment]
> Are you sure that it was installed into /usr/bin/trojan?
> 
> Obviously the error is that it cant find trojan. Whats your ls -l of that folder?

 `/usr/bin/trojan/trojan`  Binary file exists

**Comment by tomac4t** [comment]
@herozzm 你需要打上补丁并编译后才能使用：https://github.com/trojan-gfw/openwrt-trojan

**Comment by wongsyrone** [comment]
源于底层libc不同，需要重新编译

**Comment by herozzm** [comment]
> @herozzm 你需要打上补丁并编译后才能使用（你的架构都不一样哇）：https://github.com/trojan-gfw/openwrt-trojan
> 源于底层libc不同，需要重新编译

编译了2晚上都失败了，因为编译要的时间实在太长了，为什么不直接放各种编译好的版本呢
