### ISSUE TITLE
问个问题，这个项目部分或完全禁用C++流么？

### ISSUE THREAD

**Issue by expnkx** [trojan-gfw/trojan#445]
想做个简单的调查

**Comment by LimiQS** [comment]
We don't have any guideline on C++ Stream. But maintainers think it would be better if there are stream-like syntax for C++ socket.

**Comment by expnkx** [comment]
> We don't have any guideline on C++ Stream. But maintainers think it would be better if there are stream-like syntax for C++ socket.

Really? Then try fast_io!
https://github.com/expnkx/fast_io
