### ISSUE TITLE
[Feature Request] I have multiple domain and one server whitch contain multiple IP，How should i deploy？

### ISSUE THREAD

**Issue by xdkaka** [trojan-gfw/trojan#447]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GreaterFire** [comment]
You can bind trojan to a particular IP address by using a specific IP address (or domain name) in the `local_addr` field.
