### ISSUE TITLE
Trojan-GFW doesnt work

### ISSUE THREAD

**Issue by LexterS999** [trojan-gfw/trojan#448]
Don't know why but it doesn't work for my client in Turkmenistan. It's worked few months ago but not now. I'm doing all things like it must be and ping goes to the server (he is using trojan-gt5). But when he connected and try to use as proxy traffic doesn't pass. What can be done in such way? How to bypass trojan-gfw, and he is also asking me why it doesn't bypass QoS throttling at all? On official page named that it helps but don't.

不知道为什么，我在土库曼斯坦的客户无法使用。几个月前还能用，但现在不行了。我做了所有必须做的事情，ping到服务器（他使用木马-gt5）。但当他连接并尝试使用代理流量不通过。这种情况下该怎么办呢？如何绕过trojan-gfw，他还问我为什么不绕过QoS节流？在官方页面上名为有用，但不要。

**Comment by GreaterFire** [comment]
> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

**Comment by LexterS999** [comment]
It's working by the way. But doesn't connect. That's why I'm asking you about that.
