### ISSUE TITLE
[Feature Request] SSL KeyLog File

### ISSUE THREAD

**Issue by wongsyrone** [trojan-gfw/trojan#45]
从openssl 1.1.1开始，带了一个SSLKEYLOGFILE功能，生成的文件可以配置给wireshark用来debug，或者是蛋疼看TLS payload。可以参照 https://github.com/openssl/openssl/commit/4bf73e9f86804cfe98b03accfc2dd7cb98e018d6

**Comment by GreaterFire** [comment]
Proposal accepted.

**Comment by wongsyrone** [comment]
我弄了一个windows下可以解密TLS流量辅助脚本：https://github.com/wongsyrone/decrypt-ssl

**Comment by GreaterFire** [comment]
Functionality added on the `dev` branch.
