### ISSUE TITLE
[Issue Request] Would you tell me how to use the parameter "plain_http_response"?

### ISSUE THREAD

**Issue by tomxiang1** [trojan-gfw/trojan#451]
Would you tell me how to use the parameter "plain_http_response"? How to configure it to behave more like nginx server when non-TLS access occurs.

**Comment by GreaterFire** [comment]
This field points to a file, which will be sent to the client (in plaintext) when the server receives a plain HTTP request. You can form an HTTP response in the file.

**Comment by tomxiang1** [comment]
> This field points to a file, which will be sent to the client (in plaintext) when the server receives a plain HTTP request. You can form an HTTP response in the file.

I don't know how to simulate the text returned by nginx, can it be forwarded to the real nginx for processing?

**Comment by GreaterFire** [comment]
No. Not trivially possible.
