### ISSUE TITLE
[Feature Request] 能否提供Disable TLS 1.3选项？

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#452]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**
有些低价单核VPS本来Hash计算就慢，导致使用AEAD+Hash加密的性能较慢，只能用非AEAD+HMAC。以我的单核VPS为例，使用TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256的性能就比TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256慢，使用OpenSSH AES128-GCM-HMAC-SHA256-ETM也比OpenSSH AES128-CBC-HMAC-SHA256-ETM慢很多。

**Describe alternatives you've considered**

**Additional context**

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/trojan/issues/418#issuecomment-627371867

**Comment by okudayukiko** [comment]
> [#418 (comment)](https://github.com/trojan-gfw/trojan/issues/418#issuecomment-627371867)

现在的Linux发行版都是OpenSSL 1.1.1，不提供OpenSSL 1.1.0。

**Comment by GreaterFire** [comment]
@okudayukiko Compile OpenSSL 1.1.0 yourself.

**Comment by okudayukiko** [comment]
更新：
OS: Ubuntu 20.04
Trojan version: Install from APT-GET
1、`/etc/trojan/config.json`
`"cipher_tls13": "NULL"`和`"cipher_tls13": "NONE"`無效
2、`/lib/systemd/system/trojan.service`
`Environment=MaxProtocol=TLSv1.2`無效
3、`/etc/ssl/openssl.cnf`
`ssl_conf = ssl_sect`
`[ ssl_sect ]`
`system_default = system_default_sect`
`[ system_default_sect ]`
`MaxProtocol = TLSv1.2`
無效
在單核VPS和雙核VPS上，TLS-AEAD-SHA2性能都比TLS-AES-CBC-SHA2差，雖然表面上用`openssl speed -evp aes-128-gcm`和`openssl speed -evp aes-128-cbc`跑分，AES-GCM比AES-CBC快。
在手機上，TLS-AES-CBC-SHA2比TLS-AES-GCM-SHA2、TLS-CHACHA20-POLY1305-SHA2省電。
手動編譯很麻煩，自動編譯要寫script。

**Comment by okudayukiko** [comment]
我使用AnyConnect和Igniter發現，單核VPS使用AES-CBC-SHA2速度最快。AEAD-SHA2要進行兩輪計算。單核VPS，Ubuntu 20.04，看YouTube 1080P時，VPS的CPU使用率就高達50%。
`/etc/ocserv/ocserv.conf`
`#Ocserv不使用AES-GCM的設定`
`tls-priorities = "NONE:+VERS-TLS1.0:+VERS-TLS1.1:+VERS-TLS1.2:+VERS-DTLS1.0:+VERS-DTLS1.2:+SIGN-ALL:+ECDHE-RSA:+ECDHE-ECDSA:+AES-128-CBC:+AES-256-CBC:+SHA1:+SHA256:+SHA384:+CURVE-SECP256R1"`

**Comment by Chigusa0w0** [comment]
#415 #418 #452 DO NOT trash post multiple issues for an already discussed topic.
