### ISSUE TITLE
Misleading in docs/overview.md

### ISSUE THREAD

**Issue by wxh06** [trojan-gfw/trojan#453]
`strong encryption` and `However, trojan implements the direct opposite: ... HTTPS` in [`docs/overview.md`](https://github.com/trojan-gfw/trojan/blob/master/docs/overview.md) (https://trojan-gfw.github.io/trojan/overview) are in contradiction -- HTTPS (TLS) is also strong encrypted.

#### References
- https://www.youtube.com/watch?v=ePxnyW7iju4&t=14m13s
- https://www.idleleo.com/02/4064.html#title-0

**Comment by GreaterFire** [comment]
The "direct opposite" is relative to "random obfuscation", not "strong encryption".

**Comment by wxh06** [comment]
Yes, I know what you means. But it really causes misunderstanding.

**Comment by GreaterFire** [comment]
I don't think it's a hell of a big deal. If people are misled, it's their problem. I think the meaning here is obvious enough.
