### ISSUE TITLE
error with  boost 1.73.0

### ISSUE THREAD

**Issue by icebluey** [trojan-gfw/trojan#454]
-- The CXX compiler identification is GNU 8.4.0
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Boost: /opt/boost/lib/cmake/Boost-1.73.0/BoostConfig.cmake (found suitable version "1.73.0", minimum required is "1.66.0") found components: system program_options 
-- Found OpenSSL: /opt/openssl/lib/libcrypto.a (found suitable version "1.1.1g", minimum required is "1.1.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /trojan
Scanning dependencies of target trojan
[  5%] Building CXX object CMakeFiles/trojan.dir/src/core/authenticator.cpp.o
[ 11%] Building CXX object CMakeFiles/trojan.dir/src/core/config.cpp.o
In file included from /opt/boost/include/boost/property_tree/json_parser/detail/parser.hpp:7,
                 from /opt/boost/include/boost/property_tree/json_parser/detail/read.hpp:13,
                 from /opt/boost/include/boost/property_tree/json_parser.hpp:16,
                 from /trojan/src/core/config.cpp:24:
/opt/boost/include/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^

**Comment by GreaterFire** [comment]
Firstly, this is not an error, just a compiler note. Secondly, from the look of this message, this is a problem of the Boost library.

**Comment by wongsyrone** [comment]
Should be fixed via https://github.com/boostorg/property_tree/commit/d1c8825a45a0717e1ad79583d3283b0e5e32831e

**Comment by xhronos** [comment]
Please note that fix did only go into the development branch but cannot be found in boost release 1.74.

https://github.com/boostorg/property_tree/blob/bdfe275d172ac30bc5e89a6375a5a64dea20b3c0/include/boost/property_tree/json_parser/detail/parser.hpp#L217
