### ISSUE TITLE
假如访问http://xxxx.com:443 Trojan会直接中断连接，能否做跳转?

### ISSUE THREAD

**Issue by 82kg** [trojan-gfw/trojan#456]
假如访问http://xxxx.com:443 Trojan会直接中断连接，能否做跳转?
Trojan-go 里，好像可以将这个TCP连接代理到本地127.0.0.1:1234上运行的HTTPS服务，返回一个展示400 Bad Reqeust的HTTP页面

**Comment by GreaterFire** [comment]
https://trojan-gfw.github.io/trojan/config
See `plain_http_response`.

**Comment by 82kg** [comment]
> https://trojan-gfw.github.io/trojan/config
> See `plain_http_response`.

thank you
