### ISSUE TITLE
[Feature Request] trojan-panel: add units for quota

### ISSUE THREAD

**Issue by github-young** [trojan-gfw/trojan#458]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
It is not quite like a problem. It is more like a suggestion.
The quota in trojan-panel is in the unit of bytes, which is not convenient since most of the time we arrange quota for a user in several GBs.
Thus if I want to set 1GB, I have to input `` 1024*1024*1024 = 1073741824 `` in the screenshot below. It is too tedious.

**Is this problem relevant to what trojan should care about?**
It is a suggestion relevant to trojan-panel, not trojan. But trojan-panel has nowhere to file an issue.

**Describe the solution you'd like**
Add units for quotes in trojan-panel. For example, MB, GB

**Describe alternatives you've considered**
None.

**Additional context**
![IMG_20200616_022001](https://user-images.githubusercontent.com/19162282/84692116-eb304680-af77-11ea-8aa1-99e430c26d5b.jpg)

**Comment by GreaterFire** [comment]
Get used to it. Also technically `trojan-panel` is just my hobby project and will not be supported by the Trojan-GFW team.

**Comment by GreaterFire** [comment]
Actually, if you really want it you can implement it yourself. PR is welcomed though.

**Comment by github-young** [comment]
> 
> 
> Actually, if you really want it you can implement it yourself. PR is welcomed though.

Thank you. I just change the units (from original B to MB as I think the latter is more frequently used).
And I made a [PR](https://github.com/trojan-gfw/trojan-panel/pull/20), but it is up to you whether to accept such a naive change.
Preview:
![图片](https://user-images.githubusercontent.com/19162282/84793203-6b61b500-b027-11ea-9fee-2d901dba25fa.png)
