### ISSUE TITLE
[Feature Request]Add example openSSL script for cert generating to wiki

### ISSUE THREAD

**Issue by PaleNeutron** [trojan-gfw/trojan#459]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
I have tried the following command to generate the cert used by trojan, but got error:
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
```
While I changed to generating the cert with cerbot signed by letsencrypt, erverything worked.

Due to the leak of verbose ssl problem log, I am not sure where the problem is.

**Describe the solution you'd like**
So what is the right way to generate cert? Can you add it to config wiki?

**Comment by Chigusa0w0** [comment]
Self-signed certificate is not recommended for trojan.
