### ISSUE TITLE
Building instructions should be clear and on the git project page

### ISSUE THREAD

**Issue by ASmith-** [trojan-gfw/trojan#46]
The trojan build instructions should be clear and on the git project page

Combing through the readme.md and multiple other folders doesn't even add any further how-to on this. Attempting cmake, ./configure results in zip, nada. Fill in the current missing build instruction blanks in the git project page and add the build-compile instructions in a tiny .txt file for the main directory folder.

**Comment by GreaterFire** [comment]
For a detailed build instruction please visit the [documentation](https://trojan-gfw.github.io/trojan/build).

Do you mean I should put it in my main README.md?

**Comment by ASmith-** [comment]
Sure, why not? CLI commands, folder name if the builder needs to shift over into a certain folder just to compile the source on this.

For Debian users, there's a error in your documentation:

For Debian users, run sudo apt -y install build-essential cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev to install all the necessary dependencies.

Needs to be changed too

For Debian users, run sudo apt install build-essential cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev -y to install all the necessary dependencies.

**Comment by ASmith-** [comment]
This project could prove helpful with the Retroshare anonymous, encrypted communication and file sharing applications global network with Asian Retroshare users of the Regular nodes. Retroshare's hidden nodes use the Tor and I2P networks, however both Retroshare Regular and Hidden nodes can fully use and support Socks5 proxys. 

If your'e interested in this, I can supply you with established Retroshare public keys which you'd need to use the application and a invite to chat, correspond with the projects Developers.

References to the Retroshare Project Application
Readme Docs
https://retroshare.readthedocs.io/en/latest/
Retroshare Developers Blog
https://retroshareteam.wordpress.com/
Retroshare Github Project
https://github.com/RetroShare/RetroShare
Retroshare IRC Chatroom
OFTC weber.oftc.net #retroshare
Retroshare PPA Ubuntu/Mint packages
https://launchpad.net/~retroshare/+archive/ubuntu/unstable/+packages

**Comment by GreaterFire** [comment]
> Sure, why not? CLI commands, folder name if the builder needs to shift over into a certain folder just to compile the source on this.

I prefer to keep the build instructions inside the documentation. That's my personal choice. It keeps things clean in readme.

> For Debian users, there's a error in your documentation:
>
> For Debian users, run sudo apt -y install build-essential cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev to install all the necessary dependencies.
>
> Needs to be changed too
>
> For Debian users, run sudo apt install build-essential cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev -y to install all the necessary dependencies.

It's not an error. Both of these work.

> If your'e interested in this, I can supply you with established Retroshare public keys which you'd need to use the application and a invite to chat, correspond with the projects Developers.

I don't currently have time to look at this. But feel free to use trojan's code in your project, as long as you comply to GPLv3 license.

Thank you for your issue.
