### ISSUE TITLE
能不能加入限制多设备同时使用的功能

### ISSUE THREAD

**Issue by Mao-jiawei** [trojan-gfw/trojan#460]
能不能加入限制多设备同时使用的功能  像session 那样验证

**Comment by xhrm** [comment]
期待~Trojan在断开连接后会向数据库写入流量信息，由此可以判定当前是否已经链接未断开，从而再次链接进行限制

**Comment by GreaterFire** [comment]
No plans now or in the future to implement this.

**Comment by GreaterFire** [comment]
@xhrm This is way harder than you think and requires modifications to the protocol, which I **absolutely** don't want to do.
