### ISSUE TITLE
I am packaging trojan for Fedora system

### ISSUE THREAD

**Issue by karuboniru** [trojan-gfw/trojan#462]
Since the templates don't fit the topic, I am not going to use the issue templates.

## What did you do?
In short, I am trying to package this to Fedora release, and this will be finished soon, package is approved, and next thing to do is mostly QA testing and so on.

## Any benefit?
- Trojan users on Fedora will be able to install trojan in one simple command `sudo dnf install trojan` once this package process has completed.
- Trojan shipped with Fedora release will be updated with the system itself, scripts will handle replacing files and restarting services.

## Did you make any changes to the built software?
Mostly, no. I didn't touch the source code. But I **do changed the shipped configuration file**, all default cipher lists are set to `PROFILE=SYSTEM`, this is due to [Fedora's Crypto Policy][1]. This should not add the risk of being identified, since all TLS related software shipped with Fedora are using the same crypto list including browsers and CURL.
After all, users can easily roll back this change if needed.

## Will this be available to EPEL?
Maybe I will do package for EPEL 8 (CentOS 8/RHEL 8), but never for EPEL 7. This is due to a OpenSSL version issue and can never be solved if not use static linking, which is forbidden in a shipped-with-system package.

## What do you want Trojan Team to do?
Mostly nothing, I will track Red Hat bugzilla and forward bugs with Trojan itself here and make packages update to date. But if in case of a urgent security issue (such as CVEs), if possible, I want to know the issue quickly, that I can push fixes faster.

And when this package is available in Fedora's repositories, I will add a `installation guide for Fedora` part in [the wiki][2].

[1]: https://fedoraproject.org/wiki/Changes/CryptoPolicy
[2]: https://github.com/trojan-gfw/trojan/wiki/Binary-&-Package-Distributions

**Comment by GreaterFire** [comment]
Thanks. We appreciate your effort to packaging trojan for Fedora! That said, you are not required to notify us of your action regarding your package.
