### ISSUE TITLE
【求助】我的trojan可以正常运行，但是无法转发流量，我实在是摸不着头脑了，特此请教大神们。

### ISSUE THREAD

**Issue by RayLiu-1217** [trojan-gfw/trojan#463]
我的日志：
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1237 disconnected, 0 bytes recei
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [ERROR] 110.231.147.157:1242 SSL handshake failed: Conn
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1242 disconnected, 0 bytes recei
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [ERROR] 110.231.147.157:1241 SSL handshake failed: Conn
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1241 disconnected, 0 bytes recei
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [ERROR] 110.231.147.157:1239 SSL handshake failed: Conn
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1239 disconnected, 0 bytes recei
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [ERROR] 110.231.147.157:1243 SSL handshake failed: Conn
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1243 disconnected, 0 bytes recei
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [ERROR] 110.231.147.157:1244 SSL handshake failed: Conn
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1244 disconnected, 0 bytes recei
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [ERROR] 110.231.147.157:1246 SSL handshake failed: Conn
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1246 disconnected, 0 bytes recei
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [ERROR] 110.231.147.157:1240 SSL handshake failed: Conn
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1240 disconnected, 0 bytes recei
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [ERROR] 110.231.147.157:1245 SSL handshake failed: Conn
Jun 21 13:43:52 racknerd-a328ad trojan[24608]: [2020-06-21 13:43:52] [INFO] 110.231.147.157:1245 disconnected, 0 bytes recei
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [ERROR] 110.231.147.157:1271 SSL handshake failed: Conn
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [INFO] 110.231.147.157:1271 disconnected, 0 bytes recei
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [ERROR] 110.231.147.157:1280 SSL handshake failed: Conn
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [INFO] 110.231.147.157:1280 disconnected, 0 bytes recei
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [ERROR] 110.231.147.157:1277 SSL handshake failed: Conn
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [INFO] 110.231.147.157:1277 disconnected, 0 bytes recei
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [ERROR] 110.231.147.157:1268 SSL handshake failed: Conn
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [INFO] 110.231.147.157:1268 disconnected, 0 bytes recei
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [ERROR] 110.231.147.157:1286 SSL handshake failed: Conn
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [INFO] 110.231.147.157:1286 disconnected, 0 bytes recei
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [ERROR] 110.231.147.157:1274 SSL handshake failed: Conn
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [INFO] 110.231.147.157:1274 disconnected, 0 bytes recei
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [ERROR] 110.231.147.157:1283 SSL handshake failed: Conn
Jun 21 13:44:18 racknerd-a328ad trojan[24608]: [2020-06-21 13:44:18] [INFO] 110.231.147.157:1283 disconnected, 0 bytes recei
我的配置：
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "mima",
        "mima"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/root/.acme.sh/xxxx.cer",
        "key": "/root/.acme.sh/xxxx.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "key": "",
        "cert": "",
        "ca": ""
    }
}
我已经进行的具体操作：
我已经关闭了防火墙等可能阻止trojan正常运作的程序
时间也校准了，证书也申请成功了，域名也是没问题的

**Comment by RayLiu-1217** [comment]
My trojan is not working

**Comment by Alvin9999** [comment]
反馈：我的也用不了，试了很多次了。换了新ip+新域名+一键脚本，搭建几次后都无法访问网站。奇怪的是域名伪装可以成功打开，端口也是正常的。

**Comment by Alvin9999** [comment]
用最新客户端+服务端也不行

**Comment by RayLiu-1217** [comment]
根据我对日志的分析，主要问题是与ssl握手失败引起的，但是我不知道如何解决，我已经尝试了Google上的许多办法，但仍然徒劳。

**Comment by GreaterFire** [comment]
https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md

**Comment by jinwyp** [comment]
试试我的脚本 没问题啊 https://github.com/jinwyp/one_click_script

**Comment by okudayukiko** [comment]
刪掉
`"alpn_port_override": {`
`"h2": 81`
`},`
變更
`"cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384",`
不要用太簡單的密碼。
IE/Edge由於使用SOCKS4協定，用Trojan會出現TLS憑證錯誤問題或者意外斷線問題，解決方法：用Privoxy將SOCKS5 PROXY轉換為HTTP PROXY+HTTPS PROXY。Chrome預設用的是SOCKS4協定，得用「chrome --proxy-server="socks5://localhost:1080"」命令啟動Chrome。

**Comment by alongL** [comment]
明显是证书有问题，导致一直handshake failed。
好像是要用 fullchain.cer那个文件。
"cert": "/root/.acme.sh/fullchain.cer",

**Comment by crackwei** [comment]
> 刪掉 `"alpn_port_override": {` `"h2": 81` `},` 變更 `"cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384",` 不要用太簡單的密碼。 IE/Edge由於使用SOCKS4協定，用Trojan會出現TLS憑證錯誤問題或者意外斷線問題，解決方法：用Privoxy將SOCKS5 PROXY轉換為HTTP PROXY+HTTPS PROXY。Chrome預設用的是SOCKS4協定，得用「chrome --proxy-server="socks5://localhost:1080"」命令啟動Chrome。

解决我的问题，感谢！
