### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wdweidao** [trojan-gfw/trojan#464]
**Trojan Version**
1.16.0,1.15.1

**Describe the bug**
run client in ubuntu with "sudo ./trojan",it return error message

**Environment**
ubuntu18.04,desktop is Mate

![screenshot_2](https://user-images.githubusercontent.com/44543137/85267717-31b9ff80-b4a8-11ea-9f32-20750b01c25a.png)

**Comment by karuboniru** [comment]
Please check your config file: 
- listen in lower ports (a.k.a. `port number` below 1024) need privilege, you can set `setcap 'cap_net_bind_service=+ep' /path/to/trojan` to enable this for trojan. (Or use systemd to start trojan)
- `no such file or directory` is that you set wrong path to your certificate file, double check your config file.
