### ISSUE TITLE
[BUG] cannot see video in a website

### ISSUE THREAD

**Issue by terryyizhong** [trojan-gfw/trojan#466]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
tested in latest 1.16.0

**Describe the bug**
canot see video in a website called https://tomovhxtv.vhx.tv/start-here/videos/tf-lesson-001
but I can see the video throw a socket5 proxy of my company line.

**To Reproduce**
1. Go to https://tomovhxtv.vhx.tv/start-here/videos/tf-lesson-001
4. See error (cannot see the video)

**Expected behavior**
see the video in the website

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
win10, throw switchy omega of chrome

**Additional context**

**Comment by Chigusa0w0** [comment]
Any log?

**Comment by terryyizhong** [comment]
[2020-06-23 16:31:21] [INFO] 127.0.0.1:9862 requested connection to tomovhxtv.vhx.tv:443
[2020-06-23 16:31:21] [INFO] 127.0.0.1:9863 requested connection to tomovhxtv.vhx.tv:443
[2020-06-23 16:31:21] [INFO] 127.0.0.1:9864 requested connection to d2wy8f7a9ursnm.cloudfront.net:443
[2020-06-23 16:31:21] [INFO] 127.0.0.1:9865 requested connection to use.typekit.net:443
[2020-06-23 16:31:21] [INFO] 127.0.0.1:9870 requested connection to mtalk.google.com:443
[2020-06-23 16:31:24] [INFO] 127.0.0.1:9848 disconnected, 3120 bytes received, 581 bytes sent, lasted for 17 seconds
[2020-06-23 16:31:24] [INFO] 127.0.0.1:9874 requested connection to api.mousegesturesapi.com:443
[2020-06-23 16:31:24] [INFO] 127.0.0.1:9876 requested connection to cdn.vhx.tv:443
[2020-06-23 16:31:24] [INFO] 127.0.0.1:9878 requested connection to sessions.bugsnag.com:443
[2020-06-23 16:31:24] [INFO] 127.0.0.1:9879 requested connection to embed.vhx.tv:443
[2020-06-23 16:31:24] [INFO] 127.0.0.1:9882 requested connection to www.google-analytics.com:443
[2020-06-23 16:31:24] [INFO] 127.0.0.1:9883 requested connection to stats.g.doubleclick.net:443
[2020-06-23 16:31:25] [INFO] 127.0.0.1:9886 requested connection to www.google-analytics.com:443
[2020-06-23 16:31:25] [INFO] 127.0.0.1:9887 requested connection to stats.g.doubleclick.net:443
[2020-06-23 16:31:27] [INFO] 127.0.0.1:9894 requested connection to collector.vhx.tv:443
[2020-06-23 16:31:32] [INFO] 127.0.0.1:9882 disconnected, 0 bytes received, 517 bytes sent, lasted for 8 seconds
[2020-06-23 16:31:33] [INFO] 127.0.0.1:9887 disconnected, 0 bytes received, 517 bytes sent, lasted for 8 seconds
[2020-06-23 16:31:33] [INFO] 127.0.0.1:9899 requested connection to www.google.com:443

**Comment by terryyizhong** [comment]
The other part of the website shows correctly except the video.
By the way, I can only use trojan successfully by turn the verify of ssl to false in config.

**Comment by Chigusa0w0** [comment]
I don't see anything unusual from your client-side log, except that two tracker site seems to be blocked. You may need to provide server side log.

**Comment by terryyizhong** [comment]
OK thanks for your informatin. I'll post server side log later

**Comment by terryyizhong** [comment]
hi, I try to find logs on the server, but don't know where it is.
Could you tell me how to get the server side log?
Thanks

**Comment by Chigusa0w0** [comment]
`journalctl -f -u trojan`

**Comment by clerfun** [comment]
i have this problem，and gmail is closed , google translate is closed , I suspect it is DNS pollution

**Comment by terryyizhong** [comment]
I cannot see anything about trojan on the server side when I open the website by using journalctl -f -u trojan
I think this is the only log I got when I open the website: by using command journalctl -f:

Jun 28 08:28:20 shouer sshd[19692]: Invalid user liuyang from 221.12.107.26 port 34313
Jun 28 08:28:20 shouer sshd[19692]: input_userauth_request: invalid user liuyang [preauth]
Jun 28 08:28:20 shouer sshd[19692]: Received disconnect from 221.12.107.26 port 34313:11: Bye Bye [preauth]
Jun 28 08:28:20 shouer sshd[19692]: Disconnected from 221.12.107.26 port 34313 [preauth]

**Comment by terryyizhong** [comment]
this is the tail of command: journalctl -f -u trojan
Jun 24 03:34:07 shouer trojan[821]: [2020-06-24 03:34:07] [INFO] 183.233.96.135:7518 requested connection to best.d
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7521 authenticated as 21219c1c
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7521 requested connection to tracke
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7522 authenticated as 21219c1c
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7522 requested connection to discor
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7507 authenticated as 21219c1c
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7507 requested connection to tr.zam
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7519 authenticated as 21219c1c
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7519 requested connection to status
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7559 authenticated as 21219c1c
Jun 24 03:34:08 shouer trojan[821]: [2020-06-24 03:34:08] [INFO] 183.233.96.135:7559 requested connection to discor
Jun 24 03:34:09 shouer trojan[821]: [2020-06-24 03:34:09] [INFO] 183.233.96.135:7554 authenticated as 21219c1c
Jun 24 03:34:09 shouer trojan[821]: [2020-06-24 03:34:09] [INFO] 183.233.96.135:7554 requested connection to secure
Jun 24 03:34:09 shouer trojan[821]: [2020-06-24 03:34:09] [INFO] 183.233.96.135:7522 disconnected, 212 bytes receiv
Jun 24 03:34:10 shouer trojan[821]: [2020-06-24 03:34:10] [INFO] 183.233.96.135:6488 disconnected, 241 bytes receiv
Jun 24 03:34:10 shouer trojan[821]: [2020-06-24 03:34:10] [INFO] 183.233.96.135:7646 authenticated as 21219c1c
Jun 24 03:34:10 shouer trojan[821]: [2020-06-24 03:34:10] [INFO] 183.233.96.135:7646 requested connection to mb.moa
Jun 24 03:34:12 shouer trojan[821]: [2020-06-24 03:34:12] [INFO] 183.233.96.135:7674 authenticated as 21219c1c
Jun 24 03:34:12 shouer trojan[821]: [2020-06-24 03:34:12] [INFO] 183.233.96.135:7674 requested connection to endpoi
Jun 24 03:34:12 shouer trojan[821]: [2020-06-24 03:34:12] [INFO] 183.233.96.135:7433 disconnected, 1149 bytes recei
Jun 24 03:34:12 shouer trojan[821]: [2020-06-24 03:34:12] [INFO] 183.233.96.135:7735 authenticated as 21219c1c
Jun 28 03:22:08 shouer trojan[821]: [2020-06-28 03:22:08] [INFO] 36.36.201.99:15077 authenticated as 21219c1c
Jun 28 03:22:08 shouer trojan[821]: [2020-06-28 03:22:08] [INFO] 36.36.201.99:15077 requested connection to media.discordapp.net:443
Jun 28 03:23:50 shouer trojan[821]: [2020-06-28 03:23:50] [INFO] 36.36.201.99:16158 authenticated as 21219c1c
Jun 28 03:23:50 shouer trojan[821]: [2020-06-28 03:23:50] [INFO] 36.36.201.99:16158 requested connection to clients4.google.com:443
Jun 28 03:27:50 shouer trojan[821]: [2020-06-28 03:27:50] [INFO] 36.36.201.99:16158 disconnected, 8555 bytes received, 2140 bytes sent, lasted for 241 seconds
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21823 authenticated as 21219c1c
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21823 requested connection to www.google.com:443
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21824 authenticated as 21219c1c
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21824 requested connection to www.google.com:443
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21829 authenticated as 21219c1c
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21829 requested connection to www.google.com:443
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21829 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21838 authenticated as 21219c1c
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21838 requested connection to www.google.com:443
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:21838 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
Jun 28 03:28:38 shouer trojan[821]: [2020-06-28 03:28:38] [INFO] 36.36.201.99:12393 disconnected, 186050 bytes received, 10550 bytes sent, lasted for 4652 seconds
Jun 28 03:28:39 shouer trojan[821]: [2020-06-28 03:28:39] [INFO] 36.36.201.99:21844 authenticated as 21219c1c
Jun 28 03:28:39 shouer trojan[821]: [2020-06-28 03:28:39] [INFO] 36.36.201.99:21844 requested connection to fonts.gstatic.com:443
Jun 28 03:28:42 shouer trojan[821]: [2020-06-28 03:28:42] [INFO] 36.36.201.99:60788 disconnected, 4589 bytes received, 945 bytes sent, lasted for 5842 seconds
Jun 28 03:28:42 shouer trojan[821]: [2020-06-28 03:28:42] [INFO] 36.36.201.99:21823 disconnected, 3643 bytes received, 1292 bytes sent, lasted for 4 seconds
Jun 28 03:28:42 shouer trojan[821]: [2020-06-28 03:28:42] [INFO] 36.36.201.99:21824 disconnected, 48220 bytes received, 2542 bytes sent, lasted for 4 seconds
Jun 28 03:28:42 shouer trojan[821]: [2020-06-28 03:28:42] [INFO] 36.36.201.99:15049 disconnected, 2438 bytes received, 6678 bytes sent, lasted for 396 seconds
Jun 28 03:28:42 shouer trojan[821]: [2020-06-28 03:28:42] [INFO] 36.36.201.99:15077 disconnected, 239650 bytes received, 2090 bytes sent, lasted for 395 seconds
Jun 28 03:28:42 shouer trojan[821]: [2020-06-28 03:28:42] [INFO] 36.36.201.99:21844 disconnected, 2745 bytes received, 581 bytes sent, lasted for 3 seconds
Jun 28 03:57:27 shouer trojan[821]: [2020-06-28 03:57:27] [WARN] 184.105.247.194:7528 not trojan request, connecting to 127.0.0.1:80
Jun 28 03:57:27 shouer trojan[821]: [2020-06-28 03:57:27] [INFO] 184.105.247.194:7528 disconnected, 32442 bytes received, 39 bytes sent, lasted for 2 seconds

**Comment by Chigusa0w0** [comment]
Your log still contains no diagnostic information. You may need to revisit the website and provide ___both___ client/server log of the ___same time range___, be sure it is long enough to cover the full life cycle of the session.
I will close your issue for the time being, as the situation you were run into to is too rare to be considered as a defect in Trojan. But, once you have the above mentioned log, you may reopen it if it's necessary.
PS. You can try paste your log in some pastebin website like [this one](https://pastebin.com) or [this one](https://gist.github.com) and share the link, for clarity of the issue body
