### ISSUE TITLE
about lib-trojan-gfw

### ISSUE THREAD

**Issue by mingzhizhiren** [trojan-gfw/trojan#467]
- [x ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
I want a function like "lib-trojan-gfw" to integrate trojan into my project without having to move the source code

**Comment by Chigusa0w0** [comment]
See [CONTRIBUTING.md](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md)
