### ISSUE TITLE
[Feature Request] add http proxy support (aka mixed-mode)

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [trojan-gfw/trojan#469]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

ref : https://github.com/trojan-gfw/trojan/issues/122#issuecomment-517938411
> HTTP proxy server is non-trivial to implement, it's close to implementing a full HTTP server.

Hi~ @GreaterFire 

i think it can easy implement , we only need to analysis the first package first 3 byte, if find `\x05\x01\x00` it is a socks5, if find `CON` it's http connect ,if find P/G/H/D/O/T on first byte, it's other http request.

i has impl a socks5 proxy loadbalancer on this: https://github.com/Lyoko-Jeremie/Socks5BalancerAsio
and i impl the first pack analysis function on there https://github.com/Lyoko-Jeremie/Socks5BalancerAsio/blob/fbe3a78cc7f00b5a5f15bcdee1639a8d80eb6f0f/src/FirstPackAnalyzer.cpp#L149

and then, we can use Boost.Beast to parse http request like i do it on there : https://github.com/Lyoko-Jeremie/Socks5BalancerAsio/blob/fbe3a78cc7f00b5a5f15bcdee1639a8d80eb6f0f/src/FirstPackAnalyzer.cpp#L244

and the last, if it's `connect` request, trim the http header, send a `"HTTP/1.1 200 Connection Established\r\n\r\n"` response to client , like there: https://github.com/Lyoko-Jeremie/Socks5BalancerAsio/blob/fbe3a78cc7f00b5a5f15bcdee1639a8d80eb6f0f/src/FirstPackAnalyzer.cpp#L316
 then or it's other http connect, only relay all the data to server like socks5 .    
the remote target info can be find from http request header.

you can find the theory on there https://imququ.com/post/web-proxy.html

**Comment by GreaterFire** [comment]
@Lyoko-Jeremie I don't see any reason of implementing HTTP proxy. There are loads of tools converting SOCKS5 proxies to HTTP proxies. See CONTRIBUTING.md.

**Comment by okudayukiko** [comment]
Shadowsocks就是把SOCKS5 PROXY轉換為HTTP PROXY+HTTPS PROXY，用了Privoxy程式。IE/Edge（EdgeHTML）使用SOCKS4。

**Comment by Lyoko-Jeremie** [comment]
@okudayukiko 不觉得Privoxy很麻烦么

**Comment by cbdyzj** [comment]
> @okudayukiko 不觉得Privoxy很麻烦么

Hi, you can simply write a small script of dozens of lines to do the conversion, here's a node sample

```javascript
// socks_to_http.mjs

import { createServer } from 'http'
// https://www.npmjs.com/package/socks
import { SocksClient } from 'socks'

export default class ProxyServer {

    constructor(options) {
        this.options = options
    }

    handleConnect(request, requestSocket, head) {
        let proxySocket

        requestSocket.on('error', (err) => {
            console.error(`${err.message}`)
            if (proxySocket) {
                proxySocket.destroy(err)
            }
        })

        const requestUrl = new URL(`http://${request.url}`)
        const host = requestUrl.hostname
        const port = requestUrl.port | 0

        SocksClient.createConnection({
            proxy: this.options.proxy,
            destination: { host, port, },
            command: 'connect',
        }).then((conn) => {            
            proxySocket = conn.socket

            proxySocket.on('error', (err) => {
                console.error(`${err.message}`)
                requestSocket.destroy(err)
            })

            proxySocket.write(head)
            requestSocket.write(`HTTP/${request.httpVersion} 200 Connection established\r\n\r\n`)

            proxySocket.pipe(requestSocket)
            requestSocket.pipe(proxySocket)
        }).catch((err) => {
            console.error(`${err.message}`)
            requestSocket.write(`HTTP/${request.httpVersion} 500 Connection error\r\n\r\n`)
        })
    }

    start(callback) {
        const server = createServer()
        server.addListener('connect', this.handleConnect.bind(this))
        server.listen(this.options.port, this.options.host, callback)
    }
}

const options = {
    proxy: {
        ipaddress: '127.0.0.1',
        port: 9080,
        type: 5,
    },
    host: '0.0.0.0',
    port: 8080,
}

new ProxyServer(options).start(() => {
    console.log(`Serving on ${options.host}:${options.port}`)
})
```

**Comment by Lyoko-Jeremie** [comment]
@cbdyzj Thank you very much ~


but i was implement a full-functional tools for resolve socks2http & loadbalance require .
see this: https://github.com/Socks5Balancer/Socks5BalancerAsio

---
BTW, nodejs ( JS ) implement have major performance problem , i created it for a demo of above tools.
see this : https://github.com/Socks5Balancer/Socks5Balancer

**Comment by Hzqi** [comment]
> > @okudayukiko 不觉得Privoxy很麻烦么
> 
> Hi, you can simply write a small script of dozens of lines to do the conversion, here's a node sample
> 
> ```js
> // socks_to_http.mjs
> 
> import { createServer } from 'http'
> // https://www.npmjs.com/package/socks
> import { SocksClient } from 'socks'
> 
> export default class ProxyServer {
> 
>     constructor(options) {
>         this.options = options
>     }
> 
>     handleConnect(request, requestSocket, head) {
>         let proxySocket
> 
>         requestSocket.on('error', (err) => {
>             console.error(`${err.message}`)
>             if (proxySocket) {
>                 proxySocket.destroy(err)
>             }
>         })
> 
>         const requestUrl = new URL(`http://${request.url}`)
>         const host = requestUrl.hostname
>         const port = requestUrl.port | 0
> 
>         SocksClient.createConnection({
>             proxy: this.options.proxy,
>             destination: { host, port, },
>             command: 'connect',
>         }).then((conn) => {            
>             proxySocket = conn.socket
> 
>             proxySocket.on('error', (err) => {
>                 console.error(`${err.message}`)
>                 requestSocket.destroy(err)
>             })
> 
>             proxySocket.write(head)
>             requestSocket.write(`HTTP/${request.httpVersion} 200 Connection established\r\n\r\n`)
> 
>             proxySocket.pipe(requestSocket)
>             requestSocket.pipe(proxySocket)
>         }).catch((err) => {
>             console.error(`${err.message}`)
>             requestSocket.write(`HTTP/${request.httpVersion} 500 Connection error\r\n\r\n`)
>         })
>     }
> 
>     start(callback) {
>         const server = createServer()
>         server.addListener('connect', this.handleConnect.bind(this))
>         server.listen(this.options.port, this.options.host, callback)
>     }
> }
> 
> const options = {
>     proxy: {
>         ipaddress: '127.0.0.1',
>         port: 9080,
>         type: 5,
>     },
>     host: '0.0.0.0',
>     port: 8080,
> }
> 
> new ProxyServer(options).start(() => {
>     console.log(`Serving on ${options.host}:${options.port}`)
> })
> ```

Thank you! your code help me~
