### ISSUE TITLE
[ERROR] 127.0.0.1:$bignumber unknown protocol

### ISSUE THREAD

**Issue by AbsolutelyLudicrous** [trojan-gfw/trojan#47]
Trojan version 1.9.0 on both server and client.

I can't get Trojan to send any data, all connections to the local proxy running on 127.0.0.1:1080 fail with "unknown protocol". No output appears on the server's end.

If it matters at all, the server is running in a FreeBSD jail behind a reverse proxy, all traffic is routed host -> reverse-proxy -> jail.

**Comment by GreaterFire** [comment]
How did you use the proxy on the local side? Did you connect to `127.0.0.1:1080` with `HTTP` proxy? You should have connected using `SOCKS5` protocol.

**Comment by AbsolutelyLudicrous** [comment]
Welp, that would be my problem. I had it set up as an HTTP proxy, not a SOCKS proxy. Sorry about that.
