### ISSUE TITLE
[BUG] 终端下连github失败

### ISSUE THREAD

**Issue by dengcb** [trojan-gfw/trojan#471]
**Trojan Version**
1.16.0

**Describe the bug**
使用socks5协议失败，使用socks5h协议成功

**To Reproduce**
1. 下载配置并运行trojan
2. git配置为下面时，取回0数据，失败
```
[http "https://github.com"]
        proxy = socks5://127.0.0.1:1080
[https "https://github.com"]
        proxy = socks5://127.0.0.1:1080
```
3. 修改socks5为socks5h，成功

**Expected behavior**
是否应该默认就支持带域名的，因为很多proxy设置是只有socks5的

**Logs**
`[INFO] 127.0.0.1:64633 requested connection to 192.30.253.112:443` 失败
`[INFO] 127.0.0.1:64633 requested connection to github.com(192.30.253.112):443` 成功

**Environment**
Server: Ubuntu 18.04
Client: Mac OS 10.15.5

**Comment by GreaterFire** [comment]
@dengcb This should be DNS pollution of github.com. You have to redirect DNS (aka use socks5h) in this case. There is no workaround.

**Comment by dengcb** [comment]
我之前用ss的socks5的时候没有这个问题，换成trojan的socks5就不行了。
有没有办法用远程DNS解析避免污染呢？配置里有这个支持选项吗？
我的谷歌开发工具貌似也是因为这个问题更新不了。
而且我并不知道开发工具连的网址是什么，都没法通过hosts来写死解析。

**Comment by Chigusa0w0** [comment]
Trojan will use system-wide DNS settings. You may need to use tools to secure your local DNS from pollution, which is a good practice as DNS may, more or less, leak your identity and information.

**Comment by dengcb** [comment]
> Trojan will use system-wide DNS settings. You may need to use tools to secure your local DNS from pollution, which is a good practice as DNS may, more or less, leak your identity and information.

我总觉得还是哪里不对
你看，我用chrome打开google，是这样
`[2020-06-30 00:29:59] [INFO] 127.0.0.1:55580 requested connection to id.google.com:443`
谷歌开发工具更新就是这样
`[2020-06-30 00:32:13] [INFO] 127.0.0.1:55656 requested connection to 203.208.46.146:443`

我已经把dns server设置为1.1.1.1了啊，应该没有dns污染问题了
但是用ip的就不行，用域名的就可以，让我觉得是chrome做对了什么

**Comment by wangzhankun** [comment]
请问Ubuntu下开启Trojan之后如何全局代理呢？是使用下面的命令吗？
```bash
export http_proxy=socks5://127.0.0.1:8849
export https_proxy=socks5://127.0.0.1:8849
```

**Comment by dengcb** [comment]
> 请问Ubuntu下开启Trojan之后如何全局代理呢？是使用下面的命令吗？
> 
> ```shell
> export http_proxy=socks5://127.0.0.1:8849
> export https_proxy=socks5://127.0.0.1:8849
> ```

我是用
```
export all_proxy=socks5h://127.0.0.1:8849
```

**Comment by dengcb** [comment]
我的问题就是，用socks5协议，Android Studio、iTerm下git checkout github，都是取回0字节数据。

难道就只有我一个人遇到？

**Comment by Chigusa0w0** [comment]
One possible explanation is that these websites use some kind of GeoDNS technology, so cross-regional access may causes some uncertain connectivity issues. Whether the DNS is resolved by the proxy in these software is entirely determined by your configuration (the `h` in `socks5h`). Trojan should not intercept the user's DNS request without explict permission.

**Comment by dengcb** [comment]
> One possible explanation is that these websites use some kind of GeoDNS technology, so cross-regional access may causes some uncertain connectivity issues. Whether the DNS is resolved by the proxy in these software is entirely determined by your configuration (the `h` in `socks5h`). Trojan should not intercept the user's DNS request without explict permission.

两个反例，第一，chrome访问一切正常，第二，切换Trojan前用ss的socks5，一切正常

**Comment by Chigusa0w0** [comment]
Unfortunately, the information you provided is not enough for us to confirm whether this problem is a defect in Trojan's implementation, and no one else has reported a similar problem so far. Therefore, we will temporarily close this issue. If you have more technical information available, please reopen this issue.

**Comment by okudayukiko** [comment]
用Privoxy將SOCKS5代理轉換為HTTP代理+HTTPS代理。Windows代理設定（inetcpl.cpl）只支援SOCKS4。

**Comment by wangzhankun** [comment]
> > 请问Ubuntu下开启Trojan之后如何全局代理呢？是使用下面的命令吗？
> > ```shell
> > export http_proxy=socks5://127.0.0.1:8849
> > export https_proxy=socks5://127.0.0.1:8849
> > ```
> 
> 我是用
> 
> ```
> export all_proxy=socks5h://127.0.0.1:8849
> ```
请问有人能提供完整的在终端下连接外网的教程吗？不知道要怎么处理。这里的命令都不可以用。
