### ISSUE TITLE
Can't send pictures when proxy always on

### ISSUE THREAD

**Issue by wunifeng** [trojan-gfw/trojan#472]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.16.0

**Describe the bug**
when Server on windows, open the proxy on the iphone use app 'shadowrocket', set porxy 'always on', can't send any picture on Wechat.
the Windows version is 2012R2.

**To Reproduce**
1. open shadowrocket on iphone
2. set shadowrocket proxy 'always on'
3. open wechat 
4. send a picture and you will See it

**Expected behavior**
the pictures are sent normally 

**Logs**
nothing on log

**Environment**
server : Windows server version is 2012R2.
Client : shadowrocket on iphone 11
 What is your proxy set up?-- as normal

**Comment by Chigusa0w0** [comment]
This should be a connectivity / Tencent firewall issue. If you believe this issue is caused by related software, you shall open an issue in Shadowrocket first unless its developers confirm it is Trojan's problem.

**Comment by GreaterFire** [comment]
@wunifeng Shadowrocket has its own implementation of Trojan protocol and is not maintained by Trojan-GFW.
