### ISSUE TITLE
[Feature Request]服务器测速功能

### ISSUE THREAD

**Issue by paradiseduo** [trojan-gfw/trojan#477]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**
可以增加专门的服务器测速功能吗？比如我传一个url参数，测试连接到这个url的延时，大概像这样：
```
> trojan --config xxx.json --url https://www.google.com
www.google.com - Connected - 30.621ms
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Chigusa0w0** [comment]
This is not a protocol feature. You should ask UI/Manager projects for this feature.
