### ISSUE TITLE
[BUG] https网站不安全错误，导致网页功能错误或者页面样式缺失

### ISSUE THREAD

**Issue by dengcb** [trojan-gfw/trojan#481]
**Trojan Version**
1.16.0

**Describe the bug**
访问 https://www.abc.com 时，页面显示不全，有些ajax的功能失败。其中www.abc.com 就是配置里的网站。

**Logs**
`jquery.min.js?36d360cd991fb4e12f6c741b352575a4:2 Mixed Content: The page at 'https://www.abc.com/...' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.abc.com/...'. This request has been blocked; the content must be served over HTTPS.`

**Environment**
Server: Ubuntu 18.04
Client: Mac OS 10.15.5

**Additional context**
我想，应该是先通过443访问Trojan，然后去80端口取回数据，然后第二次取数据就直接去80端口了，然后就报错。

**Comment by dengcb** [comment]
多说一句。

其中 https://www.abc.com 之前是能正常访问的，启用Trojan后，就没法通过https访问了。

**Comment by Chigusa0w0** [comment]
Cannot reproduce on my deployment.

**Comment by Chigusa0w0** [comment]
Can you post your config file? You may redact as needed.

**Comment by tomxiang1** [comment]
nginx增加以下配置看能不能解决
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; ";

**Comment by onlyzf** [comment]
This site can’t provide a secure connectiongithub.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Comment by dengcb** [comment]
我发现是html里的base自动生成的是http的，所以我把base给删掉了，暂时正常了。

还有一些其他地方，自动使用了http，慢慢改吧。

多说一句，之前ss的obfs，也是443跳转80，没有发生任何问题。

**Comment by atrandys** [comment]
最近做了一个一键trojan+wordpress脚本，trojan在前做https服务器转发网站流量到nginx，https://www.atrandys.com/2020/233.html
