### ISSUE TITLE
[BUG]Trojan流量貌似可以被运营商识别

### ISSUE THREAD

**Issue by linkedsh0926** [trojan-gfw/trojan#483]
![TIM截图20200717111058](https://user-images.githubusercontent.com/34146285/87744573-60fd2b80-c81e-11ea-9426-6af695fd286d.png)
大家心里有个数

**Comment by GreaterFire** [comment]
@linkedsh0926 Please don't post unverified screenshots.

**Comment by linkedsh0926** [comment]
@GreaterFire 不信拉倒

**Comment by wongsyrone** [comment]
对对对，你说的都对

**Comment by demo0102** [comment]
无中生有的消息，你传播一遍等于你也有责任？

**Comment by chen3feng** [comment]
深圳联通 -> BWH 已被封，不过原因未知，因为还用了 WireGuard。

**Comment by wongsyrone** [comment]
> 因为还用了 WireGuard。

WireGuard 本身特征明显，因此被封也说得通

**Comment by okudayukiko** [comment]
如果是Aliyun發出的信件，那並不奇怪。

**Comment by finch-yihe** [comment]
我的被封了，各位，你们的呢？？？

**Comment by linkedsh0926** [comment]
> 我的被封了，各位，你们的呢？？？

早就不用trojan啦，现在在用v2ray+cdn，目前为止还很稳

**Comment by finch-yihe** [comment]
> > 我的被封了，各位，你们的呢？？？
> 
> 早就不用trojan啦，现在在用v2ray+cdn，目前为止还很稳

能教教我怎么搭建吗? 我没研究过v2ray的，毕竟不是c++写的。

**Comment by linkedsh0926** [comment]
> > > 我的被封了，各位，你们的呢？？？
> > 
> > 
> > 早就不用trojan啦，现在在用v2ray+cdn，目前为止还很稳
> 
> 能教教我怎么搭建吗? 我没研究过v2ray的，毕竟不是c++写的。

https://github.com/bannedbook/fanqiang/blob/master/v2ss/V2Ray%E4%B9%8BTLS%2BWebSocket%2BNginx%2BCDN%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95.md

**Comment by finch-yihe** [comment]
> > > > 我的被封了，各位，你们的呢？？？
> > > 
> > > 
> > > 早就不用trojan啦，现在在用v2ray+cdn，目前为止还很稳
> > 
> > 
> > 能教教我怎么搭建吗? 我没研究过v2ray的，毕竟不是c++写的。
> 
> https://github.com/bannedbook/fanqiang/blob/master/v2ss/V2Ray%E4%B9%8BTLS%2BWebSocket%2BNginx%2BCDN%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95.md

谢谢

**Comment by changeflyhigh** [comment]
#ICMP相关
#windows默认ping包大小可关闭proxy端口
-A INPUT -p icmp -m icmp --icmp-type 8 -m length --length 60 -m recent --remove --name PROXYOPEN --mask 255.255.255.255 --rsource -j ACCEPT
#linux默认ping包大小可关闭proxy端口
-A INPUT -p icmp -m icmp --icmp-type 8 -m length --length 84 -m recent --remove --name PROXYOPEN --mask 255.255.255.255 --rsource -j ACCEPT
#接收 1996 大小的包可以打开proxy端口34567
-A INPUT -p icmp -m icmp --icmp-type 8 -m length --length 2024 -m recent --set --name PROXYOPEN --mask 255.255.255.255 --rsource -j ACCEPT

-A INPUT -p tcp -m multiport --dports 34567 -m conntrack --ctstate NEW -m recent --update --seconds 1800 --name PROXYOPEN --mask 255.255.255.255 --rsource -j ACCEPT
-A INPUT -p icmp -j icmp-flood
