### ISSUE TITLE
[BUG] Automatically download generate_204 file instead of accessing the website

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#484]
Environment: Windows

When I wish to access blocked websites, the browser automatically downloaded a file named generate_204 instead of accessing the websites.

**Comment by Chigusa0w0** [comment]
What browser are you using. Can you upload the downloaded file?

**Comment by ghost** [comment]
> What browser are you using. Can you upload the downloaded file?

I was using Chrome. [](url)

It is a text file with the following hexadecimal content:

0000 1e04 0000 0000 0000 0100 0010 0000
0300 0000 6400 0400 1000 0000 0500 0040
0000 0600 0040 0000 0004 0800 0000 0000
000f 0001 0000 0807 0000 0000 0000 0000
0000 0000 01

**Comment by ghost** [comment]
[generate_204.txt](https://github.com/trojan-gfw/trojan/files/4941254/generate_204.txt)

**Comment by Just1n** [comment]
facing the same issue.

**Comment by Just1n** [comment]
By using MySQL authenticator.

**Comment by Chigusa0w0** [comment]
Can you visit HTTP sites like example.com? Does similar issue appears when you visiting non-Google sites? Can you post your configuration file?

**Comment by Just1n** [comment]
Hi @Chigusa0w0 I fixed it by changing the password format to "username:password".
The reason why I saw the 'generate_204' issue was, I used the wrong password. And it only happened when I was trying to open google.com, not sure if it's a trojan bug, or it might be something that related to my Chrome extension.

**Comment by Chigusa0w0** [comment]
@Just1n This is a known defect of third-party software. See #311 if you are interested in the detail.

**Comment by Just1n** [comment]
Great, thank you @Chigusa0w0

**Comment by wang-changze** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chigusa0w0"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上9:18
收件人: "trojan-gfw/trojan"<trojan@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [trojan-gfw/trojan] [BUG] Automatically download generate_204 file instead of accessing the website (#484)





 
Closed #484.
