### ISSUE TITLE
脚本安装失败

### ISSUE THREAD

**Issue by mengyyy** [trojan-gfw/trojan#487]
**Trojan Version**
1.6.0

**Describe the bug**
安装包解压失败 
tar: Refusing to read archive contents from terminal (missing -f option?)

**To Reproduce**
bash -c "$(wget -O- https://raw.githubusercontent.com/trojan-gfw/trojan-quickstart/master/trojan-quickstart.sh)"

**Expected behavior**
成功安装

**Logs**
Downloading trojan 1.16.0...
######################################################################## 100.0%
Unpacking trojan 1.16.0...
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Environment**
Ubuntu 16.04 x64

**Additional context**

** FIx**
Use tar but not tar.xz 
https://files.catbox.moe/fyvekj.tar

**Comment by Chigusa0w0** [comment]
`sudo apt-get install xz-utils`

**Comment by okudayukiko** [comment]
script可以考慮增加安裝xz功能。我直接用`apt install trojan`。
`apt install xz-utils`
`yum install xz`
