### ISSUE TITLE
[Feature Request] 增加SOCKS5僅代理TCP的功能：proxytcponly

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#489]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**
部分VPS限制了UDP下載速度。在電腦上用`ssh -D 1080 user@host`看視頻比Trojan快。在Android手機上用Firefox看視頻比YouTube App、Niconico App快。就是那種有時看視頻很快有時看視頻很慢（分辨率很低）的現象。YouTube用了QUIC協定。Google Play Store好像也用了UDP。
注意：直接用`ssh -D 1080 user@host`會被中國防火牆阻斷，用`ssh -v -D 1080 user@host`顯示`corrupted MAC`。用`ssh -D 1080 -o Ciphers=aes128-gcm@openssh.com user@host`和`ssh -D 1080 -o Ciphers=aes128-ctr -o MACs=hmac-sha2-256-etm@openssh.com`則可以用SSH SOCKS5代理。SSH SOCKS5代理是TCP only代理。
V2Ray的SOCKS5預設只代理TCP。
https://www.v2ray.com/chapter_02/protocols/socks.html
Trojan增加SOCKS5僅代理TCP的選項，預設為false。
Igniter也應該增加選項。

**Describe alternatives you've considered**

**Additional context**

**Comment by Chigusa0w0** [comment]
Trojan core don't care what it transmits. It's YOUR responsibility to configure TCP-only proxy. For example, `proxifier` will never send UDP to Trojan, because it doesn't have such ability.
But on the other hand, Igniter uses VPN interface and distinguish protocols internally. You should ask Igniter team for the feature, not here.

**Comment by okudayukiko** [comment]
Trojan伺服器端或用戶端只協商一個TLS Cipher，看視頻緩慢的問題解決。
`{`
`"run_type": "server",`（或`"run_type": "client",`）
`"ssl": {`
`"cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256",`
`"cipher_tls13": "TLS_AES_128_GCM_SHA256"`
`}`
`}`
SSH用戶端使用以下命令（手動指定一個Cipher）也可以用SSH SOCKS5：`ssh -D 1080 -o Ciphers=aes128-gcm@openssh.com user@host`、`ssh -D 1080 -o Ciphers=chacha20-poly1305@openssh.com user@host`、`ssh -D 1080 -o Ciphers=aes128-ctr -o MACs=hmac-sha2-256-etm@openssh.com user@host`。直接用`ssh -D 1080 user@host`會被中國防火牆阻斷（預設情況下SSH客戶端會協商多個Ciphers）。
