### ISSUE TITLE
All the tls 1.2 **RSA** ciphers are not working properly

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#491]
- [ok ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.

1.16.0 directly downloaded from  github release page

**Describe the bug**

***All the tls 1.2 **RSA** ciphers are not working properly***

I set ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384 in my config file.

{
    "run_type": "server",
    "local_addr": "::",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "xxx",
        "xxx"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "hidden",
        "key": "hidden",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
        	"h2",
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 82
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": true,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "key": "",
        "cert": "",
        "ca": ""
    }
}

but according to ssllab.com ***only a few of them are working***, so what happened?

![Annotation 2020-07-26 122838](https://user-images.githubusercontent.com/48143913/88471405-a23abd00-cf3b-11ea-8869-c7bc7afa44a3.png)

**To Reproduce**

Just ***use https://www.ssllabs.com/ssltest/index.html and a debian10 machine to reproduce***

**Expected behavior**

***All tls 1.2  **RSA** ciphers should be working as expected.***

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?

Debian 10

**Additional context**

**Comment by wongsyrone** [comment]
These tests will be redirected to 127.0.0.1:80 since they are not Trojan requests.

**Comment by okudayukiko** [comment]
`DHE-RSA-AES128-GCM-SHA256`和`DHE-RSA-AES256-GCM-SHA384`要求`dhparam`不為空。
`openssh dhparam -out dhparam.pem 2048`

**Comment by ghost** [comment]
@okudayukiko 默认dh是有的，是否自定义并不重要

**Comment by ghost** [comment]
https://serverfault.com/questions/991806/nginx-some-ciphers-ciphers-not-offered **sorry,but i know why now**
