### ISSUE TITLE
[Feature Request]增加DNS CAA支援

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#492]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**
現在GFW可以干擾Let's Encrypt證書的Trojan/AnyConnect，畢竟Let's Encrypt只能申請域名證書，IP-only證書都收費且價格不便宜。再者Windows、Android、iOS信任CFCA、GDCA、HKPost這三個政府CA。Igniter也跟進。中國移動4G看Trojan直播非常不穩定。Android 10導入自簽名CA證書後會經常出現不安全提示，iOS不信任導入的CA證書（描述文件）。

**Describe alternatives you've considered**

**Additional context**

**Comment by okudayukiko** [comment]
RFC 6844「Relying Applications MUST NOT use CAA records as part of certificate validation.」如要用IP-only自簽名證書，我覺得信任「自簽名CA證書」/「自簽名伺服器證書」的X.509 Fingerprint是最好的方案（但Trojan暫不支持此功能），不需導入證書，畢竟SSH就是用known_hosts紀錄伺服器公鑰的Base64/伺服器公鑰的Fingerprint。多個VPS用同一個CA簽名太麻煩了而且CA private key要妥善保管。只要CN、SAN符合IP/域名即可。
![Screenshot_20200730-180451_One UI Home](https://user-images.githubusercontent.com/17502357/88910887-ab0af600-d28f-11ea-8ba8-56ff37e8af6e.jpg)
![20200730_180524](https://user-images.githubusercontent.com/17502357/88910894-af371380-d28f-11ea-82ce-e81b01fb16e1.jpg)
![20200730_083015](https://user-images.githubusercontent.com/17502357/88907944-d2f85a80-d28b-11ea-9d97-8f6d86b21e5c.jpg)
![20200730_083001](https://user-images.githubusercontent.com/17502357/88907949-d68be180-d28b-11ea-8477-b04a305b36f8.jpg)
而且Android導入的證書不能停用只能刪除
![Screenshot_20200730-181125_Settings](https://user-images.githubusercontent.com/17502357/88911532-8cf1c580-d290-11ea-85f3-d55e16f80798.jpg)
![Screenshot_20200730-181131_Settings](https://user-images.githubusercontent.com/17502357/88911545-90854c80-d290-11ea-9d46-fb69bc2a208c.jpg)

**Comment by Chigusa0w0** [comment]
As of January 2020, Qualys reports that still, only 6.8% of the 150,000 most popular TLS-supporting websites use CAA records.

**Comment by okudayukiko** [comment]
問題找到。我們的非中國版Android/iPhone手機，使用中國移動4G、中國聯通4G有耗電大、網速不穩定、網速減慢的問題。三星售後說，只能換中國版手機，或者用「4G to Wi-Fi」。後來買了個4G to Wi-Fi，行動上網問題解決。
