### ISSUE TITLE
tproxy local traffic

### ISSUE THREAD

**Issue by junknet** [trojan-gfw/trojan#493]
看了tproxy的iiptables设置
全部是对prerouting表做设置

看了v2ray-core的代码，里面大概是把本地流量 set-mark 0x1 通过路由设置打回 lo 网卡，再跳到prerouting链，跳TPROXY链
v2ray防止流量回环的做法是在 v2ray代理和remote server建立连接时 通过setsockopt SO_MARK 数据包标记 0xff ，iptables outputing链 -m mark 0xff -j RETURN 放行，比一味的使用 -d remote_addr 要好，因为dns解析出多个ip

能否做成那种形式,这样也可以方便代理本机流量

**Comment by Chigusa0w0** [comment]
Trojan core is a protocol implementation. As it doesn't provide connection handling by itself, it will not assume the attributes of the connection nor treat them differently.
It seems like a problem with third-party software, you may ask relating developers for the feature.
