### ISSUE TITLE
希望作者能保护自己

### ISSUE THREAD

**Issue by YongChingShieh** [trojan-gfw/trojan#494]
https://github.com/Trojan-Qt5/Trojan-Qt5
![3299172095](https://user-images.githubusercontent.com/24885976/89137472-cfeeba00-d56a-11ea-9440-b89d42db18de.jpg)

**Comment by Chigusa0w0** [comment]
Thanks.

**Comment by GreaterFire** [comment]
@yongqingxie Thanks!

**Comment by okudayukiko** [comment]
昨天用Chocolatey安裝Trojan-Qt5報錯。

**Comment by fbion** [comment]
mark
