### ISSUE TITLE
[Feature Request] remote_addr support to proxy the other website

### ISSUE THREAD

**Issue by testowenyoung** [trojan-gfw/trojan#495]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

I supposed the config `{"remote_addr: "baidu.com"}` will proxy the <baidu.com> content as the probing resistance response, but it not working, I don't know if I'am missing anything, or if there is any way that I can do this.

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

If I want use `remote_addr` for probing resistance, I have to run a http server at the machine, but I don't want to run two service, so I want to use some other website response for this.

**Describe the solution you'd like**

For now, I can write a http server that response a proxy content at `127.0.0.1:80` for this.

**Describe alternatives you've considered**

**Additional context**

**Comment by Chigusa0w0** [comment]
`remote_addr` should be a HTTP-only website while `baidu.com` implements site-wide HTTPS.

**Comment by testowenyoung** [comment]
@Chigusa0w0 I have tried  <http://163.177.151.109/>`163.177.151.109`, this is the ip of `www.baidu.com`. and it can open at the browser.

But it doesn't work at trojan.

**Comment by Chigusa0w0** [comment]
Pls post your full config, redact as needed.

**Comment by testowenyoung** [comment]
Thanks, @Chigusa0w0  Here is the config:

```json
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "163.177.151.109",
    "remote_port": 80,
    "password": [
        "password1",
        "password2"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "./cert.pem",
        "key": "./key.pem",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}
```

Log:

`[2020-08-04 12:40:37] [WARN] 127.0.0.1:55984 not trojan request, connecting to 163.177.151.109:80`

**Comment by testowenyoung** [comment]
Hi, @Chigusa0w0 , Could you look the problem if you have time? I have posted the config of mine. Thank you very much!

**Comment by cdowen** [comment]
Hi, based on my understanding about the code, trojan directly forwards the request to the website specified in remote_addr. The host in the request is unmodifed and different from the host on remote_addr. So host on remote_addr returns error. It seems you must run a web server yourself for now.

**Comment by cdowen** [comment]
By the way, is the feature request still relavant? I am insterested in making some contributions but do not if the developers are willing to add new features.

**Comment by GreaterFire** [comment]
@cdowen You can't assume the request is HTTP request.

**Comment by cdowen** [comment]
Yes, but the remote_addr option is currently meaningless anyway. 

I think if the request is valid https, the header in the request gets modified and the request is sent to other Internet servers. If HOST cannot be found, I think returning 400 Bad Request should be enough to fake a web server.

**Comment by GreaterFire** [comment]
@cdowen Sorry, let me put it this way: WE can't assume the underlying traffic is HTTP, so we can't make any modifications to any "headers" in the request.

**Comment by Chigusa0w0** [comment]
@cdowen To make it very clear: no matter which detection method you would use (for HTTP header), there is a chance that a false positive will occur. We can't take the chance of that. So we will never touch the content of transferring data.

**Comment by GreaterFire** [comment]
@Chigusa0w0 To add to that, such false positives could well be ways to detect a trojan server.

**Comment by cdowen** [comment]
I understand the risks. But proxy to other websites cannot be realized without header modification in most scenarios. Maybe the remote_addr config should be discarded to reduce confusion?

**Comment by Chigusa0w0** [comment]
@cdowen You can't simply assume that everyone use HTTP as the cover up protocol or have a trivial handle stack. The field has certain use scenario and has been a part of Trojan server config for a long time. From compatibility and functionality perspective, we will not remove the field. We won't even consider it.
If you really need to make a nice and clear description for this field, you can contribute to trojan documentation ([here](https://github.com/trojan-gfw/trojan/blob/master/docs/config.md) or [here](https://github.com/trojan-gfw/trojan/wiki)).

**Comment by wd** [comment]
I think the only reason that `remote_addr` exists in `server` mode is to avoid detection, I don't think anyone will use this feature to serve his website this way. 

So if I run the trojan service through docker, I also need to run an other docker container to provide a valid `http` server for this domain. I agree with the OP here, why not just add support to set it to an other domain? it's more simple then setup another container to serve the domain for the user.

**Comment by wd** [comment]
And I also think the clarify in https://github.com/trojan-gfw/trojan/pull/533 is necessary, because I think me and the OP are not the only people who will misunderstand how to setup this option properly.
