### ISSUE TITLE
[Feature Request]能否將Trojan-GFW程式提交到Chocolatey/Windows Package Manager？

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#496]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Chigusa0w0** [comment]
Trojan is a install-free dependency-free single binary file on windows (except VCRT). IMO it is pointless to publish it to such tool.

But, as always, contribution is welcomed.
