### ISSUE TITLE
How does nginx get the client's real IP

### ISSUE THREAD

**Issue by ruanhuilingscuec** [trojan-gfw/trojan#498]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
The client IP obtained by Nginx is 127.0.0.1, If we know the real IP, we can block unrecognized IP.

**Is this problem relevant to what trojan should care about?**
It can improve safety.

**Describe the solution you'd like**
Similar to $proxy_add_x_forwarded_for to provide a field containing the real connection IP.

**Describe alternatives you've considered**

**Additional context**

**Comment by Chigusa0w0** [comment]
See #377

**Comment by owendswang** [comment]
https://github.com/trojan-gfw/trojan/issues/433#issuecomment-692878138
