### ISSUE TITLE
[BUG]從Sleep或Hibernate恢復後的Bug

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#499]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
Latest

**Describe the bug**
Trojan+Firefox，從Sleep或Hibernate恢復Windows後，Firefox無法打開網頁，必須Exit and Reopen Trojan。

**Environment**
Where are you running trojan? What is your proxy set up?
Windows 10 1909 x86-64

**Comment by Chigusa0w0** [comment]
Did you observe anything special in the log?

**Comment by Chigusa0w0** [comment]
Closed due to inactivity. You may reopen the issue when more information is available.
