### ISSUE TITLE
Quic 

### ISSUE THREAD

**Issue by superhero75** [trojan-gfw/trojan#50]
Could we add quic support ?

**Comment by GreaterFire** [comment]
@superhero75 There isn't a plan now, but we will definitely consider QUIC after it prevails.

**Comment by GreaterFire** [comment]
Since QUIC hasn't prevailed, I'll close this dangling issue until the time comes.

**Comment by mem0rz** [comment]
https://w3techs.com/technologies/history_overview/site_element/all
2021/06
HTTP/3+QUIC has 25% of the website popularity.Perhaps it is time for the project to consider supporting it.
@GreaterFire
