### ISSUE TITLE
防火长城已开始阻断ESNI扩展的TLS1.3（HTTPS）连接

### ISSUE THREAD

**Issue by YongChingShieh** [trojan-gfw/trojan#502]
这个我们需要做些什么吗 
https://www.iyouport.org/%E6%8A%A5%E5%91%8A%EF%BC%9A%E4%B8%AD%E5%9B%BD%E7%9A%84%E9%98%B2%E7%81%AB%E9%95%BF%E5%9F%8E%E5%B7%B2%E7%BB%8F%E5%B0%81%E9%94%81%E5%8A%A0%E5%AF%86%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%90%8D%E7%A7%B0%E6%8C%87/
一份由Geneva、GFW Report、iYouPort团队联合编写的报告显示中国的防火长城已经封锁加密服务器名称指示（ESNI）。
普通的TLS加密可以隐藏客户端与服务器之间的内容和URI，而TLS1.3引入了加密SNI（ESNI），这项强大的技术使审查者甚至无法得知用户使用ESNI访问了哪一个网站，审查者要么不封锁任何ESNI连接，要么封锁所有的ESNI连接。 报告现在确认GFW选择了后者。

**Comment by Chigusa0w0** [comment]
No impact on Trojan

**Comment by 0neday** [comment]
ESNI just encrypt SNI，not encrypt ssl certificates, so gfw could block connections by blocking certifications exchange. That means certificate transport by blank text.
