### ISSUE TITLE
[BUG] end of http flaw

### ISSUE THREAD

**Issue by clpd** [trojan-gfw/trojan#503]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.16.0

**Describe the bug**
Not processing end of http `\r\n\r\n` before finishing reading Hash.

**To Reproduce**
1. Connect to Trojan Server with TLS connection
2. Send `\r\n\r\n`
3. Connection is hanging.

**Expected behavior**
Connection should be redirected to remote server after reading `\r\n\r\n`.  
Expected returned value: `HTTP/1.1 400 Bad Request\r\n\r\n`

**Comment by Chigusa0w0** [comment]
Can you provide a log file?

**Comment by clpd** [comment]
It doesn't have a log, I realize this can be used to detect Trojan server.

**Comment by Chigusa0w0** [comment]
Probably. But as a reminder, Trojan is not specialized for HTTPS protocol though HTTPS is widely used. We will investigate this issue, and if there is a fixup that does not affect compatibility with other protocols, we will consider fixing it.

**Comment by ghost** [comment]
@ChinaLiePeopleDie  can not reproduce

here is my test result
```
read R BLOCK
\r\n\r\n
HTTP/1.1 400 Bad Request
Server: nginx
Date: Sun, 16 Aug 2020 07:20:08 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 150
Connection: close
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
closed
```

**Comment by HarukaMa** [comment]
@ChinaLiePeopleDie Did you try it with other HTTPS servers? Are you sure this behavior is reproducible on all other servers?

I'm not able to reproduce 400 result on all servers I could reach, including plain HTTP servers. Please provide logs about your findings.

**Comment by Chigusa0w0** [comment]
According to my test. The behavior of Trojan sites is identical to `nginx.org`.

**Comment by 0neday** [comment]
Is it possible that GFW use Trojan client to detect Trojan server, and then block it. Could you have written a paper to explain Trojan server end protocols. Just like /r/n get password segment? @Chigusa0w0 @ChinaLiePeopleDie

**Comment by Chigusa0w0** [comment]
@0neday As of now, according to our test, that's impossible. Ignore and hang with `\r\n` start line is a nginx behavior, not a trojan behavior.

**Comment by 0neday** [comment]
@Chigusa0w0 Nice, we will test on 1/10/2020, and check out whether is blocked or not.

**Comment by clpd** [comment]
My mistake, nginx ignore empty request, which only have `\r\n\r\n`.
