### ISSUE TITLE
[BUG]Nginx stream forward trojan tunnel between different server

### ISSUE THREAD

**Issue by zhyonc** [trojan-gfw/trojan#510]
**Trojan Version**
trojan 1.16.0

**Describe the bug**

***Environment***

I have 1 client and 2 servers：

- CN server bind domain：blog.domain.com and forward.domain.com

- HK server bind domain：trojan.domain.com

***Route***

client<-->CN server nginx<-->HK server trojan

***Config***

*client trojan*：

```
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "forward.domain.com",
    "remote_port": 443,
    "password": [
        "password"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "sni":"trojan.domain.com"
    }
}
```

*CN server nginx*：

```
stream {
    map $ssl_preread_server_name $name {
        blog.domain.com web;
        forward.domain.com trojan;
    }

    upstream web {
        server 127.0.0.1:8080;
    }

    upstream trojan {
        server trojan.domain.com:443;
    }

    server {
        listen 443 reuseport;
        proxy_pass  $name;
        ssl_preread on;
        error_log /var/log/nginx/stream.log info;
    }
}
```

*HK server trojan*：

```
{
    "run_type": "server",
    "local_addr": "127.0.0.1",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "password"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "sni": ""
    }
}
```

**To Reproduce**

- HK server systemctl start trojan

- CN server systemctl start nginx

- Client run trojan.exe
- CN server cat /var/log/nginx/stream.log
- HK server systemctl status trojan

**Expected behavior**

- CN server nginx can identify forward.domain.com

- HK server trojan can get request where from CN server nginx

**Logs**

*Client* 

```
[ERROR] 127.0.0.1:60449 SSL handshake failed with forward.domain.com:443 stream truncated
```

*CN server*

```
[info] client ip:port connected to 0.0.0.0:443
[error] no host in upstream "", client: ip, server: 0.0.0.0:443, bytes from/to client:0/0, bytes from/to upstream:0/0
```

*HK server*

```
[WARN] trojan service (server) started at 127.0.0.1:443
```

note：can't find any request from CN server

**Comment by Chigusa0w0** [comment]
`ssl.sni` config will overwrite client `remote_addr` SNI. Which the final result is `trojan.domain.com` in your case. 
https://github.com/trojan-gfw/trojan/blob/58e3393a12f9e8ce2f26bbe3401708e8886806c9/src/core/service.cpp#L132-L134
https://github.com/trojan-gfw/trojan/blob/2b29ced3a5c708b00b6889212b3fcabd010f6846/src/session/clientsession.cpp#L49

**Comment by zhyonc** [comment]
> `ssl.sni` config will overwrite client `remote_addr` SNI. Which the final result is `trojan.domain.com` in your case.
> https://github.com/trojan-gfw/trojan/blob/58e3393a12f9e8ce2f26bbe3401708e8886806c9/src/core/service.cpp#L132-L134
> 
> 
> https://github.com/trojan-gfw/trojan/blob/2b29ced3a5c708b00b6889212b3fcabd010f6846/src/session/clientsession.cpp#L49

It looks like my route is error,I thought trojan have 2 SSL when it set sni.

Nginx ssl_preread seem like only identify trojan ssl sni domain that is trojan.domain.com,not is forward.domain.com.

Thanks you point out the error,I rewrite the CN server nginx.conf and it work for me.

```
stream {
    map $ssl_preread_server_name $name {
        blog.domain.com web;
        trojan.domain.com trojan;
    }

    upstream web {
        server 127.0.0.1:8080;
    }

    upstream trojan {
        server trojan.domain.com:443;
    }

    server {
        listen 443 reuseport;
        proxy_pass  $name;
        ssl_preread on;
        error_log /var/log/nginx/stream.log info;
    }
}
```

**Comment by 0neday** [comment]
Try to use haproxy to relay trojan server data instead of Nginx
