### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Motophan** [trojan-gfw/trojan#511]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
I have a traefik reverseproxy, a container yml example would be extremely helpful deploying this as a container. Specifically one that does not need a volume link to the ssl cert as my reverseproxy would handle this. This also would let you buy a large number of IP addresses and rotate them. 

**Is this problem relevant to what trojan should care about?**
This makes deployment on microservers or container services easier. Especially ones that are difficult to block like azure or aws. 

**Describe the solution you'd like**
A small simple example of running this in the official container w/ and w/o a reverseproxy. I can only find one person who has used this in a container w/o a reverseproxy. 

**Describe alternatives you've considered**
https://hub.docker.com/r/teddysun/trojan
^ This almost works but I need to create a dummy snakeoil cert, then set my reverseproxy to send it to the containers :443 port. There is no real reason to have my reverseproxy to decrypt the seccondary self signed cert. 

**Additional context**
Most people using kubernetes and docker use traefik as their reverseproxy, but as long as I can get the container up ready to accept traffic from a reverseproxy it should work for any of them.

**Comment by Chigusa0w0** [comment]
> For a feature to be considered, make sure that the feature you request is really necessary to be included in this very project. ([CONTRIBUTING.md](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md))

Docker image is not a actively supported part of this project. But PR is always welcomed.

**Comment by zais** [comment]
@Motophan any luck with traefik and trojan?
