### ISSUE TITLE
 Delete

### ISSUE THREAD

**Issue by 0neday** [trojan-gfw/trojan#514]

**Comment by Chigusa0w0** [comment]
Trojan do not intercept your DNS query, you should do it by your self.

**Comment by 0neday** [comment]
@Chigusa0w0  fixed! use forword mode, like 
### trojan-forward.json
{
    "run_type": "forward",
    "local_addr": "127.0.0.1",
    "local_port": 5901,
    "remote_addr": "example.com",
    "remote_port": 443,
    "target_addr": "8.8.8.8",
    "target_port": 53,
    "password": [
        "password1"
    ],

### trojan log 

root@OpenWrt:~#  /usr/sbin/trojan -c trojan-forwaord.json
Welcome to trojan 1.16.0
[2020-08-21 07:15:13] [WARN] trojan service (forward) started at 127.0.0.1:3535
[2020-08-21 07:15:27] [INFO] 127.0.0.1:36575 forwarding UDP packets to 8.8.8.8:53 via x.x.x.x:port
[2020-08-21 07:15:33] [INFO] 127.0.0.1:36575 disconnected, 59 bytes received, 55 bytes sent, lasted for 6 seconds

### dig log
root@OpenWrt:~# dig www.google.com @127.0.0.1 -p 3535

; <<>> DiG 9.14.8 <<>> www.google.com @127.0.0.1 -p 3535
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22733
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         299     IN      A       172.217.175.68

;; Query time: 186 msec
;; SERVER: 127.0.0.1#3535(127.0.0.1)
;; WHEN: Fri Aug 21 07:15:28 CST 2020
;; MSG SIZE  rcvd: 59
