### ISSUE TITLE
[BUG]unknown protocol 

### ISSUE THREAD

**Issue by superdy00** [trojan-gfw/trojan#519]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.16

**Describe the bug**

unknown protocol 

![image](https://user-images.githubusercontent.com/17778954/91626961-26261000-e9e6-11ea-8117-fe1f697a7f81.png)

config.json
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "**.**.com",
    "remote_port": 443,
    "password": [
        "*********"
    ],
    "log_level": 1,
    "ssl": {
        "verify": false,
        "verify_hostname": false,
        "cert": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}

**Comment by superdy00** [comment]
![image](https://user-images.githubusercontent.com/17778954/91627059-1e1aa000-e9e7-11ea-85d8-cead93f1d020.png)

like this.

please help me. thank you.

**Comment by ghost** [comment]
@superdy00 please use socks to connect

**Comment by ghost** [comment]
@superdy00 you may misuse http proxy instead of socks5 proxy which causes this problem

**Comment by superdy00** [comment]
> @superdy00 you may misuse http proxy instead of socks5 proxy which causes this problem

can you tell me how to use socks to connect ? I am a rookie.. thanks..

**Comment by ghost** [comment]
@superdy00 https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif

**Comment by wongsyrone** [comment]
Use SOCKS5 please.

**Comment by superdy00** [comment]
> Use SOCKS5 please.

I dont know how. can you teach me?

**Comment by ousinkou** [comment]
I encounter the same problem when using ubuntu. In the system agent interface,  after blanking the http and https row, setting socks host with 127.0.0.1, 1080 port, the problem is solved.

**Comment by dreamingodd** [comment]
> > Use SOCKS5 please.
> 
> I dont know how. can you teach me?

It means use SOCKS5 protocol to connect your existing port 127.0.0.1:1080, as your config.json is correct.

**Comment by dreamingodd** [comment]
> > Use SOCKS5 please.
> 
> I dont know how. can you teach me?

It means using SOCKS5 protocol to connect your existing port 127.0.0.1:1080, as your config.json is correct.

**Comment by jqknono** [comment]
Use socks5 means change the prefix from `http://` to `socks5://`.
You usually use the `http://127.0.0.1:1080`, just change it to `socks5://127.0.0.1:1080`
