### ISSUE TITLE
申请 希望路由器支持

### ISSUE THREAD

**Issue by BoBppy** [trojan-gfw/trojan#52]
平常习惯于路由器，系统是OpenWRT，希望有开源代码可以编译成为ipk文件，以便装载到路由器上

**Comment by GreaterFire** [comment]
@BoBppy https://github.com/trojan-gfw/openwrt-trojan

**Comment by wongsyrone** [comment]
现在编译使用的openssl是由我们修改的版本1.1.1a，而不是在官方仓库中的版本1.0系列。由于openssl静态链接到trojan二进制，所以最后的二进制会看起来有点大，目的是为了使用TLS 1.3且不与系统自带的冲突

暂时还没有同时支持openwrt官方仓库中openssl的计划。

**Comment by babylife** [comment]
同样希望可以支持，路由器不能用的话的确比较麻烦

**Comment by oxeyelite** [comment]
同样希望可以支持.

**Comment by BaiqingL** [comment]
+1

**Comment by wazzx** [comment]
最新的目前稳定版19.07.2的openssl-util版本是1.1.1e-1
