### ISSUE TITLE
如何在Trojan服务端指定DNS？

### ISSUE THREAD

**Issue by nkta3m** [trojan-gfw/trojan#521]
非常感谢这个项目，之前使用ss，可以指定dns，就可以看奈飞，现在换用Trojan，不知道在server端如何指定dns？求解答，谢谢

**Comment by 0neday** [comment]
/etc/resolv.conf

**Comment by nkta3m** [comment]
我有设置，但是完全无效

**Comment by 0neday** [comment]
install dnsmasq and set nameserver 127.0.0.1

**Comment by ZqinKing** [comment]
有点想不通为啥server端要设置dns。连接哪个服务器是你pc上的dns决定的。trojan说白了只是一个代理。

**Comment by geonchen** [comment]
> 有点想不通为啥server端要设置dns。连接哪个服务器是你pc上的dns决定的。trojan说白了只是一个代理。

那是因为要在服务器用别人提供的dns解锁流媒体

**Comment by okudayukiko** [comment]
有的是/etc/resolv.conf
有的是systemd-resolved
有的是systemd-networkd
