### ISSUE TITLE
can i please ask if trojan-gfw support Raspberry pi v4?

### ISSUE THREAD

**Issue by callmejon** [trojan-gfw/trojan#522]
after install on rpi v4 when run get, below test same install method on x86 seems ok.

any advice?

Welcome to trojan 1.16.0
[2020-09-12 15:21:46] [FATAL] fatal: /usr/local/etc/trojan/config.json(2): expected key string
[2020-09-12 15:21:46] [FATAL] exiting. . .

**Comment by GreaterFire** [comment]
@callmejon There is a syntax error in your config file :)

**Comment by callmejon** [comment]
spot on!!!! fixed, thanks
i was using old ubuntu 1.1 config on rpi 1.16 i think..
