### ISSUE TITLE
windows failed log in

### ISSUE THREAD

**Issue by xufana7** [trojan-gfw/trojan#523]
I can not connect my vps with trojan on windows, but it can works on ios with shadowrocket.

**Comment by Chigusa0w0** [comment]
Please provide config file and log

**Comment by fytaoxingyu** [comment]
> I can not connect my vps with trojan on windows, but it can works on ios with shadowrocket.
I had same problem,it dosent work since 9.14

**Comment by xufana7** [comment]
> Please provide config file and log
log:
[INFO]  2020/09/17 16:03:44 Running client, config file: C:/Users/snow/Desktop/Trojan-Qt5-Windows/config.json
[INFO]  2020/09/17 16:03:44 Log will be written to C:/Users/snow/AppData/Roaming/trojan-qt5/core.log
[WARN]  2020/09/17 16:03:44 Found invalid cipher  ECDHE-ECDSA-AES128-GCM-SHA256
[WARN]  2020/09/17 16:03:44 "cipher_suite" contains invalid cipher name, ignored
[WARN]  2020/09/17 16:03:44 Here is a list of supported ciphers:
[WARN]  2020/09/17 16:03:44 TLS_RSA_WITH_3DES_EDE_CBC_SHA:TLS_RSA_WITH_AES_128_CBC_SHA:TLS_RSA_WITH_AES_256_CBC_SHA:TLS_RSA_WITH_AES_128_GCM_SHA256:TLS_RSA_WITH_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA:TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
[WARN]  2020/09/17 16:03:44 open C:\Users\snow\Desktop\Trojan-Qt5-Windows/geoip.dat: The system cannot find the file specified.
[WARN]  2020/09/17 16:03:44 open C:\Users\snow\Desktop\Trojan-Qt5-Windows/geosite.dat: The system cannot find the file specified.
[WARN]  2020/09/17 16:03:44 SNI is unspecified, using remote_addr as SNI
[INFO]  2020/09/17 16:03:44 Cert of the remote server is unspecified. Using default CA list
[INFO]  2020/09/17 16:03:44 trojan launched
[INFO]  2020/09/17 16:03:44 Trojan-Go client is listening on 127.0.0.1:51837
[INFO]  2020/09/17 16:03:44 Trojan-Go client-side API service is listening on 127.0.0.1:57721
config:
{
    "api": {
        "api_addr": "127.0.0.1",
        "api_port": 57721,
        "enabled": true
    },
    "buffer_size": 32,
    "forward_proxy": {
        "enabled": false,
        "proxy_addr": "127.0.0.1",
        "proxy_port": 1086
    },
    "local_addr": "127.0.0.1",
    "local_port": 51837,
    "log_file": "C:/Users/snow/AppData/Roaming/trojan-qt5/core.log",
    "log_level": 1,
    "mux": {
        "concurrency": 8,
        "enabled": false,
        "idle_timeout": 60
    },
    "password": [
        "password"
    ],
    "remote_addr": "remote_addr",
    "remote_port": 443,
    "router": {
        "enabled": false
    },
    "run_type": "client",
    "ssl": {
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "cert": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "curves": "",
        "fingerprint": "firefox",
        "reuse_session": true,
        "session_ticket": false,
        "sni": "",
        "verify": true,
        "verify_hostname": true
    },
    "tcp": {
        "fast_open": false,
        "fast_open_qlen": 20,
        "keep_alive": true,
        "no_delay": true,
        "reuse_port": false
    },
    "websocket": {
        "double_tls": false,
        "enabled": false,
        "hostname": "",
        "obfuscation_password": "",
        "path": ""
    }
}

**Comment by xufana7** [comment]
> Please provide config file and log

####log
[INFO]  2020/09/17 16:09:50 Running client, config file: C:/Users/snow/Desktop/Trojan-Qt5-Windows/config.json
[INFO]  2020/09/17 16:09:50 Log will be written to C:/Users/snow/AppData/Roaming/trojan-qt5/core.log
[WARN]  2020/09/17 16:09:50 Found invalid cipher  ECDHE-ECDSA-AES128-GCM-SHA256
[WARN]  2020/09/17 16:09:50 "cipher_suite" contains invalid cipher name, ignored
[WARN]  2020/09/17 16:09:50 Here is a list of supported ciphers:
[WARN]  2020/09/17 16:09:50 TLS_RSA_WITH_3DES_EDE_CBC_SHA:TLS_RSA_WITH_AES_128_CBC_SHA:TLS_RSA_WITH_AES_256_CBC_SHA:TLS_RSA_WITH_AES_128_GCM_SHA256:TLS_RSA_WITH_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA:TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
[WARN]  2020/09/17 16:09:50 open C:\Users\snow\Desktop\Trojan-Qt5-Windows/geoip.dat: The system cannot find the file specified.
[WARN]  2020/09/17 16:09:50 open C:\Users\snow\Desktop\Trojan-Qt5-Windows/geosite.dat: The system cannot find the file specified.
[WARN]  2020/09/17 16:09:50 SNI is unspecified, using remote_addr as SNI
[INFO]  2020/09/17 16:09:50 Cert of the remote server is unspecified. Using default CA list
[INFO]  2020/09/17 16:09:50 trojan launched
[INFO]  2020/09/17 16:09:50 Trojan-Go client is listening on 127.0.0.1:51837
[INFO]  2020/09/17 16:09:50 Trojan-Go client-side API service is listening on 127.0.0.1:57721
###config
{
    "api": {
        "api_addr": "127.0.0.1",
        "api_port": 57721,
        "enabled": true
    },
    "buffer_size": 32,
    "forward_proxy": {
        "enabled": false,
        "proxy_addr": "127.0.0.1",
        "proxy_port": 1086
    },
    "local_addr": "127.0.0.1",
    "local_port": 51837,
    "log_file": "C:/Users/snow/AppData/Roaming/trojan-qt5/core.log",
    "log_level": 1,
    "mux": {
        "concurrency": 8,
        "enabled": false,
        "idle_timeout": 60
    },
    "password": [
        "password"
    ],
    "remote_addr": "remote_addr",
    "remote_port": 443,
    "router": {
        "enabled": false
    },
    "run_type": "client",
    "ssl": {
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "cert": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "curves": "",
        "fingerprint": "firefox",
        "reuse_session": true,
        "session_ticket": false,
        "sni": "",
        "verify": true,
        "verify_hostname": true
    },
    "tcp": {
        "fast_open": false,
        "fast_open_qlen": 20,
        "keep_alive": true,
        "no_delay": true,
        "reuse_port": false
    },
    "websocket": {
        "double_tls": false,
        "enabled": false,
        "hostname": "",
        "obfuscation_password": "",
        "path": ""
    }
}

**Comment by wongsyrone** [comment]
You are using Trojan-Go and Trojan-Qt5, please send feedback to the correct repository.
