### ISSUE TITLE
什么时候支持WebSocket呢?

### ISSUE THREAD

**Issue by hudingwen** [trojan-gfw/trojan#524]
因为Trojan直接走的原始IP,但有些IP只能通过CDN加速才能使用,否则搭建好的服务器很容易受到限制

**Comment by hudingwen** [comment]
???

**Comment by Chigusa0w0** [comment]
1. Dup #393 
2. Read CONTRIBUTING.md before open issue
3. Not using template
4. The decision is well-documented
5. Support to WebSocket is not a enhancement, at least not for us

**Comment by hudingwen** [comment]
> 1. Dup [＃393](https://github.com/trojan-gfw/trojan/issues/393)
> 2. 在未解决问题之前，请先阅读CONTRIBUTING.md
> 3. 不使用模板
> 4. 该决定有据可查
> 5. 对WebSocket的支持不是增强，至少对我们而言不是

好吧 谢谢
