### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Earlesscat** [trojan-gfw/trojan#525]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
No
**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.
User data control
**Describe the solution you'd like**
I hope trojan could manage user's data periodic (monthly, annually) eg: provide 10GB data for user Jack every month, start from 10th every month, if reaching this limit, stop Jack's data until cycle. Also keep the data statistics to record the total data Jack used.
**Describe alternatives you've considered**

**Additional context**

**Comment by Chigusa0w0** [comment]
Dup #274
