### ISSUE TITLE
[Feature Request] Censorship of ESNI

### ISSUE THREAD

**Issue by kgiflwl** [trojan-gfw/trojan#528]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
I haven't go though all the code and TLS library of trojan, just wish you to read this: https://gfw.report/blog/gfw_esni_blocking/en/. Since I was kicked out from Telegram group, github issue seems the only way I could contact the author.

**Is this problem relevant to what trojan should care about?**
I'm not sure if Trojan possessed one of the six methods to avoid ESNI censorship, hope it is.

**Describe the solution you'd like**
I wish Trojan could circumvent GFW ESNI censorship.

**Comment by GreaterFire** [comment]
@kgiflwl Trojan is completely different from ESNI.

**Comment by kgiflwl** [comment]
> @kgiflwl Trojan is completely different from ESNI.

I think ESNI is part of TLS1.3 extension, and Trojan initiates real TLS handshake. I was worrying about this would expose ESNI connection. If it's not, then that's a relief.
