### ISSUE TITLE
[Feature Request]Add Web Browser Extension

### ISSUE THREAD

**Issue by svandex** [trojan-gfw/trojan#536]
Thirdparty proxy extension is not perfectly optimized for trojan, and most trojan users use it on web browser.

**Comment by Chigusa0w0** [comment]
Trojan is not a HTTP-based protocol. There will be certain difficulties to develop a browser extension-based client for Trojan.
Also, please read CONTRIBUTING.md before open feature requests.

**Comment by okudayukiko** [comment]
Firefox支援SOCKS5。對於Edge、IE、Chrome，用Privoxy將SOCKS5轉換成HTTP。
