### ISSUE TITLE
[Feature Request]建议能增加不开启tls加密的选项

### ISSUE THREAD

**Issue by XuuKoo** [trojan-gfw/trojan#537]
前端tls解密可由haproxy等软件负责，tls解密后传输明文Trojan协议的数据至trojan服务端，其余功能不变。

**Comment by Chigusa0w0** [comment]
As long as you own the certifications, you should be able to re-encrypt the connection with haproxy.

**Comment by XuuKoo** [comment]
> As long as you own the certifications, you should be able to re-encrypt the connection with haproxy.

haproxy和trojan间就没必要用tls加密了呀。

**Comment by ghost** [comment]
我也建议。给用户选择权是好的，即使你可以默认开tls
