### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EIKULG** [trojan-gfw/trojan#543]
- [= ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.
Trojan 1.16.0
**Describe the bug**
When using Trojan to open some webpages, errors will occur, such as 405 when opening https://www.tap.io/, but using shadowsocks in the same vps can open normally.
**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?
Clashforwindows clashforandroid
**Additional context**
![屏幕截图 2020-10-17 225657](https://user-images.githubusercontent.com/34759969/96342278-1a90c480-10cc-11eb-8ea8-09efac93aa42.png)

**Comment by Chigusa0w0** [comment]
Cannot reproduce

**Comment by EIKULG** [comment]
If it is the problem of vps, then shadowsocks should not be able to open the same webpage, and I don't know where the problem might be.

**Comment by Chigusa0w0** [comment]
As the website is using commercial WAF, the problem could be multi-sourced. Anyway, Trojan is not the single reason for your problem.

**Comment by EIKULG** [comment]
Got it.
