### ISSUE TITLE
Why does my trojan installation deploy successfully, but I can't get a proxy?

### ISSUE THREAD

**Issue by MrYangLingQiang** [trojan-gfw/trojan#544]
`[2020-10-20 11:30:03] [INFO] 127.0.0.1:60760 requested connection to content-autofill.googleapis.com:443
[2020-10-20 11:30:04] [INFO] 127.0.0.1:60760 disconnected, 325 bytes received, 517 bytes sent, lasted for 1 seconds`
This message comes up every time I request it, and I built it before, but the previous one was working. The one built now won't work.
Appears when using Google Chrome
`此网站无法提供安全连接www.google.com 发送的响应无效。
尝试运行 Windows 网络诊断。
ERR_SSL_PROTOCOL_ERROR`

I'm using trojan+v2rayN to access the internet.

**Comment by Chigusa0w0** [comment]
> Issues in this repository are for bug reports and feature requests, and for these purposes only. Irrelevant content, such as usage problems or server configuration issues, should not be discussed here.
