### ISSUE TITLE
Help：I'm using docker to run trojan. But I don't know how to put on a website.

### ISSUE THREAD

**Issue by Walkerby** [trojan-gfw/trojan#545]
After configuring dockerhub trojangfw/trojan correctly, trojan worked fine and I found that opening the domain didn't bring up any websites and I couldn't figure out how to add the website.

**Comment by oasiscifr** [comment]
@Walkerby Use 172.17.0.1 (the address of the host on docker0) instead of 127.0.0.1 as remote_addr.
