### ISSUE TITLE
[BUG] cant use on mac big sur

### ISSUE THREAD

**Issue by Kurt-Shiwz** [trojan-gfw/trojan#549]
cant use on mac big sur

**Comment by sbraveyoung** [comment]
How do you resolve it?

**Comment by coocood** [comment]
TrojanX is not working on mac big sur, the officially trojan binary works fine.

**Comment by sbraveyoung** [comment]
Yeah，it's right. thank you!

**Comment by BillLucky** [comment]
Mac big sur 11.0.1 can use Trojan 1.16.0!
If you also use yizhihongxing service. Just replace the remote_addr and password in config.json and it will work.

https://order.yizhihongxing.network/aff.php?aff=1385
