### ISSUE TITLE
why my server keep connecting fail?

### ISSUE THREAD

**Issue by soogood** [trojan-gfw/trojan#55]
![20190111203840](https://user-images.githubusercontent.com/5028515/51034234-06f42800-15e1-11e9-96fc-10aa4f9dcbde.png)

no route to host ....
debian 9 vps

**Comment by Chigusa0w0** [comment]
Please provide your config file and other information you think may be helpful to diagnostic this problem.
As a reminder, this error is thrown by a more underlying component but not Trojan itself. So that it may not be a problem that we, the developers of Trojan, could solve.

**Comment by GreaterFire** [comment]
Does your server have an IPv6 address that's not usable? Try disabling IPv6 and using only IPv4 for connection.

**Comment by soogood** [comment]
Yes, my server has lots of IPV6 address... thanks a lot. issue closed.
