### ISSUE TITLE
[BUG]Build 出现错误

### ISSUE THREAD

**Issue by nkta3m** [trojan-gfw/trojan#551]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.16

**Describe the bug**
Build 报错

**To Reproduce**

**Expected behavior**

**Logs**
~/trojan/src/core/service.cpp:240:9: error: ‘SSL_CTX_set_ciphersuites’ was not declared in this scope
         SSL_CTX_set_ciphersuites(native_context, config.ssl.cipher_tls13.c_str());
         ^~~~~~~~~~~~~~~~~~~~~~~~
~/trojan/src/core/service.cpp:240:9: note: suggested alternative: ‘SSL_CTX_set_cipher_list’
         SSL_CTX_set_ciphersuites(native_context, config.ssl.cipher_tls13.c_str());
         ^~~~~~~~~~~~~~~~~~~~~~~~
         SSL_CTX_set_cipher_list
~/trojan/src/core/service.cpp:268:9: error: ‘SSL_CTX_set_keylog_callback’ was not declared in this scope
         SSL_CTX_set_keylog_callback(native_context, [](const SSL*, const char *line) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
~/trojan/src/core/service.cpp:268:9: note: suggested alternative: ‘SSL_CTX_set_info_callback’
         SSL_CTX_set_keylog_callback(native_context, [](const SSL*, const char *line) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
         SSL_CTX_set_info_callback
make[2]: *** [CMakeFiles/trojan.dir/build.make:119: CMakeFiles/trojan.dir/src/core/service.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/trojan.dir/all] Error 2
make: *** [Makefile:158: all] Error 2
**Environment**
openSUSE 15.2

**Additional context**

**Comment by GreaterFire** [comment]
@nkta3m It seems to be the problem of your OpenSSL version. Try adding -DENABLE_TLS13_CIPHERSUITES=OFF and -DENABLE_SSL_KEYLOG=OFF to your cmake command

**Comment by Chigusa0w0** [comment]
Closed due to inactivity. You may reopen this issue if the problem is not resolved.
