### ISSUE TITLE
[BUG]Youtube thumbnail cannot be loaded

### ISSUE THREAD

**Issue by dumplingdumpling** [trojan-gfw/trojan#553]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.16.0

**Describe the bug**
The youtube thumbnail cannot be loaded. It happens on one server but others are perfectly fine. I updated the version of trojan, and restarted the service, and it doesn't help.

![image](https://user-images.githubusercontent.com/70169466/100076183-de474580-2e7b-11eb-933f-0f5169b5fe82.png)

**Comment by Chigusa0w0** [comment]
Cannot reproduce
