### ISSUE TITLE
[BUG]Can't not connect to server and using the service.

### ISSUE THREAD

**Issue by FrankKirin** [trojan-gfw/trojan#555]
**Trojan Version**
Trojan 1.16.0

I config socks5 in chrome, and I success once. But after a while, I can't connect to my server. The server journal show nothing. What's wrong with this?

Server config:
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "mypassword"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/root/.acme.sh/franknerd.tk_ecc/franknerd.tk.cer",
        "key": "/root/.acme.sh/franknerd.tk_ecc/franknerd.tk.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "key": "",
        "cert": "",
        "ca": ""
    }
}

Client(Mac OS) config:
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 10801,
    "remote_addr": "domain.com",
    "remote_port": 443,
    "password": [
        "mypasswod"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "/Users/frank/app/trojan/franknerd.tk.cer",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}

**Comment by Chigusa0w0** [comment]
Could you post your client-side log?

**Comment by FrankKirin** [comment]
> Could you post your client-side log?

I don't know how to get my client-side log, could you please give a hand?
But I fixed the bug, the Cloudflare DNS doesn't worked well last night.

**Comment by Chigusa0w0** [comment]
You can start your Trojan client with either one of the following command lines.
`trojan -l <desired log file path>`
or
`trojan >> <desired log file path>`

Please redact any sensitive information from your log before posting it.
