### ISSUE TITLE
[BUG]trojan ssl handshake failed tlsv1 alert internal error

### ISSUE THREAD

**Issue by predators46** [trojan-gfw/trojan#558]
我在cerboot中创建了SSL证书，但是木马中存在问题。我看到这个错误已经存在很长时间了

**Comment by lucifer662607004** [comment]
我也遇到这个问题。我也是ca证书，客户端开启允许不安全链接就能避免这个问题，但是这样ca证书就完全没意义了……

后来我发现除了tls host需要ca的域名之外，服务器地址也必须要写域名，否则就会有概率出现这个问题，不知道是不是我客户端的bug，后来我用dnsmasq劫持ca域名到固定IP，服务端地址再使用域名之后就没出现了，给后人参考吧。
