### ISSUE TITLE
[FATAL] fatal: too many positional options have been specified on the command line

### ISSUE THREAD

**Issue by MaBoCoMark** [trojan-gfw/trojan#560]
- [ V ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.16.0

**Describe the bug**
[FATAL] fatal: too many positional options have been specified on the command line

**To Reproduce**
run trojan.exe

**Expected behavior**
It should show the connection logs as normal.

**Logs**
trojan-cli\trojan.exe trojan /path/to/config.json
Welcome to trojan 1.16.0
[2020-12-11 22:46:03] [FATAL] fatal: too many positional options have been specified on the command line
[2020-12-11 22:46:03] [FATAL] exiting. . .

**Environment**
Windows 10 1809 17763.1637

**Additional context**
It can work properly yesterday, IDK why it does get some problem now

**Comment by GreaterFire** [comment]
@MaBoCoMark try trojan-cli\trojan.exe /path/to/config.json
