### ISSUE TITLE
How to automatically start trojan when using launchctl ?

### ISSUE THREAD

**Issue by huiscool** [trojan-gfw/trojan#564]
Hi, I'm a user of macOS, and I want to use launchctl to start trojan automatically. I find that it's ok to start trojan from terminal, but it doesn't work when using launchctl. Here is my plist:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Label</key>
        <string>org.trojan</string>
        <key>WorkingDirectory</key>
	<string>/Users/huyingcong/trojan</string>
        <key>ProgramArguments</key>
        <array>
                <string>/Users/huyingcong/trojan/trojan</string>
                <string>-c</string>
                <string>/Users/huyingcong/trojan/trojan/config.json</string>
        </array>
        <key>StandardOutPath</key>
        <string>/var/log/trojan.log</string>
        <key>StandardErrorPath</key>
        <string>/var/log/trojan.log</string>
        <key>KeepAlive</key>
        <true/>
</dict>
</plist>
```
![image](https://user-images.githubusercontent.com/30804350/103495628-64d94480-4e76-11eb-8523-46947adcd85d.png)

The launchctl list shows that the trojan exits with code 78 and no log file.

 Thanks!

**Comment by GreaterFire** [comment]
@huiscool See trojan-gfw/homebrew-trojan

**Comment by huiscool** [comment]
I find that I don't have the log permission and it fails to write to /var/log :(
Changing it to a user folder works for me.

**Comment by huiscool** [comment]
> @huiscool See trojan-gfw/homebrew-trojan

how can I install it ?
