### ISSUE TITLE
申请证书时出错想问一下怎么解决

### ISSUE THREAD

**Issue by cccsf** [trojan-gfw/trojan#566]
acme.sh --issue -d <自己域名> -w /var/www/acme-challenge执行这条命令后出现了-bash：自己域名： No such file or directory
想问一下怎么解决

**Comment by wdweidao** [comment]
你好，这个问题解决了吗？我也碰到了

**Comment by wdweidao** [comment]
> acme.sh --issue -d <自己域名> -w /var/www/acme-challenge执行这条命令后出现了-bash：自己域名： No such file or directory
> 想问一下怎么解决



> acme.sh --issue -d <自己域名> -w /var/www/acme-challenge执行这条命令后出现了-bash：自己域名： No such file or directory
> 想问一下怎么解决

你好，这个问题解决了吗？我也碰到了
