### ISSUE TITLE
[Guide]Alpine静态编译trojan

### ISSUE THREAD

**Issue by msl4437** [trojan-gfw/trojan#567]
Alpine编译镜像

    FROM alpine:latest

    RUN apk update && \
        apk add build-base perl linux-headers && \
        wget --no-check-certificate https://github.com/openssl/openssl/archive/OpenSSL_1_1_1i.tar.gz && \
        tar -zxf OpenSSL_1_1_1i.tar.gz && \
        cd openssl-OpenSSL_1_1_1i && \
        ./config --openssldir=/etc/ssl enable-ec_nistp_64_gcc_128 no-ssl2 no-ssl3 no-comp no-idea no-dtls no-dtls1 no-shared no-psk no-srp no-ec2m no-weak-ssl-ciphers && \
        make install_sw && \
        cd .. && \
        rm -rf OpenSSL_1_1_1i.tar.gz openssl-OpenSSL_1_1_1i && \

        wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0.tar.gz && \
        tar -zxf cmake-3.17.0.tar.gz && \
        cd cmake-3.17.0 && \
        ./bootstrap -- && \
        make -j$(nproc) install && \
        cd .. && \
        rm -rf cmake-3.17.0.tar.gz cmake-3.17.0 && \

        wget --no-check-certificate https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz && \
        tar -zxf boost_1_72_0.tar.gz && \
        cd boost_1_72_0 && \
        ./bootstrap.sh && \
        ./b2 -j$(nproc) --with-system --with-program_options variant=release link=static threading=multi runtime-link=shared install && \
        cd .. && \
        rm -rf boost_1_72_0.tar.gz boost_1_72_0 && \

        wget --no-check-certificate https://github.com/mariadb-corporation/mariadb-connector-c/archive/v3.1.7.tar.gz && \
        tar -zxf v3.1.7.tar.gz && \
        cd mariadb-connector-c-3.1.7 && \
        echo "TARGET_LINK_LIBRARIES(libmariadb pthread)" >> libmariadb/CMakeLists.txt && \
        cmake -DWITH_CURL=OFF -DWITH_DYNCOL=OFF -DWITH_MYSQLCOMPAT=ON -DWITH_UNIT_TESTS=OFF . && \
        make -j$(nproc) install && \
        cd .. && \
        rm -rf v3.1.7.tar.gz mariadb-connector-c-3.1.7

编译指令稍作修改

    git https://github.com/trojan-gfw/trojan.git
    cd trojan
    echo 'target_link_libraries(trojan dl)' >> CMakeLists.txt
    cmake -DCMAKE_CXX_FLAGS="-static" -DMYSQL_INCLUDE_DIR=/usr/local/include/mariadb -DMYSQL_LIBRARY=/usr/local/lib/mariadb/libmysqlclient.a -DDEFAULT_CONFIG=/usr/local/trojan.json -DFORCE_TCP_FASTOPEN=ON -DBoost_USE_STATIC_LIBS=ON .
    make
经测试成品可以不需要依赖环境运行在centos6 ，alpine，debian ，Ubuntu16.04

**Comment by 0neday** [comment]
centos 8 
compile error log 

-- The CXX compiler identification is GNU 8.3.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - broken
CMake Error at /usr/local/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /root/trojan/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake cmTC_0b6dc/fast && /usr/bin/gmake -f CMakeFiles/cmTC_0b6dc.dir/build.make CMakeFiles/cmTC_0b6dc.dir/build
    gmake[1]: Entering directory '/root/trojan/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_0b6dc.dir/testCXXCompiler.cxx.o
    /usr/bin/c++    -static    -o CMakeFiles/cmTC_0b6dc.dir/testCXXCompiler.cxx.o -c /root/trojan/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_0b6dc
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0b6dc.dir/link.txt --verbose=1
    /usr/bin/c++  -static     CMakeFiles/cmTC_0b6dc.dir/testCXXCompiler.cxx.o  -o cmTC_0b6dc
    /usr/bin/ld: cannot find -lstdc++
    /usr/bin/ld: cannot find -lm
    /usr/bin/ld: cannot find -lc
    collect2: error: ld returned 1 exit status
    gmake[1]: *** [CMakeFiles/cmTC_0b6dc.dir/build.make:104: cmTC_0b6dc] Error 1
    gmake[1]: Leaving directory '/root/trojan/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:138: cmTC_0b6dc/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/root/trojan/CMakeFiles/CMakeOutput.log".
See also "/root/trojan/CMakeFiles/CMakeError.log".

**Comment by 0neday** [comment]
[root@vultrguest trojan]# cmake  -DCMAKE_CXX_FLAGS="-static" -DBoost_USE_STATIC_LIBS=ON .
-- Found Boost: /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found suitable version "1.72.0", minimum required is "1.66.0") found components: system program_options
-- Found OpenSSL: /usr/local/lib64/libcrypto.a (found suitable version "1.1.1i", minimum required is "1.1.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/trojan
[root@vultrguest trojan]# make
Scanning dependencies of target trojan
[  5%] Building CXX object CMakeFiles/trojan.dir/src/core/authenticator.cpp.o
[ 11%] Building CXX object CMakeFiles/trojan.dir/src/core/config.cpp.o
[ 16%] Building CXX object CMakeFiles/trojan.dir/src/core/log.cpp.o
[ 22%] Building CXX object CMakeFiles/trojan.dir/src/core/service.cpp.o
[ 27%] Building CXX object CMakeFiles/trojan.dir/src/core/version.cpp.o
[ 33%] Building CXX object CMakeFiles/trojan.dir/src/main.cpp.o
[ 38%] Building CXX object CMakeFiles/trojan.dir/src/proto/socks5address.cpp.o
[ 44%] Building CXX object CMakeFiles/trojan.dir/src/proto/trojanrequest.cpp.o
[ 50%] Building CXX object CMakeFiles/trojan.dir/src/proto/udppacket.cpp.o
[ 55%] Building CXX object CMakeFiles/trojan.dir/src/session/clientsession.cpp.o
[ 61%] Building CXX object CMakeFiles/trojan.dir/src/session/forwardsession.cpp.o
[ 66%] Building CXX object CMakeFiles/trojan.dir/src/session/natsession.cpp.o
[ 72%] Building CXX object CMakeFiles/trojan.dir/src/session/serversession.cpp.o
[ 77%] Building CXX object CMakeFiles/trojan.dir/src/session/session.cpp.o
[ 83%] Building CXX object CMakeFiles/trojan.dir/src/session/udpforwardsession.cpp.o
[ 88%] Building CXX object CMakeFiles/trojan.dir/src/ssl/ssldefaults.cpp.o
[ 94%] Building CXX object CMakeFiles/trojan.dir/src/ssl/sslsession.cpp.o
[100%] Linking CXX executable trojan
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/trojan.dir/build.make:345: trojan] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/trojan.dir/all] Error 2
make: *** [Makefile:158: all] Error 2

**Comment by msl4437** [comment]
> [root@vultrguest trojan]# cmake -DCMAKE_CXX_FLAGS="-static" -DBoost_USE_STATIC_LIBS=ON .
> -- Found Boost: /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found suitable version "1.72.0", minimum required is "1.66.0") found components: system program_options
> -- Found OpenSSL: /usr/local/lib64/libcrypto.a (found suitable version "1.1.1i", minimum required is "1.1.0")
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /root/trojan
> [root@vultrguest trojan]# make
> Scanning dependencies of target trojan
> [ 5%] Building CXX object CMakeFiles/trojan.dir/src/core/authenticator.cpp.o
> [ 11%] Building CXX object CMakeFiles/trojan.dir/src/core/config.cpp.o
> [ 16%] Building CXX object CMakeFiles/trojan.dir/src/core/log.cpp.o
> [ 22%] Building CXX object CMakeFiles/trojan.dir/src/core/service.cpp.o
> [ 27%] Building CXX object CMakeFiles/trojan.dir/src/core/version.cpp.o
> [ 33%] Building CXX object CMakeFiles/trojan.dir/src/main.cpp.o
> [ 38%] Building CXX object CMakeFiles/trojan.dir/src/proto/socks5address.cpp.o
> [ 44%] Building CXX object CMakeFiles/trojan.dir/src/proto/trojanrequest.cpp.o
> [ 50%] Building CXX object CMakeFiles/trojan.dir/src/proto/udppacket.cpp.o
> [ 55%] Building CXX object CMakeFiles/trojan.dir/src/session/clientsession.cpp.o
> [ 61%] Building CXX object CMakeFiles/trojan.dir/src/session/forwardsession.cpp.o
> [ 66%] Building CXX object CMakeFiles/trojan.dir/src/session/natsession.cpp.o
> [ 72%] Building CXX object CMakeFiles/trojan.dir/src/session/serversession.cpp.o
> [ 77%] Building CXX object CMakeFiles/trojan.dir/src/session/session.cpp.o
> [ 83%] Building CXX object CMakeFiles/trojan.dir/src/session/udpforwardsession.cpp.o
> [ 88%] Building CXX object CMakeFiles/trojan.dir/src/ssl/ssldefaults.cpp.o
> [ 94%] Building CXX object CMakeFiles/trojan.dir/src/ssl/sslsession.cpp.o
> [100%] Linking CXX executable trojan
> /usr/bin/ld: cannot find -ldl
> /usr/bin/ld: cannot find -lstdc++
> /usr/bin/ld: cannot find -lm
> /usr/bin/ld: cannot find -lpthread
> /usr/bin/ld: cannot find -lc
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/trojan.dir/build.make:345: trojan] Error 1
> make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/trojan.dir/all] Error 2
> make: *** [Makefile:158: all] Error 2

请在alpine中编译

**Comment by 0neday** [comment]
没用过apline. 并非一定要静态，用 LD_LIBRARY_PATH 指定动态库路径。
export LD_LIBRARY_PATH=/opt/trojan/lib:$LD_LIBRARY_PATH

**Comment by 0neday** [comment]
[root@vultrguest trojan-master]# cmake -DCMAKE_CXX_FLAGS="-static"  -DBoost_USE_STATIC_LIBS=ON .
-- Boost 1.66.0 found.
-- Found Boost components:
   system;program_options
-- Found OpenSSL: /usr/local/lib64/libcrypto.a (found suitable version "1.1.1i", minimum required is "1.1.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/trojan-master
[root@vultrguest trojan-master]# make
Scanning dependencies of target trojan
[  5%] Building CXX object CMakeFiles/trojan.dir/src/core/authenticator.cpp.o
[ 11%] Building CXX object CMakeFiles/trojan.dir/src/core/config.cpp.o
[ 16%] Building CXX object CMakeFiles/trojan.dir/src/core/log.cpp.o
[ 22%] Building CXX object CMakeFiles/trojan.dir/src/core/service.cpp.o
[ 27%] Building CXX object CMakeFiles/trojan.dir/src/core/version.cpp.o
[ 33%] Building CXX object CMakeFiles/trojan.dir/src/main.cpp.o
[ 38%] Building CXX object CMakeFiles/trojan.dir/src/proto/socks5address.cpp.o
[ 44%] Building CXX object CMakeFiles/trojan.dir/src/proto/trojanrequest.cpp.o
[ 50%] Building CXX object CMakeFiles/trojan.dir/src/proto/udppacket.cpp.o
[ 55%] Building CXX object CMakeFiles/trojan.dir/src/session/clientsession.cpp.o
[ 61%] Building CXX object CMakeFiles/trojan.dir/src/session/forwardsession.cpp.o
[ 66%] Building CXX object CMakeFiles/trojan.dir/src/session/natsession.cpp.o
[ 72%] Building CXX object CMakeFiles/trojan.dir/src/session/serversession.cpp.o
[ 77%] Building CXX object CMakeFiles/trojan.dir/src/session/session.cpp.o
[ 83%] Building CXX object CMakeFiles/trojan.dir/src/session/udpforwardsession.cpp.o
[ 88%] Building CXX object CMakeFiles/trojan.dir/src/ssl/ssldefaults.cpp.o
[ 94%] Building CXX object CMakeFiles/trojan.dir/src/ssl/sslsession.cpp.o
[100%] Linking CXX executable trojan
CMakeFiles/trojan.dir/src/core/service.cpp.o: In function `boost::asio::detail::resolver_service<boost::asio::ip::tc                                                    p>::resolve(std::shared_ptr<void>&, boost::asio::ip::basic_resolver_query<boost::asio::ip::tcp> const&, boost::syste                                                    m::error_code&)':
service.cpp:(.text._ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEE7resolveERSt10shared_ptrIvERKNS3_20basic_res                                                    olver_queryIS4_EERNS_6system10error_codeE[_ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEE7resolveERSt10shared_                                                    ptrIvERKNS3_20basic_resolver_queryIS4_EERNS_6system10error_codeE]+0xaa): warning: Using 'getaddrinfo' in statically                                                     linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib64/libcrypto.a(b_sock.o): In function `BIO_gethostbyname':
b_sock.c:(.text+0x51): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shar                                                    ed libraries from the glibc version used for linking
/usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x1b8): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x282): undefined reference to `dlerror'
/usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x2f1): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x369): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x3a5): undefined reference to `dlerror'
/usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x451): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x4b1): undefined reference to `dlerror'
/usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x682): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/trojan.dir/build.make:328: trojan] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/trojan.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by wongsyrone** [comment]
This issue is simply a guide on how to compile trojan statically on Alpine Linux. Open another issue if you have questions.

**Comment by GreaterFire** [comment]
@0neday Please, refer to the docs for build guide.

**Comment by wongsyrone** [comment]
Irrelevant comments deleted to make it clear.
