### ISSUE TITLE
disconnect event right after requested connection

### ISSUE THREAD

**Issue by jovirus** [trojan-gfw/trojan#568]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.16.0
The version of trojan you are using.

**Describe the bug**
1. Start trojan service
2. output "trojan service (client) started at 127.0.0.1:4081"
3. output 127.0.0.1:51607 requested connection to github.com:443
4. disconnected, 40 bytes received, 524 bytes sent, lasted for 1 seconds
5. ....
problem: disconnect event right after requested connection.
No data could be sent between client and server. all data blocked down
Go to web browser enter any web. received a generate_204 file  from gstatic.com
My configuration works fine in southern cites closed to HK, since I moved to a south west city. nothing worked.
Where is the log file located? 
my shadowsocks worked fine still. Though long latency around 300ms+

Additional: My fake web(lets encrypt) can be connected via https
ping ip is also responsive.
I used wireshark to monitor transactions, it shows that many transactions from server are marked as Bad TCP 

<img width="1276" alt="Screen Shot 2021-02-04 at 2 52 30 PM" src="https://user-images.githubusercontent.com/1064580/106856057-e7b12180-66f8-11eb-88b6-20cf45262895.png">

**Environment**
client: macos
server: linux

**Comment by strawcarb** [comment]
OSX client could not connect the server.

Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [ERROR] 182.91.179.102:6130 SSL handshake failed: stream truncated
Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [INFO] 182.91.179.102:6130 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [ALL] 182.91.179.102:6132 incoming connection
Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [ERROR] 182.91.179.102:6132 SSL handshake failed: stream truncated
Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [INFO] 182.91.179.102:6132 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
Nov 29 06:18:51 vultr.guest trojan[870]: [2020-11-29 06:18:51] [INFO] 120.230.102.90:10154 disconnected, 213032 bytes received, 285 bytes sent, lasted for 32 seconds
Nov 29 06:18:51 vultr.guest trojan[870]: [2020-11-29 06:18:51] [INFO] 120.230.102.90:10018 disconnected, 409226 bytes received, 281 bytes sent, lasted for 32 seconds
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [ALL] 182.91.179.102:6133 incoming connection
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [ERROR] 182.91.179.102:6133 SSL handshake failed: stream truncated
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [INFO] 182.91.179.102:6133 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [ALL] 182.91.179.102:6134 incoming connection
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [ERROR] 182.91.179.102:6134 SSL handshake failed: stream truncated
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [INFO] 182.91.179.102:6134 disconnected, 0 bytes received, 0 bytes s

**Comment by jovirus** [comment]
after restart everything, it works again.
