### ISSUE TITLE
[BUG] SSL handshake failed: stream truncated

### ISSUE THREAD

**Issue by echocde** [trojan-gfw/trojan#569]
- [x] The OSX could not connect to the server.IOS is OK

**Trojan Version**
1.16.0

**Describe the bug**
OSX client could not connect the server.

Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [ERROR] 182.91.179.102:6130 SSL handshake failed: stream truncated
Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [INFO] 182.91.179.102:6130 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [ALL] 182.91.179.102:6132 incoming connection
Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [ERROR] 182.91.179.102:6132 SSL handshake failed: stream truncated
Nov 29 06:18:45 vultr.guest trojan[870]: [2020-11-29 06:18:45] [INFO] 182.91.179.102:6132 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
Nov 29 06:18:51 vultr.guest trojan[870]: [2020-11-29 06:18:51] [INFO] 120.230.102.90:10154 disconnected, 213032 bytes received, 285 bytes sent, lasted for 32 seconds
Nov 29 06:18:51 vultr.guest trojan[870]: [2020-11-29 06:18:51] [INFO] 120.230.102.90:10018 disconnected, 409226 bytes received, 281 bytes sent, lasted for 32 seconds
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [ALL] 182.91.179.102:6133 incoming connection
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [ERROR] 182.91.179.102:6133 SSL handshake failed: stream truncated
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [INFO] 182.91.179.102:6133 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [ALL] 182.91.179.102:6134 incoming connection
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [ERROR] 182.91.179.102:6134 SSL handshake failed: stream truncated
Nov 29 06:18:55 vultr.guest trojan[870]: [2020-11-29 06:18:55] [INFO] 182.91.179.102:6134 disconnected, 0 bytes received, 0 bytes s

**Comment by Chigusa0w0** [comment]
You are connecting to trojan server with different network. As Vultr is being targeted since long ago, please check your connectivity first.
