### ISSUE TITLE
socks5转http有性能损耗吗?

### ISSUE THREAD

**Issue by lgcde** [trojan-gfw/trojan#57]
![](https://i.loli.net/2019/01/15/5c3db94c535ab.png)
左边是caddy.forwardproxy 右边是trojan
trojan延时高些

httping测试 $httping -g http://google.com --proxy 127.0.0.1:1001 -Y -c 100
同时、同服务器haproxy复用443端口sni分流、都是tls1.3(winshark抓包)
配置是按examples写的,尝试修改"append_payload": false "session_ticket": true 均无改善

连接方式:
httping→privoxy→trojan(client)→trojan(server)→internet
httping→caddy.forwardproxy(http→upstream)→caddy(server)→internet

**Comment by GreaterFire** [comment]
@lgcde Thank you for your report. I'll look into it ASAP. Can you provide packet capture data (you may redact sensitive info)? I want to see whether trojan has more RTTs than Caddy forward proxy.

Also, can you provide your caddy config so I can setup and test it?

**Comment by wongsyrone** [comment]
privoxy在windows上用的是select

**Comment by wongsyrone** [comment]
但golang在win上貌似实现是IOCP

**Comment by GreaterFire** [comment]
@wongsyrone Does `select` cause a near 100-150 ms delay?

**Comment by wongsyrone** [comment]
唔，我不确定，不过性能应该比原生的IOCP差吧，select应该是最后的选择了吧

**Comment by wongsyrone** [comment]
我推荐在linux做同样的测试，privoxy用最新的3.0.28，这个版本做了点优化，应该能比较真实反映trojan和caddy的差异

**Comment by GreaterFire** [comment]
@wongsyrone I think we should eliminate the effect of privoxy. Try proxychains?

**Comment by wongsyrone** [comment]
这样就不能和这个issue里面的数据构成对照组了

**Comment by GreaterFire** [comment]
@wongsyrone We can also use proxychains for httping to use Caddy forward proxy.

**Comment by wongsyrone** [comment]
也可以，我猜测即使这样，golang可能受益于goroutine，比trojan性能好

**Comment by klzgrad** [comment]
Doesn' look like a real or fair comparison. Why would you have caddy forwardproxy locally?

**Comment by lgcde** [comment]
果然有影响
先前没想到直接用torjan socks5测试的方法,现在用firefox+switchomega

trojan(socks5):
![](https://i.loli.net/2019/01/16/5c3edf7b44ec2.png)

trojan(socks5)→privoxy(http):
![](https://i.loli.net/2019/01/16/5c3ee5676b695.png)

trojan(socks5)→glider(http):
![](https://i.loli.net/2019/01/16/5c3edf761c754.png)

caddy.forwardproxy(http):
![](https://i.loli.net/2019/01/16/5c3edf7db8285.png)

trojan+privoxy传输数据略大一些,大约增加130ms以上延时

glider(golang) is a forward proxy with multiple protocols support
glider -listen http://:PORT -forward socks5://[HOST]:PORT

**Comment by lgcde** [comment]
> Doesn' look like a real or fair comparison. Why would you have caddy forwardproxy locally?

http-https转发

**Comment by lgcde** [comment]
> 果然有影响
> 先前没想到直接用torjan socks5测试的方法,现在用firefox+switchomega
> 
> trojan(socks5):
> ![](https://camo.githubusercontent.com/c678887501a1566db58f348c7d36abc8e09219d9/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f31362f356333656466376234346563322e706e67)
> 
> trojan(socks5)→privoxy(http):
> ![](https://camo.githubusercontent.com/43e961efe7022b71851c3e5d09e48fabbf7e50f9/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f31362f356333656535363736623639352e706e67)
> 
> trojan(socks5)→glider(http):
> ![](https://camo.githubusercontent.com/a81649eb1e2eb88288bc18c983811e3aea80a59e/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f31362f356333656466373631633735342e706e67)
> 
> caddy.forwardproxy(http):
> ![](https://camo.githubusercontent.com/6c48eccc97490779c101f83500851d1f4d3bcd73/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f31362f356333656466376462383238352e706e67)
> 
> trojan+privoxy传输数据略大一些,大约增加130ms以上延时
> 
> glider(golang) is a forward proxy with multiple protocols support
> glider -listen http://:PORT -forward socks5://[HOST]:PORT

**Comment by klzgrad** [comment]
> glider

Good one. Looks like this thing does exactly the same as v2ray et al.

> http-https

If you want a fair and real test, try this:

`time curl --proxy socks5h://127.0.0.1`→trojan(client)→trojan(server)→internet 
vs
`time curl --proxy https://server`→caddy.forwardproxy(server)→internet

but we all know if you're doing https proxying with Caddy, it's actually http/2 over tls and that combo does connection multiplexing which amortizes connection setup overhead. *That* is where Caddy does better than a 1:1 connection proxying model.
