### ISSUE TITLE
[BUG]installation failed with brew on Mac m1

### ISSUE THREAD

**Issue by dddd-zdf** [trojan-gfw/trojan#570]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
1.16.0

**Describe the bug**
installation failed at "make install"

**To Reproduce**
in terminal:
```
brew tap trojan-gfw/homebrew-trojan
brew install trojan
```

error follows as:

```
==> Installing trojan from trojan-gfw/trojan
==> Downloading https://github.com/trojan-gfw/trojan/archive/v1.16.0.tar.gz
Already downloaded: /Users/<username>/Library/Caches/Homebrew/downloads/4f04cba5929123f75ebdf05332f2602c4082022d014c0807a808fc15f1e945a4--trojan-1.16.0.tar.gz
==> sed -i  s/server\.json/client.json/ CMakeLists.txt
==> cmake . -DENABLE_MYSQL=OFF
==> make install
Last 15 lines from /Users/<username>/Library/Logs/Homebrew/trojan/03.make:
[100%] Built target trojan
/opt/homebrew/Cellar/cmake/3.19.4/bin/cmake -E cmake_progress_start /tmp/trojan-20210205-41516-uj8dkj/trojan-1.16.0/CMakeFiles 0
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 preinstall
make[1]: Nothing to be done for `preinstall'.
Install the project...
/opt/homebrew/Cellar/cmake/3.19.4/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /opt/homebrew/Cellar/trojan/1.16.0/bin/trojan
CMake Error at cmake_install.cmake:59 (file):
  file cannot create directory:
  /etc/opt/homebrew/Cellar/trojan/1.16.0/trojan.  Maybe need administrative
  privileges.


make: *** [install] Error 1
```

**Expected behavior**
installation complete

**Logs**
N/A

**Environment**
MacBook Air with m1 chip. no proxy needed.

**Additional context**

**Comment by wongsyrone** [comment]
> Maybe need administrative privileges.

**Comment by dddd-zdf** [comment]
> Maybe need administrative privileges.

Homebrew no longer supports running as root so I granted access by

```
sudo chown -R $(whoami) /opt/homebrew/Cellar/
```

where I still got exactly the same error

**Comment by GreaterFire** [comment]
@dddd-zdf Try the pre-built binary?

**Comment by dddd-zdf** [comment]
> @dddd-zdf Try the pre-built binary?

the one in release works perfectly fine. I'm merely trying to put it under brew to manage.

**Comment by wongsyrone** [comment]
> sudo chown -R $(whoami) /opt/homebrew/Cellar/

It's incorrect. If you read the error message carefully, it fails to access `/etc/opt/homebrew/Cellar` when `make install` not `/opt/homebrew/Cellar/`. I don't have any Apple devices and cannot do more.

**Comment by dddd-zdf** [comment]
> > sudo chown -R $(whoami) /opt/homebrew/Cellar/
> 
> It's incorrect. If you read the error message carefully, it fails to access `/etc/opt/homebrew/Cellar` when `make install` not `/opt/homebrew/Cellar/`. I don't have any Apple devices and cannot do more.

I did realize that just now however that points out the real issue. There is no such path that `/etc/opt/homebrew/Cellar` but "cellar" is in `/opt/homebrew/Cellar/`

I figure there is something wrong with the installation script and I'm reading it.

**Comment by hss14** [comment]
> > > sudo chown -R $(whoami) /opt/homebrew/Cellar/
> > 
> > 
> > It's incorrect. If you read the error message carefully, it fails to access `/etc/opt/homebrew/Cellar` when `make install` not `/opt/homebrew/Cellar/`. I don't have any Apple devices and cannot do more.
> 
> I did realize that just now however that points out the real issue. There is no such path that `/etc/opt/homebrew/Cellar` but "cellar" is in `/opt/homebrew/Cellar/`
> 
> I figure there is something wrong with the installation script and I'm reading it.

so any results? I encountered the same problem.

**Comment by dddd-zdf** [comment]
> > > > sudo chown -R $(whoami) /opt/homebrew/Cellar/
> > > 
> > > 
> > > It's incorrect. If you read the error message carefully, it fails to access `/etc/opt/homebrew/Cellar` when `make install` not `/opt/homebrew/Cellar/`. I don't have any Apple devices and cannot do more.
> > 
> > 
> > I did realize that just now however that points out the real issue. There is no such path that `/etc/opt/homebrew/Cellar` but "cellar" is in `/opt/homebrew/Cellar/`
> > I figure there is something wrong with the installation script and I'm reading it.
> 
> so any results? I encountered the same problem.

sry, since I'm not familiar with the script, it took me a while in vain, plus I've been busy with something else during these months. I'm using the pre-built for now but I may spend some time in the future to look into it.
