### ISSUE TITLE
[Feature Request] Provide pre-build static binary in GitHub Releases

### ISSUE THREAD

**Issue by hronro** [trojan-gfw/trojan#572]
- [x ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
I notice there is an issue talking about how to build a static binary (#567), but the original issue was locked, so I have to create a new issue. 

**Is this problem relevant to what trojan should care about?**
Well this is not relevant to any source code of trojan, is about the way of shipping trojan. Considering now we are already shipping pre-build binaries in GitHub Releases, provide one more static binary should be reasonable.

**Describe the solution you'd like**
I haven't use Azure pipeline yet, maybe just add one more target?

**Comment by msl4437** [comment]
[trojan.zip](https://github.com/trojan-gfw/trojan/files/5971935/trojan.zip)
我这里编译了一份成品，你试试看。

**Comment by hronro** [comment]
Well I have to say this might be the rudest maintainer I've ever seen.
