### ISSUE TITLE
 fatal: use_certificate_chain_file: Permission denied

### ISSUE THREAD

**Issue by FrankKirin** [trojan-gfw/trojan#573]
看到过把证书权限和证书目录权限改为755的解决方案，无效，改成777也无法解决，不知道该怎么做？
服务器无法启动trojan 服务

服务器配置文件如下：
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "password",
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/root/.acme.sh/domain_ecc/fullchain.cer",
        "key": "/root/.acme.sh/domain_ecc/domain.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "key": "",
        "cert": "",
        "ca": ""
    }
}

**Comment by 0neday** [comment]
change dir 
```
"cert": "/root/.acme.sh/domain_ecc/fullchain.cer",
"key": "/root/.acme.sh/domain_ecc/domain.key",
```
to 
```
"cert": "/opt/domain_ecc/fullchain.cer",
"key": "/opt/domain_ecc/domain.key",
```

**Comment by FrankKirin** [comment]
> change dir
> 
> ```
> "cert": "/root/.acme.sh/domain_ecc/fullchain.cer",
> "key": "/root/.acme.sh/domain_ecc/domain.key",
> ```
> 
> to
> 
> ```
> "cert": "/opt/domain_ecc/fullchain.cer",
> "key": "/opt/domain_ecc/domain.key",
> ```

It works! Thank you.
