### ISSUE TITLE
enable trojan server to listen on both IPv4 and IPv6

### ISSUE THREAD

**Issue by hss14** [trojan-gfw/trojan#577]
Hi~ 

My trojan server has a domain name that can be resolved to both IPv4 and IPv6 addresses, so I would like the trojan server to listen on both IPv4 and IPv6. 

I tried but failed. It can listen on either IPv4 or IPv6, but not both. 

And I found that `local_addr` is `std::string` in the [source code](https://github.com/trojan-gfw/trojan/blob/master/src/core/config.h). So it seems that we can only set one address as the `local_addr`?

So can we enable the trojan server to listen on both IPv4 and IPv6? And how? 

Thank you so much for developing this extremely helpful tool!

**Comment by abbottjlu** [comment]
Does this work for you? 
```
    "run_type": "server",
    "local_addr": "::",
```

**Comment by hss14** [comment]
> Does this work for you?
> 
> ```
>     "run_type": "server",
>     "local_addr": "::",
> ```

yes it works! Thank you for much!
