### ISSUE TITLE
TCP_FASTOPEN_CONNECT is not supported

### ISSUE THREAD

**Issue by 1v9** [trojan-gfw/trojan#58]
My client is Windows 10 and Trojan works perfect. There is only one issue. I enabled fastopen (include trojan config and system operation) on bothside but I got this. 
```
Welcome to trojan 1.10.0
[2019-01-26 11:20:22] [WARN] TCP_FASTOPEN_CONNECT is not supported
[2019-01-26 11:20:22] [FATAL] trojan service (client) started at 127.0.0.1:800
```
I don't know why, here is my config.
```
# server config 
"tcp": {
        "prefer_ipv4": true,
        "no_delay": true,
        "keep_alive": true,
        "fast_open": true,
        "fast_open_qlen": 20
    }

# client config
"tcp": {
        "no_delay": true,
        "keep_alive": true,
        "fast_open": true,
        "fast_open_qlen": 20
    }
```

**Comment by KunagisaYuki** [comment]
@1v9 Please note that `TCP_FASTOPEN_CONNECT` (client side tcp fastopen per trojan's implementation) is only supported in Linux and not available in Windows, which is mentioned in the log.

**Comment by 1v9** [comment]
@KunagisaYuki Thank you. Is there any plan to support TFO on Windows, or is this impossible?

**Comment by GreaterFire** [comment]
@1v9 A lot of changes (basically a rewrite) has to be done on the code base.
TFO doesn't provide a significant improvement and is vulnerable to a certain kind of attack, so we generally don't recommend enabling it.
