### ISSUE TITLE
[Feature Request]plain_http_response好像不是返回一個HTML檔？

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/trojan#580]
- [X] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**
plain_http_response不是返回一個HTML檔？
`"plain_http_response": "/etc/trojan/trojan.html",`
用瀏覽器打開「https://trojan_server/」，顯示「trojan_server didn’t send any data」，而不是顯示trojan.html的內容。

**Describe alternatives you've considered**

**Additional context**

**Comment by GreaterFire** [comment]
@okudayukiko try http instead of https

**Comment by okudayukiko** [comment]
> @okudayukiko try http instead of https

http://trojan_server:443/
Protocol error

**Comment by Chigusa0w0** [comment]
Kinda duplicate #457 
What you should provide is a TCP dump. In your case, it should be a whole valid HTTP response (header+body), typically starts with "HTTP/1.1". You should never provide an HTML file directly unless you know what you are doing.
