### ISSUE TITLE
[Feature Request]请问可否增加屏蔽指定domain功能？

### ISSUE THREAD

**Issue by zhucaidan** [trojan-gfw/trojan#581]
请问下Trojan是否支持当客户端访问指定域名时返回null

从而达到屏蔽指定域名访问功能

config中没看到可以实现，可否增加屏蔽指定domain功能？

**Comment by Chigusa0w0** [comment]
Trojan is a general purpose proxy software. It is NOT designed specially for HTTP(S) protocols. So, as what you requested relys on the assumption that the inner protocol is HTTP(S), it will not be considered.

**Comment by Chigusa0w0** [comment]
If you really want to do that, the best approach is to audit connections on your server (for example, block IPs of websites via firewall). It would be rather complicate and error-prone to handle such "feature" in Trojan codebase.

**Comment by zhucaidan** [comment]
ok, thx
