### ISSUE TITLE
Disable trojan console 

### ISSUE THREAD

**Issue by a13519** [trojan-gfw/trojan#583]
I am not sure if the console can be disabled. If yes could you show me how to do it.

I think it could be a security venerability that the console was presented by default, anyone can easily screen the site by keywords of trojan.

That will be nice to have a customized console path and port, at same time put a switch to enable or disable it.

Thanks,

**Comment by Chigusa0w0** [comment]
Trojan do NOT support disabling shell output. If you want to "no-output", please try [redirection](https://www.gnu.org/software/bash/manual/html_node/Redirections.html). Trojan mainly uses `stderr` to output messages.

Anyway, if someone can view your shell activity, they are most likely already gained the capability to access your shell, or even your local files. So disabling shell output can hardly be considered as a security improvement.

**Comment by a13519** [comment]
Hi, Thanks for your message, what I mean is the web console used to manage
the trojan, that's a risk if someone scan the main page which the url are
exposed to public when use it.

**Comment by GreaterFire** [comment]
@a13519 There is no such thing as a web console.

**Comment by a13519** [comment]
How about this? after installing the trojan, it came at once.

**Comment by Chigusa0w0** [comment]
@a13519 We cannot observe any additional information in your last reply. Please note that response via email is not "what you see is what you get". Attachments and unsupported styles may be discard without warning.
