### ISSUE TITLE
【咨询】有没有更详细的trojan协议文档

### ISSUE THREAD

**Issue by kdyzm** [trojan-gfw/trojan#585]
目前打算使用java实现简单的trojan客户端，但是感觉trojan协议描述的不是很清楚，我找到了协议文档  
https://github.com/trojan-gfw/trojan/blob/master/docs/protocol.md  
但是文档中有几处疑问  

1. tls连接之后要发送以下结构的内容

| hex(SHA224(password)) |  CRLF   | Trojan Request |  CRLF   | Payload  |
|-----------------------|---------|----------------|---------|----------|
|          56           | X'0D0A' |    Variable    | X'0D0A' | Variable |

我认为这是trojan协议握手的请求，这个时候Payload字段有何作用？  难道说同一个连接中的每次数据请求都要将请求的数据放到Payload字段吗。。。  
文档中表示发送完该内容后trojan服务端会打开一个连接目标服务器的通道，然后转发该连接中的所有请求到目标服务器，关键是这第一个请求没有响应客户端吗，socks5的connet请求是要响应客户端的吧，这里trojan协议握手是不是也有个响应才对，响应格式是啥
2. Trojan Request 字段

| CMD | ATYP | DST.ADDR | DST.PORT |
|-----|------|----------|----------|
|  1  |  1   | Variable |    2     |

协议中 DST.ADDR是可变长字段，这个字段如果是Sockts5-like，是不是应该如果是ipv4，则固定4个字节长度；如果是域名类型，则第一个字节是域名长度，后面是域名内容？

希望大佬指点指点~

**Comment by Chigusa0w0** [comment]
1a. Payload is the first user request data, bundled within the initial packet.
https://github.com/trojan-gfw/trojan/blob/3e7bb9aecdc694f9bcae8d646fae395f773d60f8/src/session/serversession.cpp#L169-L170

1b. Response data is written to socket as-is
https://github.com/trojan-gfw/trojan/blob/3e7bb9aecdc694f9bcae8d646fae395f773d60f8/src/session/serversession.cpp#L255-L260

2. Partially correct
https://github.com/trojan-gfw/trojan/blob/3e7bb9aecdc694f9bcae8d646fae395f773d60f8/src/proto/socks5address.cpp#L31-L71
