### ISSUE TITLE
It shows "Bad CPU type in executable" when I use Macbook Air with the latest M1 CPU. Is it possible to be compatible with this NEW CPU, thanks..  [BUG]

### ISSUE THREAD

**Issue by yufengwa** [trojan-gfw/trojan#589]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of trojan, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, my issue will be closed immediately without any notice.

**Trojan Version**
The version of trojan you are using.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment**
Where are you running trojan? What is your proxy set up?

**Additional context**

**Comment by Chigusa0w0** [comment]
You can compile it by yourself or try third-party build at your own risk, like this one #579.
