### ISSUE TITLE
Don't print FATAL on server start

### ISSUE THREAD

**Issue by klzgrad** [trojan-gfw/trojan#59]
```
[FATAL] trojan service (server) started at 0.0.0.0:443
```
Doesn't look fatal to me.

**Comment by GreaterFire** [comment]
What log level would you recommend?
https://github.com/trojan-gfw/trojan/blob/master/src/service.cpp#L204

**Comment by wongsyrone** [comment]
Why not choose INFO for both start and stop

**Comment by GreaterFire** [comment]
@wongsyrone I was thinking about using the highest log level for start and stop so whichever log level you set, this info will be logged.

**Comment by Chigusa0w0** [comment]
It's FATAL to your adversary LoL. Alright, not so fatal.
