### ISSUE TITLE
[Feature Request] Support socks4

### ISSUE THREAD

**Issue by Spencerzy** [trojan-gfw/trojan#590]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
Windows built-in proxy only supports socksv4 not socks5. I spent few hours in setting up another proxy to get it work: socks5 proxy=> http proxy => trojan client. Supporting socksv4 will be very user-friendly to Windows users and save them lots of effort.

**Is this problem relevant to what trojan should care about?**
More easy usage and friently to windows users to set up system-level proxy.

**Describe the solution you'd like**
Support socks4.

**Describe alternatives you've considered**

**Additional context**

**Comment by GreaterFire** [comment]
@Spencerzy SOCKS4 doesn't support remote DNS so we don't consider it

**Comment by Spencerzy** [comment]
How about integrating a http proxy to provide user more options not just socks5?

**Comment by Chigusa0w0** [comment]
This is Trojan Core repo, not Trojan UI.
