### ISSUE TITLE
[Feature Request] The network traffic forwarded to the upstream retains the real client IP.

### ISSUE THREAD

**Issue by ghost** [trojan-gfw/trojan#591]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
Currently, the traffic forwarded by trojan to remote_addr does not set the real client IP, so upstream websites, such as Nginx, believe that all requests received are from 127.0.0.1, which causes the statistical features of the website to not work.
![image](https://user-images.githubusercontent.com/53471588/120902332-60f25e00-c672-11eb-9b35-b8a624cbd8c3.png)

**Is this problem relevant to what trojan should care about?**
Trojan is a protocol implementation, not a full-fledged proxy client. Features such as custom routing will not be accepted.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Chigusa0w0** [comment]
Trojan will not add such feature #377 but you can use Nginx to append such information in the connection https://github.com/trojan-gfw/trojan/issues/433#issuecomment-692878138
