### ISSUE TITLE
trojan 使用 443 端口被封了

### ISSUE THREAD

**Issue by doghappy** [trojan-gfw/trojan#597]
我使用 nginx 443 转发到 trojan，实现共用 443 端口，它一直工作得很好。但是在 2021/6/28 下午，443 端口被封了。有其他网友遇到这种现象吗？

**Comment by doghappy** [comment]
伪装的网站是 Welcome to CentOS 的默认网页，是否与这个有关系？

**Comment by dotAge** [comment]
我现在一直报dial tcp4 .... i/o timeout

**Comment by dotAge** [comment]
确认80端口可连接，但443则连接失败，手机数据信号及多个宽带网络都不行了。
Trojan服务器端换443以外的端口可行吗？

**Comment by doghappy** [comment]
我跟你的提示一样，最终确定是端口被封了。更换端口可以继续使用服务，但有网友反馈说，如果更换端口再次被识别，可能会封锁 ip，请慎重。

如果只有一台 vps，尝试更换协议和端口。

我是中午看了一会油管后被封的。

**Comment by wongsyrone** [comment]
> 我现在一直报dial tcp4 .... i/o timeout

你这个也不是trojan-gfw的输出啊

**Comment by doghappy** [comment]
trojan服务端正常，这个是v2rayN客户端的输出。

**Comment by dotAge** [comment]
> > 我现在一直报dial tcp4 .... i/o timeout
> 
> 你这个也不是trojan-gfw的输出啊

我这个是clash for android的日志

**Comment by dotAge** [comment]
> 我跟你的提示一样，最终确定是端口被封了。更换端口可以继续使用服务，但有网友反馈说，如果更换端口再次被识别，可能会封锁 ip，请慎重。
> 
> 如果只有一台 vps，尝试更换协议和端口。
> 
> 我是中午看了一会油管后被封的。

如何更换服务器端口？

**Comment by xiaobovlog** [comment]
So do I, 6/28/2021

**Comment by jackxiaoo** [comment]
Maybe the https SSL have broken

**Comment by jackxiaoo** [comment]
new install script , good project. https://github.com/jinwyp/one_click_script

**Comment by wongsyrone** [comment]
> 共用 443 端口

其他共用的都有什么服务，伪装站怎么搭建的

**Comment by BaiqingL** [comment]
换个端口搭建服务，我之前也有遇到这个问题。

**Comment by kgiflwl** [comment]
2021/6/29中午开始不能访问，ping.pe正常，port.ping.pe发现443端口被封，80端口到目前2021/6/30，trojan仍然可以接到http请求。伪装网站是每月定期从某hub.io搬运，时常有随机更新。

可能是某种行为pattern被标记了。

**Comment by wongsyrone** [comment]
搭建是否使用一键脚本，如果使用给出链接地址

**Comment by kgiflwl** [comment]
> 搭建是否使用一键脚本，如果使用给出链接地址

从头搭建的，根据https://trojan-gfw.github.io/trojan
已正常使用一年有余，每次有新release都会更新，用的客户端：自己在openwrt编的、shadowrocket、igniter

**Comment by wongsyrone** [comment]
伪装站的nginx配置和伪装站源码

**Comment by kgiflwl** [comment]
> 伪装站的nginx配置和伪装站源码

伪站源mlcommons.org，nginx是原始debian 10 deb包默认配置未修改（稍后附上），只用80，用trojan伪装nginx 443。cert是letsencrypt对应debian+nginx，每90天更新

**Comment by kgiflwl** [comment]
> nginx是原始debian 10 deb包默认配置未修改（稍后附上）

[nginx.zip](https://github.com/trojan-gfw/trojan/files/6737121/nginx.zip)

**Comment by kgiflwl** [comment]
trojan log，能看到从80进去的请求被识别，trojan转给nginx。443发过去的已经收不到了。除了443，其它维护端口都是通的。

**Comment by doghappy** [comment]
> > 共用 443 端口
> 
> 
> 
> 其他共用的都有什么服务，伪装站怎么搭建的

trojan-gfw 使用官方镜像运行的容器，用物理机非443端口映射容器443端口，证书使用 certbot/let's encrypt 申请，也映射了到容器中。

nginx 监听443和80

搭建流程： https://doghappy.wang/Article/Detail/10183

**Comment by wongsyrone** [comment]
目前上面几位看不出问题，贴一下目前暂时没有被封锁的流程：

1. nginx server_tokens off
2. nginx 监听0.0.0.0:80 并仅负责301到443， nginx监听127.0.0.1:80 托管伪装站
3. trojan监听0.0.0.0:443，负责接入所有外部443请求

**Comment by kgiflwl** [comment]
> nginx server_tokens off

这个我没设，可能的原因之一

**Comment by xhrm** [comment]
近期多个服务器443被封，其他端口正常，从海外访问正常，国内GG

**Comment by kgiflwl** [comment]
我们应该尽可能的列举使用习惯、流量习惯、客户端习惯这些，看看pattern标记的漏洞在哪里。trojan protocol本身已经论证过不少回了，能被标记的概率比较小。

**Comment by BaiqingL** [comment]
> > nginx server_tokens off
> 
> 这个我没设，可能的原因之一

这个只是表明不会反馈nginx版本，是个常见的安全措施，不至于成为原因之一。

**Comment by 0neday** [comment]
trojan 已经被标记为可识别的协议

**Comment by strongbugman** [comment]
我这的伪装站挂了，不知道是不是这个原因

**Comment by xiaobovlog** [comment]
有可能是伪装站挂了的原因，我的也变成了nginx的默认页面了

**Comment by keengrass** [comment]
> 换个端口搭建服务，我之前也有遇到这个问题。

换个端口搭建会不会容易直接封IP了？（裸奔）

**Comment by ghost** [comment]
我两个节点作为备份，所以我的ssh流量我也走trojan，这样可以突破公网对ssh的限制。以前都一直好好的，这几天不行了。我节点可以上github.com和google.com，但是ssh连不上。我不知道是否ssh over tls被GFW识别了？

这两天两个节点也挂了一个，换了IP只管了几个小时。还好还有一个可以用的。

是无差别封锁还是trojan不再坚挺了呢，我的节点应该2年多了，一直挺稳定的，以前关键时期都没出过问题，这次挂了。

**Comment by earth-5G** [comment]
> 我两个节点作为备份，所以我的ssh流量我也走trojan，这样可以突破公网对ssh的限制。以前都一直好好的，这几天不行了。我节点可以上github.com和google.com，但是ssh连不上。我不知道是否ssh over tls被GFW识别了？
> 
> 这两天两个节点也挂了一个，换了IP只管了几个小时。还好还有一个可以用的。
> 
> 是无差别封锁还是trojan不再坚挺了呢，我的节点应该2年多了，一直挺稳定的，以前关键时期都没出过问题，这次挂了。

无差别i封锁 之前64就大面积封杀了一次，现在我i在这里还一切安好！

**Comment by fourdim** [comment]
Sever side log
```
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-06-30 06:54:00 EDT; 4min 28s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
 Main PID: 1479 (trojan)
    Tasks: 2 (limit: 1168)
   Memory: 1.2M
   CGroup: /system.slice/trojan.service
           └─1479 /usr/local/bin/trojan /usr/local/etc/trojan/config.json

Jun 30 06:54:00 systemd[1]: Started trojan.
Jun 30 06:54:00 trojan[1479]: Welcome to trojan 1.16.0
Jun 30 06:54:00 trojan[1479]: [2021-06-30 06:54:00] [WARN] trojan service (server) started at 0.0.0.0:443
Jun 30 06:54:04 trojan[1479]: [2021-06-30 06:54:04] [WARN]  *.*.*.*:4480 not trojan request, connecting to 127.0.0.1:80
Jun 30 06:54:04 trojan[1479]: [2021-06-30 06:54:04] [INFO]  *.*.*.*:4480 disconnected, 2929 bytes received, 283 bytes sent, lasted for 1 seconds
Jun 30 06:56:33 trojan[1479]: [2021-06-30 06:56:33] [WARN]  *.*.*.*:57321 not trojan request, connecting to 127.0.0.1:80
Jun 30 06:57:38 trojan[1479]: [2021-06-30 06:57:38] [INFO]  *.*.*.*:57321 disconnected, 1372 bytes received, 1384 bytes sent, lasted for 65 seconds
Jun 30 06:58:02 trojan[1479]: [2021-06-30 06:58:02] [WARN]  *.*.*.*:50887 not trojan request, connecting to 127.0.0.1:80
Jun 30 06:58:04 trojan[1479]: [2021-06-30 06:58:04] [WARN] *.*.*.*:42921 not trojan request, connecting to 127.0.0.1:80
```

The thing is these requests should be trojan requests. However, trojan proxies them to port 80.

**Comment by sheiy** [comment]
我也被封了

**Comment by YongChingShieh** [comment]
我也被封了

**Comment by intgyl** [comment]
我的也不行了，也是443端口被封了，能不能支持cdn

**Comment by Maimez** [comment]
+1

**Comment by imoonkin** [comment]
应该是油管导致的，前一天开看过别的，挺正常的，看了油管就凉凉了

**Comment by Yppup** [comment]
俺也一样

**Comment by PSC-F** [comment]
+1

**Comment by 747969780** [comment]
+1， 近期443端口被封，但其他开启的端口没问题，然后换成4413，今天又被封了，服务器上除了这两个端口，其他开启的端口都访问正常

**Comment by 747969780** [comment]
> 我跟你的提示一样，最终确定是端口被封了。更换端口可以继续使用服务，但有网友反馈说，如果更换端口再次被识别，可能会封锁 ip，请慎重。
> 
> 如果只有一台 vps，尝试更换协议和端口。
> 
> 我是中午看了一会油管后被封的。

我也是中午看了油管后被封

**Comment by aperioristo** [comment]
前来汇报，443 over~
上次64也是前后封锁了5天，这次71是29号开始至今，目前还没解封。
我“认为”应该是无差别封锁疑似IP的端口。
比如监测到这个IP长期大流量，或者是长期由固定的几个国内用户对其链接并保持大流量。
我“认为”可能增加伪装站的流量和IP数量或许可以解决此事。
比如伪装站做成一个资源更丰富的视频网站，然后长期用流量精灵跑PV。

**Comment by Mao-jiawei** [comment]
> 前来汇报，443 over~
> 
> 上次64也是前后封锁了5天，这次71是29号开始至今，目前还没解封。
> 
> 我“认为”应该是无差别封锁疑似IP的端口。
> 
> 比如监测到这个IP长期大流量，或者是长期由固定的几个国内用户对其链接并保持大流量。
> 
> 我“认为”可能增加伪装站的流量和IP数量或许可以解决此事。
> 
> 比如伪装站做成一个资源更丰富的视频网站，然后长期用流量精灵跑PV。

伪装怕是墙在偷笑

**Comment by Krysme** [comment]
你们是不是用的香港的？我这边香港的主机443端口被墙，但是美国的那台就还好。

**Comment by aperioristo** [comment]
对，的确是香港的，不过今天上午已经恢复正常了。

发自我的iPhone

**Comment by kgiflwl** [comment]
> 2021/6/29中午开始不能访问，ping.pe正常，port.ping.pe发现443端口被封，80端口到目前2021/6/30，trojan仍然可以接到http请求。伪装网站是每月定期从某hub.io搬运，时常有随机更新。
>
> 可能是某种行为pattern被标记了。

今天发现443端口已恢复。此前发现被封以后我主动关闭此端口5天，并无其它操作。
看起来只是发现单端口持续大流量进行的无差别封锁，GFW并不能认定，所以敏感时间过后主动解封。

**Comment by aperioristo** [comment]
> > 2021/6/29中午开始不能访问，ping.pe正常，port.ping.pe发现443端口被封，80端口到目前2021/6/30，trojan仍然可以接到http请求。伪装网站是每月定期从某hub.io搬运，时常有随机更新。
> > 可能是某种行为pattern被标记了。
> 
> 今天发现443端口已恢复。此前发现被封以后我主动关闭此端口5天，并无其它操作。
> 看起来只是发现单端口持续大流量进行的无差别封锁，GFW并不能认定，所以敏感时间过后主动解封。

对，我已经几乎确定是宁可杀错不可放过式的对所有可疑IP的可疑端口进行封锁。
为了避免误杀，并没有封IP和其他端口，并且也会主动解封，避免影响过大。

我准备将端口切换到宝塔面板的888端口，等待下次规模封锁看看会不会有好的结果。

**Comment by sheiy** [comment]
已恢复。。。

**Comment by ningfeiyu** [comment]
之前好像也是这么回事，法定节假日就会这样几天。。。。真是有病。

**Comment by doghappy** [comment]
443 这两天再次被封，是直接封锁高危ip段吗？

**Comment by ningfeiyu** [comment]
我感觉就是敏感节日就会这样。。。

HeroWong ***@***.***> 于2022年2月2日周三 12:39写道：

**Comment by free-znet** [comment]
我也被封了，443端口，不过我没使用后过了几天又好了，要是能支持 cdn 就好了。。

**Comment by ningfeiyu** [comment]
过年期间封了半个月443端口，今天试一下又好了。中间还重新安装了一遍
不知道咋回事。。。


trojan ***@***.***> 于2022年2月11日周五 18:57写道：

**Comment by chenmin1992** [comment]
我也被封了，443端口，伪装站是一个 html 模板，封之前使用腾讯云的轻量服务器通过 iptables 转发流量来着，从 2022/02/25 到 2022/03/02 期间封禁，3号早上通过 https://port.ping.pe/ 测试端口已经解封，服务可以正常使用。
麻烦官方作者查看一下是不是被识别了流量，还是其他特征识别的。

**Comment by keengrass** [comment]
和流量大小有关系。BAN了解了，解了又被ban， 换端口也是一样，最近一直在反复。感觉这个脚本已经不能再用了。

**Comment by ningfeiyu** [comment]
你是一直看YouTube吗？我改了一次端口后现在就没ban了。我之前就是会看youtube直播，视频。说说你们被ban之前的操作看。

keengrass ***@***.***> 于2022年3月3日周四 11:11写道：

**Comment by lalinking** [comment]
被封来报道。
同样是443阵亡，80仍然正常。
我是俄罗斯的vps。

**Comment by eelzs** [comment]
我是2月开始出现被封，更换ip后，大约2周会再次封，平常不看视频，只搜索资料时用用。

**Comment by Mao-jiawei** [comment]
> 我是2月开始出现被封，更换ip后，大约2周会再次封，平常不看视频，只搜索资料时用用。

我有个方案 写个crontab任务  每2小时stop一次trojan  当要用的时候登录服务器手动起服务

**Comment by billowing** [comment]
我今天也被封了，今年被封了很多次了，腾讯云的轻量服务器，好像也是昨天看了油管，今天就挂了.......

**Comment by Yangtzeus** [comment]
#可以发现，在被封的例子中基本都有个共同点：都是在流量大量交换后被封（如看youtube视频）。个人认为GFW目前由于trojan的特殊的一般性（使用最常见的https）无法辨认一个网站是否存在代理，因而对短时间内大流量交换的网站进行端口阻塞TCP封锁(阻断)。解决端口阻塞，若单纯地更换trojan端口，引用一段话回应：“GFW之所以单独封一个端口，可能原因就是吃不准到底是不是代理，如果你很快就换了端口继续做代理，那么GFW就认为很大概率是代理，于是就可以封禁了。”（此处的封禁包括但不限于：封ip，DNS劫持，TCP RST阻断）So，那么目前可靠的解决方法便是套CDN（比如cloudflare），当然这是trojan-go才可实现的；或者更换为 v2ray（或xray）+ws+tls（但个人测试trojan-go+CDN效果好于v2ray+ws+tls）。最后补充一点：建议伪装网站用动态的（比如cloudreve网盘？），这样才说得通大流量交换（感觉GFW是有人工审查网页的，不然你想想对着个静态网页撸出了几G流量，怎么能说得清）。

以上个人拙见，包含自己的理解，可能有所偏差。
参考：
https://doubibackup.com/_2y705r7-2.html
http://www.oneyearago.me/2019/06/14/learn_gwf/

**Comment by aperioristo** [comment]
是的，我最近被封了很多端口，而最近和之前最大的变化是我和朋友都在居家看netflix。
所以我也认为是持续大流量造成的“宁可杀错不可放过”。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 中午1:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [trojan-gfw/trojan] trojan 使用 443 端口被封了 (#597)





 
#可以发现，在被封的例子中基本都有个共同点：都是在流量大量交换后被封（如看youtube视频）。个人认为GFW目前由于trojan的特殊的一般性（使用最常见的https）无法辨认一个网站是否存在代理，因而对短时间内大流量交换的网站进行端口阻塞TCP封锁(阻断)。解决端口阻塞，若单纯地更换trojan端口，引用一段话回应：“GFW之所以单独封一个端口，可能原因就是吃不准到底是不是代理，如果你很快就换了端口继续做代理，那么GFW就认为很大概率是代理，于是就可以封禁了。”（此处的封禁包括但不限于：封ip，DNS劫持，TCP RST阻断）So，那么目前可靠的解决方法便是套CDN（比如cloudflare），当然这是trojan-go才可实现的；或者更换为 v2ray（或xray）+ws+tls（但个人测试trojan-go+CDN效果好于v2ray+ws+tls）。最后补充一点：建议伪装网站用动态的（比如cloudreve网盘？），这样才说得通大流量交换（感觉GFW是有人工审查网页的，不然你想想对着个静态网页撸出了几G流量，怎么能说得清）。
 
以上个人拙见，包含自己的理解，可能有所偏差。
 参考：
 https://doubibackup.com/_2y705r7-2.html
 http://www.oneyearago.me/2019/06/14/learn_gwf/

**Comment by YongChingShieh** [comment]
根据我的观察  在ipv4的443端口会被封锁 但ipv6不会 理由如下
 在2台oracle的vps上分别搭建了v2ray 和trojan 同时开启ipv4和ipv6
经过一段时间后 搭建trojan的机器 ipv4 443端口被封锁 而ipv6没有问题  v2ray的ipv4和ipv6都没有问题

**Comment by aperioristo** [comment]
所以，v2ray是什么原因导致没有问题？从理论来说，trojan不会被成功探测。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YongChing ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 晚上7:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [trojan-gfw/trojan] trojan 使用 443 端口被封了 (#597)





 
根据我的观察  在ipv4的443端口会被封锁 但ipv6不会 理由如下
 在2台oracle的vps上分别搭建了v2ray 和trojan 同时开启ipv4和ipv6
 经过一段时间后 搭建trojan的机器 ipv4 443端口被封锁 而ipv6没有问题  v2ray的ipv4和ipv6都没有问题

**Comment by YongChingShieh** [comment]
> 

个人推测是和运行机制有关系 v2ray是在网站后面运行 而trojan是放在网站前面运行   请参考下面的图示 我在oracle上搭建也是和下面这个图一样
![Image1](https://user-images.githubusercontent.com/24885976/163559238-fc0f6a53-77dc-40d6-9d40-e81dc1a3dd5c.png)

**Comment by Mao-jiawei** [comment]
> > 
> 
> 
> 
> 个人推测是和运行机制有关系 v2ray是在网站后面运行 而trojan是放在网站前面运行   请参考下面的图示 我在oracle上搭建也是和下面这个图一样
> 
> ![Image1](https://user-images.githubusercontent.com/24885976/163559238-fc0f6a53-77dc-40d6-9d40-e81dc1a3dd5c.png)
> 
> 

nginx还能代理v2ray？

**Comment by YongChingShieh** [comment]
> 

请参考下面这个



v2ray服务端:
> {
  "inbounds": [{
      "port": 8080,
      "protocol": "vless",
     "settings": {
		   "decryption": "none",
        "clients": [{
          "id": "",//uuid
          "alterId": 64
        }]
      },
      "streamSettings":{
          "wsSettings":{
              "path":"/proxy",
              "headers":{}
          },
          "network":"ws",
          "security": "none"
      }
    }
  ],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  }]
}

v2ray客户端
> 
{
	 "log": {
    "loglevel": "warning",  
    "access": "",  
    "error": ""
  },
  "inbounds": [
    {
      "port": 10083,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "域名或ip地址",
            "port": 443,
            "users": [
              {
				 "encryption":"none",
                "id": "",//服务端id
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
		  "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "wsSettings": {
          "path": "/proxy"
        }
      }
    }
  ]
}

nginx:
> 
server {
 listen 80 default_server;
    listen [::]:80 default_server;
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;
  
  ssl_certificate       /etc/letsencrypt/live/v.yching.gq/fullchain.pem;//证书路径
  ssl_certificate_key   /etc/letsencrypt/live/v.yching.gq/privkey.pem; //证书路径
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  
  ssl_protocols         TLSv1.2 TLSv1.3;
  ssl_ciphers           ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;
  
  server_name           _;
  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains;" always; 
    if ($scheme = http) {
        return 301 https://$server_name$request_uri;
}
  location /proxy {  
    if ($http_upgrade != "websocket") {  
        return 404;
    }
    proxy_redirect off;
    proxy_pass http://127.0.0.1:8080; 
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    # Show real IP in v2ray access.log
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}

**Comment by lalinking** [comment]
> 我是2月开始出现被封，更换ip后，大约2周会再次封，平常不看视频，只搜索资料时用用。

我也是，不过我现在换成 nginx 走443，trojan 走80 （没换机器ip），一个月了暂时80没被封。

**Comment by HappyLife-page** [comment]
> 所以，v2ray是什么原因导致没有问题？从理论来说，trojan不会被成功探测。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YongChing ***@***.***&gt;; 发送时间: 2022年4月14日(星期四) 晚上7:18 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [trojan-gfw/trojan] trojan 使用 443 端口被封了 (#597) 根据我的观察 在ipv4的443端口会被封锁 但ipv6不会 理由如下 在2台oracle的vps上分别搭建了v2ray 和trojan 同时开启ipv4和ipv6 经过一段时间后 搭建trojan的机器 ipv4 443端口被封锁 而ipv6没有问题 v2ray的ipv4和ipv6都没有问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

v2ray: ws+tls+vless 两年多任何时候从未中断过，稳如泰山，无任何伪装站点和页面，默认nginx首页
trojan设计理念应该没问题，问题最大的地方在于，如果没有ws的path前置支持，任何伪装都没用。
这个逻辑是：v2ray的ws的path在被请求访问时默认是加密的，也即只有ws的支持才是最安全的伪装，任何人都获取不到你的真实访问url，这好比访问Java服务页面，浏览器地址栏是加密的一样，gfw不能因为这个地址是加密的就干扰你。
所以目前来看，最安全稳定的方案：ws是必不可少的（不使用ws而只靠伪装站，可能你的伪装站就是最大的特征）

**Comment by HappyLife-page** [comment]
> > 所以，v2ray是什么原因导致没有问题？从理论来说，trojan不会被成功探测。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "YongChing _**@**_._**>; 发送时间: 2022年4月14日(星期四) 晚上7:18 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [trojan-gfw/trojan] trojan 使用 443 端口被封了 (#597) 根据我的观察 在ipv4的443端口会被封锁 但ipv6不会 理由如下 在2台oracle的vps上分别搭建了v2ray 和trojan 同时开启ipv4和ipv6 经过一段时间后 搭建trojan的机器 ipv4 443端口被封锁 而ipv6没有问题 v2ray的ipv4和ipv6都没有问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> v2ray: ws+tls+vless 两年多任何时候从未中断过，稳如泰山，无任何伪装站点和页面，默认nginx首页 trojan设计理念应该没问题，问题最大的地方在于，如果没有ws的path前置支持，任何伪装都没用。 这个逻辑是：v2ray的ws的path在被请求访问时默认是加密的，也即只有ws的支持才是最安全的伪装，任何人都获取不到你的真实访问url，这好比访问Java服务页面，浏览器地址栏是加密的一样，gfw不能因为这个地址是加密的就干扰你。 所以目前来看，最安全稳定的方案：ws是必不可少的（不使用ws而只靠伪装站，可能你的伪装站就是最大的特征）

参考：https://www.happylife.page/107/2

**Comment by sjush** [comment]
> 我们应该尽可能的列举使用习惯、流量习惯、客户端习惯这些，看看pattern标记的漏洞在哪里。trojan protocol本身已经论证过不少回了，能被标记的概率比较小。

也许是youtube流量即使加密过也有宏观特征

**Comment by toyo2333** [comment]
> > 所以，v2ray是什么原因导致没有问题？从理论来说，trojan不会被成功探测。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "YongChing _**@**_._**>; 发送时间: 2022年4月14日(星期四) 晚上7:18 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [trojan-gfw/trojan] trojan 使用 443 端口被封了 (#597) 根据我的观察 在ipv4的443端口会被封锁 但ipv6不会 理由如下 在2台oracle的vps上分别搭建了v2ray 和trojan 同时开启ipv4和ipv6 经过一段时间后 搭建trojan的机器 ipv4 443端口被封锁 而ipv6没有问题 v2ray的ipv4和ipv6都没有问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> v2ray: ws+tls+vless 两年多任何时候从未中断过，稳如泰山，无任何伪装站点和页面，默认nginx首页 trojan设计理念应该没问题，问题最大的地方在于，如果没有ws的path前置支持，任何伪装都没用。 这个逻辑是：v2ray的ws的path在被请求访问时默认是加密的，也即只有ws的支持才是最安全的伪装，任何人都获取不到你的真实访问url，这好比访问Java服务页面，浏览器地址栏是加密的一样，gfw不能因为这个地址是加密的就干扰你。 所以目前来看，最安全稳定的方案：ws是必不可少的（不使用ws而只靠伪装站，可能你的伪装站就是最大的特征）

用的vless+ws+TLS+Nginx，其他的方案和你的基本一样。Nginx在前面通过tls访问，vless内容通过路径转发给xray。

不同的是，我在nginx做了个转发。就是直接访问域名的话，跳到别的站的页面比如bing.com，或者某个网盘的域名，或者下载站的域名

 ```
    location / {
           proxy_pass https://bing.com; #伪装网址
           proxy_redirect off;
           proxy_ssl_server_name on;
           sub_filter_once off;
           sub_filter "bing.com" $server_name;
           proxy_set_header Host "bing.com";
           proxy_set_header Referer $http_referer;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header User-Agent $http_user_agent;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto https;
           proxy_set_header Accept-Encoding "";
           proxy_set_header Accept-Language "zh-CN";
```

用了半个月没任何问题，但是昨天晚上443被封了。这个会是因为设置那个伪装网址的做法不合适么？（相比你这种不设置任何伪装站点或者转发）

有什么改进建议呢？谢谢！

**Comment by HappyLife-page** [comment]
伪装不至于暴露
需要注意1,尽量使用ios系统
2,pc端尽量不要安装国产软件，如果可以应该使用mac系统

最近比较严，许多知名vps厂商都是重点关注对象，IP容易被特别关照，可以尝试小众地区

**Comment by ArcCal** [comment]
如果坚持要用trojan，客户端不要使用官方的，必封

**Comment by birdeagles** [comment]
> > > 所以，v2ray是什么原因导致没有问题？从理论来说，trojan不会被成功探测。
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "YongChing _**@**_._**>; 发送时间: 2022年4月14日(星期四) 晚上7:18 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [trojan-gfw/trojan] trojan 使用 443 端口被封了 (#597) 根据我的观察 在ipv4的443端口会被封锁 但ipv6不会 理由如下 在2台oracle的vps上分别搭建了v2ray 和trojan 同时开启ipv4和ipv6 经过一段时间后 搭建trojan的机器 ipv4 443端口被封锁 而ipv6没有问题 v2ray的ipv4和ipv6都没有问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > v2ray: ws+tls+vless 两年多任何时候从未中断过，稳如泰山，无任何伪装站点和页面，默认nginx首页 trojan设计理念应该没问题，问题最大的地方在于，如果没有ws的path前置支持，任何伪装都没用。 这个逻辑是：v2ray的ws的path在被请求访问时默认是加密的，也即只有ws的支持才是最安全的伪装，任何人都获取不到你的真实访问url，这好比访问Java服务页面，浏览器地址栏是加密的一样，gfw不能因为这个地址是加密的就干扰你。 所以目前来看，最安全稳定的方案：ws是必不可少的（不使用ws而只靠伪装站，可能你的伪装站就是最大的特征）
> 
> 用的vless+ws+TLS+Nginx，其他的方案和你的基本一样。Nginx在前面通过tls访问，vless内容通过路径转发给xray。
> 
> 不同的是，我在nginx做了个转发。就是直接访问域名的话，跳到别的站的页面比如bing.com，或者某个网盘的域名，或者下载站的域名
> 
> ```
>    location / {
>           proxy_pass https://bing.com; #伪装网址
>           proxy_redirect off;
>           proxy_ssl_server_name on;
>           sub_filter_once off;
>           sub_filter "bing.com" $server_name;
>           proxy_set_header Host "bing.com";
>           proxy_set_header Referer $http_referer;
>           proxy_set_header X-Real-IP $remote_addr;
>           proxy_set_header User-Agent $http_user_agent;
>           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>           proxy_set_header X-Forwarded-Proto https;
>           proxy_set_header Accept-Encoding "";
>           proxy_set_header Accept-Language "zh-CN";
> ```
> 
> 用了半个月没任何问题，但是昨天晚上443被封了。这个会是因为设置那个伪装网址的做法不合适么？（相比你这种不设置任何伪装站点或者转发）
> 
> 有什么改进建议呢？谢谢！

我的和你的一樣，用nginx做僞裝，就是web+ws+tsl+v2ray，有一個vps剛建好就被封了，另一個用了兩天也挂了。我懷疑這種方式的某個特徵已經能被GFW探測出來，所以才被封的。如果不做改進繼續建站，結局也是一樣。可以試試把nginx的監聽端口換了，如果還是被封，十有八九就是被探測了，如果能繼續運行，那就是443被針對。
因爲本來這樣做法是把加密數據僞裝成HTTPS放在HTTPS這個森林裏，結果可能這棵樹長得太特別了，所以被發現

**Comment by ArcCal** [comment]
> 所以，v2ray是什么原因导致没有问题？从理论来说，trojan不会被成功探测。

谁说的trojan不会被成功探测?

**Comment by birdeagles** [comment]
> > 所以，v2ray是什么原因导致没有问题？从理论来说，trojan不会被成功探测。
> 
> 谁说的理论来说，trojan不会被成功探测

trojan已经可以被精准识别了，请参看下面的视频

https://www.youtube.com/watch?v=Z_URro3bZqM
