### ISSUE TITLE
Fatal: open: too many open files

### ISSUE THREAD

**Issue by klzgrad** [trojan-gfw/trojan#60]
Trojan died after a while.

**Comment by GreaterFire** [comment]
Maybe it is because of too many connections. Try raising the hard and soft limit of max fd?

**Comment by wongsyrone** [comment]
How to reproduce the issue?

**Comment by klzgrad** [comment]
I don't know. In principle open() should check for EMFILE and fail gracefully. But I don't see where open() is called in this.

**Comment by GreaterFire** [comment]
@klzgrad Maybe somewhere inside asio's code throws. We should catch that.

**Comment by klzgrad** [comment]
I got another case of this. I'll post coredump next time.

**Comment by GreaterFire** [comment]
@klzgrad You can set the max fd limit down and test.
