### ISSUE TITLE
希望trojan软件可以显示tls证书的关键信息

### ISSUE THREAD

**Issue by jacklee789** [trojan-gfw/trojan#601]
有些trojan节点采用不可验证自签名tls证书，之前是可以翻墙的。
但现在墙审查tls证书，这些trojan节点的443端口已不能翻墙了，非443端口暂时还可以翻墙。

下面这个网站可以查看Trojan节点的服务器是否配置了可验证的tls证书
https://www.websiteplanet.com/zh-hans/webtools/ssl-checker/

下面两个网站的trojan节点都配置了可验证的tls证书。
EDITed by wongsyrone: **_[ADs removed]_**

**Comment by Chigusa0w0** [comment]
Closed (Suspected Ads)
