### ISSUE TITLE
[BUG] SSL handshake failed with xxx.xxx.xxx:443 

### ISSUE THREAD

**Issue by crackfan** [trojan-gfw/trojan#603]
- centos7
- nginx
- trojan+ssl (by let's encrypt)

[Trojan] [2021-07-11 09:19:17] [INFO] 127.0.0.1:51548 disconnected, 0 bytes received, 282 bytes sent, lasted for 0 seconds
[Trojan] [2021-07-11 09:19:17] [INFO] 127.0.0.1:49868 requested connection to chromiumextension.com:443
[Trojan] [2021-07-11 09:19:17] [INFO] 127.0.0.1:49868 disconnected, 0 bytes received, 282 bytes sent, lasted for 0 seconds
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:58854 requested connection to chromiumextension.com:443
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:61527 requested connection to chromiumextension.com:443
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:52859 requested connection to chromiumextension.com:443
[Trojan] [2021-07-11 09:19:18] [ERROR] 127.0.0.1:61527 SSL handshake failed with xxx.xxx.xxx:443: Զ������ǿ�ȹر���һ�����е����ӡ�
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:61527 disconnected, 0 bytes received, 286 bytes sent, lasted for 0 seconds
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:57004 requested connection to chromiumextension.com:443
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:52859 disconnected, 0 bytes received, 286 bytes sent, lasted for 0 seconds
[Trojan] [2021-07-11 09:19:18] [ERROR] 127.0.0.1:57004 SSL handshake failed with xxx.xxx.xxx:443: Զ������ǿ�ȹر���һ�����е����ӡ�
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:57004 disconnected, 0 bytes received, 286 bytes sent, lasted for 0 seconds
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:58372 requested connection to chromiumextension.com:443
[Trojan] [2021-07-11 09:19:18] [ERROR] 127.0.0.1:58372 SSL handshake failed with xxx.xxx.xxx:443: Զ������ǿ�ȹر���һ�����е����ӡ�
[Trojan] [2021-07-11 09:19:18] [INFO] 127.0.0.1:58372 disconnected, 0 bytes received, 286 bytes sent, lasted for 0 seconds
[Trojan] [2021-07-11 09:19:19] [INFO] 127.0.0.1:63518 requested connection to chromiumextension.com:443
[Trojan] [2021-07-11 09:19:19] [INFO] 127.0.0.1:58854 disconnected, 0 bytes received, 286 bytes sent, lasted for 1 seconds
[Trojan] [2021-07-11 09:19:19] [ERROR] 127.0.0.1:63518 SSL handshake failed with xxx.xxx.xxx:443: Զ������ǿ�ȹر���һ�����е����ӡ�
[Trojan] [2021-07-11 09:19:19] [INFO] 127.0.0.1:63518 disconnected, 0 bytes received, 282 bytes sent, lasted for 0 seconds
[Trojan] [2021-07-11 09:19:19] [INFO] 127.0.0.1:63323 requested connection to chromiumextension.com:443

**Comment by 0xj0hn** [comment]
How did you fix it? @crackfan
