### ISSUE TITLE
windows 客户端不能启动

### ISSUE THREAD

**Issue by TangBoheng** [trojan-gfw/trojan#605]
今天突然windows 客户端不能启动，类似于闪退。查了杀毒软件黑名单之类的没有在里面。有没有地方可以输出日志查看原因？

**Comment by TangBoheng** [comment]
端口被占用了

**Comment by Soulwander2010** [comment]
大佬，请教一下，端口被占用了，怎么解决的？

**Comment by Soulwander2010** [comment]
> 端口被占用了
大佬，请教一下，端口被占用了，怎么解决的？
