### ISSUE TITLE
如何代理到https的remote addr

### ISSUE THREAD

**Issue by sheiy** [trojan-gfw/trojan#607]
![image](https://user-images.githubusercontent.com/12210038/130194591-f029a411-6015-4c70-9e61-745acfb6e5e9.png)

**Comment by sheiy** [comment]
@felixonmars @xsm1997   
https://github.com/sheiy/trojan
我想实现多remote add 代理  通过http header 里的host来区分走哪个remote 服务
现在代理http的remote addr可以  但是https的不行

**Comment by icpz** [comment]
I think the behavior you described is by design. Trojan performs TLS termination on those fallback requests. So you should not put a https host in the remote_addr field.

**Comment by sheiy** [comment]
@icpz Is there have some way to support https host in the remote_addr field?

**Comment by Chigusa0w0** [comment]
If you want to dispatch requests to different services, you may need to use other tools, like nginx or haproxy (#131), to do that. Trojan is not designed to be used as a dispatcher.

Trojan can not connect to HTTPS backend by implementation. If you have to do that, I believe you should setup a local proxy to wrap the HTTP request with TLS (for example, by using reverse proxy).

**Comment by sheiy** [comment]
@Chigusa0w0 ok thanks
