### ISSUE TITLE
[BUG]开了forward和nat访问google还是不行

### ISSUE THREAD

**Issue by chainofhonor** [trojan-gfw/trojan#609]
用一台rockylinux当软路由
eth0是内网
eth1是外网
firewall开启转发
然后下面的客户端可以正常访问网络了

然后开始配置
国外的一台服务器上配置好了server
在软路由上配置了forward和nat   ipset也设置好了

实测访问国外IP的网站的时候会正常的从nat走
解析域名也能正常的走forward

访问部分网站比如github正常
但是访问google就提示网络异常  

软路由配置client模式,然后浏览器用switchyomega插件的话就是正常的
但是我想弄全局的,就像上面那样操作了,不知道为什么会有部分网站异常

**Comment by chainofhonor** [comment]
......找到原因了  
dnsmasq开了缓存 解析的还是缓存的被污染的地址 
把dnsmasq的缓存功能关闭就正常了 

我写了个脚本全自动的把"解析的IP是国外"的域名自动添加到5353端口  
技术有限,只能用这种笨办法 
感觉DNS服务器应该出一个功能的,自动统计那些域名的IP地址是国外的,然后把这些域名自动转发到5353端口去解析

**Comment by Metric640** [comment]
Trojan不再开发了吗？
