### ISSUE TITLE
[Feature Request] 是否支持在ssl server hello阶段，传输假证书，以哄骗GFW

### ISSUE THREAD

**Issue by luuillu** [trojan-gfw/trojan#613]
通信过程中使用的真实证书通常是没有备案的，容易被GFW阻挡。如果让GFW看到的是大厂已备案的域名，是否会降低阻挡概率？

具体操作是:
1. 准备实际通信过程中所需的真实域名对应的证书和秘钥文件CertA和KeyA
2. 找一个已备案的域名B(比如baidu.com),然后得到对应的证书CertB
3. 在torjanServer端设置CertA 和KeyA ,启动ssl Server。
4. torjanClient端连接Server的时候，先发Client Hello 包，客户端先把Client Hello 包中的SNI字段改成域名B，然后发给torjanServer
5. torjanServer 给客户端返回Server Hello后，会下发证书CertA，在server端拦截这个证书，替换成CertB， 发给torjanClient。
6. torjanClient收到CertB后，按预先约定，把CertB还原会CertA，交给ssl库处理， 继续后面的通信。

最终想要实现的效果是，客户端与server实际通信的证书是CertA， 而网络中传输的证书是CertB。

**Comment by netheril96** [comment]
你自己弄的baidu.com的证书必然是假的，GFW一看就知道你在使坏

**Comment by luuillu** [comment]
baidu.com的证书可以直接从baidu.com网站下载，和baidu.com建立ssl连接就取到真实的证书了。所以可以得到真实的证书，只是得不到证书对应的私钥。然而GFW没法确认我只有证书而没有私钥。

**Comment by Chigusa0w0** [comment]
This design will break existing installations and may prevent normal browsers/active probers from validating the cert.

We will not consider this proposal. Yet, you can fork and develop it yourself.
