### ISSUE TITLE
如何在termux上编译 trojan

### ISSUE THREAD

**Issue by shawokou123** [trojan-gfw/trojan#617]
运行环境：
未root的 termux

求助问题：
如何在termux上编译 trojan

**Comment by shawokou123** [comment]
以上问题已经解决，大家可以按如下办法，在termux上安装、编译 使用trojan，不需要root:
1、
apt install cmake boost mariadb
2、
cd $TMPDIR
3、提前挂上其他代理，让终端可以科学上网
4、
git clone 'https://github.com/trojan-gfw/trojan.git' --depth=1
5、
cd trojan
6、
cmake -DMYSQL_INCLUDE_DIR=$PREFIX/include/mariadb/ -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX .
7、
make
8、
make install
9、至第8步，整个编译完成，直接使用：
./trojan -c xxx.json
即可使用

**Comment by Ltre** [comment]
> 以上问题已经解决，大家可以按如下办法，在termux上安装、编译 使用trojan，不需要root: 1、 apt install cmake boost mariadb 2、 cd $TMPDIR 3、提前挂上其他代理，让终端可以科学上网 4、 git clone 'https://github.com/trojan-gfw/trojan.git' --depth=1 5、 cd trojan 6、 cmake -DMYSQL_INCLUDE_DIR=$PREFIX/include/mariadb/ -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX . 7、 make 8、 make install 9、至第8步，整个编译完成，直接使用： ./trojan -c xxx.json 即可使用

你的是arm架构吗？我的照做不行


`$ cmake -DMYSQL_INCLUDE_DIR=$PREFIX/include/mariadb/ -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX .
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/data/data/com.termux/files/home/mydir/bin/trojan/trojan-dev/Boost_INCLUDE_DIR
   used as include directory in directory /data/data/com.termux/files/home/mydir/bin/trojan/trojan-dev

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
$ make install
[  5%] Building CXX object CMakeFiles/trojan.dir/src/core/authenticator.cpp.o
In file included from /data/data/com.termux/files/home/mydir/bin/trojan/trojan-dev/src/core/authenticator.cpp:20:
In file included from /data/data/com.termux/files/home/mydir/bin/trojan/trojan-dev/src/core/authenticator.h:26:
/data/data/com.termux/files/home/mydir/bin/trojan/trojan-dev/src/core/config.h:25:10: fatal error: 'boost/property_tree/ptree.hpp' file not found
#include <boost/property_tree/ptree.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/trojan.dir/build.make:76: CMakeFiles/trojan.dir/src/core/authenticator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/trojan.dir/all] Error 2
make: *** [Makefile:146: all] Error 2`
