### ISSUE TITLE
Does this project still in development?

### ISSUE THREAD

**Issue by moonpole** [trojan-gfw/trojan#627]
It seems this project haven't updated since Nov 2020. Does this project still in development?

My primary concern is the safety of GreaterFire and the seconds is: is it still unidentifiable by the GFW?

**Comment by GreaterFire** [comment]
@moonpole Hi! Thanks for your concern. I'm perfectly fine, just shifted my interest to other stuff in my life. As for the protocol, I don't think it's identifiable, but GFW is clearly taking actions to block port 443 indiscriminately.

**Comment by moonpole** [comment]
@GreaterFire I'm glad to hear that. Thanks for developing such a great software to the world.
