### ISSUE TITLE
支持国内直连么

### ISSUE THREAD

**Issue by jiangxiaoqiang** [trojan-gfw/trojan#645]
可否配置国内直连

**Comment by chainofhonor** [comment]
可以 我就是这样用的  服务器建议选国外的 别选香港的

**Comment by jiangxiaoqiang** [comment]
你是怎么配置的啊，现在不管上任何网络都慢，估计是走了代理， 我用的trojan官方客户端

**Comment by chainofhonor** [comment]
我用一台rockylinux当软路由 
然后在这台软路由上配置了trojan的forward和nat  
用的dnsmasq当DHCP和dns服务

iptables配置防火墙,国内的IP走正常出口 国外的IP走trojan-nat

**Comment by jacklu2016** [comment]
> 我用一台rockylinux当软路由 然后在这台软路由上配置了trojan的forward和nat 用的dnsmasq当DHCP和dns服务
> 
> iptables配置防火墙,国内的IP走正常出口 国外的IP走trojan-nat

怎么配置的？ 老哥
