### ISSUE TITLE
macOS: [FATAL] fatal: config.json: cannot open file

### ISSUE THREAD

**Issue by zeku2022** [trojan-gfw/trojan#68]
**I've edited the "config.json" file and downloaded the "private.crt" to the directory**
`"cert": "/etc/ssl/cert.pem"`
`"cert": "private.crt"`,
**which one is correct?**

**When i run the trojan exec file,it shows :**
[2019-02-22 09:44:54] [FATAL] fatal: config.json: cannot open file
[2019-02-22 09:44:54] [FATAL] exiting. . . 
**what's wrong?  please help.**

**Comment by Chigusa0w0** [comment]
@xiaoxiongke The first one is correct. But the error log indicates that you are not facing an issue with cert file. The true problem is that Trojan CANNOT open and read config.json. This may caused by wrong file path or insufficient file privilege. Please check you have correctly set these values.

**Comment by GreaterFire** [comment]
@xiaoxiongke Try running the start.command provided. Also, you should use a certificate to put in the config file, not a private key.

**Comment by zeku2022** [comment]
> @xiaoxiongke The first one is correct. But the error log indicates that you are not facing an issue with cert file. The true problem is that Trojan CANNOT open and read config.json. This may caused by wrong file path or insufficient file privilege. Please check you have correctly set these values.

The config.json' file content shows below, I think it doesn't have any problems.And the file path or privilege are all ok. 
`
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 10800,
    "remote_addr": "XXXXXXXX",
    "remote_port": 443,
    "password": [
        "XXXlovetrojan"
    ],
    "append_payload": true,
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "/etc/ssl/cert.pem",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305-SHA256:ECDHE-RSA-CHACHA20-POLY1305-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:RSA-AES128-GCM-SHA256:RSA-AES256-GCM-SHA384:RSA-AES128-SHA:RSA-AES256-SHA:RSA-3DES-EDE-SHA",
        "sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}
`

**Comment by zeku2022** [comment]
> @xiaoxiongke Try running the start.command provided. Also, you should use a certificate to put in the config file, not a private key.

Sorry,there' no start.command....

**Comment by GreaterFire** [comment]
@xiaoxiongke Launch a terminal, cd to the trojan directory, and run ./trojan config.json

**Comment by zeku2022** [comment]
> @xiaoxiongke Launch a terminal, cd to the trojan directory, and run ./trojan config.json

Thanks,I've tried.But it seems the cert config is wrong...
`
[FATAL] trojan service (client) started at 127.0.0.1:1080
[2019-02-22 10:46:38] [INFO] 127.0.0.1:51916 requested connection to www.youtube.com:443
[2019-02-22 10:46:38] [ERROR] 127.0.0.1:51916 SSL handshake failed with xxxxxxx.xyz:443: certificate verify failed
[2019-02-22 10:46:38] [INFO] 127.0.0.1:51916 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
`

**Comment by zeku2022** [comment]
> @xiaoxiongke Launch a terminal, cd to the trojan directory, and run ./trojan config.json

Finally I edit the config.json file,and change `"cert": "/etc/ssl/cert.pem"` to `"cert": "private.crt"`,then it runs very well....

**Comment by gaojiweish** [comment]
masOS catalin run is the same error, don't know you solved no？
