### ISSUE TITLE
Cannot install on Fedora 29

### ISSUE THREAD

**Issue by kamasylvia** [trojan-gfw/trojan#75]
Followed the wiki, Fedora 28 installed trojan successfully but Fedora 29 failed. The error is `Error: Failed to synchronize cache for repo 'fei1yang/trojan'`. SELinux and firewall are already closed.

**Comment by ghost** [comment]
@ZhangYue-vhyt Sorry,but I am not able to build packages for Fedora 29.
You can use the binary in releases page.

**Comment by kamasylvia** [comment]
I switched to Fedora 28 now. Can you mark this on the Wiki?

**Comment by ghost** [comment]
@ZhangYue-vhyt I suggest you to use the latest system and software.
Also,I remove my fedora copr repo from the wiki.
