### ISSUE TITLE
socks5 not work on windows system proxy setting

### ISSUE THREAD

**Issue by Bubblingo0** [trojan-gfw/trojan#76]
I was trying to add automatic system proxy setting to trojan-qt on windows , but when i only set 127.0.0.1:xxx to Internet Proxy Settings->Socks (Use the same proxy server for all protocols not checked, HTTP, Secure , FTP are cleared)

log  shows:

` [ERROR] 127.0.0.1:15769 unknown protocol
`

socks5 works fine on chrome + SwitchyOmega
http proxy works fine with Privoxy forward-socks5
socks5 not work with Privoxy forward-socks5

**Comment by GreaterFire** [comment]
@HernWang Windows only supports SOCKS4.

**Comment by Bubblingo0** [comment]
Thanks for the prompt reply,  so i guess implement windows system proxy settings requires Privoxy like ss and v2ray.
What i found is that when i use Privoxy to forward trojan socks5 that socks can't work even with chrome + SwitchyOmega (only http works).

**Comment by GreaterFire** [comment]
@HernWang Privoxy is a HTTP proxy. Trojan is a SOCKS5 proxy.

**Comment by Bubblingo0** [comment]
ok, i got it. shadowsocksr has implemented http/socks5 on same port, just notice that.

**Comment by Chigusa0w0** [comment]
@HernWang You should use Proxifier instead.
