### ISSUE TITLE
Support UDP forwarding

### ISSUE THREAD

**Issue by HarukaMa** [trojan-gfw/trojan#81]
Seems that forwarding mode only supports TCP protocol and I couldn't find a way to encapsulate UDP packets through it. Is it possible to support UDP forwarding in the future?

Specifically I was trying to tunnel wireguard traffic through trojan, and obviously proxy is not supported.

**Comment by GreaterFire** [comment]
UDP forwarding is supported. It uses SOCKS5 `UDP ASSOCIATE` specified [here](https://tools.ietf.org/html/rfc1928). Unfortunately, few applications support this, so the applicability is limited.

**Comment by HarukaMa** [comment]
As forward mode directly processes raw TCP connection, is it possible to also apply that to UDP connections?

**Comment by GreaterFire** [comment]
It's possible, but hard to implement.

**Comment by HarukaMa** [comment]
Using redsocks could do the work at the moment.

**Comment by GreaterFire** [comment]
Feature added in `dev` branch.
