### ISSUE TITLE
Is trojan able to bypass the cert-filter of GFW to my letsencrypt SSL certification

### ISSUE THREAD

**Issue by yyuurrii34** [trojan-gfw/trojan#88]
it is said that gfw has a sort of function to recognize and filter the certifications simply by type name or trusted user list.
for  an official or business use of an SSL in https get apply(as my connection disguised to be),this letsencrypt cert generated by certbot can't be that ordinary.
if the gfw were trying to make cert type list of all connections detected,what was mine would be an outstanding one and would possibly cause an termination for a reason of recognized unsafe connection or so.
does trojan have any solution to this issue?
'cos it will be a another big cost if i buy a real cert for my domain.

**Comment by GreaterFire** [comment]
@yyuurrii34 No. You'll have to buy one if that really happens. Trojan cannot help.

**Comment by Chigusa0w0** [comment]
@yyuurrii34 There are millions of websites using Let's Encrypt. Which the fact itself, alongside an appropriate choice of cover site, is already the best disguise. If you are trying to disguise as a gov or commercial website, then you really should buy a certificate, or reconsider your choice.

**Comment by yyuurrii34** [comment]
> @yyuurrii34 There are millions of websites using Let's Encrypt. Which the fact itself, alongside an appropriate choice of cover site, is already the best disguise. If you are trying to disguise as a gov or commercial website, then you really should buy a certificate, or reconsider your choice.

got it ,thank you so much
