### ISSUE TITLE
can you tell me how to apply udp forward.json config file

### ISSUE THREAD

**Issue by yyuurrii34** [trojan-gfw/trojan#89]
exactly the question in the tittle.
how to apply the udp-forwarding.json config file,by what argument of the main application?
I only know -c is to use the config.json file,what about the udp-forwarding

**Comment by GreaterFire** [comment]
@yyuurrii34 I'm not quite sure what your use case is. Can you elaborate on that? Also, please provide your config file if necessary.

**Comment by yyuurrii34** [comment]
I'd like to trans-send all the flows through an udp tunnel customized to port 20942/udp,then let my server transport all these flows to port 443/tcp which is the trojan https service listening port.
'cos by a mean that UDP will accelerate the buffer speed and increase the buffer size when i'm watching flow video on internet,as i assume it is a fully use of the trans-send-receive ability of my server.
the udp-forwarding.json config file is not much different with your forward.json example in the repo.
I've tried some other independent application such as kcptun,but it seemed that kcptun won't cooperate well with trojan,only part of the flows go through kcptun,and either a termination of trojan or kcptun will cause a fatal error to entire connection.
@GreaterFire

**Comment by GreaterFire** [comment]
Sounds like you want to use a UDP tunnel in between trojan client and server. In this case, the connection should look like:
```
Trojan Client --- KCPTun Client --- KCPTun Server --- Trojan Server
```
You'll still want to use the client config instead of forward config.

**Comment by GreaterFire** [comment]
More specifically, the `remote_*` options in trojan client should be pointed to the address and port of your kcptun client (don't forget to set `SNI` field to your trojan server domain name). The target settings of your kcptun server should be pointed to the address and port of your trojan server. (Configure other things as normal.)

As a side note, the use of a UDP tunnel defies the purpose of trojan. That is, to imitate other services to make the proxy service unidentifiable.

**Comment by yyuurrii34** [comment]
thanks a lot for your help.maybe it's the sni that cause the collapse of my kcptun service.
what i was thinking was just using trojan as a game speeder or flow video accelerator.As kcp is an unscripted proto on internet,i do not think this will to any nature change the https disguise of trojan.

**Comment by GreaterFire** [comment]
@yyuurrii34 If you leave the SNI field blank, you'll get a certificate verify error.

**Comment by yyuurrii34** [comment]
@greaterfire  got it.I should have either set the SNI or configure both the httpd server and the client to skip the certification verifying.I prefer the second choice. 
anyway thank you very much for your help

**Comment by GreaterFire** [comment]
@yyuurrii34 The second choice will put you in a dangerous spot where you can be MitMed.
