### ISSUE TITLE
图标可以设置隐藏吗

### ISSUE THREAD

**Issue by fredericky123** [trojan-gfw/trojan#91]
RT,想让它在任务栏隐藏的图标默默运行，何以实现？

**Comment by GreaterFire** [comment]
@fredericky123 This behavior involves some Windows specific code, which is not preferred in this project. I suggest you make trojan a system service.

**Comment by skygate2012** [comment]
You can run it in background with VBScript, I haven't found any workaround to hide it to tray though.
```
Dim objShell
Set objShell = WScript.CreateObject("WScript.Shell")
objShell.Run "trojan.exe", 0
Set objShell = Nothing
```

**Comment by fredericky123** [comment]
https://wangye.org/blog/archives/644/
this tool is easy to use.

**Comment by siaimes** [comment]
[CommandTrayHost](https://github.com/rexdf/CommandTrayHost/releases/latest)控制台托盘化工具！
