### ISSUE TITLE
Can't receive any data after downloading for a long time

### ISSUE THREAD

**Issue by zhoutingztzt** [trojan-gfw/trojan#93]
I downloaded a large ZIP file, about 33GB, and the download time was long. At the time of download, I can't receive any data about every 30 minutes. 

I used the `systemctl status trojan.service` command to check status of trojan service. 
The service is running, and the connection with my client is also established. But can't receive any data, I can only restart trojan.service

the system is debian 9

**Comment by GreaterFire** [comment]
@abelZhou123 What version are you using?

**Comment by zhoutingztzt** [comment]
trojan 1.12.2

**Comment by GreaterFire** [comment]
At the time this bug is triggered, is it possible to establish new connections or just that connection isn't working? Is there anything strange in the log?

**Comment by zhoutingztzt** [comment]
the log is about like this:
Jun 04 07:57:42 localhost.localdomain trojan[19146]: [2019-06-04 07:57:42] [INFO] xxx.xxx.xxx.xxx:xxx established, 0 bytes received, 0 bytes sent, lasted for 35 seconds

**Comment by zhoutingztzt** [comment]
this bug is triggered just now, and the log is:
Jun 04 08:52:10 localhost.localdomain trojan[19195]: [2019-06-04 08:52:10] [INFO] xxx.xxx.xxx.xxx:xxx authenticated as xxx
Jun 04 08:52:10 localhost.localdomain trojan[19195]: [2019-06-04 08:52:10] [INFO] xxx.xxx.xxx.xxx:xxx requested connection to nl-rcd.iqiyi.com:443
Jun 04 08:52:22 localhost.localdomain trojan[19195]: [2019-06-04 08:52:22] [INFO] xxx.xxx.xxx.xxx:xxx disconnected, 1208 bytes received, 1273 bytes sent, lasted for 241 seconds
Jun 04 08:52:25 localhost.localdomain trojan[19195]: [2019-06-04 08:52:25] [INFO] xxx.xxx.xxx.xxx:xxx disconnected, 1279 bytes received, 1477 bytes sent, lasted for 241 seconds
Jun 04 08:52:29 localhost.localdomain trojan[19195]: [2019-06-04 08:52:29] [INFO] xxx.xxx.xxx.xxx:xxx disconnected, 7763 bytes received, 15224 bytes sent, lasted for 662 seconds
Jun 04 08:52:41 localhost.localdomain trojan[19195]: [2019-06-04 08:52:41] [INFO] xxx.xxx.xxx.xxx:xxx authenticated as xxx
Jun 04 08:52:41 localhost.localdomain trojan[19195]: [2019-06-04 08:52:41] [INFO] xxx.xxx.xxx.xxx:xxx requested connection to cache.video.iqiyi.com:443
Jun 04 08:52:45 localhost.localdomain trojan[19195]: [2019-06-04 08:52:45] [INFO] xxx.xxx.xxx.xxx:xxx authenticated as xxx
Jun 04 08:52:45 localhost.localdomain trojan[19195]: [2019-06-04 08:52:45] [INFO] xxx.xxx.xxx.xxx:xxx requested connection to clients1.google.com:443
Jun 04 08:53:08 localhost.localdomain trojan[19195]: [2019-06-04 08:53:08] [INFO] xxx.xxx.xxx.xxx:xxx disconnected, 7785040 bytes received, 346 bytes sent, lasted for 72 seconds

**Comment by emiyalee1005** [comment]
I happen to have the similar issue. In some random cases, after a period of time the client can not send or receive any data. So i check the client log and can't see any new connections established, the log seem to stuck there. And also check the server log and everything looks good includeing the network between C/S.  After restarting the client trojan.exe, everything works fine again. It happens for around 20 times within one week usage.

Btw I have 4 servers (hk+usa+jp+singapore) running ubuntu (19.04/16.04) and trojan-server(1.10.2/1.12.2). The client is always v1.12.2. They all have this issue but happen randomly. I'm not sure if this related to my modification to some configurations:

net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
net.ipv4.tcp_fastopen = 3

the server and client trojan all have fast tcp open = true

**Comment by emiyalee1005** [comment]
sorry i can't provide log because it happens randomly and now it just work fine

**Comment by GreaterFire** [comment]
@emiyalee1005 Alright. Maybe it's just the wall doing its stuff. I'll keep monitoring this behavior.

**Comment by GreaterFire** [comment]
Fixed in c766ed995cf832da821a49a6d7e5c448439f62cf.

**Comment by GreaterFire** [comment]
@abelZhou123 @emiyalee1005 Please test.
