### ISSUE TITLE
[QUESTION] is there any way to support cdn without buying any 3rd-party services?

### ISSUE THREAD

**Issue by emiyalee1005** [trojan-gfw/trojan#94]
first sorry if this question is duplicated with #70. 
What i want to know is there is a way to support cdn natively in trojan programs without buying any 3rd-party services like cloudflare premium?I really want to protect the ip of my vps servers from being banned by the gfw(recently this situation often happens). If not, why?

**Comment by KunagisaYuki** [comment]
@emiyalee1005 As trojan works on pure *bare* TLS traffic flow it is impossible to implement such type of CDN

**Comment by emiyalee1005** [comment]
3q @KunagisaYuki
