### ISSUE TITLE
[QUESTION] is trojan support tls 1.3 and encryted sni?

### ISSUE THREAD

**Issue by emiyalee1005** [trojan-gfw/trojan#95]
is trojan support tls 1.3 and encryted sni?

**Comment by KunagisaYuki** [comment]
@emiyalee1005 Trojan is not handling encryption process, it's OpenSSL doing so. currently we support TLS 1.3 as long as your OpenSSL supports it.

**Comment by emiyalee1005** [comment]
I see, 3q @KunagisaYuki

**Comment by k79e** [comment]
目前规范加密sni反而更好污染. 而且那个加密跟没加密没什么区别
