### ISSUE TITLE
When use alpn:['h2'], chrome can't open the mask website of the server

### ISSUE THREAD

**Issue by emiyalee1005** [trojan-gfw/trojan#96]
when i set alpn:['h2'] and then use chrome to open the mask website of the server, it show "this site can't be reached with ERR_SPDY_PROTOCOL_ERROR instead.."

**Comment by Chigusa0w0** [comment]
You shall configure the remote source to support _cleartext TCP_ HTTP/2. As, in most implementation, HTTP/2 _over TLS_ is expected, so pure H2 support may not be enabled by default.

**Comment by emiyalee1005** [comment]
I use caddy and it enable http2 by default
