### ISSUE TITLE
Maybe it's the cert problem

### ISSUE THREAD

**Issue by yyuurrii34** [trojan-gfw/trojan#98]
letsencrypt certs no longer work for trojan
```
Jun 05 03:59:09 authenticated as 8cdf9f32-9389-4d.....
Jun 05 03:59:09 requested connection to www.google.com:443
Jun 05 03:59:09   [ERROR]  cannot establish connection to remote server www...eachable
Jun 05 03:59:09  [INFO]  disconnected, 0 bytes received, 205 bytes sent, l... seconds
```

can't get through any website except github.com

**Comment by yyuurrii34** [comment]
the connection has been terminated unexpectedly

**Comment by GreaterFire** [comment]
It's not about the certificate. The TCP connection cannot be established. Check if you can still connect to your server.
