### ISSUE TITLE
installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by asdfzxh8** [trojan-gfw/trojan#99]
I used
sudo apt --fix-broken install python-pycurl python-apt
sudo add-apt-repository ppa:greaterfire/trojan
sudo apt update
sudo apt install trojan

or 

sudo add-apt-repository ppa:greaterfire/trojan
sudo apt-get update
sudo apt-get install trojan

to try to install trojan on Ubuntu 18.04.

But in both cases IIRC the server showed something like 'unable to find trojan'.
On Ubuntu 18.10
sudo add-apt-repository ppa:greaterfire/trojan
sudo apt-get update
sudo apt-get install trojan
worked fine. How should one install trojan on 18.04?

**Comment by GreaterFire** [comment]
@asdfzxh8 Due to insufficient boost version, Trojan is no longer supported in Ubuntu 18.04. This change has been reflected on the wiki. Please use the provided pre-built binary.

**Comment by asdfzxh8** [comment]
Thanks very much. Just a quick question, could boost be manually updated to sufficient version in 18.04 to allow the use of Trojan? The VPS provider I am using does not give 18.10.

**Comment by GreaterFire** [comment]
Yes, you could.
